### ISSUE TITLE
score per activity

### ISSUE THREAD

**Issue by SarahSie** [matsim-org/matsim-code-examples#100]
Hello,
 
I would like to have the scores in for each person per activity per trip.
I have set the planCalcScore in the config file.
However, in the outcome, the scores for the activities and legs are always the same.
For more clarification, in following you can find an example of output file. The scores for 3 agents "1", "2", "3" are written.

```
1	0.0	-0.11226010722666668	-0.11226010722666668	-0.22452021445333337	-0.22452021445333337	-0.22452021445333337
2	0.0	-0.43138429653413146	-0.43138429653413146	-0.6093225448925012	-0.6093225448925012	-1.1495778878057892	-1.1495778878057892	-1.1495778878057892
3	0.0	0.3152251369333332	0.3152251369333332	0.6304502738666664	0.6304502738666664	1.003564037613333	1.003564037613333	1.3766778013599996	1.3766778013599996	1.3766778013599996
```

As you can see, the scores are always two by two the same.
I will be Thankful if you can kindly help me to understand the reason.
Alternatively, if you are aware of a better way that I can get my desired result, I will be happy to know.
 
Thank you,
Sahel

**Comment by mrieser** [comment]
What is the name of the output file you show above? This would help us pinpoint better what output you examine in detail.

**Comment by SahelHasti** [comment]
Thank you for your reply.
The name of the output file is “0.experienced_plans_scores.txt”.
If you have further questions, I would be happy to answer.
