### ISSUE TITLE
about the coordinate of network and xy.txt 

### ISSUE THREAD

**Issue by lucici1999** [matsim-org/matsim-code-examples#1018]
Hi, I am a beginner in matsim, is the coordinate system of the network in matsim wg84? Why is it not normal latitude and longitude coordinates after I convert OSM to network? 
![image](https://github.com/matsim-org/matsim-code-examples/assets/68318084/6271c6fd-a053-4ff8-a303-8921bded5220)
If I want to import a normal latitude and longitude xy file, how do I display it on the network?
![image](https://github.com/matsim-org/matsim-code-examples/assets/68318084/29be3484-d20f-4652-b751-737d62d24286)
![image](https://github.com/matsim-org/matsim-code-examples/assets/68318084/2d4a7d1a-dd65-4443-ae0b-c2d001fadbce)
please and thank you

**Comment by jingjunL** [comment]
There is a setting in MATSim where you can define the CRS of your network

```
	<module name="network" >
		<!-- The Coordinates Reference System in which the coordinates are expressed in the input file. At import, the coordinates will be converted to the coordinate system defined in "global", and willbe converted back at export. If not specified, no conversion happens. -->
		<param name="inputCRS" value="null" />
		<param name="inputChangeEventsFile" value="null" />
		<param name="inputNetworkFile" value="newNetwork.xml" />
		<param name="laneDefinitionsFile" value="null" />
		<param name="timeVariantNetwork" value="false" />
	</module>
```

In the parameter inputCRS

**Comment by lucici1999** [comment]
> MATSim 中有一个设置，您可以在其中定义网络的 CRS
> 
> ```
> 	<module name="network" >
> 		
> 		<param name="inputCRS" value="null" />
> 		<param name="inputChangeEventsFile" value="null" />
> 		<param name="inputNetworkFile" value="newNetwork.xml" />
> 		<param name="laneDefinitionsFile" value="null" />
> 		<param name="timeVariantNetwork" value="false" />
> 	</module>
> ```
> 
> 在参数输入CRS中
thanks for your reply！

**Comment by Janekdererste** [comment]
Please note, that MATSim only works with eucledean CRS, because it calculates distances using eucledean math. `WSG84` is a spheric coordinate system and cannot be used in MATSim. 

You must transform your coordinates into a eucledean CRS. The [UTM coordinate](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system) system works well for many applications.
