### ISSUE TITLE
Question about the mode statistics

### ISSUE THREAD

**Issue by hsyfyc** [matsim-org/matsim-code-examples#1020]
Hello, I have some small questions about the output mode statistics.
In my experience of MATSim, most time the output picture have steep increase or drop like the follow picture shows.
![modestats](https://github.com/matsim-org/matsim-code-examples/assets/73547130/081a3aa2-0d3c-4cd8-814c-f6b1541657de)
In the config file, I had set 0.95 for the parameter "fractionOfIterationsToDisableInnovation". And before the steep increase, the line is smooth.
Is this means that I need to run more iterations? but if so why the line before is so smooth?

**Comment by tschlenther** [comment]
The height of the jump after innovation switch off depends on your scenario, its settings and on your strategy weights, as well.
I think that, by theory, the jump is higher if mode choice has a higher weight.

For the convergence on the model, it is important to have all lines horizontal before the innovation switch off.
Your example indeed looks alright when it comes to that. However, its mode shares should also be stabilized after the innovation switch off. Your graph suggests that you should run more iterations after the switch off. As 100 iterations are not very many in the first place (depending on what you are doing), you could think about increasing the total number of iterations. Generally, we recommend to set the `fractionOfIterationsToDisableInnovation` to values smaller than `0.95`, e.g. `0.9` or even `0.8`. This might be all you need in your example as mode shares are more or less stable after ITER 50.

**Comment by hsyfyc** [comment]
Thanks for your reply, I will try it.

**Comment by hsyfyc** [comment]
Hello, another question about the mode statistics, the output statistics referring to the percentage of legs in different modes or trips in different modes?
For example, if an agent have a trip with three legs: walk-pt-walk, what will MATSim do to deal with this trip for mode statistics?

**Comment by hsyfyc** [comment]
Hello @tschlenther , another question about the mode statistics, the output statistics referring to the percentage of legs in different modes or trips in different modes?
For example, if an agent have a trip with three legs: walk-pt-walk, what will MATSim do to deal with this trip for mode statistics?
Thanks.

**Comment by mrieser** [comment]
For future reference: the mode statistics are per trip, not per leg.
