### ISSUE TITLE
Running MATSim from Jupyter Notebook

### ISSUE THREAD

**Issue by adiljonna** [matsim-org/matsim-code-examples#1021]
Hello MATSim Community,

I am very newy user of MATSim. I am working on my project , for which i need to automate MATSim with Jupyter notebook (python). I am struggling to do that. Can anyone help me how to interface MATSim with Jupyter Notebook.

Thanks
Adil

**Comment by Janekdererste** [comment]
According to https://stackoverflow.com/questions/89228/how-do-i-execute-a-program-or-call-a-system-command you could start MATSim as a subprocess. The general command to run a MATSim run, actually to run any java application would be a command like the following:

```
java -jar ./path/to/your/matsim.jar /path/to/your/config.xml
```
Why do you want to wrap MATSim into a python script?

**Comment by adiljonna** [comment]
Thanks for your help @Janekdererste 

Actually, i am working on a optmisation model for public  transportation. By using results, i am generating required MATSim  xml files(config, plan, network, transitvehicle,trabsitschedule).   Using that files i need to run MATSim envoirnment from Jupyter. At that point i am struggling

**Comment by adiljonna** [comment]
Hello @Janekdererste 

I try to implement your suggestion.
with following code

import subprocess

config_file_path = r"D:\jupyter\config.xml"
matsim_jar_path = r"D:\jupyter\matsim-example-project-0.0.1-SNAPSHOT.jar"

subprocess.run(["java", "-jar" , matsim_jar_path , config_file_path]) 


above code is opening Matsim now and not advancing to choose config file and  not running simulation.

Any help on above issue?

**Comment by Janekdererste** [comment]
The example-project has set the GUI-Application as default run class. If you want to run without the GUI you could start the run class directly with the following command
```
java -cp ./path/to/matsim.jar org.matsim.project.RunMatsim /path/to/config.xml
```

**Comment by adiljonna** [comment]
Hello @Janekdererste 

Thank you so much for helping. I managed to run now.

Have a good day.
