### ISSUE TITLE
Initialize an older version/using extensions

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#103]
Hello,

I started using Matsim not a long time ago and faced a problem runing it.

For the installation, I wanted to use eclipse because it seemed to be the easiest way to initialize the project. I then wanted to extensions and contributions (taxi, multimodal, bike, etc....).

The problem I am facing is that I do not know how to install a stable version. If I do it using the eclipse tutorial on the website, I end up using the 0.11.0-SNAPSHOT, which isn't functioning.
So I downloaded the latest stable version, the 0.10.1, and I am able to run that one with the normal example scenarios.
But the problem is I do not understand how to use extensions with the version I downloaded myself.

I wanted to go further and start using the multimodal system, and so I tried to run the Berlin multimodal scenario.
I saw I need to use the following command:

`
java -Xmx2000m -cp MATSim.jar:contrib/contrib.jar org.matsim.contrib.run.RunXxx
config.xml
`

I understand this line, I used it but it doesn't work. This is what I did:
(I am using windows)

`
java -Xmx1000m -cp matsim-0.10.1.jar;\Extensions\multimodal-0.10.1\multimodal-0.10.1\multimodal-0.10.1.jar org.matsim.run.Controler D:\Profiles\Roberts\Documents\MATSim\matsim-0.10.1\matsim-0.10.1\examples\berlin\config_multimodal.xml
`

 and what I got:

`
2019-04-05 09:51:48,090 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: multimodal
`

Therefore, I would like to know how to install an older version to use the extension with eclipse, or how to use extensions through the .zip version.

**Comment by mrieser** [comment]
When using the matsim-example-project in eclipse, you can change the version of MATSim to be used in the `pom.xml` file.

About using it on the command line: You correctly changed `:` to `;` on Windows, but I'm not sure if the path `\Extensions\multimodal-...` is correct. Usually, as `\` at the start means an absolute path from the root of your file system, but on Windows that's typically `C:\` or `D:\` or similar, so I'm not sure the extension will actually be found.
Also, while you add the jar-file with the multi-modal extension, you still execute the standard `org.matsim.run.Controler` which does not know about multimodal, and thus does not initialize anything related to the extension, and this produces the error message which states that you have a section "multimodal" in your configuration which isn't used at all.

The documentation for multimodal states:

> For a quickstart, confer to org.matsim.contrib.multimodal.Main.

So have a look at this class and try using this instead of the regular Controler.

**Comment by PlumeRoberts** [comment]
thank you @mrieser for your quick reply.

about eclipse:
is it needed to change every pom.xml file ? or only on ?

About the command line:
you were indeed right for the `\`, to sole the issue I used an absolute path.

`java -Xmx1000m -cp matsim-0.10.1.jar;D:\Profiles\Roberts\Documents\MATSim\matsim-0.10.1\matsim-0.10.1\Extensions\multimodal-0.10.1\multimodal-0.10.1\multimodal-0.10.1.jar org.matsim.contrib.multimodal.Main examples\berlin\config.xml`

But I now get a new error,

`Unable to find or load the main class org.matsim.contrib.multimodal.Main`

and

`Unable to find or load the main class org.matsim.contrib.multimodal.Main.`

I've looked a bit for it's origin, but I can not find it's source.

**Comment by mrieser** [comment]
> is it needed to change every pom.xml file ? or only on ?

There should be only one in the [matsim-example-project](https://github.com/matsim-org/matsim-example-project). Do not checkout the matsim-project itself, this is only intended for core-developers. "Users" of MATSim should use MATSim as a dependency only, as it is set up in the example project.

> But I now get a new error...

sorry. It looks like the documentation is out-dated and the class got renamed to `org.matsim.contrib.multimodal.RunMultimodalExample`.

**Comment by PlumeRoberts** [comment]
I have downloaded the 0.10.1 version of matsim trough Eclipse and GIT, and I am trying to find out how to run the multimodal berlin scenario with eclipse, but I do not find the rigth class to execute in Eclipse.

I have tried it also, but I get the same result, saying that the main class could not be found or loaded.

**Comment by PlumeRoberts** [comment]
I have now successfully (I think) installed MATSim 0.10.1 with eclipse on my computer.
Instead of checking the master branch, I checked the **0.10.x** branch.

Yet, I still have one remaining problem, how do I run it ? I've found the way to ru nthe "normal" matsim, in `\git\matsim10.x\matsim\src\main\java\org\matsim\run`
This file, including a main, is able to run MATSim in a normal way, but I am looking for a way to launch MATSim using multiple contributions.
I understood the way to run it using the command line, but I know need to know how to run it trough Eclipse.

**Comment by mrieser** [comment]
> I am looking for a way to launch MATSim using multiple contributions.

This heavily depends on the actual contributions. Most extensions provide a main-class to run their functionality with MATSim. If you want to use multiple extensions, you have to write a Main-class yourself that combines the functionality from the different extensions. Please be aware that extensions are not very well tested to work in arbitrary combinations.

In Eclipse, you create so-called "Run-Configurations". There you could also just specify another class as main-class, e.g. also a class from an extension.
