### ISSUE TITLE
Exploring the practical usage of Facility and Household files

### ISSUE THREAD

**Issue by ArezHK** [matsim-org/matsim-code-examples#1051]
Hello, I am trying to understand the practical uses of Facility and Household files along with their defined attributes. I would like to inquire about scenarios or examples that demonstrate the utilization of these data sets. Could you please assist me with information on this topic? 
Thank you in advance.

**Comment by JWJoubert** [comment]
Hi @ArezHK. I doubt if the `households` are actively used _inside_ the MATSim machinery. It is a container (read placeholder) allowing one to, maybe in future, use it for planning.

That said, the infrastructure is used. Albeit not inside a MATSim run. For example, generating synthetic populations (for MATSim) often use the household (infra)structure: See [Sun & Erath (2015)](https://doi.org/10.1016/j.trc.2015.10.010), [Joubert (2018)](https://doi.org/10.1016/j.dib.2018.05.126) and possibly [Hörl & Balac(2021)](https://doi.org/10.1016/j.procs.2021.03.089).

**Comment by JWJoubert** [comment]
On facilities, I guess it mostly relates to [accessibility](https://github.com/matsim-org/matsim-libs/tree/master/contribs/accessibility) and the activity opportunities provided by different facilities. See [Ziemke et al (2018)](https://doi.org/10.1007/s11067-017-9360-3).

**Comment by Areza622** [comment]
Dear Prof. @JWJoubert , thank you for your response and asistance.
