### ISSUE TITLE
Visualize the output files in MATSim 15.0

### ISSUE THREAD

**Issue by MadushaSammani** [matsim-org/matsim-code-examples#1055]
I am using the MATSim 15.0 version. Via only visualizes 500 agents. I want to visualize all the agents. Could you please let me know how to visualize the simulation results? Does OTFVisVisualization work for MATSim 15.0 version?

**Comment by paulheinr** [comment]
The OFTVis Module works fine with MATSim 15. Have a look at the example project (https://github.com/matsim-org/matsim-example-project/blob/master/src/main/java/org/matsim/project/RunMatsim.java). If you uncomment the respective line, it works fine.
