### ISSUE TITLE
Ie there a Freight Traffic Simulation tutorial?

### ISSUE THREAD

**Issue by Cuiyi20** [matsim-org/matsim-code-examples#106]
Dear everyone:
How to simulate the freight traffic in MATSim?By reading the article as 'Adding freight traffic to MATSim',the "carrier agents" is hard for me to understand.I would like to ask you if there are any cases for reference.How the “Freight Traffic Data” to construct?
Thank you!

**Comment by kainagel** [comment]
There is `RunFreightExample` in the `matsim-code-examples` repo.  Note that the file inputs for that class come from here: https://github.com/matsim-org/matsim/tree/master/examples/scenarios/freight-chessboard-9x9 .

**Comment by Cuiyi20** [comment]
Thank you, Professror!
