### ISSUE TITLE
Issue with the GUI

### ISSUE THREAD

**Issue by visoo10** [matsim-org/matsim-code-examples#1064]
[equil.zip](https://github.com/matsim-org/matsim-code-examples/files/13873747/equil.zip)
Hi, I´m having problems uploading the config file into the GUI, I suspect there´s trouble with either the network or the plans file.

I attach you guys the files to see if someone can help me, thanks!

**Comment by mrieser** [comment]
Your plans file is the culprit:

```xml
<?xml version='1.0' ?>
<!DOCTYPE plans SYSTEM "http://www.matsim.org/files/dtd/plans_v4.dtd">
<plans xml:lang="de-CH">
  <person id="1">
    <plan>
      <act type="h" x="0" y="404064" end_time="19:00" />
      <leg mode="car">
        <route>37 1 2 3 4 5 6 7</route>
      </leg>
    </plan>
  </person>
</plans>
```

Every plan must start and end with an activity. Your plan only has one activity at the start and then a leg, but no second activity.
