### ISSUE TITLE
robotic vehicle 

### ISSUE THREAD

**Issue by Hamadneh** [matsim-org/matsim-code-examples#107]
Hi, When I run the robotictaxi example, how can I know the average leg distance of taxi?
I got this output
https://www.dropbox.com/s/0dioxqmi68eor8f/traveldistancestats.png

**Comment by michalmac** [comment]
Currently taxi legs do not contain distance therefore they are skipped when calculating this statistics. However, many interesting stats on taxi performance can be taken from the taxi-specific output files.

**Comment by Hamadneh** [comment]
Thank you so much for your replay. Is here anyway to find the traveled distance by the fleet? I have the driven time!
