### ISSUE TITLE
What happens to new modes in the utility function scoring?

### ISSUE THREAD

**Issue by jinkai89** [matsim-org/matsim-code-examples#11]
I want to add new modes to the scoring function, for example "bike share" or "car share". Will these new new modes be teleported during the simulation giving me just the free flow speed? Please let me know. Thanks.

**Comment by kainagel** [comment]
Dear jinkai, could you please have a look at the [userguide](https://matsim.org/docs/userguide/), section 4.6 "Other Modes than Car"?  In general, besides defining the mode for scoring, you also need to define it for routing, even if that is just teleportation routing.  Something like 
```
<module name="planscalcroute" >
   <parameterset type="teleportedModeParameters" > 
      <param name="mode" value="newMode" />
      <param name="teleportedModeFreespeedFactor" value="null" />
      <param name="teleportedModeSpeed" value="4.167" />
      <param name="beelineDistanceFactor" value="1.3" />
   </parameterset>
   ... 
</module>
```
The above specification would say that the network distance would assumed as 1.3 times the beeline distance.  And the speed on that network would assumed to be 4.167 meters per second.

**Comment by jinkai89** [comment]
Dear Dr. Nagel, 
From what I read in the userguide section 4.6, any mode that is not registered in Qsim is going to be teleported. But can I specify any mode in the Qsim? For example can I do the following:

<module name ="qsim">
         <param name ="mainMode" value="car, tricycle"
...
</module>

Will MatSim recognize the "tricycle" mode and route it on the network?
