### ISSUE TITLE
How to visualize DRT + PT + CAR - VIA

### ISSUE THREAD

**Issue by LorenaBR** [matsim-org/matsim-code-examples#110]
Dear Matsim Community,

I would like to know if there is a possibility to visualize the traffic flow of pt, cars and DRT all together in the network.
In my case a I have a file describing the vehicles bus  and another one describing the drt vehicles, so just put the output_vehicles.xml as a layer in VIA  it's possible to visualize these 3 modes??

Many Thanks!

**Comment by mrieser** [comment]
Via visualizes vehicles based on the events, so by loading the network and events and creating a vehicles-layer, you should see all of them. Then, to visually differentiate the vehicles (pt/car/DRT), you could either use the Vehicle-Groups feature in the vehicles setup dialog in Via, or try to differentiate them just based on the vehicle id (e.g. "pt_*" for pt-vehicles).
