### ISSUE TITLE
Creating synthetic population on MATSim

### ISSUE THREAD

**Issue by cnabu** [matsim-org/matsim-code-examples#1101]
Hello,

I want to know how to create **plans.xml,** **population.xml** and **vehicles.xml** etc for the synthetic population from the **census** and **travel survey data**? Are there any resources that you can tell me which can be useful to do this task?

**Comment by Janekdererste** [comment]
We have an example, where a population is created from commuter data. 

https://github.com/matsim-org/matsim-code-examples/tree/15.x/src/main/java/org/matsim/codeexamples/population/demandGenerationFromShapefile

**Comment by cnabu** [comment]
Thank you for sharing this. I want to create all the aforementioned **xml files** with the help of **NTS Travel Survey** data (link below). Is it possible to do this by following the procedure given in the example you shared in your post?

https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=5340

**Comment by Janekdererste** [comment]
The example above only creates a population file. "Plans" and "population" file reference the same thing. Those terms are used interchangeably. I think "population" conforms to the most recent nomenclature.

What exactly are you planning on doing with the vehicles file? The vehicles file contains two types of information:

1. Vehicle types: The different vehicle types used in your simulation. Types contain the specification of a vehicle such as max velocity, length, width, etc. This could be something like "car" or "bicycle". Or, if your model requires this, you could split the specification for individual modes into more detailed categories like "car_large", "car_medium", and so forth.
2. Vehicles: This is a very simple container with a `vehicleId` and a `vehicleTypeId`. Usually, we don't include individual vehicles into the file, as per default MATSim will generate vehicles of each network mode for each person before the simulation starts. However, you can specify vehicles in your vehicle file and assign vehicles to persons manually. Most of the time this level of control is not necessary, but it depends on what you are trying to model

In case you only need vehicle types, you can easily create this file by hand, using any vehicles file in our public repositories as a starting point. For example [this](https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v6.1/input/berlin-v6.1-vehicleTypes.xml) one

**Comment by cnabu** [comment]
Thank you for your explanation. I want to figure out emissions in my simulation so I believe I need vehicleTypes.xml. Is there a good example that you can share with me for that?

**Comment by Janekdererste** [comment]
The Open-Berlin-Scenario contains emission calculations. The simple use case is in [this](https://github.com/matsim-scenarios/matsim-berlin/blob/4ba494fabed38311791789ee7a027bca4ab72fa0/src/main/java/org/matsim/legacy/analysis/emissions/RunOfflineAirPollutionAnalysisByVehicleCategory.java#L119) file. The folder contains more complicated setups. 

Please note, that you need your own emission factors. Unfortunately, we can't provide these factors, as one needs to buy a license for them.

**Comment by cnabu** [comment]
Hello Janek,

Thanks for this. Out of curiosity, how much is the license?

Kind regards,
Arsal
________________________________

**Comment by Janekdererste** [comment]
I have no idea. You can check here https://www.hbefa.net/en/software#licensing
