### ISSUE TITLE
Vulkaneifel scenario keep failing to compile.

### ISSUE THREAD

**Issue by cnabu** [matsim-org/matsim-code-examples#1109]
Hi I've used the following repo for Vulkaneifel scenario and followed all the instructions that was given in Seminar 2 to run the scenario but no matter what I do it keeps failing to compile. I even changed all input files with the output ones but it still give the following error. 

_https://github.com/matsim-scenarios/matsim-vulkaneifel_

**738 ERROR MatsimRuntimeModifications:76 Getting uncaught Exception in Thread main
java.lang.ExceptionInInitializerError: null**

I've attached the **logfile** and **logfileWarningsError** along with this post. Can someone please help me resolving this issue. I've chosen to use this scenario for my Homework assignment.

[vulkaneifel-v1.2-25pct.logfile.log](https://github.com/matsim-org/matsim-code-examples/files/15204164/vulkaneifel-v1.2-25pct.logfile.log)
[vulkaneifel-v1.2-25pct.logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/15204165/vulkaneifel-v1.2-25pct.logfileWarningsErrors.log)

**Comment by Janekdererste** [comment]
The simwrapper module from before the 2024.0 release is not compatible with Java 22. Either install Java 20 (you could also try 21 and tell us the results) and run it with that jvm, or remove the Simwrapper component from the run setup on the following line, in case you don't need it. 

https://github.com/matsim-scenarios/matsim-vulkaneifel/blob/c280452fe499774043725bfbbb1c8a9b2399749f/src/main/java/org/matsim/run/RunVulkaneifelScenario.java#L89

**Comment by cnabu** [comment]
I've tried it with JDK 17 but it gave me the **Memory Observer** message during compiling a few times before shutting down without finish compiling. Attach are the **logfile** and **logfileWarningsError** along with this post. As per your suggestion, I'll disable the Simwrapper and try again.

[vulkaneifel-v1.2-25pct.logfile.log](https://github.com/matsim-org/matsim-code-examples/files/15232411/vulkaneifel-v1.2-25pct.logfile.log)
[vulkaneifel-v1.2-25pct.logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/15232412/vulkaneifel-v1.2-25pct.logfileWarningsErrors.log)

**Comment by cnabu** [comment]
Nope. still doesn't work even after disabling simwrapper (attached picture).
![disable-simwrapper](https://github.com/matsim-org/matsim-code-examples/assets/160872955/e0967bab-8c7a-43e8-a08b-0644a22587fe)

**Comment by Janekdererste** [comment]
> I've tried it with JDK 17 but it gave me the Memory Observer

The interesting part of the logfile is this one:
```
2024-05-05T21:49:36,784  INFO MemoryObserver:42 used RAM: 4043 MB  free: 16 MB  total: 4060 MB
2024-05-05T21:50:36,820  INFO MemoryObserver:42 used RAM: 4048 MB  free: 11 MB  total: 4060 MB
2024-05-05T21:51:44,749  INFO MemoryObserver:42 used RAM: 4056 MB  free: 3 MB  total: 4060 MB
2024-05-05T21:52:51,640  INFO MemoryObserver:42 used RAM: 4059 MB  free: 0 MB  total: 4060 MB
2024-05-05T21:53:54,823  INFO MemoryObserver:42 used RAM: 4055 MB  free: 4 MB  total: 4060 MB
2024-05-05T21:55:00,416  INFO MemoryObserver:42 used RAM: 4057 MB  free: 2 MB  total: 4060 MB
2024-05-05T21:56:06,648  INFO MemoryObserver:42 used RAM: 4056 MB  free: 3 MB  total: 4060 MB
2024-05-05T21:57:16,017  INFO MemoryObserver:42 used RAM: 4058 MB  free: 1 MB  total: 4060 MB
2024-05-05T22:04:00,949 ERROR MatsimRuntimeModifications:76 Getting uncaught Exception in Thread main
java.lang.OutOfMemoryError: Java heap space
```
You can watch the simulation run out of memory, before it crashes with `java.lang.OutOfMemoryError: Java heap space`. All other errors are from post processing which can't find output files because they were never written. 

Try to assign more memory by using `-Xmx20G` (or as much ram as you can spare on your machine.

**Comment by cnabu** [comment]
Changing the JDK to 17 and adding VM value to 8GB did the trick. Thanks
