### ISSUE TITLE
Suggestions for processing heavy MATSim outputs

### ISSUE THREAD

**Issue by jafshin** [matsim-org/matsim-code-examples#111]
Hello everyone,

I am working with some heavy MATSim output files (output_event.xml is about 22 GB and output_plans.xml is about 14 GB). I considered using postgresql to work with these data however as they are in XML format it can be tricky to convert them to postgres tables. However as MATSim has been already used for large-scale scenarios in several cases around the world before, I guess there should be a solution for this. I would appreciate if you can share any suggestions or experiences you might have in processing large MATSim outputs.

 Best,
Afshin

**Comment by tduberne** [comment]
Dear Afshin,

the best way to work with this kind of output is to parse the stream of events with Java or another language (the format is fairly minimal, so writing a basic parser by hand for your language of choice should not take too long), aggregating the results in whatever way is useful for you, and then analyze this aggregated dataset. The key is to avoid storing all events in memory.

For instance, assuming you want to produce statistics about average travel times, you would listen to departure and arrival events, and do the following:
- for each departure, store the departure time for the agent in a Map
- for each arrival, retrieve the departure time from the Map, compute the travel time and write it to file/store it in an internal data structure.

https://github.com/matsim-org/matsim-code-examples/tree/11.x/src/main/java/org/matsim/codeexamples/programming/eventsHandling/carTravelDist is an example of such an approach using Java.

**Comment by kainagel** [comment]
An addition to Thibaut's statement: When you are indeed using the matsim code base, you can as well gzip the files, since the matsim code base can read and write gzipped files natively.  That does not help with processing speed, but at least it reduces disk space consumption.

**Comment by jafshin** [comment]
Thanks @tduberne and @kainagel  for your suggestions, will keep that in mind Kai. In the meantime, I also played around with some possible solutions and realized as you mentioned Thibaut, the best solution is to avoid loading all the events at once. So what I ended up doing now is to use `SAX` (Simple API for XML) to parse the output files.

Thanks again.
