### ISSUE TITLE
Is switching to matsim 11.0 safe/worth it ?

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#114]
I am curently working with matsim 10.1, and I am wondering of going to MATSim 11.0 is usefull or not. Is their a lot of changes ? Is their enough documentation ? The 10.1 documentation is pretty light for devs so I don't want to change if there is even less doc? 
Should I just stick with the 10.1 ?

**Comment by JWJoubert** [comment]
> The 10.1 documentation is pretty light for devs so I don't want to change if there is even less doc?

I then recommend you stick with 10.1 ;-) as 11 is still actively being developed/changed. Especially if you use it for a specific project/study... work with what is stable.

**Comment by PlumeRoberts** [comment]
Okay, thank you very much :-)
