### ISSUE TITLE
How does MATSim affect a link to a facility ?

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#115]
I am working on a project and we need to use facilities. The thing we know about them is their coordinates, so I ran a few test to see how it reacted, and I faced an unexpected result.
![Capture](https://user-images.githubusercontent.com/38692785/56897883-f2547680-6a8f-11e9-94b6-6a9530bdbe69.PNG)

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE network SYSTEM "http://www.matsim.org/files/dtd/network_v1.dtd">

<network name="Network_Test1">

<!-- ====================================================================== -->

	<nodes>
		<node id="1" x="0.0" y="0.0" />
		<node id="2" x="10000.0" y="0.0" />
		<node id="3" x="5000.0" y="4000.0" />
		<node id="4" x="2000.0" y="6000.0" />
		<node id="5" x="8000.0" y="6000.0" />
		<node id="6" x="5000.0" y="9000.0" />

		
	</nodes>
<!-- ====================================================================== -->

	<links capperiod="01:00:00" effectivecellsize="7.5" effectivelanewidth="3.75">
	    
		<link id="12" from="1" to="2" length="10000.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		<link id="21" from="2" to="1" length="10000.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />

		<link id="14" from="1" to="4" length="6325.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		<link id="41" from="4" to="1" length="6325.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />

		<link id="25" from="2" to="5" length="6325.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		<link id="52" from="5" to="2" length="6325.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />

		<link id="43" from="4" to="3" length="3610.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		<link id="34" from="3" to="4" length="3610.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />

		<link id="53" from="5" to="3" length="3610.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		<link id="35" from="3" to="5" length="3610.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />

		<link id="64" from="6" to="4" length="4243.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		<link id="46" from="4" to="6" length="4243.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />

		<link id="65" from="6" to="5" length="4243.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		<link id="56" from="5" to="6" length="4243.0" freespeed="10" capacity="3600.0" permlanes="1.0" oneway="1" origid="1" type="1"  modes="car" />
		
	</links>
<!-- ====================================================================== -->

</network>
```

the upper Facility (above 6) is the house of the agent, and the lower (under 3) is the working facility, only defined by the coordinates (5000, 1000).

The problem is that while going to work, I was expecting the facility to be either linked to 12 or 21. But then reading the function ```getNearestRightEntryLink``` I saw it was based on the nearest node, which is 3.
The problem is that the worker go through 65->53->34. I expected it to be near 3 so on 43 or 53 but no, it choose to be linked on 34.

Why ?

I understood that in this case, it will go to the link with the lowest id, but why doesnt the priority go to 43 or 53 because it is an input link ?

Edit: I saw that the function wasn't called, so wich function is called ? or why isn't that one called ?

**Comment by kainagel** [comment]
All of the automatic ways of assigning links to coordinates have disadvantages.  It seems that wwhat MATSim actually does is not stable over time, which is not good, but hard to avoid in a community project.

If you want to keep control, I would strongly suggest to give both coordinates and linkIds to activities (in the plans file), then it should just use those.  Please let us know how it goes.

**Comment by PlumeRoberts** [comment]
The thing is that I do not understand wich function is used. I don't really mind using the getNearestRightEntryLink, which isn't that bad. I guess that if it is in the code it might be used somewhere. Juste for our study, we'd like to know which link is choosen, and how it is choosen, to understand and possibly adapt our data.

**Comment by kainagel** [comment]
In this particular case, `PrepareForSimImpl` eventually points, through `XY2LinksForFacilities.run(...)`, to `NetworkUtils.getNearestLink(...)`.  However, some execution paths, depending on your configuration, will run `FacilitiesFromPopulation`, which uses `NetworkUtils.getNearestLinkExactly(...)`.  Look into `PrepareForSimImpl` for the code.   There is already a comment in the code that it is inconsistent.
We find it difficult to keep such things consistent.  One day, someone makes it consistent, the next day, someone else implements something new and it is once more inconsistent. 
 :-( . Again, if you want to keep control, provide the link IDs in the activities.  See https://github.com/matsim-org/matsim-code-examples/blob/12.x/src/main/java/org/matsim/codeexamples/population/addLinkIdsToActivities/RunAddLinkIdsToActivitiesExample.java .

**Comment by PlumeRoberts** [comment]
I Understand. Thank your for your help on this issue.
