### ISSUE TITLE
Bicycle Modelling in MATSim

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#1163]
I see there is a bicycle contrib in the MATSim library, but I didn't see any description about it. I am wondering what functionalities this contrib has achieved compared to the classic way of teleportation?

Thanks!

**Comment by dziemke** [comment]
Hi Jingjun,
the bicycle contrib enhances routing and scoring; specifically attributes like surface types, existence of dedicated cycling infrastructure, gradients etc. are (or better: can be) considered in scoring (and, to enable that travel options that perform well in regard of such attributes, are actually found by the router) also to some extent in routing.
The clearest documentation is the code itself. Other than that, [this paper](https://www.sciencedirect.com/science/article/abs/pii/S0167739X17320447) talks about the main aspects of this contrib -- no guarantee that all is still by 100% up to date.
