### ISSUE TITLE
Sharing extension fares and scoring

### ISSUE THREAD

**Issue by fadamidis** [matsim-org/matsim-code-examples#1168]
Hello, I was wondering about the sharing extension (shared_mobility contrib):

1. If simulated shared vehicle services are somehow considered in scoring, especially in `SubtourModeChoice`. Is their scoring calculated based on the underlying mode (e.g. car for carsharing)?
2. What is the impact of the service characteristics (base, time, distance fares) on the scoring of trips by shared services? i.e. how are the fares taken into account during scoring?

I was going through previous conversations and could not find an answer. I think that @sebhoerl or @balacmi could easily answer my questions- Thank you!

**Comment by sebhoerl** [comment]
Hi, scoring is basically independent of the sharing contrib. The underlying modes will be scored as if they had been used independently, so you can set up everything via configuration. Beyond that, you may write some handlers to integrate the specific sharing events for successful and missed rentals etc:

https://github.com/matsim-org/matsim-libs/tree/master/contribs/shared_mobility/src/main/java/org/matsim/contrib/shared_mobility/service/events

But there is no preconfigured code for that as far as I remember.

**Comment by sebhoerl** [comment]
Maybe here they actually did that, you could check back with them:
https://www.sciencedirect.com/science/article/pii/S1877050923005823

**Comment by fadamidis** [comment]
That's clear. Thank you @sebhoerl for the explanation and the sources.
