### ISSUE TITLE
Using GPU (Cuda) with MATSim

### ISSUE THREAD

**Issue by Tetsujinfr** [matsim-org/matsim-code-examples#117]
Hi

Does MATSim support GPU acceleration (e.g. CUDA)?
The only ref I found on yhis was a paper from 2009 but no tutorial or example. Can someone point me into a direction?
Thanks

**Comment by mrieser** [comment]
Currently, there is no support for running MATSim on GPUs.
D. Strippgen implemented an early version of MATSim on an early CUDA version as a research project, but it did not pay off at that time, so it was not followed up.

**Comment by golanbendor** [comment]
There is a new CUDA based Implementation by Aleksandr Saprykin (see the reference below) which also includes GPU use for PT and other modes. The study is still in the experimental stage but shows promising results with a runtime which is ~30-60 times faster than the current one (for the Zurich scenario).

Saprykin, A., Chokani, N., & Abhari, R. S. (2019). GEMSim: A GPU-Accelerated Multi-Modal Mobility Simulator for Large-Scale Scenarios. Simulation Modelling Practice and Theory.‏

**Comment by Tetsujinfr** [comment]
Ok thanks. I saw the GEMSIM paper but I did not realize it was MATSIM related. Do you think this will end end in the open source domain?

**Comment by kainagel** [comment]
To add to the "David Strippgen" thread: The CUDA mobsim was about a factor of 70 faster than standard matsim.  The problems were:
(1) Conversion of the java objects to C++ to start the CUDA mobsim, and conversion back of the events from CUDA C++ to Java objects was eating up all the performance gains.
(2) Java is a higher level language than C++, and C++ is a higher level language than CUDA.  In consequence, having our current functionality in CUDA would have been impossible to achieve with the resources we had.  And even if someone else would have written it for us, it would be impossible to maintain it with the resources we have.
