### ISSUE TITLE
Deactivating built-in TripRouter when using QueueSimulationListeners to provide dynamic re-routing

### ISSUE THREAD

**Issue by robfitzgerald** [matsim-org/matsim-code-examples#12]
Hello!

Using MATSim 0.10.1. I have implemented a `Provider<Mobsim>` which re-routes vehicles in a `BeforeSimStepEventHandler`. This over-writes the route provided by the built-in router, in my case set as FastDijkstras in my config.xml file. The dynamic re-routing works correctly.

However, I am noticing that starting MATSim still takes a very long time. When I inspected the simulation using jvisualvm, I found that MATSim was still running it's own FastDijkstras at the beginning of the day, which I _believe_ is not necessary for my implementation. As I attempt to run simulations with populations 10k and above, this becomes a big time sink. I tried building a DummyRoutingProvider which might simply return an empty Leg, but I didn't find how I could wire that in, as everything in the TripRouter class hierarchy seems private. 

Perhaps these need to be calculated for the simulator to run correctly? But if not, it would be great to bypass them. I am only running a single iteration of MATSim, so no behavioral learning going on here, just queue simulation of agents with fixed plans.

Thank you for any help!

Rob
Denver, CO

**Comment by robfitzgerald** [comment]
More specifics on my issue: Running a simulation on 3k vertices and 8k links with 15k agents takes only a few seconds to begin, but, running a simulation on 12k vertices and 35k links with 30k agents, and the simulation hangs after calling `controler.run()` (I gave up after 90 minutes).

I believe the only thing that is in the control flow related to my code after `controler.run()` are my event handlers and qsim listeners. When I debug these, I don't see them getting called. While hanging, 100% CPU is in use, but plenty of memory is still available (should rule out thrashing?). I wrap `controler.run()` in a try catch statement, but don't see any evidence of an exception. Is something failing silently?

I know this is suspicious in that it could be on my implementation. I don't think my inputs are too big. Perhaps something about adding an overriding QSim? Happy to provide more details if requested.

**Comment by jfbischoff** [comment]
This setup should not take more than a couple of minutes to route.
Do you perhaps have links with a length=0.0 or NaN in your network? This sometimes leads to the behavior you described.

Am 19.09.2018 23:29 schrieb Rob Fitzgerald <notifications@github.com>:

More specifics on my issue: Running a simulation on 3k vertices and 8k links with 15k agents takes only a few seconds, but, running a simulation on 12k vertices and 35k links with 30k agents, and the simulation hangs after calling controler.run() (I gave up after 90 minutes).

While hanging, 100% CPU is in use, but plenty of memory is still available (should rule out thrashing?).

I know this is suspicious in that it could be on my implementation. I don't think my inputs are too big. Perhaps something about adding an overriding QSim? Happy to provide more details if requested.

-

**Comment by tduberne** [comment]
To answer to your initial point: you are right that MATSim will attempt to route all trips that are incomplete (missing route) during the PrepareForSim step.

Your approach with a dummy router is also the option I would use as a first step. I actually see two options:
- let the MATSim Router "teleport" all modes based on crow-fly distance. It will still compute routes, but this will be fast.
  - pros: no code, all from config (look at the output config in section "planCalcRoute" and set the parameters in your input config file for all modes to something similar to what is defined there for "walk"
  - cons: all your plans will have valid (though meaningless) routes. This means that if, for one reason or another, your Mobsim module does not do what it should, your simulation might silently produce non-sense
- implement a dummy "RoutingModule" that simply returns empty legs, and set it as the routing module for all modes. I did not test it, but I think this should work.
  - pros: if there is somehow a problem in you Mobsim code, the mobsim will complain about not getting enough information to do its job, allowing you to catch the problem early
  - cons: a bit more code

An third option would be to store all the information PrepareForSim tries to compute in your input plans.

But as Joschka said, there seems to be another problem in your setup, which is difficult to identify given the information we have.

**Comment by robfitzgerald** [comment]
`length="0.0"` was the issue. After adjusting these to "1.0" I found my experiment runs.

The initial delay due to PrepareForSim routing is only about 30 seconds for my current inputs. This amount of delay is not an issue for me at this point, but if it becomes an issue, I will likely implement a DummyRoutingModule.

Thank you @jfbischoff for your intuition, and @tduberne for your suggestion!
