### ISSUE TITLE
Errors implementing RunMultiModeDrtExample.java 

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#121]
Hello,

  I am working on a scenario implementation with the RunMultiModeDrtExample.java in the drt module in SNAPSHOT 12. I made a few additions to the run file in order to access and edit a few config modules in runtime from the code.  I want to add two drt (drt_A and drt_B) operators and set their input values in the run file. I tried to implement it but I am getting an error. Maybe I have not implemented what I want in the right way. I have attached the RunMultiModeDrtExample.java file and the error file. The additional code that I have added is within the comment lines //start additional code and //end additional code (between lines 52 and 74).
Any help would be deeply appreciated.
@jfbischoff @michalmac   
[RunMultiModeDrtExample.java.txt](https://github.com/matsim-org/matsim-code-examples/files/3181668/RunMultiModeDrtExample.java.txt)
[Error file.txt](https://github.com/matsim-org/matsim-code-examples/files/3181669/Error.file.txt)

**Comment by michalmac** [comment]
You need to use `MultiModeDrtConfig` instead of `DrtConfig` for grouping all DRT configs. Line 71 should look like:
```
MultiModeDrtConfigGroup drt = new MultiModeDrtConfigGroup();
```
Everything else looks ok.

**Comment by michalmac** [comment]
Oh, and there is no need to handle DRT/taxi config checking manually - it all happens automatically now, so lines 78-79 can be removed.
