### ISSUE TITLE
Population distribution in destinations with maximum capacity of agents

### ISSUE THREAD

**Issue by OrranaLhaynher** [matsim-org/matsim-code-examples#122]
I have an initial number of x agents that should be routed to 5 shelters, however each shelter has a y number of full capacity. I made this script -> https://github.com/OrranaLhaynher/matsim-example-project/blob/master/src/main/java/org/matsim/project/PopulationGenerationRandomly, to generate my population, but the distribution of agents for each shelter is being done at random. How can I make this distribution following the parameters given above? Thank you for your help right away!

**Comment by kainagel** [comment]
I think you need sampling without replacement.  Something like:
```
List<Coord> places = new ArrayList<>() ;
for ( int ii=0 ; ii<shelter1Capacity; ii++ ) {
   places.add(coord1) ;
}
for ( int ii=0 ; ii<shelter2Capacity; ii++ ) {
   places.add(coord2) ;
}
...
// (at this point you have as many "places" as you have capacity in all shelters combined)
Collections.shuffle( places ) ; // this will shuffle those places into random sequence
```
And then use `places.get(ii)` for person number `ii`.  As long as you have not more persons than places, this will work.  If you have more persons than places, some persons will not be allocated.

There are probably more elegant solutions.  Maybe search "sampling without replacement" together with "java".

**Comment by OrranaLhaynher** [comment]
Thank you for your help!! I tried to create the coordinates for the shelters with the help of your code and I managed to create them, but I could not get them to allocate the necessary amount of agents. The distribution always has a margin of error, for more or less. Do you know why? My script for this case is the https://github.com/OrranaLhaynher/matsim-example-project/blob/master/src/main/java/org/matsim/project/RunPopulationMaximumCapacityShelters. And, trying not to ask too much, could you answer me one thing? I have a big question about creating the vehicle.xml script: is there a code where I can create it or do I create it based on a general example, setting it to the features I want? Thank you again for your help, I'm very grateful!

**Comment by kainagel** [comment]
(1) Thanks for putting this in a github repo, that makes structured answering much easier.

(2) Could you please make the code in the github project compile?  You have files that do not have the *.java ending, classes where the class name does not correspond to the filename, and the package names are not correct.   Thanks

**Comment by OrranaLhaynher** [comment]
Thank you for helping me and replying me! My github project is already updated and I put my input data there too. Thank you again for your answer!
https://github.com/OrranaLhaynher/matsim-example-project/blob/master/src/main/java/org/matsim/project/RunPopulationMaximumCapacityShelters.java

**Comment by kainagel** [comment]
I think that you need to get the method that ultimately calls `shuffle` out of the person loop.  Here is the correct code:
```
		List<Coord> coord = new ArrayList<>();
		coord = getShelter(ct); // getShelter eventually calls shuffle

		for (Person pers : pop.getPersons().values()) { //this loop iterates over all persons
			int i = 0;
			Plan plan = pers.getPlans().get(0); //each person has exactly one plan, that has been created in createPersons(...)
			Activity homeAct = (Activity) plan.getPlanElements().get(0); //every plan has only one activity so far (home activity)
			homeAct.setEndTime(7*3600); // sets the endtime of this activity to 7 am
                    ...
```

**Comment by OrranaLhaynher** [comment]
When I take the method out of the people loop the shelters are only created with one of the coordinates that were set
                
		List<Coord> coord = new ArrayList<>();
		coord = getShelter(ct); // getShelter eventually calls shuffle
                   
		for (Person pers : pop.getPersons().values()) { //this loop iterates over all persons
			int i = 0;
			Plan plan = pers.getPlans().get(0); //each person has exactly one plan, that has been created in createPersons(...)
			Activity homeAct = (Activity) plan.getPlanElements().get(0); //every plan has only one activity so far (home activity)
			homeAct.setEndTime(7*3600); // sets the endtime of this activity to 7 am

			Leg leg = pb.createLeg(TransportMode.car);
			plan.addLeg(leg); // there needs to be a log between two activities

			//work activity on a random link within one of the commercial areas
			//Coord p = getRandomElement(coord);
			Activity shelt = pb.createActivityFromCoord("shelter", new Coord((coord.get(i).getX()), (coord.get(i).getY())));
			double startTime = 8*3600;
			shelt.setStartTime(startTime);
			shelt.setEndTime(startTime + 6*3600);
			plan.addActivity(shelt);	
			i++;

I also tried putting the method inside a for loop with the amount of people, but that did not work either

**Comment by kainagel** [comment]
you can't set `i=0` inside the loop; it will reset `i` to zero every time it comes to that line.

**Comment by OrranaLhaynher** [comment]
Thanks!! I already discovered this a few days ago lol but totally forgot to close the problem. I'm really sorry, and thank you so much for your help !!!
