### ISSUE TITLE
MATSim and Docker container

### ISSUE THREAD

**Issue by mlclemente** [matsim-org/matsim-code-examples#123]
Can MATSim run in a container?

**Comment by mrieser** [comment]
I don't know of any publicly available docker image containing MATSim (i.e. there is no official MATSim docker image), but it's just Java, so you should be able to add it to a base image that contains java. In fact, I know of people running MATSim as a docker image on AWS, so it's definitely doable.

**Comment by JWJoubert** [comment]
> I know of people running MATSim as a docker image

I think Pieter Fourie (@langkoos) might be a good starting point to ask.
