### ISSUE TITLE
Heap memory is not fully used

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#125]
Hello,

For our study, dealing with autonomous vehicles, we are running some basic tests, using a simplified version of Paris, and around 600'000 agents. To move, their only solution is to use a taxi. In this scenario, there is 50'000 taxis in three different point of the city.

The problem is the following,
at 07:00:00, the simulation doesn't do anything anymore, it simply keep runnin gwithout apparently doing anything.
Using JVM monitor, an Eclipse plug-in, I wanted to see if the problem was because of the heap memory.
![image](https://user-images.githubusercontent.com/38692785/58095279-f4af7980-7bd2-11e9-8733-2ffa433419d3.png)
The memory just goes up and down, without doing anything.

I tried adding more memory, to the point where Eclipse is launched with 15G of RAM, and using JVM arguments, MATSim is launched with 13G.

I tried to limit the number of taxis (going down to a thousand), The only difference are the "Handled event #65539" messages showing up but the result is the same, the heap memory going up and down.

Does anyone know with this problem occurs and if yes, do you have a solution ?

Thank you for your time.

**Comment by mrieser** [comment]
The memory in the graph goes up to around 6G. Running it with 13G, the problem should not be memory related, I think. 

I don't know how efficient the scheduling algorithms are for thousands of vehicles. If the code tries to find the best taxi for a request, it could mean iterating over all taxis to find the best one. This would not scale very well for your number of taxis. As I said, I don't know how it's implemented, it's just a gut feeling that some non-scaling data-structure or algorithm might be the problem.

**Comment by jfbischoff** [comment]
Could you please post your taxi config group? There are some specific settings that should be set for such huge vehicle fleets.

**Comment by michalmac** [comment]
There are many factors that have influence on the actual computation time. As a reference point: we were able to simulate 2.5M trips with 100k vehicles in 3 hours (Berlin). I would need to have a look at your taxi config to say something more.

**Comment by PlumeRoberts** [comment]
```xml
	<module name="taxi">

		<!-- Used in AStarEuclidean for shortest path search for occupied drives. 
			Values above 1.0 (typically, 1.5 to 3.0) speed up the search, but at the 
			cost of obtaining longer paths -->
		<param name="AStarEuclideanOverdoFactor" value="1.0" />

		<param name="breakIfNotAllRequestsServed" value="false" />
		
		<param name="changeStartLinkToLastLinkInSchedule" value="true" />
		
		<!-- If false, the drop-off location remains unknown to the optimizer and 
			scheduler until the end of pickup -->
		<param name="destinationKnown" value="false" />

		<!-- If true, detailed hourly taxi stats are dumped after each iteration. -->
		<param name="detailedStats" value="true" />

		<!-- Typically, 60 seconds -->
		<param name="dropoffDuration" value="60.0" />

		<!-- If true, vehicles are (GPS-like) monitored while moving. This helps 
			in getting more accurate estimates on the time of arrival. Online tracking 
			is necessary for vehicle diversion. -->
		<param name="onlineVehicleTracker" value="true" />

		<!-- Typically, 120 seconds -->
		<param name="pickupDuration" value="120.0" />

		<!-- An XML file specifying the taxi fleet. The file format according to 
			dvrp_vehicles_v1.dtd -->
		<!-- To create your own vehicles, see org.matsim.contrib.av.vehicles.CreateTaxiVehicles  -->
		<param name="taxisFile" value="taxisVehicles50k.xml" />

		<!-- If true, time profiles of vehicle statuses (i.e. current task type) 
			and the number of unplanned requests -->
		<param name="timeProfiles" value="true" />

		<!-- If true, vehicles can be diverted during empty trips. Requires online 
			tracking. -->
		<param name="vehicleDiversion" value="true" />

		<parameterset type="optimizer">
			<param name="cellSize" value="1000" />
			<param name="goal" value="DEMAND_SUPPLY_EQUIL" />
			<param name="id" value="example" />
			<param name="nearestRequestsLimit" value="99999" />
			<param name="nearestVehiclesLimit" value="99999" />
			<param name="type" value="FIFO" />
		</parameterset>
	</module>
```

Sadly, There isn't a lot of documentation on the taxi module (or I haven't found it) so I do not know the details of the algorithm I am using.
The router is A*Landmarks, and the optimizer is of ```type="FIFO"``` which honnestly doesn't mean a lot to me, so I do not know if for This size of data, there is a better algorithm or optimizer.

On other scenarios, we've already used 5'000 taxis on a 40'000 agents network without any problems, so I do not know really know how to solve the issue.
Maybe increasing the number of taxi would be useful but intuitively, I sound more like a bad idea than a good one because it would need to loop through even more taxis.

As I said, I do not have a lot informations on the modules I am handling

**Comment by jfbischoff** [comment]
`			<param name="nearestRequestsLimit" value="99999" />
			<param name="nearestVehiclesLimit" value="99999" />`

Please set the requestLimits to something closer - 40 or even 20, this should speed up things significantly.

**Comment by michalmac** [comment]
And the optimiser type should be `RULE_BASED` (not `FIFO`)

**Comment by PlumeRoberts** [comment]
thank your for your ideas, but I am sad to say the result is the same, no "INFO EventsManagerImpl:134  event # 65536" or anything else shows up, it just sit there without evolving.

**Comment by jfbischoff** [comment]
If you run 50.000 robotaxis, simulating will actually take quite some time - it should progress eventually.

**Comment by michalmac** [comment]
Then maybe set `AStarEuclideanOverdoFactor` to 3.0 (should speed up things) and `onlineVehicleTracker` to `false` (not used in the rule-based algo...; may speed up slightly).

**Comment by michalmac** [comment]
And increase the fleet size, maybe to 100k. It sounds counter-intuitive, but the algorithm runs much faster if there are idle taxis nearby.

Or ideally, start with 5k taxis and 50k agents to get an initial hint on the expected computation time for the 100% case.

**Comment by michalmac** [comment]
One more hint: there may be also a huge congestion in the first iteration, since taxis will use links which are supposed to be good for an empty network (no info on traffic in iter.0). There are a few ways of solving this issue. But as a quick check, you could run a simulation with the following values in the `qsim` config group:
```
<param name="flowCapacityFactor" value="2.0" />
<param name="storageCapacityFactor" value="3.0" />
```

**Comment by PlumeRoberts** [comment]
Thank you verry much, I've followed you instructions and it now works, the simulation works perfectly.
I still have questions about taxis but they don't belong here.
I will open a new issue about this to understand better.
