### ISSUE TITLE
Trouble running the simulation

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#129]
Hello,

I am running a simulation and I faced a problem.
my agents end their firste activity between 07:00:00 and 09:00:00. Problem is, they do not go out. After viewing the result on Via, the whole simulation gives out results between 06:20:00 and 06:53:00, but some agents havent even done their day.
I check the different data, like the leg histogram, it show departures between 7am and 9am, and people are on the roads until 10pm. But the simulation still only shows me people for half an hour.

Would someone be able to give me an explanation ?

**Comment by mrieser** [comment]
If MATSim's leg histogram shows departures between 7 and 9, then I would trust that over Via's visualization. Probably there was an error loading the data in Via? Could you please check Via's logfile after loading the data and/or send it to me? (In Via, select the Help menu and select "Report Bug/Feedback" to get to the logfile and the address to send it to).

**Comment by PlumeRoberts** [comment]
I just sent it to the mail adress and I will add it here if anybody hels may want to help, but the log file doesn't seem to show up any problem.

[logfile.txt](https://github.com/matsim-org/matsim-code-examples/files/3222363/logfile.txt)

**Comment by PlumeRoberts** [comment]
The problem came from the limited number of agents, and the simulation didn't load agents that started later on.

Thank you very much for you help.
