### ISSUE TITLE
Can't run osm.pbf with java to create "Network Generation" for MATsim

### ISSUE THREAD

**Issue by thth776** [matsim-org/matsim-code-examples#13]
When I run command 
java -cp osmosis.jar --read-pbf file =antarctica-latest.osm.pbf \--bounding -box top =47.701 left =8.346 bottom =47.146 right =9.019 \completeWays = true --used - node --wb allroads .osm.pbf
to generate a MATSim network is from OSM data but I receive some following errors:
Unrecognized option: --read-pbf
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
I downloaded osmosis from http://wiki.openstreetmap.org/wiki/Osmosis 
and osm.pbf file (antarctica-latest.osm.pbf) from http://download.geofabrik.de/
My Java version is 1.8.0_181 running on ubuntu 16.04.5 x64
Can you help me to solve that problems, thank you

**Comment by JWJoubert** [comment]
Hi @thth776 I'm not sure why you use the `java -cp osmosis.jar` command. After installing osmosis, I use it by simply calling `path/to/osmosis --read-pbf ...`

See the [examples](https://wiki.openstreetmap.org/wiki/Osmosis#Detailed_usage). Also, I don't know why you have the backslash in from of `completeWays`: in my view it should be `completeWays=true` without spaces (but I'm not sure how the spaces are interpreted).

And this works on my Mac and ons my server (Linux Ubuntu)

**Comment by mrieser** [comment]
It looks like you forgot the main class to execute. So either try to just start `osmosis` as @JWJoubert suggested, or try the following:

    java -cp osmosis.jar org.openstreetmap.osmosis.core.Osmosis --read-pbf ......

Also, I don't think antarctica covers the specified bounding-box... although I'm highly interested in a MATSim model for Antarctica! :-)
