### ISSUE TITLE
What are the possible inputCRS and coordinateSystem?

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#130]
Hello,

This is an extremely simple question. What are the possible 'inputCRS' and the globale > 'coordinateSystem' ? I saw there is Atlantis, but what are the other available ? WGS84 for example ? Lambert93 ?

**Comment by JWJoubert** [comment]
Hi @RobertsOwen the _preconfigured_ ones are captured in the class `org.matsim.core.utils.geometry.transformations.TransformationFactory` but you can pass any EPSG code as a `String` to describe the coordinate reference system.

**Comment by JWJoubert** [comment]
The short `String` version is [here](https://github.com/matsim-org/matsim/blob/master/matsim/src/main/java/org/matsim/core/utils/geometry/transformations/TransformationFactory.java) while its detailed definitions are [here](https://github.com/matsim-org/matsim/blob/master/matsim/src/main/java/org/matsim/core/utils/geometry/geotools/MGC.java). Still, probably better to just find and use the correct EPSG code.

**Comment by PlumeRoberts** [comment]
Thank you very much.
