### ISSUE TITLE
Apply zones to network

### ISSUE THREAD

**Issue by NandaYogeshwar** [matsim-org/matsim-code-examples#131]
Hi,
I'm trying to apply a grid network onto my MATSim network, that divides it into squared zones. I came across the zone contribution (within the dvrp contrib). Unfortunately I can't find any examples. Therefore I'm a bit stuck and am not sure how to apply it. Right now I tried the following code but I'm not sure, the resulting XML is supposed to look like this (shouldn't it contain more information about e.g. the centroid of the zone etc.?):

My code:

``` 
SquareGrid grid = new SquareGrid(scenario.getNetwork(), 50);
Map<Id<Zone>, Zone> zones = new HashMap<Id<Zone>, Zone>();
for(int i = 0; i < grid.getZones().length; i++){
  zones.put(Id.create(grid.getZones()[i].getId(), Zone.class), grid.getZones()[i]);
}
ZoneXmlWriter zoneXmlWriter = new ZoneXmlWriter(zones);
zoneXmlWriter.write(ZONE_FILE);
```

And an extract from the resulting XML:
```
	<zone id="3640" type="square"/>
	<zone id="3638" type="square"/>
	<zone id="3639" type="square"/>
	<zone id="3630" type="square"/>
	<zone id="3631" type="square"/>
	<zone id="3632" type="square"/>
	<zone id="3633" type="square"/>
	<zone id="3634" type="square"/>
	<zone id="3635" type="square"/>
	<zone id="3636" type="square"/>
	<zone id="3637" type="square"/>
	<zone id="3650" type="square"/>
	<zone id="3651" type="square"/>
	<zone id="0" type="square"/>
	<zone id="3649" type="square"/>
	<zone id="1" type="square"/>
	<zone id="2" type="square"/>
	<zone id="3" type="square"/>
	<zone id="4" type="square"/>
```

I would appreciate any help, either as to what I'm doing wrong or example code, that I overlooked.

Thanks very much in advance!

Nanda

**Comment by michalmac** [comment]
To simply use a square grid the first line is enough:
```
SquareGrid grid = new SquareGrid(scenario.getNetwork(), 50);
```

The resulting XML is okay. No need to save the grid to a file, however, if you want to do so and then read it back from the file, you also need to write the shape file, which you can do by adding this line:
```
new ZoneShpWriter(zones, coordinateSystem).write(SHP_FILE)
```


BTW. This is not an official Zone in MATSim. Not even sure if there is one official implementation. You may also have a look at other implementations and choose the one that fits your needs. For instance, the accessibility contrib also comes with zone-related functionality (in the package `org.matsim.contrib.accessibility.gis`)

**Comment by NandaYogeshwar** [comment]
Thank you very much for your answer! I will try it without saving the grid to a file.
