### ISSUE TITLE
User guide cannot be dowloaded

### ISSUE THREAD

**Issue by davidwedekind** [matsim-org/matsim-code-examples#133]
The user guide cannot be downloaded via http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf. The loading screen appears but nothing happens, the download does not start.

**Comment by dhixsingh** [comment]
Seems to be working ok from here in Australia at the moment. It can also sometimes be slow I have found, so perhaps make sure it is not your browser timing out.

**Comment by davidwedekind** [comment]
Thanks for the hint. In the end, the download just did not work on Chrome (V 74.0.3729.169) but on Internet Explorer (V. 11.503.17763.0IC).
