### ISSUE TITLE
handling PersonMoneyEvent at the end of iteration

### ISSUE THREAD

**Issue by zahra-n1** [matsim-org/matsim-code-examples#135]
Hi,
We'd like to implement thresholds for the amount of money that agents pay in the simulation. To do so, we've created a handler to be called at the end of each iteration and refund the agents a certain amount of money (in a way that the refunded money is considered in their scoring) by processing a PersonMoneyEvent. We were expecting to be able to process the PersonMoneyEvents at ScoringEvent or AfterMobsimEvent (with a given time, e.g. midnight), but it seems that the PersonMoneyEvent is ignored after mobsim step. The only event that we managed to get it to work is at MobsimAfterSimStepEvent, which presumably increases the run overhead as it is triggered after each simulation step. To remedy that, the code goes through the processing only if the simulation step time is midnight, but it may cause inaccuracies.
So the question is what is the event that can be used at the end of each iteration to process the PersonMoneyEvent in the correct way.
Thanks a lot.

**Comment by JWJoubert** [comment]
@zahra-n1 nice question. I'm also interested in the answer. 

The way I've overcome it in the past is to generate/implement a complete new `ScoringFunctionFactory` but I'm still not convinced that was the most efficient way of getting it done.

**Comment by jfbischoff** [comment]
MobsimAfterSimStepEvent should work., the performance decrease is, in my opinion, negligible.
 
To circumvene the midnight problem, you could use the end time from the config, i.e.

`if (simTime == config.qsim().getEndTime()-1`

---

Then again, Johan's method might be more elegant.

**Comment by zahra-n1** [comment]
Great idea @JWJoubert !
Thanks  a lot @jfbischoff , but it seems that if (simTime == config.qsim().getEndTime()-1) doesn't work for us. Any time after midnight seems to be ignored. Could it be because of the plans? or does it sound like sth that we need to be worried?
Also, I was just wondering if there is an explanation for why PersonMoneyEvent can't be processed after mobsim. Is there anyway to find out what event can be processed in which step (with no trial & error)?
Thanks.

**Comment by ikaddoura** [comment]
Why don't you just write your own person money events handler which checks during the simulation each agent's total daily payments and once a certain threshold is reached reimburses any further money event (by throwing the same money event with a positive amount instead of a negative amount)?

**Comment by zahra-n1** [comment]
Thanks @ikaddoura, of course that's a better solution. My follow-up questions are just to better understand  how MATSim works, to avoid mistakes and time-consuming try&error method in the future. Thanks.
