### ISSUE TITLE
null node using the autonomous taxi 

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#138]
Hello,

Running a big simulation with 200'000 agents and 40'000 taxis, it end up with an error because "No route was found from node null to node 25275080". I do not understand how it can be and I don't see a solution. Can someone explain how it can occur ?

Thank you for your time.

[taxis40k_random.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3264961/taxis40k_random.xml.txt)

[config.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3264962/config.xml.txt)

GitHub stops me from posting the network and the agents plans because of the size.

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/3264975/logfile.log)

**Comment by michalmac** [comment]
A potential reason is that your network is a disconnected graph: https://en.wikipedia.org/wiki/Connectivity_(graph_theory)

**Comment by PlumeRoberts** [comment]
Yes, indeed. I ran NetworkCleaner and it worked.

Thank you very much.
