### ISSUE TITLE
Urban Air Mobility network & fleet size optimization

### ISSUE THREAD

**Issue by AnneBartB** [matsim-org/matsim-code-examples#139]
Dear MATSim community,

A fellow student and I are working on designing a route network for an Urban Air Mobility System. We have data on what amount of passengers want to travel from different areas to other areas at different times of the day. *We have to determine the number of areas we want to efficiently serve the most people while minimizing the fleet size and the waiting time of potential passengers*. (So if an area almost does not make use of the system, it could be left out, because it does not add value in any kind of way).

Our vehicle will be able to carry a maximum of 4 passengers, however, it is allowed to take off with less than the maximum capacity of passengers in it if this leads to a more efficient overall system. The system will only know where what amount of passengers are waiting at that point in time, so it will not know how the demand changes in a few minutes / hours. 

The main problem is, that we have a very limited time space (1 to max 1,5 weeks). Do you have any recommendations on how to approach this problem? If someone would be willing to help us out or provide us with any useful information that would be highly appreciated!!

Kind regards,
Anne Bart Beijneveld & Birgitte Hennink

**Comment by michalmac** [comment]
You could simulate your system using the DRT contrib/extension. In this project: https://github.com/matsim-org/matsim-maas, you will find a stop-based example that you can start from.

Running a simulation will give you some performance indicators for a given UAM setup. To answer you main question, you need to run multiple simulations to find out the best one.

**Comment by AnneBartB** [comment]
Dear Michalmac,

Thank you for the tip! We have started to work with this particular project and it looks like it might be of great use to us. However, we're still struggling with getting it to work the way we would like it to.
In "Scenarios > Mielec_2014_02 > network.xml"  we have changed this network that was originally used to a simplified version of our own Network. When we then try to run "mielec_drt_config.xml", all the different outputs remain un-updated. We did update the configuration file and plans file. Do you have any idea why "output_events" this is not updated to the new network? (Besides this, all other output files remain unchanged too). 

Hopefully, you have a clue! Thank you in advance!

Kind Regards,
Birgitte & Anne Bart

**Comment by michalmac** [comment]
Could you attach the log file? Otherwise it is hard to say what went wrong. Thanks.

**Comment by AnneBartB** [comment]
Dear Michalmac, 

Thank you for your quick reply every time we posted something. However, due to the time constraint, we have decided to use a more simplistic optimization. If we have the time after our project, we will definitely look into the matter again. Thanks again for your time!

Kind regards,
Birgitte & Anne Bart
