### ISSUE TITLE
Flexible-route transit

### ISSUE THREAD

**Issue by gregmacfarlane** [matsim-org/matsim-code-examples#14]
I know that MATSim is capable of running flexible route transit services based on papers [like this one](https://www.sciencedirect.com/science/article/pii/S2352146517309262) by @jishnuns and others, but I don't see any examples on how to specify the route areas or make them available to agents in the sim.

**Comment by michalmac** [comment]
There is a new project where we want to store all examples related to non-flexible services/on-demand: https://github.com/matsim-org/matsim-maas
There are already a couple of them, and we are going to add more in the near future.

**Comment by gregmacfarlane** [comment]
Thanks for sending that along. If I'm following everything correctly, it seems that there are effectively two paradigms for service:

  - A door-to-door service that takes people from their origins to their destinations, sharing rides as the vehicle capacity allows.

  - A stop-based service where vehicles take people to and from discrete points in a network, sharing rides as the vehicle capacity allows. 

In both cases, the vehicles begin service on a specific network link, but there isn't anything restricting the area in which they serve.  In many existing demand responsive services, vehicles will remain within a particular area, traveling to and from a heavy rail system (for example). Is there a way to specify this kind of service?

**Comment by ikaddoura** [comment]
Simply implement your own DrtRequestValidator. Have a look into the RunDrtExampleIT.

**Comment by gregmacfarlane** [comment]
Do you have a link to the `RunDrtExampleIT`?

**Comment by ikaddoura** [comment]
oh, sure.
https://github.com/matsim-org/matsim/blob/master/contribs/drt/src/test/java/org/matsim/contrib/drt/run/examples/RunDrtExampleIT.java
