### ISSUE TITLE
org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.core.population.routes.NetworkRoute

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#140]
Hello,

I have absolutely no idea why this error occurs, where it occurs or any of the data that may be at fault because those data work on other project.
I am running a heavy simulation including autonomous taxis.

I would like to know if anyone lnow why this error may occur.

Thank you for your time.

[config.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3265380/config.xml.txt)

**Comment by michalmac** [comment]
Could you attach a log file? Thanks.

**Comment by PlumeRoberts** [comment]
Sorry I forgot to add it. Here it is. 

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/3265634/logfile.log)

**Comment by michalmac** [comment]
The reason behind is a bit complicated and relates to the way private vehicles are auto-generated for each person.

You need to remove `taxi` from:
```
		<param name="mainMode" value="taxi,car" />
```
in the QSim config.

In short: people use the taxi mode to call a taxi, but taxicabs are simulated as cars in QSim. So we do not want to generate a taxicab for each passenger.

**Comment by PlumeRoberts** [comment]
Thank you very much, I could never find this out.
