### ISSUE TITLE
QSim error without details

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#141]
Hello,

I am trying to run a simulation, but a QSim error shows up and it is lacking details (at least in the log) for me to understand it myself. I've been looking at the config file, taxis file and other, but I have not found where the error could be. I guesse it may be in the controler but I didn't found it.
Would womebody kind enough to help me on this matter ?

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/3266120/logfile.log)

[config.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3266125/config.xml.txt)

Thank you very much fo ryour time and excuse me for soliciting you so much.

**Comment by michalmac** [comment]
```
org.matsim.contrib.dvrp.vrpagent.VrpAgentSource.insertAgentsIntoMobsim(VrpAgentSource.java:71)
```
has many meanings depending on which matsim version you are using. If you are using matsim 0.10 then there is a problem with the start link of one of your taxis. (Maybe a side effect the network cleaning you have recently performed???)

**Comment by PlumeRoberts** [comment]
Indeed, I generated the taxi file before running the network cleaner. Thank you very much for the help you gave me today.
