### ISSUE TITLE
Ways to get the simulation to go faster

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#143]
Hello,

we are running a Simulation with 200'000 agents and 40'000 autonomous taxis, and we are facing a problem, the simulation simply take to long. Even after 6 hours of calculation, we weren't able ta reach 08:00:00. It simply go up until 07:00:00 and do its work, simulating and generating events, but never reaches the next hour.

I would like to know if there is ways to get it to go faster, other than reducing the scale of the simulationn which isn't done yet because we would like to keep the precision.
But if it is the only way, we will do it.

Thank you very much for your time.

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/3275305/logfile.log)

[config.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3275317/config.xml.txt)

**Comment by michalmac** [comment]
You need to adapt the taxi config as it was shown in #126 (incl. the optimiser params).

**Comment by PlumeRoberts** [comment]
Indeed thank you very much.
