### ISSUE TITLE
MATSim link ID for bus stops

### ISSUE THREAD

**Issue by TaniyaSultana** [matsim-org/matsim-code-examples#146]
Is it possible to pull out MATSim link ID for the bus stops of a particular bus route?

**Comment by mrieser** [comment]
The link id of a TransitStopFacility must be specified in transitSchedule.xml, and there is also a getter for it in the code, e.g. `TransitStopFacility busStop = ....; Id<Link> stopLinkId = busStop.getLinkId()`

**Comment by TaniyaSultana** [comment]
Thank you very much Mrieser. Can you please give me more details? e.g. where and how to get the link IDs? Thank you again.

**Comment by mrieser** [comment]
In the code, you should have access to the scenario. Then, you could write something like this to access all links of a bus route:

```java
TransitSchedule schedule = scenario.getTransitSchedule();
Id<TransitLine> lineId = Id.create("my-line-id", TransitLine.class);
Id<TransitRoute> routeId = Id.create("my-route-id", TransitRoute.class);

TransitLine line = schedule.getTransitLines().get(lineId);
TransitRoute route = line.getRoutes().get(routeId);

for (TransitRouteStop stop : route.getStops()) {
  TransitStopFacility facility = stop.getStopFacility();
  Id<Link> linkId = facility.getLinkId();
  System.out.println(linkId.toString());
}
```

**Comment by TaniyaSultana** [comment]
Thanks a lot Mrieser. should I write these codes in the config file or schedule file?
