### ISSUE TITLE
how to reach a reasonable computation time ?

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#149]
Hello,

I ran a simulation overnight to let it process all the data, so it ran for more than 15 hours.

This morning I came back hoping to see at least 1 or 2 iterations, but it didn't even do a single iteration. Here is the log:

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/3289431/logfile.-.Copie.log)

This clearly isn't working out so I'd like to know how to make it run over a reasonable time, other than diminishing the number of Agents.

[config.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3289450/config.xml.txt)

There is here a little bit over 200'000 agents

Thank you for your time.

**Comment by michalmac** [comment]
DRT is slower than taxi, because the underlying optimisation problem is more complex.

Some basic info on the biggest scenario we have run so far: https://github.com/matsim-org/matsim/pull/274#issuecomment-390388047

But that network was simplified before running, which probably helped with speeding up things, but not sure by how much. And we run it on a machine with 12 logical cores and 32GB of RAM.

I suggest trying DRT first with a smaller problem like 20k agents.

**Comment by PlumeRoberts** [comment]
Alright, thank you very much for you answer. Sadly we don't have a Computer that powerfull avaible so we will probably use 20'000 agents, even if it mean loosing so much precision.

**Comment by michalmac** [comment]
UPDATE:
Actually, we run 100% DRT for Berlin as well. The mobsim itself took 31 h, whereas for 10% it took only 1.5 h. Looking at the outcomes: relatively, a bit more vehicles were busy in 10% than in 100% as it was harder to have 4 passengers on board at the same time (we used the vehicle capacity of 4). But in general the picture was very similar.

**Comment by PlumeRoberts** [comment]
I see. the problem on our side is that we use pretty fine data, talking about some times ONE agents having an unique plan, so we can not simply divid the number of agents by 10, we'll need to select the agents to delete.

How many iteration were done in 90 minutes in the 10% scenario ?

**Comment by jfbischoff** [comment]
>Alright, thank you very much for you answer. Sadly we don't have a Computer that powerfull avaible so we will probably use 20'000 agents, even if it mean loosing so much precision.

Actually, the precision you lose is relatively small. DRT and taxi tend to scale down rather well.

**Comment by michalmac** [comment]
> How many iteration were done in 90 minutes in the 10% scenario ?

All the numbers I gave were all about a single iteration.

**Comment by g-bd** [comment]
Just for comparison our Tel-Aviv Metropolitan area DRT simulation takes about ~1 hours for each iteration with departure time mutation and plan selection turned on. The network is about ~20k links. The population is also 10% which is about 330k agents. The running time is almost the same for 5k-40k vehicles (with 4 seats).

**Comment by golanbendor** [comment]
Just for comparison our Tel-Aviv Metropolitan area DRT simulation takes about ~1 hour for each iteration with departure time mutation and plan selection turned on. The network is about ~20k links. The population is also 10%, which is about 330k agents. The running time is almost the same for 5k-40k vehicles (with four seats).

**Comment by PlumeRoberts** [comment]
This Île-de-France Simulation, The whole region aroung Paris, involved over 200k agent, the OSM Network, which means over 250k links and 33k vehicles, and running over night (15 hours) it went from 07:00:00 to 08:00:00 of the 1st iteration.
We needed a reasonnable computation time so we launched a 10% simulation returning to 20k agents, because we are not able to deploy bigger computers.

**Comment by michalmac** [comment]
> And we run it on a machine with 12 logical cores and 32GB of RAM.

Just to clarify things - you do not need such a machine. A typical "everyday productivity" laptop with 4 physical cores is enough to get most of the speed up in DRT. In your log, the used memory was also quite far from the max memory.
