### ISSUE TITLE
Why are two facilities associated with a single facility id in facilities.xml files?

### ISSUE THREAD

**Issue by saxenism** [matsim-org/matsim-code-examples#152]
The code below makes sense that a particular location marked with a particular co-ordinates represent a specific facility.

    <facility id="15" x="260.0" y="110.0">
        <activity type="leisure">
        </activity>
    </facility>

But, what does the below code depict??

    <facility id="4" x="310.0" y="150.0">
        <activity type="home">
        </activity>
        <activity type="shop">
        </activity>
    </facility>

**Comment by mrieser** [comment]
The `activity` describes, what type of activities can be performed in a facility. Think of the facility as a building, and what you can do in that building. Maybe it's a restaurant, than you can either `work` there, or spend `leisure` time there. Or it's a shop, than you could `shop` there, `work` there, and maybe in the same building on the upper floors are flats, so you can be at `home` there.

**Comment by saxenism** [comment]
Ok, I get this now. Thanks. One more thing though, if we have to introduce another activity in MATSim such as charging of an EV, how do we go about it? Do we simply write it up in a facilities.xml file or do we have to make changes elsewhere?
Thanks.
