### ISSUE TITLE
How is the vehicles capacity of an arc is determined ?

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#157]
Hello,

I am wondering how the number of vehicles an arc is able to hold is determined using qsim. I guess in JDEQSim, it is the length times the number of ways divided by the length of a vehicles but what about QSim ?

Thank you.

**Comment by mrieser** [comment]
It's the same in QSim, link_length  * number_of_lanes / vehicle_length. This "storage capacity" is then multiplied with the storageCapFactory (in the qsim-configuration) to adapt to simulations where only a sample is simulated.
