### ISSUE TITLE
Maven build issue with MATSim 11

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/matsim-code-examples#165]
Hi all,

a project that uses MATSim 11 as a dependency breaks when building with maven, resulting in the following errors:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project mito: Compilation failure: Compilation failure:
[ERROR] error: error reading C:\Users\Nico\.m2\repository\javax\media\jai_core\1.1.3\jai_core-1.1.3.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Nico\.m2\repository\jgridshift\jgridshift\1.0\jgridshift-1.0.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Nico\.m2\repository\javax\media\jai_core\1.1.3\jai_core-1.1.3.jar; error in opening zip file
[ERROR] error: error reading C:\Users\Nico\.m2\repository\jgridshift\jgridshift\1.0\jgridshift-1.0.jar; error in opening zip file
```

I tried clearing the local mvn repo and rerun clean install but still got the same issue. When trying to open the downloaded .jar it says that the files are corrupted.

Was there any change to matsim dependencies?

Meanwhile, what worked for me is to exclude them in the dependencies as they seem to be transitive from geotools through matsim - not sure if this is something one should do though :)
:
```
 <dependency>
            <groupId>org.matsim</groupId>
            <artifactId>matsim</artifactId>
            <version>${matsimVersion}</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>javax.media</groupId>
                    <artifactId>jai_core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>jgridshift</groupId>
                    <artifactId>jgridshift</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by michalmac** [comment]
to me it looks like the OSGeo maven repo issues (happened to me at least once)

**Comment by nkuehnel** [comment]
@michalmac how did you fix it?

**Comment by michalmac** [comment]
just waited a while :-) ?? 

But you could try adding an alternative repo to your pom.xml. For instance, jgridshift is on 
Geomajas and OSGeo (see: https://mvnrepository.com/artifact/jgridshift/jgridshift/1.0).

**Comment by nkuehnel** [comment]
okay ;) thanks!
