### ISSUE TITLE
The different datas outputed by MATSim using the DRT contrib

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#169]
Hello,

I am using the DRT contribution and I am having trouble understanding the signification of all the data. Is there a documentation explaining what each file, each column and each image represents ?

Thank you very much.

**Comment by jfbischoff** [comment]
Hi, most things are documented in the headers of the CSV files. That's as much documentation we provide by default. Let us know if there's anything particular that's unclear.

**Comment by PlumeRoberts** [comment]
Thank you for helping me. Here are my concerns:

on the csv files:
I do not understand the X.drt_alightments_drt.csv and X.drt_boardings_drt.csv, why is the **x** always equal to the **y** and what does it represent ?
X.drt_detours_drt.csv: I do not understand the **distanceDetour** and **timeDetour** columns, I think they are a ratio ?
X.drt_trips_drt.csv: I do not understand the difference between **travelDistance_m** and **directTravelDistance_m**.
X.vehicleDistanceStats_drt.csv: what represent the **revenueDistance_pm** field ?

For the images, there is mainly on important thing, what is the difference between a **travel** and a **ride** ?

Thank you very much

**Comment by jfbischoff** [comment]
>I do not understand the X.drt_alightments_drt.csv and X.drt_boardings_drt.csv, why is the x always equal to the y and what does it represent ?

Oh, actually these should be coordinates. Apparently, there's a bug in the output. I will fix this.
These numbers are boardings and alightments per location aggregated over the day.

>X.drt_trips_drt.csv: I do not understand the difference between travelDistance_m and directTravelDistance_m.

in DRT, passengers make detours in order to pool with other passengers. travelDistance is the actual travelled distances of a ride, whereas directTravelDistance represents the direct travel distance, if no pooling would have been involved.

>X.vehicleDistanceStats_drt.csv: what represent the revenueDistance_pm field ?

revenue distance (in Personmeters) is the distance traveled by a vehicle multiplied by the number of people on board. 


Travel and ride is usually the same.

**Comment by PlumeRoberts** [comment]
Thank you very much for those explanation.

If so, I do not understand the diffference between **x.drt_detours_drt_rideTimePlot.png** and **x.drt_detours_drt_travelTimePlot.png**

**Comment by michalmac** [comment]
> If so, I do not understand the diffference between x.drt_detours_drt_rideTimePlot.png and x.drt_detours_drt_travelTimePlot.png

Travel is Wait+Ride, so without prebooking `Travel time  > Ride time` unless you are very lucky and the bus is already at your door (by coincidence).

**Comment by PlumeRoberts** [comment]
I understand, thank you very much you for your explanations.

**Comment by PlumeRoberts** [comment]
I am really sorry. It seems I wen tto fast, there are still files I do not understand, and it is the files in the root folder: 
drt_customer_statcs_drt.csv and the "mean" attributes:
inVehiclesTravelTime_mean
distance_m_mean
directDistance_m_mean
totalTravelTime_mean

drt_vehicle_stats_drt.csv:
totalRevenueDistance 
averageRevenueDistance
d_r/d_t
l_det 

I am sorry for the closing/reopening, but I need these informations to complete my documentation.

**Comment by jfbischoff** [comment]
>inVehiclesTravelTime_mean
>distance_m_mean
>directDistance_m_mean
>totalTravelTime_mean

These are average values over all trips.

>totalRevenueDistance
>averageRevenueDistance

These are the fleet-wide and average (per vehicle) revenue distance.

>d_r/d_t
>l_det

These are detour factors, see
J. Bischoff, M. Maciejewski, K. Nagel City-wide Shared Taxis: A Simulation Study in Berlin, IEEE ITSC 2017, DOI: 10.1109/ITSC.2017.8317926<https://doi.org/10.1109/ITSC.2017.8317926>
for more details about them.
