### ISSUE TITLE
Via doesn't load - 'StringIndexOutOfBound' exception

### ISSUE THREAD

**Issue by rutym** [matsim-org/matsim-code-examples#177]
Hi all.
I've downloaded the newest Via version (19.2, released on May 2019), and I'm trying to run it on my linux machine, using Java 11.
Unfortunately, there's a 'StringIndexOutOfBound' exception when trying to load the painter, and the software doesn't even present the painter - it gets stuck on the opening screen (the red-purple one that says 'Via' and presents the license details). Anyone encountered this issue?
I already tried removing the installation and all related hidden files and download them again. 
I also tried looking for help in simunto's website, but didn't found this problem in their FAQ page. It also seems they don't give links to older versions of Via on their site. I did manage to find their contact email(via@simunto.com) and send them a question, but if anyone has encountered this issue, I'd highly appreciate you helping me resolve this.

I'm attaching the log file with the exception: [via.log](https://github.com/matsim-org/matsim-code-examples/files/3389900/via.log)

**Comment by mrieser** [comment]
Via, just like the latest MATSim version, requires Java 8 and has known problems to start on Java 11.

The next version of Via is planned to run on Java 11, you can give the current development version a try by downloading it from https://simunto.com/via/download-beta. But please be aware that being it a beta version, there likely are other problems with the software currently, as the change from Java 8 to Java 11 required the replacement of quite a lot of functionality in Via.
