### ISSUE TITLE
MATSim course at TU-Berlin

### ISSUE THREAD

**Issue by SarahSie** [matsim-org/matsim-code-examples#178]
I would like to have access to the online-course software where the slides and exercises are uploaded to for MATSim course at TU-Berlin.
I have the link and joined as guest. However, some documents are missing and are not uploaded there. For example "Using Collections: The difference between Set and List".
I will be happy if you can kinly provide me with all the slides.

**Comment by jfbischoff** [comment]
In general, everything relevant is part of the public course, so there is no need to access the other one.
A new version for MATSim 11 should be out soon.
