### ISSUE TITLE
Issues in running extension- DVRP, otfvis, Analysis

### ISSUE THREAD

**Issue by Sharmeela16** [matsim-org/matsim-code-examples#18]
I am facing issues in running matsim and its extensions- DVRP, OTFVis, Analysis, etc. I come from a non-programming background and need help to understand the process to run Matsim with it's extensions. I am able to to run Matsim.jar independently but unable to use it with extensions.

java -Xmx500m -cp matsim-0.10.1.jar:dvrp-0.10.1/dvrp-0.10.1.jar org.matsim.contrib.dvrp
I am using this command to run DVRP extension and getting an error-
Error: Could not find or load main class org.matsim.run

What should I do?

**Comment by mrieser** [comment]
are you running it on Linux or Windows? If on windows, replace the : with ;  For example:

    java -Xmx500m -cp matsim-0.10.1.jar;dvrp-0.10.1/dvrp-0.10.1.jar org.matsim.contrib.dvrp

Also, I think that command is not complete, as it only specifies a package name in the end, but not a main class.

**Comment by Sharmeela16** [comment]
I am using it on windows, and tried it with ; still didn't work
how do I specify main class?

**Comment by jfbischoff** [comment]
In general, we do not support the use of Contribs via the Command line anymore. It's error prune and support is hard to provide.
Please consider checking out  https://github.com/matsim-org/matsim-code-examples or, if your specifically interested in DVRP / Taxi / DRT, https://github.com/matsim-org/matsim-maas , which contains some more guidance of using Dynamic Transport Modes in MATSim.

**Comment by Sharmeela16** [comment]
yes i am interested in DRT, but i am unable to run dvrp jar file of matsim extension, I am using dvrp-0.10.1 version

**Comment by jfbischoff** [comment]
Please try to check out the matsim-maas repository using git and an IDE. This is your best bet to get going.

**Comment by Sharmeela16** [comment]
I tried to run java eg mentioned above, I loaded matsim dvrp, drt jars into my java project i am getting some errors, let me know if I am missing some parameters.
`Exception in thread "main" javax.validation.ConstraintViolationException: 
Errors in config:
dvrp.mode: must not be null
	at org.matsim.contrib.util.BeanValidationConfigConsistencyChecker.checkConsistency(BeanValidationConfigConsistencyChecker.java:55)
	at org.matsim.contrib.dynagent.run.DynQSimConfigConsistencyChecker.checkConsistency(DynQSimConfigConsistencyChecker.java:34)
	at org.matsim.contrib.dvrp.run.DvrpConfigConsistencyChecker.checkConsistency(DvrpConfigConsistencyChecker.java:32)
	at org.matsim.contrib.drt.run.DrtConfigConsistencyChecker.checkConsistency(DrtConfigConsistencyChecker.java:35)
	at org.matsim.core.config.Config.checkConsistency(Config.java:227)
	at org.matsim.contrib.drt.run.DrtControlerCreator.adjustConfig(DrtControlerCreator.java:119)
	at org.matsim.contrib.drt.run.DrtControlerCreator.createControler(DrtControlerCreator.java:68)
	at com.sharmeela.drt.taxi.run(taxi.java:44)
	at com.sharmeela.drt.taxi.main(taxi.java:51)`

[config.txt](https://github.com/matsim-org/matsim-code-examples/files/2457588/config.txt)

**Comment by jfbischoff** [comment]
You are mixing up versions here, it seems.
If you use the release version (by using the 0.10.1 jars), you need to use config file that work for 0.10.
You can find example files within the resource path of the DRT jar or here:
https://github.com/matsim-org/matsim/tree/0.10.x/contribs/drt/src/main/resources

The matsim-maas runs on the snapshot, where some config parameters have changed in the last weeks. To use these, check out the git project and use maven within your IDE.
