### ISSUE TITLE
Waiting time in scoring part of the taxi mode

### ISSUE THREAD

**Issue by Lichen-L** [matsim-org/matsim-code-examples#180]
Hi all MATSimians,

I am now working with the taxi contrib in MATSim (ver. 0.10.1) and it just make me wonder that if waiting time is incorporated in scoring part of the taxi mode. That is, will waiting time be processed (just as travel time) by the "marginalUtilityOfTraveling_util_hr" in "modeParams" of taxi ?

Btw, I cannot help noticing that there exists a "taxifare" module, which has "distanceFare_m" parameter. Is this different from the "monetaryDistanceRate" parameter in "modeParams"?

Thank you for the time.

Lichen

**Comment by jfbischoff** [comment]
Hi Lichen,

Waiting times are indeed processed as marginalUtilityOfTraveling_util_hr. 

>Btw, I cannot help noticing that there exists a "taxifare" module, which has "distanceFare_m" 
parameter. Is this different from the "monetaryDistanceRate" parameter in "modeParams"?

The monetaryDistanceRate is based on the distance written into the (pre-computed) route of an agent's leg.
For taxi (and other dynamic modes), these routes are calculated on the spot and thus the information in the pre-computed leg is not very accurate. The taxifare module circumvents this by measuring the actually driven route. In a way, it works like a taximeter :-)

**Comment by Lichen-L** [comment]
Hi Mr.Bischoff,

Thank you for your answers, you perfectly clear up my doubts.

Lichen
