### ISSUE TITLE
How to create person attributes?

### ISSUE THREAD

**Issue by paud0** [matsim-org/matsim-code-examples#182]
Hello,

I read that a MATSim person is attributable since version 12.
Is there a way to define an attribute like "possible transport modes" per agent?
And ifnot is there a way to define the subpopulation an agent is part of directly from plans file without using a person attributes file?

Thanks in advance
Paul

**Comment by JWJoubert** [comment]
@pdowideit indeed, being `Attributable` means you can come up with any attribute (and also call it what you want). The fact that you _can_ does, of course, not mean you _should_.

The attributes is simply a container of data. It does not, automagically, make the code know about it. If you introduce a new attribute, you should also introduce the machinery (be it routing, scoring, replaning, etc) that _uses_ that attribute(s).

> is there a way to define the subpopulation an agent is part of directly from plans file without using a person attributes file?

Indeed, as part of the refactoring, the attribute `subpopulation` is now standard in the plans file, so you need not have it separately defined in a person attributes file. I say the attribute `subpopulation` is _standard_. You can change that name in the config file, but I don't recommend doing that. So, if you want to set a person's subpopulation, you could do it as follows:

```
person.getAttributes().putAttribute( config.plans().getSubpopulationAttributeName(), "geeksOnUnicycles");
```

**Comment by paud0** [comment]
Okay thanks for the quick response!
