### ISSUE TITLE
using counts instead of population file

### ISSUE THREAD

**Issue by zahraeftekhar** [matsim-org/matsim-code-examples#183]
I have the link counts of several links in my network. Is it possible to directly feed the counts to MATSim instead of having a population file? For having population file we need to have the travel diary for each agent, what if we do not want to be this detailed and we want to simulate in a more general level of abstraction? Moreover, Do we need to initially know the type of each activity in the population file?

**Comment by mrieser** [comment]
MATSim is a tool to give detailed answers, and thus requires detailed data if it should be able to run realistic scenarios.

If you are missing data and want to get started, you could try to make assumptions and good guesses to initially substitute for missing data, but clearly the quality of your model will suffer from this.

> Do we need to initially know the type of each activity in the population file?

Technically, you could have all agents just travelling from `home` to `home` or from `work` to `work`, or more generally from `someActivity` to `someActivity`. But be aware that temporal restrictions like typical durations and opening times are defined per activity type. Having just one (or very few) activity type(s) will make it nearly impossible to calibrate your model.

You could start with simple "single-trip agents". These are agents that have just 2 activities and a single leg in the plan, where the activity locations can be free chosen based on e.g. population and workplace density. But such a demand will not allow you to use the full potential of MATSim.
