### ISSUE TITLE
Differences between the actual network and the network created in MATSim

### ISSUE THREAD

**Issue by OrranaLhaynher** [matsim-org/matsim-code-examples#185]
Hi! I'm working with the creation of a scenario where I have to use the road network of Hawaii, but while creating the input files to MATSim I've noticed that the network was filtraded and some of its routes have desapeared. For while I've only have the .osm file and I like to know if there's somethings wrong with my code. 

The real network -> https://github.com/OrranaLhaynher/matsim-example-project/blob/master/original-input-data/realnetwork.png

The filtered network -> https://github.com/OrranaLhaynher/matsim-example-project/blob/master/original-input-data/filterednetwork.png

My network code is here -> https://github.com/OrranaLhaynher/matsim-example-project/blob/master/src/main/java/org/matsim/project/network/NetworkGenerator.java

Thanks in advance for your attention and help!

**Comment by mrieser** [comment]
The OpenStreetMap data likely contains roads, but also paths and stairs which are only accessible by walking or maybe with a bicycle, but not with a car. The MATSim converter only keeps roads which are open to public cars, and it simplifies the road segments to straight lines between intersections. Also, parts of the road network which are not connected to the rest, get removed.

**Comment by OrranaLhaynher** [comment]
Thanks for your response! But I think something is wrong because there are five airports in Hawaii and there must be routes to these airports, but on the network these routes don't appear

**Comment by JWJoubert** [comment]
@OrranaLhaynher is it possible that they were tagged as `service` roads. Because, I think, by default the `OsmNetworkReader` ignores service roads. Just a thought.

**Comment by OrranaLhaynher** [comment]
Thanks for your response! I think your idea makes sense, but how can I fix it? Because I know .osm files have an attribute table with a column called highway, and sometimes that column is filled or not. And that is where the route is set as primary, service, and so on. But I don't know how to fix it.

**Comment by JWJoubert** [comment]
@OrranaLhaynher Once you created your `OsmNetworkReader`, the object has a method to overwrite the default highway types that MATSim will use. You can have a look at the defaults [here](https://github.com/matsim-org/matsim/blob/master/matsim/src/main/java/org/matsim/core/utils/io/OsmNetworkReader.java).

You will that the class has a `setHighwayDefaults(...)` method. So if you want to add `service` roads too, you can. You have to set the defaults _prior_ to parsing the `osm` file.  So, for example, something like...

```
onr.setHighwayDefaults(1, "service", 1, 60/3.6, 1, 600);
```

**Comment by OrranaLhaynher** [comment]
Thanks again! I didn't know about this method and I will surely try this.
