### ISSUE TITLE
Memory expectations for large scenario (~1 M agents)

### ISSUE THREAD

**Issue by josiekre** [matsim-org/matsim-code-examples#189]
I found an old document saying the following:

> Currently, we simulate most of our scenarios on machines with 16 or 32 GB RAM, having 2 dual- or quad-core processors. The amount of memory allows us to run 2 scenarios at the same time on the machines. [Source](https://github.com/matsim-org/matsim/blob/5b77bd781d18a2c11d44b31ef8180cfa4e2a9af8/matsim/docs/user-guide/chapters/sysRequirements.tex#L35)

Above that text, I see for large scenarios (described as 100 000+ agents, networks with 50 000+ links), "a high-end desktop computer with at least 4GB RAM and 200 GB free disk space" is needed. I'm running a scenario in Washington DC in the States. Here are some stats:
- 900k agents (15% sample)
- 84k links (including pt links)
- using a transit schedule that reflects an "average day" with headway simplifications
- no DRT or AVs
- Amazon Linux machine with 64 GB RAM and 8 virtual CPUs

I passed `-Xmx64g` into the call to MATSim to set the maximum heap size. Yet the scenario crashed in the 21st iteration, I think due to memory. There's no memory error in the log, but in the past increasing the memory on the machine has led to a completed run.

The very first memory stats dump in the log at iteration 0 has the total memory at 19212 MB (~18 GB). The last log of memory before crashing is 55676 MB (~54 GB). See screenshot of log for reference (using SSH and a VIM session so pasting in the text was too much of a feat).

<img width="763" alt="Screen Shot 2019-08-12 at 1 09 38 PM" src="https://user-images.githubusercontent.com/5776153/62902416-613e9e00-bd14-11e9-8910-54c4c7b390ec.png">

A few questions:

1. Does this memory requirement match your expectations? It seems to scale somewhat linearly with the number of agents/links: 4GB RAM for 100k agents/50k links vs > 54GB RAM for 900k agents/80k links.
2. What drives the growth of heap size iteration after iteration if the number of plans per agent is limited to 5 (`config.strategy().setMaxAgentPlanMemorySize(5)`)? At the end of iteration 4, the total heap size was only 37 GB (~30 GB used).
3. I told Java to use up to 64 GB, but it crashed using around 54 GB. Since nothing else was running on this machine, could the stack take up ~10 GB? (If this seems fishy, is there something else I should be looking to as the cause of the error?)

**Comment by josiekre** [comment]
Looking actively during a run, I'm seeing that when MATSim outputs a "total" memory usage of ~32 GB in the log using `Runtime.getRuntime().totalMemory()`, a call to `top` from the commandline says the Java job is actually using about ~36 GB RAM. (So the stack must be about 25% of the heap at this point early in the run.)

If I extrapolate, that means a heap of 54 GB would require 54 GB * 1.25 = ~67 GB, so it would make sense that the machine would crash. 

This seems to support the idea that the rest of the ~10 GB was taken up by the stack (question 3 above). Questions 1 and 2 are still unanswered.

**Comment by mrieser** [comment]
1) 
Wow, that cited source is indeed old, based on the history it looks to be at least 5 years old, and the content is likely even older. I wouldn't be surprised if the quoted numbers are even from a time when public transport was rarely used. In the mean time, MATSim got more complex, and thus uses probably a bit more memory as well. Also, additional modules like PT or DRT may require additional memory as well as if one is only simulating private cars. The number of activity types also adds to the memory consumption, the more act types, the more memory.

But in general: Yes, the numbers match *my* expectations. I've recently run a scenario with around 1m agents, 250k links, 13 act types, maxAgentPlanMemorySize=3, and I had a similar observation: I was able to run a few iterations with < 64GB, but in the end had to switch to a larger machine so I could run it with around 95GB. Actual memory consumption was between 60 and 90 GB, but that's a typical range for Java applications such that the Garbage Collector can run efficiently.

2) 
> What drives the growth of heap size iteration after iteration if the number of plans per agent is limited to 5 (config.strategy().setMaxAgentPlanMemorySize(5))? At the end of iteration 4, the total heap size was only 37 GB (~30 GB used).

The configuration value is the number of plans per Agent. In each iteration, only a share of agents get a new, additional plan (typically around 30%, depends on the replanning configuration). It thus takes a lot more iterations until every agent has 5 plans.

3) 
Does the machine have swap space? Or is there a hard-limit for processes not being able to take more than 64 GB? If you specify `-Xmx64g`, that means that the Java heap can grow to 64 GB. But the JVM requires some memory on top of that for internal data structures. So it could be that while the Java process used 54 GB, it tried to allocate more memory (e.g. during Garbage collection when the JVM figured out, that it will need more memory in the future as the existing heap was getting full), ending up with a total consumption of more than 64 GB, which resulting in a failure from the operating system, as the JVM was not allowed to take as much memory (or, if there is no swap, there was actually not as much memory). The JVM being killed by the OS could also explain why you don't see an OutOfMemory exception.

**Comment by josiekre** [comment]
> Actual memory consumption was between 60 and 90 GB

Thanks. Good to know this. Do you have a rule of thumb for guessing a -Xmx setting for a particular run?

> only a share of agents get a new, additional plan

Good point! I forgot about the fact that only a certain number get a new plan each iteration.

> Does the machine have swap space?

A quick search seems to indicate that AWS EC2 machines do not have swap space by default. You have to set it up. So this is why.

**Comment by mrieser** [comment]
> Do you have a rule of thumb for guessing a -Xmx setting for a particular run?

The memory consumption depends on a lot of factors: 
- number of agents, 
- number of links in the network, 
- number of links in the average route (e.g. is the network very detailed, or just "large"),
- number of activity types,
- features (e.g. public transport, taxi, drt, ...)

In the models I have experience with, typically covering large urban areas, with a detailed network, around 15 activity types and public transport, I would estimate around 100KB per agent. That is 1 GB per 10k agents. But it really is just a single number estimation, which might not be applicable to different types of models (e.g. models for long-distance trips between cities).

(100KB per agent sounds like a lot.... would be interesting to see if we could reduce that in MATSim...)

**Comment by kainagel** [comment]
A route has very roughly sqrt(network size) link entries.  So a network of 10^6 links results in routes of 10^3 links.  Each agent has about 5 plans with about 3 routes each, this means 10^3 x 3 x 5 x 4Byte/word = 60kB per agent.  So this confirms @mrieser's order of magnitude.  (Could someone please check this calculation; I know that I keep getting it wrong.)  

One compression option are @mrieser's "compressed routes".  They should still be there.

**Comment by josiekre** [comment]
I'm following your calculations @kainagel. The only thing is that both @mrieser and I are usually running with a magnitude less than 1 million links (10^6). I'm usually <100k, and @mrieser's example had 250k.

**Comment by mrieser** [comment]
The calculation of @kainagel are covering only the (car-)routes in agents. But there is other stuff using memory as well (the network itself, agent and network attributes, routing-graphs, ...). And my 100kb/agent already includes the overhead the JVM needs to properly work, i.e. the actual memory consumption per agent would be lower.

Also, at least in your scenarios that I know, I think the agents have more than just 3 routes (=3 car-legs) per plan, which probably offsets the shorter routes from the smaller network.

**Comment by josiekre** [comment]
I think I can close this issue. Thanks for the input @mrieser and @kainagel.
