### ISSUE TITLE
Creating vehicle ID examples

### ISSUE THREAD

**Issue by Eunby** [matsim-org/matsim-code-examples#19]
Dear all,

I'm trying to create vehicle ID matched to the Person ID in MATSim. Is there any possibility to find an example for this?
Thank you!

**Comment by mrieser** [comment]
Id.create(personId.toString(), Vehicle.class)

**Comment by jfbischoff** [comment]
> Id.create(personId.toString(), Vehicle.class)

This is true, as long as agents only use cars as network modes.

If you use also other network modes, by default the Vehicle Id consists of the person Id followed by the network mode (EXCEPT for car).

` Id.create(personId.toString()+"_"+networkMode, Vehicle.class)
`
