### ISSUE TITLE
Assign vehicles to links but don't congest them

### ISSUE THREAD

**Issue by NandaYogeshwar** [matsim-org/matsim-code-examples#190]
Hi everyone, 

I'm working with the taxi contribution and added a taxi rank. Up until now, this was only a link where I send the taxis. The problem is that once I do that, those taxis congest that link for the amount of time, they are supposed to be staying at the rank. 
Now I wonder: Is there a possibility to send vehicles to a link, but once they reach it, they are 'assigned' to that link, but don't congest it? 

Thanks very much!

Nanda

**Comment by tschlenther** [comment]
Hi,
you can make the taxis execute a TaxiStayTask. In fact, in the taxi contrib, the last task in a taxi's schedule always should be a TaxiStayTask, so when you schedule a drive to the rank's link using the standard TaxiScheduler, this should be done automatically for you.

Cheers
Tilmann

**Comment by NandaYogeshwar** [comment]
Thanks for your quick response!

Since I have implemented a TaxiStayAtRankTask, which extends the TaxiStayTask, I figured the problem lies somewhere else: I had the flowCapacityFactor set to 0.03. Increasing it to 0.2 did the trick and decongested the links. But thanks anyway!
