### ISSUE TITLE
Remove damaged links in routes recommendation

### ISSUE THREAD

**Issue by OrranaLhaynher** [matsim-org/matsim-code-examples#192]
Hello! Using my network and population scripts, I was able to simulate my case study, but I realized that there were links that agents were using that should not be used. My case study is about evacuation, so there are parts of the network that were damaged during the disaster and could not be taken as an escape route. After some research I found that there is a way to create specific events on this case, but couldn't figure out how. Could someone explain to me how these events work and how can I use them?

**Comment by mrieser** [comment]
These "events" are so-called NetworkChangeEvents, which allow you to modify link-attributes at some point of time in the simulation, e.g. change the number of lanes, the free speed, or the capacity.

There is an example setup available at https://github.com/matsim-org/matsim-code-examples/tree/11.x/scenarios/equil-extended. Have a look at the files `config-with-network-change-events.xml` and `networkChangeEvents.xml`.

**Comment by OrranaLhaynher** [comment]
Thank you for answering me, I will definitely look at these files!

**Comment by OrranaLhaynher** [comment]
Your answer was of great help! Thanks again!
