### ISSUE TITLE
Problems while trying to implement a script to send evacuees to the nearest shelter

### ISSUE THREAD

**Issue by OrranaLhaynher** [matsim-org/matsim-code-examples#195]
In my case study there are some shelters where I should send evacuees from the danger area, but after several simulations and consequent changes, I realized that the recommended evacuate shelter was often not the closest. With that I started to implement this part, since in a real situation evacuates will go to shelters near their location. But I'm having trouble with that. I have a part already implemented in the scripts below, however I am unable to send to my agents the location of the nearest shelter to them. Please, does anyone know how to help me with this problem?

Script to create the population and set the near shelter -> https://github.com/OrranaLhaynher/matsim-example-project/blob/master/src/main/java/org/matsim/project/population/RunPopulationMaximumCapacityShelters.java

Script to set the shelter's coordinates -> https://github.com/OrranaLhaynher/matsim-example-project/blob/master/src/main/java/org/matsim/project/population/ShelterCoord.java

Thank you all in advance!

**Comment by kainagel** [comment]
Just looked at this, but the files seem to be gone.  The general approach for spatial queries would be a quad tree.  MATSim has an implementation in the package `org.matsim.core.utils.collections`.

**Comment by OrranaLhaynher** [comment]
Oh, thank you. I would definitely take a look at this implementation!
