### ISSUE TITLE
Some questions about "ev" contribution

### ISSUE THREAD

**Issue by applibres** [matsim-org/matsim-code-examples#198]
I have test RunEvExample.java from "ev" contribution (12.0Snapshot).  It is a little confusing for me to understand:
1) What are the criteria used to choose the charging station during the trip? What is the way that an agent decides to charge?
2) Can we specify a charging station during the trip as part of an agent's plan?
3) Which units are defined for battery's capacity and soc? 
4) Which model for charge/discharge is used? 
5) Are there a basic bibliography, documentation or tutorial to understand the basis of "ev contrib" model? 
Cheers !

**Comment by jfbischoff** [comment]
Hi,

> What are the criteria used to choose the charging station during the trip? What is the way that an agent decides to charge?

Charging is roughly scheduled between 10 and 20 percent SoC. 

> Can we specify a charging station during the trip as part of an agent's plan?

This would require some programming work, but is possible.

>Which units are defined for battery's capacity and soc?

The files use kWh for batteries and kW for chargers. Internally, all computations use SI units.

>Which model for charge/discharge is used?

There are two models for dis-charging available, see the example code. You can easily write your own though. For charging, several fast charging modes are available. That said, you can also implement your own.

>Are there a basic bibliography, documentation or tutorial to understand the basis of "ev contrib" model?

For an overview, see papers 19-07 and 19-13:
https://www.vsp.tu-berlin.de/menue/forschung/publications/vspwp/

**Comment by applibres** [comment]
OK. Thanks so much @jfbischoff for your answers and references.
