### ISSUE TITLE
how to use issue tracker?

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-code-examples#2]
I don't know how to use this issue tracker.  Could you please help me?

**Comment by kainagel** [comment]
I don't know either.  Maybe someone else can?

**Comment by mrieser** [comment]
hmm, works for me. 🥇

**Comment by neuma** [comment]
that spam comment is still visible (if needed)

**Comment by jfbischoff** [comment]
magic. so that is done now?
