### ISSUE TITLE
Best strategies for convergence

### ISSUE THREAD

**Issue by Aitanm** [matsim-org/matsim-code-examples#203]
I'm currently running different scenarios using the DRT extension. After some trials in order to achieve converge I'm not sure of which one is the best.
 
The first figure shows a strategy that in summary has the following setup: 	fractionOfIterationsToDisableInnovation: 0.8, maxAgentPlanMemorySize: 3, TimeAllocationMutator, value=0.1. The scores are improving, but they are not converging, I already tried 120 iterations and it continues to increase.

Second picture has the following setup: fractionOfIterationsToDisableInnovation: 0.8, maxAgentPlanMemorySize: 3, TimeAllocationMutator, value=0.2, SelectRandom, value = 0.1.
It converges but with a lower score than the average score achieved by the other setup. Even though scores are lower, is it a better setup ? Any idea of how to achieve convergence with higher scores? 

![str1](https://user-images.githubusercontent.com/22937247/64576889-e13f3e80-d37a-11e9-93b8-d71c7f25b8c0.png)
![str2](https://user-images.githubusercontent.com/22937247/64576892-e3a19880-d37a-11e9-8288-07549b39023d.png)

**Comment by vsp-gleich** [comment]
120 iterations is not enough. We run most simulations with about 1000 iterations. Unfortunately simulating DRT is rather time-consuming, so we sometimes try with "only" a couple of hundred iterations, but 120 sounds too small.

**Comment by Aitanm** [comment]
I tried 1000 iterations and could achieve convergence in around 200 iterations, sounds good enough for me.

![str](https://user-images.githubusercontent.com/22937247/64712273-36826980-d4bb-11e9-92ee-95dfa260e3e8.png)
