### ISSUE TITLE
events2traveldiary handler not recognizing pt

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-code-examples#209]
Dear MATSim Team, 

Are there any examples that provide guidance on debugging/configuring the events2traveldiaries event handler from the main contrib -> analysis? 

I am running it on a scenario with fully routed pt (other outputs and Via analysis confirm this), but currently the events2traveldiaries handler does not find my pt, and only returns outputs for car, bike, walk, and non-network walk. 

Does the handler need to be further configured to read the pt events? My model references "pt" in the plans input as well as in the "transit" and "changeMode" modules of the config, while pt is implemented as "bus" in the schedule, network and vehicles inputs as well as at the corresponding "modeParm" in the config. 

Thanks in advance

**Comment by mr-illington** [comment]
As an update, I have now also run this on example scenarios to see if the problem was my model. For both the Siouxfalls-2014 and pt-simple scenarios, the events2traveldiary handler does not output pt information. I have verified that the input configs use routed transit, and the events file contains pt interactions. 

In the events2traveldiaries log (attached) there is a line from Kai stating: 

> 2019-10-01 14:14:50,439  WARN PlansCalcRouteConfigGroup:317 It used to be the case that manually setting one mode routing here would first clear all the default values.  I have now removed this clearing, i.e. default values will remain.  If they are in the way, removeModeRoutingParams(...) can be used to individually remove them.  kai, apr'19

And then it states various mode routing params that have been replaced. 

Could this be related?
[events2diariesLOG.txt](https://github.com/matsim-org/matsim-code-examples/files/3676158/events2diariesLOG.txt)

**Comment by mr-illington** [comment]
Hi again, 

Any support on this one? Still have not been able to get a single pt result on a full pt simulation - and also not with the Siouxfalls-2014 and pt-simple scenarios. 

![image](https://user-images.githubusercontent.com/17620869/66744823-b1a1bb80-ee7d-11e9-8eeb-0867960b30cf.png)

**Comment by kainagel** [comment]
Events2traveldiary is not maintained by the Berlin group, so right now we cannot help there.  

(1) Is it still working with the matsim release (11.0)?  If so, would you be able to go back to that version?

(2) Would you be willing and able to write a regression test?

**Comment by mr-illington** [comment]
Thanks for the response. I did retry it with matsim 11.0 and can report no change - still the above lack of catching pt events. My gut says the issue is something on my side possibly to do with transit/pt/bus naming conventions which I'm still occasionally confused about. 

I'm stronger in R than Java, so for now proceeded with a custom handler to print out a bulk event dump to csv that I can group and summarize in R. 

Thanks

**Comment by kainagel** [comment]
I think that that makes sense in the end.  Analyze in a language one feels proficient in.
