### ISSUE TITLE
AtlantisToWGS84 conversion

### ISSUE THREAD

**Issue by vasilis-mourtakos** [matsim-org/matsim-code-examples#212]
Hi, 
I have my network file with CRS Atlantis and I want to convert it to WGS84. 
The actual goal here is to be able to put an OSM map behind my network in VIA. And a reference system that VIA accepts is WGS84.
I've been trying something like (after i have loaded the desired config file) :

	Scenario scenario = ScenarioUtils.createScenario(config);
	for (Node nodes : scenario.getNetwork().getNodes().values()){
			Coord coord = nodes.getCoord();
			AtlantisToWGS84 change = new AtlantisToWGS84();
			Coord changedcoord  = change.transform(coord);
			nodes.setCoord(changedcoord);
		}

But I couldn't really get it to work. Any suggestions?

Thanks for your time,
Vasilis

**Comment by mrieser** [comment]
> But I couldn't really get it to work.

Please be more specific. What did not work? What did you expect to happen, and what happened actually?

> I have my network file with CRS Atlantis and I want to convert it to WGS84.

This will not work. `Atlantis` is not a real CRS, it's one we made up in the early days of MATSim to describe test scenarios that are not related to anything in the real world, like the equil-network used for tests. It basically maps the coordinates somewhere close to 0/0 longitude/latitude, so the coordinates typically end up somewhere in the Atlantic ocean.

> The actual goal here is to be able to put an OSM map behind my network in VIA.

This implies you are using a network representing an actual real-world region. How did you create the network? Did you convert it from OpenStreetMap? What CoordinateSystem did you specify there for the conversion.

Via supports any real-world CRS, not only WGS84. So probably you don't have to convert anything, but just have to know which CRS your network actually uses. And no, Atlantis is not the right answer, even if it is specified in the config-file.

**Comment by vasilis-mourtakos** [comment]
@mrieser Thank you for your answer. I was not available for quite a while that's why I took so long to answer.
I will try to find the correct CRS of the network as you said!
Thanks again.
