### ISSUE TITLE
Estimation of mode choice model

### ISSUE THREAD

**Issue by KamijoYo** [matsim-org/matsim-code-examples#214]
Hello everyone.
I am trying to estimate a mode choice logit model with ride-sharing DRT by conducting an SP survey.
If you have any reference materials or precautions when conducting an SP survey for the Scoring function of MATSim, I would appreciate it if you could introduce it.
At present, I’m considering calibrating the estimated mode choice model according to the explanation of p.32 to p.33 of "The Multi-Agent Transport Simulation MATSim".

**Comment by kainagel** [comment]
In the current user guide matsim.org/userguide<http://matsim.org/userguide> , look at section 5.4, starting with "a possibe approach to calibration is as follows".  This is hopefully still fairly similar to what is in the book.

Please make sure you understand how it works with beta_perf (marginal utility of time as a resource, or opportunity cost of time).  Maybe you already know this, but it frequently goes wrong.

I have heard that Sergio Jara-Diaz has tried to estimate the marginal utility of time as a resource in Switzerland, but I have also heard that that was not easy.  So the pragmatic approach in section 5.4 might be more, well, pragmatic.

**Comment by KamijoYo** [comment]
Thank you very much for your reply.
I would like to calibrate the estimated mode choice model by the pragmatic approach in section 5.4.
I have another question. Is it not recommended to use mode choice model parameters as they are without using the activity utility at all？
If using the parameters as they are, I think that the meaning of the score is easy to interpret intuitively.

**Comment by kainagel** [comment]
One _can_ use matsim with beta_perf=0.  **Note that time allocation mutation will _not_ work any more.**  Reason is that the concave (in practice: logarithmic) function for the reward of performing an activity pushes the relative durations of the activities towards their typical durations.  E.g. if the typical durations are: home=12h, work=8h, shop=2h, then the time allocation will push towards 12:8:2 for the relative time allocations.  With beta_perf=0, and as a tendency arrival/departure times will just move out of congested time slots.  E.g. people will make work shorter and shopping longer if that means that the trip from work to shop can be moved out of congested times by doing this.  So in this case one needs to leave time mutation switched off.

With beta_perf=0, all the remaining values are indeed just the logit model values.

**Comment by KamijoYo** [comment]
Thank you very much for your reply.
I do not plan to use time allocation mutation, so I will use the logit model values as they are for the Scoring function of MATSim.
