### ISSUE TITLE
scoring function of drt waiting time

### ISSUE THREAD

**Issue by KamijoYo** [matsim-org/matsim-code-examples#217]
Hello everyone.
In the drt module, is it correct that DRT waiting time is added to the ride time and the total ride time score is calculated?
If I want to separate the score calculation and set the parameter for the waiting time, is it correct that I have to add code to MATSim?

**Comment by jfbischoff** [comment]
Hi,
yes, that is true. You would need to implement your own scoring function for this. However, that should not be too difficult.

**Comment by KamijoYo** [comment]
Thank you very much for your reply.
I'd like to try adding code for waiting time.
