### ISSUE TITLE
Missing example configuration for example13MultiStageTripRouting

### ISSUE THREAD

**Issue by gregmacfarlane** [matsim-org/matsim-code-examples#22]
I'm up-to-date on the v0.11.x branch of this repository, and am trying to run the `main()` method of [`RunTeleportationMobsimWithCustomRoutingExample`](https://github.com/matsim-org/matsim-code-examples/blob/0.11.x/src/main/java/org/matsim/codeexamples/router/example13MultiStageTripRouting/RunTeleportationMobsimWithCustomRoutingExample.java#L48), and it tries to load a configuration file in `examples/pt-tutorial/`. 

```java
public class RunTeleportationMobsimWithCustomRoutingExample {
	private static final String configFile = "examples/pt-tutorial/config.xml";


	public static void main(final String[] args) {
		// make sure we get all the log messages in the logfile
		OutputDirectoryLogging.catchLogEntries();


		// load the config ...
		final Config config = ConfigUtils.loadConfig( configFile );
```

This path is not in this repository; is the path simply out of date or has the data been moved elsewhere?  Should I update the path to the configuration at `scenarios/equil-mixedTraffic/` or something similar?

**Comment by mrieser** [comment]
Looks like this got reorganized a while ago, please look here: https://github.com/matsim-org/matsim/tree/master/examples/scenarios

**Comment by gregmacfarlane** [comment]
Any advice on bringing the source data from the master branch into the version branch? Or should I just clone a second version of the repo?

**Comment by gregmacfarlane** [comment]
NVM, I see that it's MATSim's examples folder, not this repo's

**Comment by kainagel** [comment]
Just fixed it.  There is `ExampleUtils.getTestScenarioURL(...)` for this type of problem.

The code still throws an exception later, because the scoring is not defined for the new mode.

We will happily take pull requests.  Also for a regression test.  :-)

**Comment by gregmacfarlane** [comment]
Was just about to write an issue about the new mode scoring. Thanks for looking into this one.

**Comment by gregmacfarlane** [comment]
I just tried to submit a PR for the scoring issue in https://github.com/matsim-org/matsim-code-examples/pull/23, but I don't see it in every environment.
