### ISSUE TITLE
subpopulation filtered outputs 

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-code-examples#222]
I'm currently running a simulation with two subpopulations based on [the 12.x approach creating subpopulation specific strategies and filtering the subpopulation directly in code](https://github.com/matsim-org/matsim-code-examples/blob/12.x/src/main/java/org/matsim/codeexamples/programming/multipleSubpopulations/RunSubpopulationsExample.java). 

This works really nicely, however at the end one still has to deal with a combined set of plan and event outputs. In my initial analysis I filter these manually outside of Java, but a more elegant solution would be to filter by subpopulations at the level of the plans and events output. 

This is now of particular relevance in order to run the vsp travelTimeValidation analysis tool on one of the two subpopulations, requiring a complete plans and events output specific to that output.  

Is there an elegant way to already separate the plans and events outputs based on the subpopulation IDs while keeping the overall xml for each output intact?

**Comment by FarnooshNm** [comment]
I have the same question. Is there a straightforward way to do this?
