### ISSUE TITLE
How to set free-form attributes

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/matsim-code-examples#228]
Hi everybody, 
I wonder how can I use free-form attributes for population file (like "sex" parameters ), where and how do I have to set it up? And "age" parameter is also free-form to be defined or standard? 
And about car license possession or car avalilability, how can I take into consideration as discriminant for switching leg mode?
Hope you can give me infos. Thanks

**Comment by Janekdererste** [comment]
You could use attributes like this:
```
for (Person person : scenario.getPopulation().getPersons().values()) {
			
	person.getAttributes().putAttribute("sex", "other");
	person.getAttributes().putAttribute("age", 31);
}
```
As long as you only store basic parameters like Strings and Numbers those attributes should be stored in the population file as well.
