### ISSUE TITLE
Beginner trying to use berlin as example for further development but meet with problems

### ISSUE THREAD

**Issue by huangyuantan** [matsim-org/matsim-code-examples#231]
Hi i am a beginner for matsim and i want to use it for my dissertation，Here is the problem: i use the **matsim-example-project** in Eclipse and **berlin-v5.3-1pct** configuration file. I thought this example would work well ,But it can not work. The error log is as followed:
[berlin-v5.3-1pct.logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/3802958/berlin-v5.3-1pct.logfileWarningsErrors.log)

I am using windows 7 with 64bit 
matsim version:r92f5a963d96c1378d104c07359ace3469f91ad77 (2019-04-10 11:10:17)
java version: 1.8.0_211; Oracle Corporation; mixed mode; 64-bit

I am not good at programming and still working at it. Please tell me what cause this problem and how can i save it! thank you so much

**Comment by ikaddoura** [comment]
Welcome to MATSim. The berlin-v5.x-1pct configuration files requires a berlin-specific run class. Please have a look into our open berlin scenario project: https://github.com/matsim-vsp/matsim-berlin

... and then find the class org.matsim.run.RunBerlinScenario

You can also add a maven dependency to the berlin project into your own project...

add the following to your pom:

`<repository>
   <id>jitpack.io</id>
   <url>https://jitpack.io</url>
</repository>`

`<dependency>
	 <groupId>com.github.matsim-vsp</groupId>
	 <artifactId>matsim-berlin</artifactId>
	<version>5.4</version>
</dependency>`

... and then create your own run class and write something like...

Config config = RunBerlinScenario.prepareConfig( args ) ;
// do what ever you need to change...

Scenario scenario = RunBerlinScenario.prepareScenario( config ) ;
// do what ever you need to change...

Controler controler = RunBerlinScenario.prepareControler( scenario ) ;
// do what ever you need to change...

controler.run();
