### ISSUE TITLE
Some problems about ev

### ISSUE THREAD

**Issue by Thomas960707** [matsim-org/matsim-code-examples#235]
I downloaded the files here [http://ci.matsim.org:8080/job/Doxygen_MATSim/ws/contribs/ev/] and tried to learn how to model the electric vehicles. Then I run the test files but failed.

Here is the logfileWarningsErrors files: 2019-11-05 12:51:27,797 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: ev.

When I delete the codes about ev in the config.xml :
`
<config>
    <module name="ev">
        <param name="auxDischargeTimeStep" value="10"/>
        <param name="chargeTimeStep" value="5"/>
        <param name="chargersFile" value="chargers.xml"/>
        <param name="timeProfiles" value="true"/>
        <param name="vehiclesFile" value="evehicles.xml"/>
    </module>
`

It succeeds but has none buiness with ev. I don't know what it means by "Unmaterialized config group: ev."

**Comment by kainagel** [comment]
The "unmaterialized config group" error means that you have a config group that is not picked up by the simulation.  It is an insurance device so that you do not think that you are using "ev" while in reality you are not.  

Unfortunately, I cannot say how to plug it together correctly; the maintainers of that package need to speak for themselves, sorry.

**Comment by Thomas960707** [comment]
> The "unmaterialized config group" error means that you have a config group that is not picked up by the simulation. It is an insurance device so that you do not think that you are using "ev" while in reality you are not. Unfortunately, I cannot say how to plug it together correctly; the maintainers of that package need to speak for themselves, sorry.

So do you think I lack something for example JAVA packages?

**Comment by michalmac** [comment]
This is an example with EV simulation: https://github.com/matsim-org/matsim/blob/master/contribs/ev/src/main/java/org/matsim/contrib/ev/example/RunEvExample.java

**Comment by xy2017** [comment]
> This is an example with EV simulation: https://github.com/matsim-org/matsim/blob/master/contribs/ev/src/main/java/org/matsim/contrib/ev/example/RunEvExample.java

I did run this code, as well as its config.xml file in test folder. But it still reported the error: java.lang.RuntimeException: Unmaterialized config group: ev. So is there anything wrong with the process?

**Comment by Thomas960707** [comment]
> This is an example with EV simulation: https://github.com/matsim-org/matsim/blob/master/contribs/ev/src/main/java/org/matsim/contrib/ev/example/RunEvExample.java

I can't find the package 
"import org.matsim.contrib.ev.routing.EvNetworkRoutingProvider;"
I don't know why?

**Comment by xy2017** [comment]
> This is an example with EV simulation: https://github.com/matsim-org/matsim/blob/master/contribs/ev/src/main/java/org/matsim/contrib/ev/example/RunEvExample.java

I have tried the example above, but there's an error: 
`Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and org.matsim.contrib.ev.discharging.AuxEnergyConsumption$Factory is not explicitly bound.
  while locating org.matsim.contrib.ev.discharging.AuxEnergyConsumption$Factory
    for field at org.matsim.contrib.ev.data.ElectricFleetModule$InitAtIterationStart.auxConsumptionFactory(ElectricFleetModule.java:75)
  at org.matsim.contrib.ev.data.ElectricFleetModule.install(ElectricFleetModule.java:51) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.ev.EvModule -> org.matsim.contrib.ev.data.ElectricFleetModule)
`
It seems like the "ev" project above is not compatible with maven  in version. But the maven package works well in other project and cannot be modified. So how can I solve this problem?

**Comment by ghost** [comment]
> I have tried the example above, but there's an error:
`Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
[...]
It seems like the "ev" project above is not compatible with maven in version. But the maven package works well in other project and cannot be modified. So how can I solve this problem?

I'm having the same issue (MATSim 11.0). Maybe the given example only works with a newer version of MATSim? Have you found a solution yet?

> I can't find the package
"import org.matsim.contrib.ev.routing.EvNetworkRoutingProvider;"
I don't know why?

Try it with "import org.matsim.contrib.ev.routing.EVNetworkRoutingProvider;". The routing class has been renamed.

**Comment by michalmac** [comment]
Seems that the example was broken at the moment of releasing matsim 11.0. Please use the snapshot (development) version or a weekly release. There is one more argument for doing so:
EV contrib was added shortly before the release of matsim 11. Lots of improvements have been added afterwards.

**Comment by Thomas960707** [comment]
> > I have tried the example above, but there's an error:
> > `Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
> > [...]
> > It seems like the "ev" project above is not compatible with maven in version. But the maven package works well in other project and cannot be modified. So how can I solve this problem?
> 
> I'm having the same issue (MATSim 11.0). Maybe the given example only works with a newer version of MATSim? Have you found a solution yet?
> 
> > I can't find the package
> > "import org.matsim.contrib.ev.routing.EvNetworkRoutingProvider;"
> > I don't know why?
> 
> Try it with "import org.matsim.contrib.ev.routing.EVNetworkRoutingProvider;". The routing class has been renamed.

Thank you, and I have found the package. I wonder  where I can find the ev's parameter available when writing .xml config files? I have checked the user documentation, but there's no parameters list about ev.

**Comment by michalmac** [comment]
You can find them here: https://github.com/matsim-org/matsim/blob/master/contribs/ev/src/main/java/org/matsim/contrib/ev/EvConfigGroup.java (master branch) and https://github.com/matsim-org/matsim/blob/11.x/contribs/ev/src/main/java/org/matsim/contrib/ev/EvConfigGroup.java (11.x)

**Comment by Thomas960707** [comment]
> You can find them here: https://github.com/matsim-org/matsim/blob/master/contribs/ev/src/main/java/org/matsim/contrib/ev/EvConfigGroup.java (master branch) and https://github.com/matsim-org/matsim/blob/11.x/contribs/ev/src/main/java/org/matsim/contrib/ev/EvConfigGroup.java (11.x)

Thanks a lot!
