### ISSUE TITLE
Cadyts Plan selection

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/matsim-code-examples#239]
Hi everybody,
So I'm trying to use cadyts to get some kind of real traffic loading on the network. I've already tested cadyts function for 10 iterations, seem to work.
**I had one specific question**: is there a way to keep only the best score/max likelihood plan as output? So that I can use it at as basic scenario, and clean from unnecessary plans. Thanks in advance. 

If needed, I attach here my scenario's git:
[https://github.com/MAlbertini95/matsim-example-project.git](url)

**Comment by Janekdererste** [comment]
Do you want the plan with the best score after you have finished your cadyts runs?

**Comment by Janekdererste** [comment]
You could filter your population for the best scored plans like this:

```
Scenario scenario = ScenarioUtils.createScenario(ConfigUtils.createConfig());
new PopulationReader(scenario).readFile("path/to/your/population/file/from/your/cadyts/run.xml.gz");

for (Person person : scenario.getPopulation().getPersons().values()) {
	Plan highestScoring = person.getPlans().stream()
		// get the plan with the highest score
		.min((plan1, plan2) -> Double.compare(plan2.getScore(), plan1.getScore()))
		.orElseThrow(() -> new RuntimeException("something went wrong"));

	person.getPlans().clear();
	person.addPlan(highestScoring);
	person.setSelectedPlan(highestScoring);
}

new PopulationWriter(scenario.getPopulation()).write("path/to/your/new/population-file.xml.gz");
```
You would run this snippet after all your cadyts iterations have finished. The resulting population file could be the input of your base case.

**Comment by MAlbertini95** [comment]
Thank you so much! Very useful in my case!

**Comment by whizkid-25** [comment]
@MAlbertini95 
Hi, is there a way to get this my coding directly into the config. file?
