### ISSUE TITLE
Is Id class thread safe?

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-code-examples#241]
@mrieser this is probably a question for you. I'm trying to create a network using parallel streams. Within the pipline new links and nodes are created, including new Ids. This seems to be not thread safe: 
```
private Node createNode(Coord coord, long nodeId) {
		
	Id<Node> id = Id.createNodeId(nodeId);
        return network.getFactory().createNode(id, coord);
}
```
Looking at your implementation of the node cache, look ups are thread safe writes not. Can you confirm?
This is how I've worked around it so far:
```
private Node createNode(Coord coord, long nodeId) {
	synchronized (Id.class) {
		Id<Node> id = Id.createNodeId(nodeId);
		return network.getFactory().createNode(id, coord);
	}
}
```

**Comment by Janekdererste** [comment]
Well, I guess it is not.

**Comment by mrieser** [comment]
Sorry, I must have missed this issue before. 
Indeed, currently the creation of Ids is not thread safe. Is this a real issue? I thought about it when implementing it and came to the conclusion that all places where Ids are created are single-threaded: reading from files, creating agents or vehicles within a loop, etc. I couldn't come up with a case where Ids could be created in multiple threads, without having existed before.
If there is such a case, it shouldn't be too hard to make the Id creation thread-safe.

**Comment by michalmac** [comment]
DVRP request IDs are created on the fly (although not yet in parallel). So something that needs to be addressed.
