### ISSUE TITLE
customize scoring function

### ISSUE THREAD

**Issue by DmitryTsad** [matsim-org/matsim-code-examples#243]
Dear All,

I am working on the public transport simulation within MatSim environment. The utility function of the model should include the following parameters: age of the passenger, his/her education level, the waiting time until the bus arrives as well as its loading (e.g., heavily, low loaded and so on).

The main question is how can I model this function within the config file.

Thanks in advance,

Dmitry

**Comment by mrieser** [comment]
> how can I model this function within the config file

You can't. The default scoring function does not take age or education level into account. If you want to do this, you have to provide your own scoring function, which needs to be written in Java.

**Comment by AliAlderete** [comment]
> > how can I model this function within the config file
> 
> You can't. The default scoring function does not take age or education level into account. If you want to do this, you have to provide your own scoring function, which needs to be written in Java.

Which are the files that control the scoring/scoring algorithm?
