### ISSUE TITLE
Implementing tolls 

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/matsim-code-examples#244]
Hello everybody, I was trying to implement a simple roadpricing scheme for my scenario. I was trying to use the roadpricing contrib, but there's something not completely clear to me:

1. Is the toll for single links working? ( some comments in the package-info are quite old, so I don't know how far the whole contrib has gone in fixing/implementing)
2. How does it affect the scoring function, is it just adding the toll or there needs to be a special attention?
3. How can I define the modes affected by the toll (example only car and ride)?

Hope you can help. Thank you!

**Comment by JWJoubert** [comment]
@MAlbertini95 
1. To my knowledge, yes, it is working. We are using it quite frequently in different use cases.
2. I'm not sure what you mean with _special attention_ but yes, it is adding the toll as a monetary value if that is how you set it up.
3. Implement your own specific `TollFactor` from the interface.

**Comment by MAlbertini95** [comment]
So I guess I should use this kind of script in my RunMatsim, right?

		// define the toll factor as an anonymous class.  If more flexibility is needed, convert to "full" class.
		TollFactor tollFactor = (personId, vehicleId, linkId, time) -> {
			VehicleType someVehicleType = null; // --> replace by something meaningful <--
			//noinspection ConstantConditions
			if (scenario.getVehicles().getVehicles().get(vehicleId).getType().equals(someVehicleType)) {
				return 2;
			} else {
				return 1;
			}
		};

		// instantiate the road pricing scheme, with the toll factor inserted:
		URL roadpricingUrl = IOUtils.extendUrl(config.getContext(), rpConfig.getTollLinksFile());
		RoadPricingSchemeUsingTollFactor.createAndRegisterRoadPricingSchemeUsingTollFactor(roadpricingUrl, tollFactor, scenario ); 

But it is unclear to me where I have to define the modes ( instead of null value only?), and in which section. ( Under scenario or controler?). Thanks again, I'm not a expert java user so I'm kind of learning step by step.

**Comment by JWJoubert** [comment]
Yes, you should script it @MAlbertini95. The `TollFactor` allows you to differentiate the toll/roadpricing by person, vehicle, link and time. Mode is not accounted for, so you will have to find a way to incorporate it into you vehicle, for example.

From my experience (I was also a Java newbie) I would advise that you first invest some time into mastering Java a bit... it will save you much frustration.

**Comment by kainagel** [comment]
This all looks good.  `VehicleType`, at least its newer version, in principle has `mode`.  But I would rather resort to `Attributable`:
```
vehType.getAttributes().put("modeForToll","abc");
```
(maybe not totally obvious where to insert this; let us know if this is a problem).

And extract by
```
String modeForToll = (String) vehType.getAttributes().get( "modeForToll" ) ;
```

Since this is also rather old, I will close it with this comment.
