### ISSUE TITLE
Executed score is not near best or average

### ISSUE THREAD

**Issue by gregmacfarlane** [matsim-org/matsim-code-examples#25]
I was running some scenarios and noticed that my average executed score was ending up near my average worst score. My understanding is that it should be near the average best after several iterations.

![image](https://user-images.githubusercontent.com/2234830/47391214-3e8cbb80-d6e7-11e8-8e88-80bd622204aa.png)

I think I had a bug where I set the strategy mode twice in the above plot, but I can't tell if that would be a problem or not. So I started to build another test.

## BestScore
This is the configuration for the BestScore selector, drawn from the `output_config.xml`

```xml
		<parameterset type="strategysettings" >
			<!-- iteration after which strategy will be disabled.  most useful for ``innovative'' strategies (new routes, new times, ...). Normally, better use fractionOfIterationsToDisableInnovation -->
			<param name="disableAfterIteration" value="-1" />
			<!-- path to external executable (if applicable) -->
			<param name="executionPath" value="null" />
			<!-- strategyName of strategy.  Possible default names: SelectRandomBestScoreKeepLastSelectedChangeExpBetaSelectExpBetaSelectPathSizeLogit (selectors), ReRoute TimeAllocationMutator ChangeLegMode TimeAllocationMutator_ReRoute ChangeSingleLegMode ChangeSingleTripMode SubtourModeChoice ChangeTripMode TripSubtourModeChoice  (innovative strategies). -->
			<param name="strategyName" value="BestScore" />
			<!-- subpopulation to which the strategy applies. "null" refers to the default population, that is, the set of persons for which no explicit subpopulation is defined (ie no subpopulation attribute) -->
			<param name="subpopulation" value="null" />
			<!-- weight of a strategy: for each agent, a strategy will be selected with a probability proportional to its weight -->
			<param name="weight" value="0.7" />
		</parameterset>
```

This results in the following score pattern (diff, by the way, is the average difference between the agents best and worst scores, and the ribbon is the standard deviation of that statistic):

![image](https://user-images.githubusercontent.com/2234830/47391584-2c5f4d00-d6e8-11e8-8960-25e5986ceca6.png)

## ChangeExpBeta
Again, from the output

```xml
		<parameterset type="strategysettings" >
			<!-- iteration after which strategy will be disabled.  most useful for ``innovative'' strategies (new routes, new times, ...). Normally, better use fractionOfIterationsToDisableInnovation -->
			<param name="disableAfterIteration" value="-1" />
			<!-- path to external executable (if applicable) -->
			<param name="executionPath" value="null" />
			<!-- strategyName of strategy.  Possible default names: SelectRandomBestScoreKeepLastSelectedChangeExpBetaSelectExpBetaSelectPathSizeLogit (selectors), ReRoute TimeAllocationMutator ChangeLegMode TimeAllocationMutator_ReRoute ChangeSingleLegMode ChangeSingleTripMode SubtourModeChoice ChangeTripMode TripSubtourModeChoice  (innovative strategies). -->
			<param name="strategyName" value="ChangeExpBeta" />
			<!-- subpopulation to which the strategy applies. "null" refers to the default population, that is, the set of persons for which no explicit subpopulation is defined (ie no subpopulation attribute) -->
			<param name="subpopulation" value="null" />
			<!-- weight of a strategy: for each agent, a strategy will be selected with a probability proportional to its weight -->
			<param name="weight" value="0.7" />
		</parameterset>
```

![image](https://user-images.githubusercontent.com/2234830/47391709-8829d600-d6e8-11e8-966e-c500051aba10.png)

In both cases, the average executed is gradually closing the gap with the average best, which makes sense. What doesn't make sense to me is how the *average* average can catch up to, and then pass, the average executed, particularly in the `bestScore` selection regimen. Is there something I'm not setting appropriately?

Also, is there any explanation for what I could have seen in the first scenario? It's almost as if the agents were *selecting* the worst plan.

**Comment by mrieser** [comment]
After some iterations, the agents might have pretty good plans. Thus, in replanning, chances are high they create a new plan that is worse than what has survived the evolutionary process so far. Example: The agents have found the optimal mode for their plan, but still continue to randomly try out other modes, e.g. walking very long distances instead of taking the car. This leads to the fact that once the iterations have produced good plans for agents, the replanning will in many cases produce bad plans. And thus the avg. executed score is lower than the avg. average and close by the avg. worst plan.

This is also the reason the option "disableAfterIteration" was added to the strategies, or the more global parameter "fractionOfIterationsToDisableInnovation" was added, so that no longer likely bad plan-variations will be created, but the agents can only choose from the known-to-be-likely-good plan set they have.

**Comment by kainagel** [comment]
I agree with Marcel, but that does not explain why in the first case the average executed equals the average worst.  A possible cause might be that all agents are innovating in each iteration.

Another thing to notice is that plans removal interacts fairly strongly with plan selection.  For illustrative studies, it is often useful to set the maximumNumberOfPlans to infinity (encoded, I think, as "0").

**Comment by gregmacfarlane** [comment]
What are the memory costs of keeping more than a handful of plans? It seems that with 50 iterations keeping 50 plans around would be costly, but I don't know if that's the biggest thing or not.

**Comment by gregmacfarlane** [comment]
As an update, I successfully stopped the plans innovation at 80% of the iterations. This caused the worst plans to be discarded. I still think it's interesting, though, that the executed plans are trending to the worst scores instead of the best or even the average.

![image](https://user-images.githubusercontent.com/2234830/47445496-05a42380-d787-11e8-8063-3f8090044c23.png)

Here's the complete strategy settings; is it possible that my weights are too high? or too low? What are the implications of this?

```xml
	<module name="strategy" >
		<!-- the external executable will be called with a config file as argument.  This is the pathname to a possible skeleton config, to which additional information will be added.  Can be null. -->
		<param name="ExternalExeConfigTemplate" value="null" />
		<!-- time out value (in seconds) after which matsim will consider the external strategy as failed -->
		<param name="ExternalExeTimeOut" value="3600" />
		<!-- root directory for temporary files generated by the external executable. Provided as a service; I don't think this is used by MATSim. -->
		<param name="ExternalExeTmpFileRootDir" value="null" />
		<!-- fraction of iterations where innovative strategies are switched off.  Something link 0.8 should be good.  E.g. if you run from iteration 400 to iteration 500, innovation is switched off at iteration 480 -->
		<param name="fractionOfIterationsToDisableInnovation" value="0.8" />
		<!-- maximum number of plans per agent.  ``0'' means ``infinity''.  Currently (2010), ``5'' is a good number -->
		<param name="maxAgentPlanMemorySize" value="5" />
		<!-- strategyName of PlanSelector for plans removal.  Possible defaults: WorstPlanSelector SelectRandom SelectExpBetaForRemoval ChangeExpBetaForRemoval PathSizeLogitSelectorForRemoval . The current default, WorstPlanSelector is not a good choice from a discrete choice theoretical perspective. Alternatives, however, have not been systematically tested. kai, feb'12 -->
		<param name="planSelectorForRemoval" value="WorstPlanSelector" />
		<parameterset type="strategysettings" >
			<!-- iteration after which strategy will be disabled.  most useful for ``innovative'' strategies (new routes, new times, ...). Normally, better use fractionOfIterationsToDisableInnovation -->
			<param name="disableAfterIteration" value="-1" />
			<!-- path to external executable (if applicable) -->
			<param name="executionPath" value="null" />
			<!-- strategyName of strategy.  Possible default names: SelectRandomBestScoreKeepLastSelectedChangeExpBetaSelectExpBetaSelectPathSizeLogit (selectors), ReRoute TimeAllocationMutator ChangeLegMode TimeAllocationMutator_ReRoute ChangeSingleLegMode ChangeSingleTripMode SubtourModeChoice ChangeTripMode TripSubtourModeChoice  (innovative strategies). -->
			<param name="strategyName" value="ChangeExpBeta" />
			<!-- subpopulation to which the strategy applies. "null" refers to the default population, that is, the set of persons for which no explicit subpopulation is defined (ie no subpopulation attribute) -->
			<param name="subpopulation" value="null" />
			<!-- weight of a strategy: for each agent, a strategy will be selected with a probability proportional to its weight -->
			<param name="weight" value="0.7" />
		</parameterset>
		<parameterset type="strategysettings" >
			<!-- iteration after which strategy will be disabled.  most useful for ``innovative'' strategies (new routes, new times, ...). Normally, better use fractionOfIterationsToDisableInnovation -->
			<param name="disableAfterIteration" value="-1" />
			<!-- path to external executable (if applicable) -->
			<param name="executionPath" value="null" />
			<!-- strategyName of strategy.  Possible default names: SelectRandomBestScoreKeepLastSelectedChangeExpBetaSelectExpBetaSelectPathSizeLogit (selectors), ReRoute TimeAllocationMutator ChangeLegMode TimeAllocationMutator_ReRoute ChangeSingleLegMode ChangeSingleTripMode SubtourModeChoice ChangeTripMode TripSubtourModeChoice  (innovative strategies). -->
			<param name="strategyName" value="ReRoute" />
			<!-- subpopulation to which the strategy applies. "null" refers to the default population, that is, the set of persons for which no explicit subpopulation is defined (ie no subpopulation attribute) -->
			<param name="subpopulation" value="null" />
			<!-- weight of a strategy: for each agent, a strategy will be selected with a probability proportional to its weight -->
			<param name="weight" value="0.4" />
		</parameterset>
		<parameterset type="strategysettings" >
			<!-- iteration after which strategy will be disabled.  most useful for ``innovative'' strategies (new routes, new times, ...). Normally, better use fractionOfIterationsToDisableInnovation -->
			<param name="disableAfterIteration" value="-1" />
			<!-- path to external executable (if applicable) -->
			<param name="executionPath" value="null" />
			<!-- strategyName of strategy.  Possible default names: SelectRandomBestScoreKeepLastSelectedChangeExpBetaSelectExpBetaSelectPathSizeLogit (selectors), ReRoute TimeAllocationMutator ChangeLegMode TimeAllocationMutator_ReRoute ChangeSingleLegMode ChangeSingleTripMode SubtourModeChoice ChangeTripMode TripSubtourModeChoice  (innovative strategies). -->
			<param name="strategyName" value="ChangeTripMode" />
			<!-- subpopulation to which the strategy applies. "null" refers to the default population, that is, the set of persons for which no explicit subpopulation is defined (ie no subpopulation attribute) -->
			<param name="subpopulation" value="null" />
			<!-- weight of a strategy: for each agent, a strategy will be selected with a probability proportional to its weight -->
			<param name="weight" value="0.4" />
		</parameterset>
		<parameterset type="strategysettings" >
			<!-- iteration after which strategy will be disabled.  most useful for ``innovative'' strategies (new routes, new times, ...). Normally, better use fractionOfIterationsToDisableInnovation -->
			<param name="disableAfterIteration" value="-1" />
			<!-- path to external executable (if applicable) -->
			<param name="executionPath" value="null" />
			<!-- strategyName of strategy.  Possible default names: SelectRandomBestScoreKeepLastSelectedChangeExpBetaSelectExpBetaSelectPathSizeLogit (selectors), ReRoute TimeAllocationMutator ChangeLegMode TimeAllocationMutator_ReRoute ChangeSingleLegMode ChangeSingleTripMode SubtourModeChoice ChangeTripMode TripSubtourModeChoice  (innovative strategies). -->
			<param name="strategyName" value="TimeAllocationMutator" />
			<!-- subpopulation to which the strategy applies. "null" refers to the default population, that is, the set of persons for which no explicit subpopulation is defined (ie no subpopulation attribute) -->
			<param name="subpopulation" value="null" />
			<!-- weight of a strategy: for each agent, a strategy will be selected with a probability proportional to its weight -->
			<param name="weight" value="0.1" />
		</parameterset>
	</module>
```

**Comment by josiekre** [comment]
@gregmacfarlane and I just chatted some more. There's really just one question we are asking still:

1. Given the weights we have been running with, 56% of the time (0.4 + 0.4 + 0.1 / 0.4 + 0.4 + 0.1 + 0.7) people iterate on their most recently executed plan. The other 44% of the time they change to a different plan with probability dependent on e^score_deltas. If 44% of the time, there's a good chance the Best plan will be executed, why is the executed score tracking so close to the Worst time? (@kainagel suggested keeping more plans in memory, but I do not understand how, given our current results, that would make people more likely to execute their Best plan.)

**Comment by gregmacfarlane** [comment]
As another test, I deemphasized the replanning strategies to 0.2, 0.1, 0.1 but left the selection at 0.7, resulting in:

![image](https://user-images.githubusercontent.com/2234830/47449858-adbeea00-d791-11e8-937b-59e2889d9f21.png)

It seems as though the worst score will still catch up with the executed score, but more slowly. The best score is still effectively the same as previously found, though it took a little longer for the average score to get there.

**Comment by josiekre** [comment]
@gregmacfarlane is providing more information by testing our weights. To state it for my own understanding more than anyone else's: with the new weighting people should select a plan in memory to execute 70% of the time with probability equal to e^score_deltas.

The question still stands though: why is the selector more likely to grab the worst plan than the best?

**Comment by tduberne** [comment]
Hi both,

this is really just me thinking out loud, but I think the main explanation is the following: the graphs show averages, that are very sensitive to outliers, and are particularly uninformative in the case of multi-modal or heavy-tailed distributions. Your "diff" stat does show a lot of variability between agents in terms of the difference between their best and worst. A potential explanation is that most agents have 5 pretty good plans in memory, except some of the agents that just switched modes, and got told to walk for 20 or even 100km, just to see if it might make sense. _Those_ agents will get a totally terrible score, way below anything other agents have. Sure, they will throw it away in the next iteration, but then new agents will get the same kind of plan. Those plans are both the worst _and_ the selected plan for those agents, so the two stats are equal for them. For other agents, the worst and selected plans are very similar, so the stats are almost equal for those as well. So we explained why the executed score is similar to the worst score. Now the graph is confusing, because it gives the idea that the difference between best and worst is quite substantial for all agents, when only the first agents bring those stats far off the average best. I would bet that if you do an histogram of the difference between best and worst score, you would see a bi-modal distribution, or at least a very heavy-tailed one: most agents would have a very small difference, but a few will have a very big one. And from the algorithm design, those bad plans have a high probability to be fresh mutated plans, which are selected by design.

The average score is not as affected as the executed score, because those "outlier" agents still have 5 good unselected plans in memory, that pull their average score towards the best score.

This also explains the "jump" that happens when switching off innovations very well: the worst plan of all agents that innovated in the last iteration get deleted (because they have 6 plans), so all of a sudden, those terrible "outlier" plans disappear altogether, and you remain with only very similar plans in the memory.

I hope that can help.

**Comment by gregmacfarlane** [comment]
@tduberne Thanks for your response. I guess I had sort of come up with that explanation in my own head. I think I'd like to build a complete database of all the scores as they evolve and dig through it some more, but I'll have to do that at another time.

For now, I'm curious if this is typical behavior or abnormal. Do you normally see the executed track towards the worst or towards the best? I know it is going to differ by city, strategy, etc., but are we off-base even thinking this is weird?

**Comment by tduberne** [comment]
Yes, it is quite typical to have the executed score pretty close to the worst score, for those simulation with mode choice enabled (I just checked a few outputs I had lying around, and observed this only with those ones with mode choice, which is consistent with my previous message). The "jump" at the time of innovation switch-off does occur consistently as well. After this jump, executed score is typically close to the best score. What can also be seen quite often are sudden drops in the worst and executed score, that only last for one iteration. This typically occurs in simulations with scarce resources (bike/car sharing for instance), where a plan might be in one of two very different states at execution: either the resource (eg. car) is available and score is high, either it is not (all cars were rented), the agent gets stuck, and score is absolutely terrible. There, you also do not need a lot of agents encountering this problem to have observable effects on the average.

I guess the main takeaway message is that those graphs are useful, but should always be taken with a grain of salt.

Also be aware that it is typical for the score graph to look flat, but for mode shares to still change substantially from iteration to iteration.

**Comment by josiekre** [comment]
Thanks @tduberne! Very helpful information. I have a follow-up to your last sentence: "Also be aware that it is typical for the score graph to look flat, but for mode shares to still change substantially from iteration to iteration."

If the scores look flat but the mode share is jumping around, could we expect mode shares to stabilize with more iterations? Or is that something that will never stabilize due to the innovation setup?

**Comment by tduberne** [comment]
Yes, mode shares do stabilize as well, only slower. Note I am not speaking of "jumping around", but rather monotonously converging to a stable value. From my understanding, this is the case when car and public transport options are very similar in score, but the best possible plan for one of them (say PT) is a bit worse than the best plan of the other: it will take some time for the replanning to generate enough "best" car plans to purge the agent's memory from all good PT plans, but it will happen eventually.

We actually regularly have some debate internally as to whether one should wait for mode shares to stabilize or not. When using the innovation switch-off, the aim of the innovative iterations it to generate a plan choice set for the agents: you do not actually want all agents to only have n copies of the same plan. But unfortunately, there is no theory to guide you in deciding on what time is the best to stop iterations...
