### ISSUE TITLE
Tutorial not accessible?

### ISSUE THREAD

**Issue by sebhoerl** [matsim-org/matsim-code-examples#250]
I just tried to access the TUB MATSim tutorial (SS18) after "logging in as guest". When I click on any PDF link (book chapters, slides, etc.) I get the message

    The requested file is no longer available for copyright reasons. If you think the file is blocked for no reason, please contact a teacher. 

Is this intended or did maybe something change with the permissions etc?

**Comment by jfbischoff** [comment]
Mhm, TUB locks courses after 18 months. Anyone with moderator access should be able to fix this easily.

**Comment by jwilk79** [comment]
Fixed, all 2018 tutorial material is accessible again.
