### ISSUE TITLE
Regarding stuck vehicles

### ISSUE THREAD

**Issue by Lichen-L** [matsim-org/matsim-code-examples#252]
Hi all MATSimians,

I just noticed in the config file there is a "stuck" state defined for vehicle that in the foremost of a queue and did not move for a certain period.
Could someone tell me in what case would a foremost vehicle cannot move?
I guess waiting for flow capacity integrated to 1 (vehicle) could be one cause, I am wondering if there is any other situation?

Thank you. 

Best,

Lichen

**Comment by mrieser** [comment]
It can happen if you have circular structures, something like:

```
-----(A)-----(B)-----
       \     /
        \   /
         \ /
         (C)
          |
          |
```

where the front-most vehicle von `AB` wants to `BC`, the front-most vehicle on `BC` wants to `CA`, and the front-most vehicle on `CA` wants to `AB`. If all these links are full, then no vehicle can move as each front-most vehicle waits for a space to open up on the down-stream link, which won't happen in this case. Thus, a gridlock (or deadlock) occurs, which gets detected and solved with the config parameter.

**Comment by Lichen-L** [comment]
Prof. Rieser,

Thank you for your prompt reply! That is a valuable information to know.

By the way, by mentioning "(the girdlock) gets detected and solved with the config parameter", which specifically the parameter are you pointing to? 

Best, 

Lichen

**Comment by mrieser** [comment]
> gridlock gets detected and solved with the config parameter

In the `qsim` config module, there are two parameters: `stuckTime` and `removeStuckVehicles`. The first, `stuckTime`, specifies for how many seconds a vehicle has to be ready at the front of a link (=the vehicle would be ready to go to the next link) until it gets detected as being stuck. The second parameter, `removeStuckVehicles` can either be `true` or `false`, with `false` being the default. If set to `true`, such vehicles will just be removed from the simulation, and the agents fail to finish their plan. If set to `false`, the vehicle will be pushed to the next link, even if that link is full. Think of it as if the vehicle uses some additional space, e.g. by driving onto the sidewalk, to make space so a blocked intersection can start moving again.

**Comment by kainagel** [comment]
And in addition: we strongly recommend removeStuckVehicles=false .  The reason is that otherwise analyses become quite difficult.  E.g. assume that in your base case no vehicles get stuck, but in your policy measure case many vehicles on long trips get stuck.  Then the average trip length will go down, since vehicles with long trips are no longer part of the average.  But it would entirely be an artifact caused by the stuck vehicles.  So rather have them move on anyways, and don't make the stuck time too long, since then the simulation needs to run forever until they are cleared.  (And don't finish the simulation early, since then you have the same problem with un-finished trips/plans.)

**Comment by Lichen-L** [comment]
Thank you Prof. Rieser and Prof. Nagel for the valuable suggestions.

Just want to be clear, the stuckTime parameter still works when removeStuckVehicles=false, right?

I actually get a problem with my simulation that some of the links seems require average traveltime of more than 10,000s according to linkStats.xml in output data. All of those problematic links are around or far less than 1km long and do have a capacity attribute (from 600/h to 1500/h, subject to a 0.02 flowCap factor), so I think the travel time is definitely abnormal.

I guessed it was a kind of stuck issue that caused this, but according to your valuable explanation of how the stuck issue works, I think is probably somewhere went wrong (I set removeStuckVehicles=false and StuckTime = 300 in the simulation, so I think it at most took 300 seconds to travel across one link, do I get it right?)

I am wondering if any other insights could be offered to explain the abnormal travel time. 
Sorry for your time and thank you so much again.

Best,

Lichen

**Comment by kainagel** [comment]
yes, the stuckTime param still works when removeStuckVehicles=false.

300(seconds) is pretty high.  It means that each vehicle needs 300sec.  So if you have 100 stuck vehicles on that link, it will take 100 x 300 = 30'000 sec to clear them.

Try running with 10sec, see if the problem resolves, and slowly increase.

A problem is that this parameter does not cooperate will with small sample sizes.  Assume you set it to 60sec.  Then you have a capacity of 1veh/60sec in congested conditions, i.e. 60veh/hr.  For a 100% sample, this is not a lot.  But for a 2% sample, this would correspond to 3000veh/hr.

Which is another reason why runs below 10% can be used for "structural" investigations, but not for quantitative results.

**Comment by Lichen-L** [comment]
Prof Nagel,

I see, I did not realize there might be more than 1 stuck vehicle in the links.

And yes, the problem you kindly pointed out is exactly why I previously set StuckTime to 300s, which is actually around 600veh/h in a 2% sample. I think I might be better to keep it to 300s, otherwise capacity would just become too large.

Anyway, that is definitely of great help, Thank you a lot. I see the necessity to do a population synthesis or sth to enlarge the sample to 10% in future for my case. 

Best,

Lichen
