### ISSUE TITLE
Population and activity filters

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/matsim-code-examples#255]
Hello everybody, I was wondering if there's a simple script to be used for reducing a plans.xml file by filtering agents who use a specific mode ( only "bike" or only "taxi" ), can anyone help?
Secondly, is there a script to remove certain activities like "bike interaction" activities?
Thanks in advance, Best regards.

**Comment by jfbischoff** [comment]
For removing interaction activities (and removing the defined route), there is 
TripsToLegsAlgorithm. All it requires is a MainModeIdentifier. 


To filter modes, I would suggest writing your own script (after running TripsToLegsAlgorithm).

**Comment by JWJoubert** [comment]
@MAlbertini95 I agree with @jfbischoff - there are just too many permutations of analysis. Each person wants something different. So best to write your own script.

@jfbischoff I didn't know about the `TripsToLegsAlgorithm` - I'm definitely going to check it out, Thanks! It can likely save me some time too.
