### ISSUE TITLE
agent Problem after running parking

### ISSUE THREAD

**Issue by huangyuantan** [matsim-org/matsim-code-examples#256]
Since my last issue is a little bit congested with my posted question, so i put another one here for my latest question.
<img width="1154" alt="微信图片_20191218112619" src="https://user-images.githubusercontent.com/46890305/71067308-4a6ef300-21af-11ea-958d-1afc40ac4938.png">
I have already combined Berlin Scenario and parking search module together. And i remove all the other modes except **car**. The simulation runs properly but when i put them into visualzation i found problems:
1. if i using parking search strategy **Benenson**. The vehicle just stuck on the road and keep moving between two links.
2. if i using parking search strategy **Distancememory**. The result is better with no stuck. But another problem is like the picture shown above(the left side is with parking and the right doesn't) that some of the agents don't finish their daily plans (most of them just disappeared in their first activity) while some others runs properly. I have no idea why this happening as the event file shows that they are **startparkingsearch** event there
and the output file contain parking lots that have been occupied.
my tutor told me maybe the input file problem but i can find nothing different about the two agents. The first picture below is the agent that runs properly while another is not.
<img width="1020" alt="微信图片_20191218160758" src="https://user-images.githubusercontent.com/46890305/71067989-9c644880-21b0-11ea-9180-4cc91c6f8cf9.png">
<img width="1085" alt="微信图片_20191218160806" src="https://user-images.githubusercontent.com/46890305/71067995-9e2e0c00-21b0-11ea-8b69-5f1ca42803b4.png">

Thanks so much...I REALLY NEED YOU HELP as i have been stuck on this issue for likely a month which drives me crazy...Thanks @kainagel  @jfbischoff

**Comment by huangyuantan** [comment]
I find out that the difference between them is the **end time**, once the agent want to take an activity without endtime and only duration properity, it will not do the following legs and activities. I tried to edit the end time manually and the result runs properly. So i am wondering if there are any ways that i can do it by code to get a resonable end time for these activities since there are thousands of agents here...Any good suggestions to solve this?

**Comment by ikaddoura** [comment]
We use the duration instead of end time on purpose. For short activities (e.g. 5 minutes) it's difficult to get the end time right because an agent may be delayed and then arrive at an activity after the activity end time. This will then result in an activity duration of only 0 or 1 seconds which will have some weird effects on the resulting value of travel time savings...

Of course, you can try to set the end time correctly:
end time = previous activity end time + (estimated) travel time + duration
But keep in mind that resulting scores and travel decisions might be a bit weird.

Good luck!

**Comment by jfbischoff** [comment]
>I find out that the difference between them is the end time, once the agent want to take an activity without endtime and only duration properity, it will not do the following legs and activities. I tried to edit the end time manually and the result runs properly. So i am wondering if there are any ways that i can do it by code to get a resonable end time for these activities since there are thousands of agents here...Any good suggestions to solve this?

That is very likely indeed. 
When we programmed the Parking Agents, we most likely did not think of having durations in the scenario (back then, they weren't used in our scenarios. Fixing this bug should not be too complicated so I'll see what I can do.

**Comment by jfbischoff** [comment]
I've added a bugfix. It might take some hours before it is accessible to your (please update your maven projects).

**Comment by huangyuantan** [comment]
是

**Comment by huangyuantan** [comment]
Thanks sir. very appreciate for your reply. 
Actually i got plenty of questions for the usage of parking module so far... The one that i concern most is that i saw in your paper that you got **WALK TIME** result as the picture shows below. But when i try to simulate the combination of berlin and parking module, the result part only contains the non_network_walk, and unfortunately they are teleportated and with no time information(i think it is because i set the **usingtimecheckinteleportation** as FALSE as they always turns out to be error about dynagent, so i turn it off, but according to @michalmac says, **DynAgent does not support teleporting (at least currently). I added a more explanatory message to the thrown exception.**
<img width="443" alt="微信图片_20191220145305" src="https://user-images.githubusercontent.com/46890305/71236144-22ab9680-2339-11ea-89e5-5f47b31895b4.png">
So the key problem i want to ask is: as you analyze the parking behaviors in your paper, do you use the non_network_walk as the basis of calculating walk time or something else? if you did, how do you get the result like walk time as the dynagent doesn't support(or it was able to do that before, when you running you example at that time)
Thanks a lot！

**Comment by jfbischoff** [comment]
Hi,
> @michalmac says, DynAgent does not support teleporting (at least currently). I added a more explanatory message to the thrown exception.

That is actually not right. The parking agents do support teleportation. It is all coded in the parking search module, specifically in the ParkingAgentLogic, not in DynAgent itself. 

Please note, you have to base all your analysis, including walking times and travel distances, from the Events File (or on the VIA output). 
Do you have a facilities file that contains information about the available parking spaces on your links? If not, then this is the cause of the zero-second-walk time.

**Comment by huangyuantan** [comment]
I am still look at the pom thing you posted above..There is a question that i use the berlin example from https://github.com/matsim-scenarios/matsim-berlin
And i add the parking module like this:
        <dependency>
                    <groupId>org.matsim.contrib</groupId>
                    <artifactId>parking</artifactId>
                    <version>${matsim.version}</version>
              </dependency>

I don't have much knowledge about the implementation of pom.. How can i edit the code to get the version you editted yesterday?

**Comment by huangyuantan** [comment]
> Hi,
> 
> > @michalmac says, DynAgent does not support teleporting (at least currently). I added a more explanatory message to the thrown exception.
> 
> That is actually not right. The parking agents do support teleportation. It is all coded in the parking search module, specifically in the ParkingAgentLogic, not in DynAgent itself.
> 
> Please note, you have to base all your analysis, including walking times and travel distances, from the Events File (or on the VIA output).
> Do you have a facilities file that contains information about the available parking spaces on your links? If not, then this is the cause of the zero-second-walk time.

I don't change any of the **runparkingsearch** example and i just added it into the **runberlinscenario**  like the picture below. And if i turn the setUsingTravelTimeCheckInTeleportation to TRUE. it turns out to be error of Dynagent. I don't know the reason for that so i just turned false instead. So if i want to use the parking agent like you said, is there anything i need to change for the config or something else to make it?
<img width="898" alt="微信图片_20191220161807" src="https://user-images.githubusercontent.com/46890305/71240530-59d37500-2344-11ea-9be7-91a3369a829d.png">

Actually i check the event file and found that the event time of non_network_walk doesn't change for the situation like the agent leaves the vehicle and walk to its destination. So i think there got to be some problems with it.
While for the facility files, I not sure for your question. As i use the data from OSM and create the input file without link id, and use the **AddlinkidTofacility** in the matsim-code-examples to get those id. These facilities are presented well in the VIA. But i don't know Is this way correct ?

<img width="1189" alt="微信图片_20191220160901" src="https://user-images.githubusercontent.com/46890305/71240037-13314b00-2343-11ea-9a2b-257e9aff73c5.png">
Some of the facility information are in the picture above.

**Comment by jfbischoff** [comment]
Hi, the facilities are in the right format, but the link IDs are wrong. They need to correspond with the IDs of the MATSim network.

**Comment by jfbischoff** [comment]
> setUsingTravelTimeCheckInTeleportation 
You do not need the travel time check.

**Comment by huangyuantan** [comment]
I know so i use the add the link id like this:
<img width="598" alt="微信图片_20191220163623" src="https://user-images.githubusercontent.com/46890305/71241559-e54e0580-2346-11ea-83a4-7b802dfc9fbc.png">
Is it correspond with the network like you said?

**Comment by jfbischoff** [comment]
yes, that looks good

**Comment by huangyuantan** [comment]
I delete the setUsingTravelTimeCheckInTeleportation and runs the simulation but i can't see any difference. I check the event file, and The non_network_walk distance is still 0...
Take this for example.

<img width="1031" alt="微信图片_20191220170819" src="https://user-images.githubusercontent.com/46890305/71243539-8474fc00-234b-11ea-93d1-41ec75745ad5.png">

So i check the parkingslots file and the parking lot is actually been occupied by veh187766301 during this period. 
<img width="449" alt="微信图片_20191220171047" src="https://user-images.githubusercontent.com/46890305/71243613-aec6b980-234b-11ea-8355-9a2cccd6d968.png">

Which makes me confused if this simulation runs properly or not...Do you have the right format for parking search in relative scenario ?  I just want to know whether it is correct, if not, what could be the reason for that
Thanks a lot

**Comment by huangyuantan** [comment]
> I've added a bugfix. It might take some hours before it is accessible to your (please update your maven projects).

Still confused about the update of my maven project. There is a question that i use the berlin example from https://github.com/matsim-scenarios/matsim-berlin
And i add the parking module like this:
<img width="550" alt="微信图片_20191220160437" src="https://user-images.githubusercontent.com/46890305/71266929-65469080-2384-11ea-8a05-eac09c115385.png">


I don't have much knowledge about the implementation of pom.. How can i edit the code to get the version you editted yesterday?

**Comment by huangyuantan** [comment]
For that question above. Actually i editted the origin plan file from berlin-1ct-plan-file.
As the picture below:
<img width="1085" alt="微信图片_20191221010239" src="https://user-images.githubusercontent.com/46890305/71271036-fcfcac80-238d-11ea-90d9-d5f27a010bd3.png">
I delete the part of car interaction and non_network_walk here as if i run the simulation with them. The events file will not contains event like person leaves vehicles and others related to the normal situation, which keeps me wonder if these information are important or not?

I have already edit my plan files like the example in parking search as:
<img width="1085" alt="微信图片_20191221012043" src="https://user-images.githubusercontent.com/46890305/71277527-261e3c80-2390-11ea-8cff-1806c8bb836a.png">

Is this format correct. So far i could only try to make these input file as close to the example input as possible but the result is still not good.

My biggest concern is still about the walking part between activity location and parking lots. I want to know what the common events look like and what i can do to make the simulation result with these walk information. 

Please give me some explanation if you have time to do so. As the creator of parking search you have more experience in dealing with problems with it than others. Sorry for rudeness cause I have looked for your advice for month.

Thanks anyway! 
@jfbischoff

**Comment by huangyuantan** [comment]
I also post my run example here to see if there are any problems with it (the code related to parking search is from the **RunparkingsearchExample** and is not changed at all ,is that correct?)

public final class RunBerlinScenario {

	private static final Logger log = Logger.getLogger(RunBerlinScenario.class );

	public static void main(String[] args) {
		
		for (String arg : args) {
			log.info( arg );
		}
		
		if ( args.length==0 ) {
			args = new String[] {"scenarios/berlin-v5.4-10pct/input/berlin-v5.4-1pct.config.xml"}  ;
		}

		Config config = prepareConfig( args ) ;
		
		
		
		boolean otfvis = false;

		new RunBerlinScenario().run(config,otfvis);

	}
	

	public static Controler prepareControler( Scenario scenario ) {
		// note that for something like signals, and presumably drt, one needs the controler object
		
		Gbl.assertNotNull(scenario);
		
		final Controler controler = new Controler( scenario );
		
		if (controler.getConfig().transit().isUsingTransitInMobsim()) {
			// use the sbb pt raptor router
			controler.addOverridingModule( new AbstractModule() {
				@Override
				public void install() {
					install( new SwissRailRaptorModule() );
				}
			} );
		} else {
			log.warn("Public transit will be teleported and not simulated in the mobsim! "
					+ "This will have a significant effect on pt-related parameters (travel times, modal split, and so on). "
					+ "Should only be used for testing or car-focused studies with a fixed modal split.  ");
		}
		
		// use the (congested) car travel time for the teleported ride mode
		controler.addOverridingModule( new AbstractModule() {
			@Override
			public void install() {
				addTravelTimeBinding( TransportMode.ride ).to( networkTravelTime() );
				addTravelDisutilityFactoryBinding( TransportMode.ride ).to( carTravelDisutilityFactoryKey() );
			}
		} );       
		return controler;
	}
	
	public static Scenario prepareScenario( Config config ) {
		
		Gbl.assertNotNull( config );
		
		// note that the path for this is different when run from GUI (path of original config) vs.
		// when run from command line/IDE (java root).  :-(    See comment in method.  kai, jul'18
		// yy Does this comment still apply?  kai, jul'19

		final Scenario scenario = ScenarioUtils.loadScenario( config );
		
		for ( ActivityFacility fac : scenario.getActivityFacilities().getFacilities().values() ) {
			if ( fac.getLinkId()==null ) {
				final Coord coord = fac.getCoord();
				Gbl.assertNotNull(coord);
				Link link = NetworkUtils.getNearestLink( scenario.getNetwork(), coord) ;
				Gbl.assertNotNull(link);
				((ActivityFacilityImpl)fac).setLinkId( link.getId() );
			}
		}
		
		return scenario;
	}
	
	public static Config prepareConfig( String [] args ) {
		OutputDirectoryLogging.catchLogEntries();
		
		String[] typedArgs = Arrays.copyOfRange( args, 1, args.length );

		final Config config = ConfigUtils.loadConfig( args[ 0 ], new ParkingSearchConfigGroup() ); // I need this to set the context
		
		config.controler().setRoutingAlgorithmType( FastAStarLandmarks );
		
		config.subtourModeChoice().setProbaForRandomSingleTripMode( 0.5 );
		
		StarttimeInterpretation onlyUseStarttime=StarttimeInterpretation.onlyUseStarttime;
		config.qsim().setSimStarttimeInterpretation(onlyUseStarttime);
		
		config.transit().setUseTransit(false);
		config.transit().setUsingTransitInMobsim(false);
		
		ParkingSearchConfigGroup configGroup = (ParkingSearchConfigGroup) config.getModules().get(ParkingSearchConfigGroup.GROUP_NAME);
		configGroup.setParkingSearchStrategy(ParkingSearchStrategy.Random);
		
		config.plansCalcRoute().setRoutingRandomness( 3. );
		config.plansCalcRoute().removeModeRoutingParams(TransportMode.ride);
		config.plansCalcRoute().removeModeRoutingParams(TransportMode.pt);
		config.plansCalcRoute().removeModeRoutingParams(TransportMode.bike);
		config.plansCalcRoute().removeModeRoutingParams("undefined");
	  

		config.qsim().setInsertingWaitingVehiclesBeforeDrivingVehicles( true );
				
		// vsp defaults
		config.vspExperimental().setVspDefaultsCheckingLevel( VspExperimentalConfigGroup.VspDefaultsCheckingLevel.info );
		config.plansCalcRoute().setInsertingAccessEgressWalk( true );
		config.qsim().setTrafficDynamics( TrafficDynamics.kinematicWaves );
				
		// activities:
		for ( long ii = 600 ; ii <= 97200; ii+=600 ) {
			config.planCalcScore().addActivityParams( new ActivityParams( "home_" + ii + ".0" ).setTypicalDuration( ii ) );
			config.planCalcScore().addActivityParams( new ActivityParams( "work_" + ii + ".0" ).setTypicalDuration( ii ).setOpeningTime(6. * 3600. ).setClosingTime(20. * 3600. ) );
			config.planCalcScore().addActivityParams( new ActivityParams( "leisure_" + ii + ".0" ).setTypicalDuration( ii ).setOpeningTime(9. * 3600. ).setClosingTime(27. * 3600. ) );
			config.planCalcScore().addActivityParams( new ActivityParams( "shopping_" + ii + ".0" ).setTypicalDuration( ii ).setOpeningTime(8. * 3600. ).setClosingTime(20. * 3600. ) );
			config.planCalcScore().addActivityParams( new ActivityParams( "other_" + ii + ".0" ).setTypicalDuration( ii ) );
		}
		config.planCalcScore().addActivityParams( new ActivityParams( "freight" ).setTypicalDuration( 12.*3600. ) );

		ConfigUtils.applyCommandline( config, typedArgs ) ;


		
		return config ;
	}
	
	public void run(Config config, boolean otfvis) {
		Scenario scenario = prepareScenario( config ) ;
		Controler controler = prepareControler( scenario ) ;
		config.qsim().setSnapshotStyle(SnapshotStyle.withHoles);

		
		controler.addOverridingModule(new AbstractModule() {
			
			@Override
			public void install() {
				ParkingSlotVisualiser visualiser = new ParkingSlotVisualiser(scenario);
				addEventHandlerBinding().toInstance(visualiser);
				addControlerListenerBinding().toInstance(visualiser);
			}
		});
		if (otfvis) {
			controler.addOverridingModule(new OTFVisLiveModule());
		}
		SetupParking.installParkingModules(controler);
		controler.run();
	}
}

**Comment by huangyuantan** [comment]
In addition. How can i use the **ParkingSearchAndEgressTimeEvaluator** in parking search module? i check the runexample there and it is not used. Could you please give me an example of how to using this? as i am not sure how to implement the variables there like the monitored ID
@jfbischoff  Thanks a lot

**Comment by huangyuantan** [comment]
<img width="471" alt="微信图片_20191221141342" src="https://user-images.githubusercontent.com/46890305/71304083-7cc16000-23fc-11ea-9998-284c9ef5aa4f.png">
I found another serious mistake is that i check the parkingslots file and it shows that during the same period, there are so many parking lots being occupied by the same vehicle...
I have no idea why so many erros happen around...Please give me some suggestions for improvement...
Thanks
