### ISSUE TITLE
problems about using pom.xml

### ISSUE THREAD

**Issue by huangyuantan** [matsim-org/matsim-code-examples#257]
Hi. I am using the pom of https://github.com/matsim-scenarios/matsim-berlin and i used to added the dependency of parking module by this.
<img width="550" alt="微信图片_20191220160437" src="https://user-images.githubusercontent.com/46890305/71260276-7340e500-2375-11ea-93f6-dc9cc2c4ade9.png">

But yesterday the parking module is editted with new features and i want to refresh it but the result is the same. So i am wondering what i need to change about the pom if i want to use the parking of https://github.com/matsim-org/matsim ?
 And i check the mastim master and it is using 12.0-snapshot but when i change the version nothing happen at all.
Thanks. I am not good at the maven..so i come to ask this question.

**Comment by michalmac** [comment]
The CI pipeline: http://ci.matsim.org:8080/job/MATSim_M2/ is broken right now. We will try to resolve it in the coming days.

**Comment by michalmac** [comment]
Since it's broken, new snapshot versions are not being deployed.

**Comment by huangyuantan** [comment]
> Since it's broken, new snapshot versions are not being deployed.

so currently no update is allowed for the pom?

**Comment by jfbischoff** [comment]
In case it is working again: You can update your project via Maven->Update using intelliJ. Not sure how it works using other IDEs.

**Comment by huangyuantan** [comment]
> In case it is working again: You can update your project via Maven->Update using intelliJ. Not sure how it works using other IDEs.

so is that means i can just use the version 12.0-snapshot in pom when it is able to work?

**Comment by michalmac** [comment]
@huangyuantan the snapshot deployments is back. Please update the maven dependencies in your project (in an hour or two from now).

**Comment by mirony0** [comment]
@michalmac Hi, my account can't reply by some reason so i have to use another one. I try to update my project but it doesn't work. here is my pom file. I notice that the update is in matsim.master. Is that the problem? What do i need to edit in my pom to get the latest? Thanks!
<img width="486" alt="微信图片_20200103190845" src="https://user-images.githubusercontent.com/59462570/71720456-cda17180-2e5c-11ea-81f5-4366e66aaf71.png">

**Comment by michalmac** [comment]
please set the matsim version to `12.0-SNAPSHOT`

**Comment by mirony0** [comment]
I also tried this but it still don't work
My whole pom file is as below:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.github.matsim-vsp</groupId>
	<artifactId>matsim-berlin</artifactId>
	<version>5.4</version>

	<name>MATSim Open Berlin scenario project</name>
	<description>MATSim Open Berlin scenario project</description>
	
	<properties>
	  
	  <matsim.version>12.0-SNAPSHOT</matsim.version>
	</properties>

	<repositories>
		
		
		<repository>
			<id>matsim</id>
			<url>https://dl.bintray.com/matsim/matsim</url>
		</repository>
		
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
		
		<repository>
			
			<id>osgeo</id>
			<name>Geotools repository</name>
			<url>http://download.osgeo.org/webdav/geotools</url>
		</repository>
		
		<repository>
			
			<id>ojo-snapshots</id>
			<url>http://oss.jfrog.org/libs-snapshot</url>
		</repository>
		
	</repositories>

	<dependencies>
		
		
		<dependency>
			<groupId>org.matsim</groupId>
			<artifactId>matsim</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		
		<dependency>
        		<groupId>org.matsim.contrib</groupId>
        		<artifactId>emissions</artifactId>
        		<version>${matsim.version}</version>
        		<scope>compile</scope>
      		</dependency>

		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			
			<groupId>org.matsim</groupId>
			<artifactId>matsim</artifactId>
			<type>test-jar</type>
			<version>${matsim.version}</version>
			<scope>test</scope>
		</dependency>
		
		<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.2.11</version>
        </dependency>
        
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.2.11</version>
        </dependency>
        
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.2.11</version>
        </dependency>
        
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>
        
		<dependency>
            
            
            
            
            		
			
			
			
			

			
			
			<groupId>com.github.vsp-gleich</groupId>
			<artifactId>matsim-sbb-extensions</artifactId>
			<version>11.6-vsp-2019-08-26</version>
        </dependency>
            
		<dependency>
                  <groupId>org.matsim.contrib</groupId>
                  <artifactId>common</artifactId>
                  <version>${matsim.version}</version>
            	</dependency>
              	
       <dependency>
                    <groupId>org.matsim.contrib</groupId>
                    <artifactId>parking</artifactId>
                    <version>12.0-SNAPSHOT</version>
              </dependency>
              
		<dependency>
                    <groupId>org.matsim.contrib</groupId>
                    <artifactId>analysis</artifactId>
                    <version>${matsim.version}</version>
              </dependency>

	      
	      
	      
	      
	      
	      
	      
	      
	      
	      
	      
	      

        </dependencies>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<showWarnings>false</showWarnings>
					<showDeprecation>false</showDeprecation>
					<encoding>UTF-8</encoding>
					
					<fork>true</fork>
					<meminitial>128m</meminitial>
					<maxmem>512m</maxmem>
					<compilerArguments>
						<Xmaxwarns>4000</Xmaxwarns>
						<Xmaxerrs>100</Xmaxerrs>
					</compilerArguments>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
				<configuration>
					<downloadSources>true</downloadSources>
					<downloadJavadocs>true</downloadJavadocs>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19</version>
				<configuration>
					<excludes>
						<exclude>**/*$*</exclude> 
						<exclude>org/matsim/testcases/TestDepth.java</exclude>
						<exclude>org/matsim/testcases/MatsimTestCase.java</exclude>
					</excludes>
					<forkMode>once</forkMode>
					
					<argLine>-Xmx6000m -Djava.awt.headless=true -Dmatsim.preferLocalDtds=true</argLine>
					
					
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<archive>
						<manifest>
							<mainClass>org.matsim.gui.RunBerlinScenarioGUI</mainClass>
						</manifest>
					</archive>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>  
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	
	<profiles>
		<profile>
			<id>release</id>
			<build>
				<defaultGoal>assembly:assembly</defaultGoal>
				<pluginManagement>
					<plugins>
						<plugin>
							<artifactId>maven-assembly-plugin</artifactId>
							<configuration>
								<descriptors>
									<descriptor>src/main/assembly/assembly-release.xml</descriptor>
								</descriptors>
							</configuration>
						</plugin>
						<plugin>
							<artifactId>maven-jar-plugin</artifactId>
							<configuration>
								<archive>
									<manifest>
										<addClasspath>true</addClasspath>
										<classpathPrefix>libs/</classpathPrefix>
									</manifest>
								</archive>
							</configuration>
						</plugin>
					</plugins>
				</pluginManagement>
			</build>
		</profile>
		<profile>
			<id>java-9+</id>
			<activation>
				<jdk>[9</jdk>
			</activation>
			<dependencies>
				<dependency>
					<groupId>javax.xml.bind</groupId>
					<artifactId>jaxb-api</artifactId>
					<version>2.3.1</version>
				</dependency>
				<dependency>
					<groupId>com.sun.xml.bind</groupId>
					<artifactId>jaxb-core</artifactId>
					<version>2.3.0.1</version>
				</dependency>
				<dependency>
					<groupId>com.sun.xml.bind</groupId>
					<artifactId>jaxb-impl</artifactId>
					<version>2.3.0.1</version>
				</dependency>
			</dependencies>
		</profile>
	</profiles> 
	
</project>

**Comment by michalmac** [comment]
Looks OK. What is the error?
