### ISSUE TITLE
There exists already a node with id = 1.

### ISSUE THREAD

**Issue by Mayoookh** [matsim-org/matsim-code-examples#26]
Hello , 

I tried to make my manual networks by **typing** a config file instead of any code. A basic netwok file with 7 nodes and 4 Public Transport stops to get started with _mode choice strategy_ of MATSim. 

However, I get this error after running MATSim 0.10 :

Error in custom provider, java.lang.IllegalArgumentException: There exists already a node with id = 1.

There is just one node in my network file. I have attached my files here so you could have an idea. 
[config.zip](https://github.com/matsim-org/matsim-code-examples/files/2519579/config.zip)
[network.zip](https://github.com/matsim-org/matsim-code-examples/files/2519580/network.zip)
[population.zip](https://github.com/matsim-org/matsim-code-examples/files/2519581/population.zip)
[transitschedule.zip](https://github.com/matsim-org/matsim-code-examples/files/2519582/transitschedule.zip)
[transitVehicles.zip](https://github.com/matsim-org/matsim-code-examples/files/2519583/transitVehicles.zip)

Thanks a lot in advance!

**Comment by kainagel** [comment]
Hello, could you please attach the logfile as well?  Thanks ...

**Comment by Mayoookh** [comment]
Hello Dr. Nagel, 

Thank you for a quick revert. 

My config file doesn't produce any output because of this error, therefore, I don't have a logfile for this case. Therefore, I have just copied the error messages into text file and pasted it here. I hope that works. 

[logFile.zip](https://github.com/matsim-org/matsim-code-examples/files/2519776/logFile.zip)

**Comment by Mayoookh** [comment]
Hello Dr. Nagel, 

I hope I have attached the correct file.
