### ISSUE TITLE
Error whit Av contrib

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/matsim-code-examples#260]
Hello Everybody and best wishes,
I'm trying to introduce Autonomous Taxi fleet service in my scenario, so I adapted my RunCode and set everything, but I get an error when I try to run. 
I'm getting stuck with this, so i'm asking, but I guess it's something very basic in the config/Runcode, so I'll attach here all. Hope you can help. Thanks and Merry Christmas to everybody.
ATaxi is the mode I'm trying to introduce as AVs:

ERROR LogFile
[AT0.logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/3998380/AT0.logfileWarningsErrors.log)

RunCode:
`
import org.matsim.api.core.v01.Scenario;
import org.matsim.contrib.av.robotaxi.fares.taxi.TaxiFareConfigGroup;
import org.matsim.contrib.dvrp.run.DvrpConfigGroup;
import org.matsim.contrib.dvrp.run.DvrpModule;
import org.matsim.contrib.dvrp.run.DvrpQSimComponents;
import org.matsim.contrib.taxi.run.TaxiConfigConsistencyChecker;
import org.matsim.contrib.taxi.run.TaxiConfigGroup;
import org.matsim.contrib.taxi.run.TaxiModule;
import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.controler.Controler;
import org.matsim.core.controler.OutputDirectoryHierarchy;
import org.matsim.core.gbl.Gbl;
import org.matsim.core.scenario.ScenarioUtils;
import org.matsim.roadpricing.RoadPricingConfigGroup;
import org.matsim.roadpricing.RoadPricingModule;

import ch.sbb.matsim.config.SwissRailRaptorConfigGroup;
import ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule;

/**
 * @author MAlbertini 
 *
 */
public class RunTrentoATaxi{
	public static void main(String[] args) {
		if ( args.length==0 ) {
			args = new String [] { "scenarios/AT introduction/AT_Config.xml" } ;
		} else {
			Gbl.assertIf( args[0] != null && !args[0].equals( "" ) );
		}

		Config config = ConfigUtils.loadConfig( args, new DvrpConfigGroup(), new TaxiConfigGroup(), new TaxiFareConfigGroup(),new RoadPricingConfigGroup(), new SwissRailRaptorConfigGroup() ) ;
		
		// possibly modify config here----------------------------------------------------------------------------------------------
		
//		config.controler().setLastIteration( 10 );
		config.controler().setOverwriteFileSetting( OutputDirectoryHierarchy.OverwriteFileSetting.deleteDirectoryIfExists );
		config.plansCalcRoute().setInsertingAccessEgressWalk( true );
		config.addConfigConsistencyChecker(new TaxiConfigConsistencyChecker());
		config.checkConsistency();

		String mode = TaxiConfigGroup.get(config).getMode();

		// ------------------------------------------------------------------------------------------------------------------------
		
		Scenario scenario = ScenarioUtils.loadScenario(config) ;

		// possibly modify scenario here-------------------------------------------------------------------------------------------

//		new NetworkCleaner().run( scenario.getNetwork() );
		
		Controler controler = new Controler( scenario ) ;
		
		// possibly modify controler here------------------------------------------------------------------------------------------
		
//		To use SwissRailRaptor faster and working pt router (Part 1 of 1)
		controler.addOverridingModule(new SwissRailRaptorModule());
//		controler.addOverridingModule( new OTFVisLiveModule() ) ;
		controler.addOverridingModule(new DvrpModule());
        controler.addOverridingModule(new TaxiModule());
		controler.addOverridingModule( new RoadPricingModule() );   
		controler.configureQSimComponents(DvrpQSimComponents.activateModes(mode));     
                
		// ------------------------------------------------------------------------------------------------------------------------
		
		controler.run();
	}
	
}
`

Config File:

> <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">

<config>

	<module name="global">
		<param name="randomSeed" value="4711" />
		<param name="coordinateSystem" value="EPSG:3857" />
		<param name="numberOfThreads" value="8" />
	</module>
	
	<module name="network">
		<param name="inputNetworkFile" value="Trento_Network.xml" />
	</module>

	<module name="plans">
		<param name="inputPlansFile" value="CaydtsUpScaledPopulation.xml.gz" />
	</module>

	<module name="transit">
		<param name="useTransit" value="true" />
		<param name="transitScheduleFile" value="ScheduleFile.xml" />
		<param name="vehiclesFile" value="vehicleFile.xml" />
		<param name="transitModes" value="pt" />
	</module>
	
	<module name="TimeAllocationMutator">
		<param name="mutationRange" value="3600.0"/>

	</module>
		<module name="changeMode" >
		
		<param name="ignoreCarAvailability" value="false" />
		
		<param name="modeSwitchBehavior" value="fromSpecifiedModesToSpecifiedModes" />
		
		<param name="modes" value="car,ride,pt,bike,walk" />
	</module>

	<module name="controler">
		<param name="outputDirectory" value="./output/ModeShareCalibration" />
		<param name="firstIteration" value="0" />
		<param name="lastIteration" value="500" />
		<param name="mobsim" value="qsim" />			
		<param name="runId" value="ModalShare" />
		
		<param name="routingAlgorithmType" value="FastAStarLandmarks" />
		<param name="eventsFileFormat" value="xml" />
		
		<param name="writeEventsInterval" value="50" />
		<param name="writePlansInterval" value="50" />
		<param name="snapshotFormat" value="" />
		<param name="writeSnapshotsInterval" value="50" />
	</module>
	
	<module name="counts">
		<param name="countsScaleFactor" value="1.9" />
		<param name="inputCountsFile" value="counts.xml" />
		<param name="outputformat" value="all" />
		<param name="distanceFilter" value="null" />
		<param name="distanceFilterCenterNode" value="null" />
		
		<param name="analyzedModes" value="car" />
		
		<param name="averageCountsOverIterations" value="1" />
		
		<param name="outputformat" value="txt" />
		<param name="writeCountsInterval" value="50" />
	</module>
	<module name="ptCounts" >
		<param name="countsScaleFactor" value="1.0" />
		<param name="distanceFilter" value="null" />
		<param name="distanceFilterCenterNode" value="null" />
		
		<param name="inputAlightCountsFile" value="null" />
		
		<param name="inputBoardCountsFile" value="null" />
		
		<param name="inputOccupancyCountsFile" value="null" />
		<param name="outputformat" value="txt" />
		<param name="ptCountsInterval" value="50" />
	</module>

	<module name="qsim">	
	    <param name="startTime" value="00:00:00" />
		
		<param name="endTime" value="24:00:00" />
		<param name="vehiclesSource" value="modeVehicleTypesFromVehiclesData" />
		
		<param name="mainMode" value="car" />
		
		<param name="linkDynamics" value="PassingQ" />
		
		<param name="numberOfThreads" value="8" />
		<param name="trafficDynamics" value="kinematicWaves" />
		
		<param name="stuckTime" value="30.0" />	
		
		<param name="useLanes" value="false" />
		
		<param name="vehicleBehavior" value="teleport" />
		<param name="snapshotperiod"	value = "00:00:00"/> 		
		<param name="flowCapacityFactor" value="0.75" /> 
		<param name="storageCapacityFactor" value="0.9" />
		<param name="snapshotStyle" value="queue" />
		<param name="insertingWaitingVehiclesBeforeDrivingVehicles" value="true"/>
	</module>

	<module name="strategy">
		
		<param name="fractionOfIterationsToDisableInnovation" value="Infinity" />
		
		<param name="maxAgentPlanMemorySize" value="5" />
		<parameterset type="strategysettings">
			
			<param name="strategyName" value="ChangeExpBeta"/>
			<param name="weight" value="1.0"/>
		</parameterset>
		<parameterset type="strategysettings">
			<param name="strategyName" value="ReRoute"/>
			<param name="weight" value="0.1"/>
		</parameterset>
		<parameterset type="strategysettings">
			<param name="strategyName" value="TimeAllocationMutator"/>
			<param name="weight" value="0.1"/>
		</parameterset>		
		<parameterset type="strategysettings">
			<param name="strategyName" value="SubtourModeChoice"/>
			<param name="weight" value="0.1"/>
		</parameterset>	
	</module>
	
	<module name="subtourModeChoice">
		<param name="chainBasedModes" value="car,bike" />
		<param name="considerCarAvailability" value="true"/>
		
		<param name="behavior" value="fromSpecifiedModesToSpecifiedModes" />
		
		<param name="modes" value="car,pt,bike,ride,walk" />
	</module>

	<module name="planCalcScore">	
		<param name="PathSizeLogitBeta" value="1.0" />
		<param name="learningRate" value="1.0" />
		<param name="BrainExpBeta" value="2.0" />
		<param name="marginalUtilityOfMoney" value="1.0" />
		<param name="lateArrival" value="-18" />
		<param name="performing" value="+6" />
		<param name="traveling" value="-6" />
        <param name="waiting" value="0.0" />
		<param name="waitingPt" value="-2.0" />
		<param name="utilityOfLineSwitch" value="-1" />
		<parameterset type="activityParams" >
			<param name="activityType" value="home" />
			<param name="minimalDuration" value="00:15:00" />
			<param name="typicalDuration" value="08:00:00" />
		</parameterset>			
		<parameterset type="activityParams" >
			<param name="activityType" value="work" />
			<param name="minimalDuration" value="05:00:00" />
			<param name="typicalDuration" value="08:00:00" />
			<param name="openingTime" value="06:00:00" />
			<param name="latestStartTime" value="13:00:00" />
			<param name="closingTime" value="21:00:00" />
		</parameterset>			
		<parameterset type="activityParams" >
			<param name="activityType" value="education" />
			<param name="minimalDuration" value="03:00:00" />
			<param name="typicalDuration" value="06:00:00" />
			<param name="openingTime" value="08:00:00" />
			<param name="latestStartTime" value="15:30:00" />
			<param name="closingTime" value="18:30:00" />
		</parameterset>		
		<parameterset type="activityParams" >
			<param name="activityType" value="leisure" />
			<param name="minimalDuration" value="00:15:00" />
			<param name="typicalDuration" value="01:00:00" />
		</parameterset>		
		<parameterset type="activityParams" >
			<param name="activityType" value="shop" />
			<param name="minimalDuration" value="00:25:00" />
			<param name="typicalDuration" value="01:00:00" />
		</parameterset>
		<parameterset type="modeParams">
			<param name="mode" value="car"/>
			<param name="constant" value="-1.87" />
			<param name="marginalUtilityOfDistance_util_m" value="0.0" />
			<param name="marginalUtilityOfTraveling_util_hr" value="-0.3" />
			<param name="monetaryDistanceRate" value="-0.00035" />
		</parameterset>
		<parameterset type="modeParams">
			<param name="mode" value="ride"/>
			<param name="constant" value="-3.10" />
			<param name="marginalUtilityOfDistance_util_m" value="0.0" />
			<param name="marginalUtilityOfTraveling_util_hr" value="-0.2" />
			<param name="monetaryDistanceRate" value="-0.0002" />
		</parameterset>	
		<parameterset type="modeParams">
			<param name="mode" value="pt"/>
			<param name="constant" value="-0.55" />
			<param name="marginalUtilityOfDistance_util_m" value="0.0" />
			<param name="marginalUtilityOfTraveling_util_hr" value="-0.185" />
			<param name="monetaryDistanceRate" value="-0.00002" /> 
		</parameterset> 
		<parameterset type="modeParams">
			<param name="mode" value="walk"/>
			<param name="constant" value="-0.25" />
			<param name="marginalUtilityOfDistance_util_m" value="0.0" />
			<param name="marginalUtilityOfTraveling_util_hr" value="-12.0" />
			<param name="monetaryDistanceRate" value="0.0" />
		</parameterset> 
		<parameterset type="modeParams" >
			<param name="mode" value="bike" />
			<param name="constant" value="-3.30" />
			<param name="marginalUtilityOfDistance_util_m" value="0.0" />
			<param name="marginalUtilityOfTraveling_util_hr" value="-9.0" />
			<param name="monetaryDistanceRate" value="0.0" />
		</parameterset>
	</module>
	
	<module name="planscalcroute" >

		<param name="networkModes" value="car,bike,ride" />
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="walk" />
			<param name="teleportedModeSpeed" value="1.111111" />
		</parameterset>
	</module>
	
	<module name="transitRouter" >
		
		<param name="additionalTransferTime" value="0.01" />
		
		<param name="directWalkFactor" value="99999999.0" />
		
		<param name="extensionRadius" value="200.0" />
		
		<param name="maxBeelineWalkConnectionDistance" value="600.0" />
		
		<param name="searchRadius" value="1000.0" />
	</module>
	<module name="swissRailRaptor">
		<param name="useIntermodalAccessEgress" value="false" />  
		<parameterset type="intermodalAccessEgress" >
			<param name="mode" value="walk" />
			<param name="radius" value="1000" />
		</parameterset>
	</module>
	
	<module name="roadpricing" >
		<param name="tollLinksFile" value="Toll.xml" />
	</module>
	
	<module name="vehicles" >
		<param name="vehiclesFile" value="mode vehicles.xml" />
	</module>
	
	<module name="travelTimeCalculator" >
		<param name="analyzedModes" value="car,bike,pt,walk,ride" />
		<param name="separateModes" value="true" />
	</module>		

</config>

**Comment by michalmac** [comment]
I do not see a taxi config specified in your config file. Could you verify this?

**Comment by MAlbertini95** [comment]
Yes, I solved a couple of days ago,  the issue is mainly closed, still have one question about DVRP module.. How does the network mode parameter act? Is it better to use "car" only or "car,taxi"? How are taxis travel time calculated? Do it consider congestion of car+taxi on the network? Thanks

**Comment by michalmac** [comment]
There are a couple of different ways "mode" can be interpreted within the DVRP context:
- mobsim mode (here all taxis are "cars", and so the car travel time is used to estimate the taxi travel time; see `DvrpConfigGroup.networkModes`)
- routing/network mode (determining which links can be used by taxis, by default the "car" network is used; however you can change it with `DvrpConfigGroup.networkModes` and `Taxi/DrtConfigGroup.isUseModeFilteredSubnetwork`)
- service mode (used by passengers who want to travel using this service, typically "taxi" or "drt", but could be "uber" or "myFavouriteLocalTaxi")

**Comment by MAlbertini95** [comment]
Thank you, that cleared my doubt!
