### ISSUE TITLE
Mode Analysis error

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/matsim-code-examples#262]
Hello everybody, 
I switched to MATSim 12.0-SNAPSHOT, but when I make a run, I notice a strange behaviour: the mode share statistics are completely wrong. 

1. I set analyzedModes values, but they'just ignored in the output mode stats, considering also access_walk and egress_walk.

2. Looks like some modes are initially not used (0.0) while for sure they exists in plans file and were used in 11.0 version. The whole stats are very confused and wrong, and I can see it in the leg histograms file, which seem to be correct.

3. If I set no mode params/route params for access_walk/egress_walk ( already in plans file ), the simulation stops saying something like [access_walk] does not pertain to [modes]. 

Any idea on how to solve? Thanks for attention, best regards.

**Comment by Janekdererste** [comment]
The handling of modes during routing and analysis is currently undergoing substantial changes. For your simulation runs you should opt for the stable 11-version or, if you really need a new feature, pin your matsim version to a weekly release.

**Comment by kainagel** [comment]
See #263.
