### ISSUE TITLE
How to map road congestion?

### ISSUE THREAD

**Issue by KamijoYo** [matsim-org/matsim-code-examples#269]
I want to map traffic and congestion on the roads in the simulation, using Via or GIS.
I would like to know if there is such a function or a hint to do this.
I know the file linkstats.txt is important.

**Comment by MAlbertini95** [comment]
Hi,
I was interested in doing the same, so I wonder if  you have found some way to do it..

**Comment by JWJoubert** [comment]
@KamijoYo @MAlbertini95 I would recommend you look at Via's documentation. For example, the [Link Volumes](https://docs.simunto.com/via/analyses/network-queries.html#link-volumes).

Also, you can visualise the links itself. Once you loaded a network and events file into Via, you can change the _Link Attributes_ and click on Add... and that will allow you load average speeds and volumes from the events file.  When the attributes are created, you can change the link colour to use those added attributes (they should then appear in your drop-down list).

**Comment by KamijoYo** [comment]
Thank you very much for your reply.
I tried as advised and was able to map volumes.
