### ISSUE TITLE
Issues with cadyts contrib

### ISSUE THREAD

**Issue by LorenaBR** [matsim-org/matsim-code-examples#27]
I'm trying to automatically calibrate my simulation with the cadyts extension, using maven as recommended, because the result of the counts I had with the simulation was quite different from the real counts.
I believe I did everything correctly, but when I run the matsim via maven appears this error: 

java.lang.NullPointerException
at org.matsim.contrib.cadyts.car.PlansTranslatorBasedOnEvents.handleEvent (PlansTranslatorBasedOnEvents.java:131)

I am attaching my log file.
Thanks in advance for any help.

[Logfile.txt](https://github.com/matsim-org/matsim-code-examples/files/2545361/Logfile.txt)

**Comment by golanbendor** [comment]
Are you using PT in your simulation?

If so, PT doesn't have any plans (like a regular agent has) so this could explain why you are getting the java.lang.NullPointerException from line 131 in the class PlansTranslatorBasedOnEvents.java:
`Plan selectedPlan = person.getSelectedPlan();`

This is a known issue - more details and a possible fix here:
https://matsim.atlassian.net/browse/MATSIM-648

**Comment by LorenaBR** [comment]
From what I understand, I would have to modify the code, and I am not allowed to do that. How can I change the code? How can i put -- (person == null) ? return-- in the PlansTranslatorBasedonEvents ?
Thans for your answer

**Comment by LorenaBR** [comment]
Hello again,
Yes, i'm using PT simulation and I want to use Cadyts to work with a scenario that simulates public transit vehicles as regular vehicles on links. (transit vehicles pass a count station the same way as private cars)

I believe I did what you recommended correctly, 
I defined - ((person == null)? return - in the PlansTranslatorBasedonEvents, but the same error in the same place (L131) happened .. it seems the change I made did not work .

I don't know if i did something wrong or actually to put (_person=null) return_ it will not make difference in my case.

Do you know anything else I can do?
Follow my logfile.

[logfileWarningsErrors2.txt](https://github.com/matsim-org/matsim-code-examples/files/2554469/logfileWarningsErrors2.txt)

Thanks for any help!!

**Comment by LorenaBR** [comment]
> Are you using PT in your simulation?
> 
> If so, PT doesn't have any plans (like a regular agent has) so this could explain why you are getting the java.lang.NullPointerException from line 131 in the class PlansTranslatorBasedOnEvents.java:
> `Plan selectedPlan = person.getSelectedPlan();`
> 
> This is a known issue - more details and a possible fix here:
> https://matsim.atlassian.net/browse/MATSIM-648

**Comment by g-bd** [comment]
Try replacing the original line (121):
`if (driverId == null)`
with this line:
`if (driverId == null || driverId.toString().startsWith(TransportMode.pt)) `

**Comment by golanbendor** [comment]
Try replacing the original line (121): 
`if (driverId == null) `
with this line:
` if (driverId == null || driverId.toString().startsWith(TransportMode.pt))`

**Comment by kainagel** [comment]
> I defined - ((person == null)? return - in the PlansTranslatorBasedonEvents, but the same error in the same place (L131) happened .. it seems the change I made did not work .

if ( person == null ) return ;

is probably not the same as what you tried with ? and :; see here:

https://stackoverflow.com/questions/18124745/java-ternary-operator-and-nullpointerexception

Your code is not exactly the same as that one, but since you did not give the full code I cannot really tell.

**Comment by LorenaBR** [comment]
Thansk for all your answer, but i realized that even doing this changes in the code, it seems like  the if condition (if person=null return) that i've added  it's not being called that's why nothing different happens in my simulation. Do you know how can i "trigger" this change made in in the PlansTranslatorBasedonEvents?
