### ISSUE TITLE
MATsim ReRouting Strategy

### ISSUE THREAD

**Issue by gden173** [matsim-org/matsim-code-examples#272]
Hi, I am new to MATsim and looking to run a DTA using a population which only takes one trip per day from a "dummy" activity to another "dummy" activity. Per the example on page 326 in the 2016 MATsim book.    I am currently using two strategies  ChangeExpBeta (Weight = 0.7) and ReRoute(Weight = 0.3) with innovation disabled after 0.9 of the total iterations. 

My problem is that  a large number of agents are staying  on the network for far too long, and this does not seem to be improving with a larger number of iterations.   I have used a network imported from another traffic modelling software as well as one converted from OSM and still get very similar congestion patterns.   From what I can gather,  the default rerouting strategy does not take into account the previous iterations travel  times when it generates new plans in the re-planning stage.
My Question is, does MATsim currently have the capabilities to re-route plans (in the ReRoute strategy)  using  time dependent costs for each link generated by the previous iterations events?

Here is a copy of the congestion pattern from a recent simulation run using 1% of the total population.
![100 legHistogram_car](https://user-images.githubusercontent.com/50355587/72945406-688bcc80-3dc7-11ea-9928-f49219a3dbb0.png)
As well as the  config file (The simulation is mixed vehicle (car,lcv,hcv) but I have made all three types have identical attributes in the vehicles file)
[config.txt](https://github.com/matsim-org/matsim-code-examples/files/4100692/config.txt)

**Comment by kainagel** [comment]
This looks all quite plausible. 

To begin with, the ReRoute strategy surely uses the travel times of the previous iteration, so it should do what you expect it to do.  

Did you look at your results using a visualizer (e.g. VIA or otfvis)?  Often, something like what you see is a consequence of geometry, e.g. some source or sink of traffic connected to the network in a low-capacity way, and then it just takes some time to get our or in.

If you want us to have a quick look, please make output_network.xml.gz and output_events.xml.gz available to us.

**Comment by gden173** [comment]
Hi Kai,
Thanks for the quick reply.
I managed to fix the issue,  it was due to the locations people where placed on the network being slightly off  causing the congestion.
Thanks again.
