### ISSUE TITLE
Freight Config Files

### ISSUE THREAD

**Issue by giftchega** [matsim-org/matsim-code-examples#275]
Hello community, 

I am doing research on freight transport in South Africa, I am looking for examples/templates config files for a freight simulation model that I can base my configuration on. 

Please help, thanks in advance.

**Comment by kt86** [comment]
Hello giftchega,
please have a look to the answer in #276 . 

For answering more specific questions regarding a (freight) model for South Africa, @JWJoubert can most likely help you better.

**Comment by giftchega** [comment]
much appreciated
