### ISSUE TITLE
Matsim version for DRT

### ISSUE THREAD

**Issue by ChristophTraf** [matsim-org/matsim-code-examples#284]
Which matsim version would you recommend for the simulation of DRT. The release version 11.0 or the 12.0-snapshot version.

Thanks!

**Comment by jfbischoff** [comment]
11.0 is the first release with a stable running DRT. However, there are a couple of new features, such as service areas, in the snapshot version. Therefore I would recommend using the latter, if possible on a weekly release rather than the Snapshot directly.

**Comment by ChristophTraf** [comment]
thanks :)
