### ISSUE TITLE
Citations for using drt

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#288]
Hello,

  Which paper should be cited if we are using the drt module? (version 11 and 12 snapshot) I suppose the module is constantly updated. Is there a most recent publication?

Thanks,
Jishnu

**Comment by jfbischoff** [comment]
Hi Jishnu,
so far, the most up to date paper is 

J. Bischoff, M. Maciejewski, K. Nagel; City-wide Shared Taxis: A Simulation Study in Berlin, IEEE ITSC 2017, DOI: 10.1109/ITSC.2017.8317926

That said, something more up to date should be published in April.

Cheers
