### ISSUE TITLE
Exporting average link speed of all network links 

### ISSUE THREAD

**Issue by zahraeftekhar** [matsim-org/matsim-code-examples#289]
Hi all,

I am quite new to MATSim. Currently, I am running a scenario but I want to save the average speed data of all links. I also use the configuration file section of "travelTimeCalculator" but I have not got this data as an output. I also used "linkstat" section of the configuration file but nothing new happened and I also ended up with an error so I removed it again. Would you please help me.  My config file is as follows: `<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>

	<module name="global">
		<param name="randomSeed" value="1500" />
		<param name="numberOfThreads" value="5" />
	</module>
	<module name="network">
		<param name="inputNetworkFile" value="new.xml" />
	</module>

	<module name="plans">
		<param name="inputPlansFile" value="PlanWithMoreThan1.xml" />
	</module>
    <module name="parallelEventHandling" >

		
		<param name="estimatedNumberOfEvents" value="null" />

		
		<param name="numberOfThreads" value="5" />

		
		<param name="oneThreadPerHandler" value="false" />

		
		<param name="synchronizeOnSimSteps" value="true" />
	</module>
	<module name="controler">
		<param name="outputDirectory" value="./Results for Base case Amsterdam" />
		<param name="overwriteFiles" value="deleteDirectoryIfExists" />
		<param name="firstIteration" value="0" />
		<param name="lastIteration" value="1" />
		<param name="eventsFileFormat" value="xml" />
		<param name="writeEventsInterval" value="1" />
		
		<param name="writePlansInterval" value="1" />
		
		<param name="writeSnapshotsInterval" value="0" />
		<param name="snapshotFormat" value="" />
	</module>
	<module name="travelTimeCalculator"> 
		<param name="filterModes" value="true" />
		<param name="calculateLinkTravelTimes" value="true" />
	</module>
	<module name="qsim">
		<param name="startTime" value="00:00:00" />
		<param name="endTime" value="30:00:00" />
		<param name="flowCapacityFactor" value="0.2" />
		<param name="storageCapacityFactor" value=".8" />
		<param name="numberOfThreads" value="5" />
		<param name="snapshotperiod" value="00:00:00"/>

		
		<param name="removeStuckVehicles" value="false" />

		
		<param name="stuckTime" value="3600.0" />
		<param name="timeStepSize" value="00:00:01" />

		
		<param name="trafficDynamics" value="queue" />
	</module>

	<module name="planCalcScore">
	<param name="learningRate" value="1.0" />
		<param name="BrainExpBeta" value="2.0" />
        
		<param name="fractionOfIterationsToStartScoreMSA" value="0.8" /> 
		<param name="marginalUtilityOfMoney" value="-0.685" />
		 
		<param name="lateArrival" value="-18" />
		<param name="earlyDeparture" value="-0" />
		<param name="performing" value="+6" />
		<param name="traveling" value="-6" />
		<param name="waitingPt" value="-12.0" />
		<param name="utilityOfLineSwitch" value="-0.5" />
		
		
		<parameterset type="modeParams" >
				
				<param name="constant" value="-15" />
				
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				
				<param name="marginalUtilityOfTraveling_util_hr" value="-6" />
				<param name="mode" value="car" />
				
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				
				<param name="constant" value="10" />
				
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				
				<param name="marginalUtilityOfTraveling_util_hr" value="-6" />
				<param name="mode" value="pt" />
				
				<param name="monetaryDistanceRate" value="0.000154" />
			</parameterset>
			<parameterset type="modeParams" >
				
				<param name="constant" value="20" />
				
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				
				<param name="marginalUtilityOfTraveling_util_hr" value="-6" />
				<param name="mode" value="walk" />
				
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				
				<param name="constant" value="0" />
				
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="bike" />
				
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				
				<param name="constant" value="0.0" />
				
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="ride" />
				
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				
				<param name="constant" value="0.0" />
				
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="other" />
				
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				
				<param name="constant" value="0.0" />
				
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="transit_walk" />
				
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="activityParams">
			<param name="activityType" value="work" />
			<param name="typicalDuration" value="08:00:00" />
			<param name="openingTime" value="04:00:00" />
			<param name="latestStartTime" value="18:00:00" />
			<param name="closingTime" value="23:00:00" />
			<param name="priority" value="1.0" />
		</parameterset>

		<parameterset type="activityParams">
			<param name="activityType" value="home" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="12:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="bringget" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="business" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="shoppingD" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="shoppingND" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="service" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="sozializing" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="leisure" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="touring" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="1:00:00" />
		</parameterset>
	</module>

	<module name="strategy">
		<param name="fractionOfIterationsToDisableInnovation" value="0.8" />
		<param name="maxAgentPlanMemorySize" value="5" /> 

		<param name="ModuleProbability_1" value="0.7" /> 
		<param name="Module_1" value="BestScore" />

		<param name="ModuleProbability_2" value="0.1" />   
		<param name="Module_2" value="ReRoute" />

		<param name="ModuleProbability_3" value="0.1" />  
		<param name="Module_3" value="TimeAllocationMutator" />
        
		<param name="ModuleProbability_4" value="0.1" />  
		<param name="Module_4" value="ChangeTripMode" />
	</module>
 <module name="transit">
		<param name="useTransit" value="true" />
		<param name="transitScheduleFile" value="transitSchedule.xml" />
		<param name="vehiclesFile" value="transitVehicle.xml" />
		<param name="transitModes" value="pt" />
	</module>
	
	<module name="changeMode">
		<param name="modes" value="pt,car, bike, walk" />
	</module>
</config>

`

**Comment by kainagel** [comment]
Hello, could you please look in the output directory under `ITERS/it.<lastIteration>`?  There might be a file `*.linkstats.txt.gz`.  If so, could you please have a look if that helps you.  If not, we need to find out how to switch that on. :-)

The `TravelTimeCalculator`, where you changed the config for, is for the router.  It may have some influence onto the output (I don't know), but certainly output is not its primary purpose and so I would indeed recommend to leave it alone (i.e remove all entries, also the ones shown above) for what we are discussing here. (Also, `TravelTimeCalculator` until release 11 is very difficult to configure correctly ... another reason to leave if at all possible.)
