### ISSUE TITLE
Using MATSim as a beginner.

### ISSUE THREAD

**Issue by nnuk** [matsim-org/matsim-code-examples#29]
I was working on a project related to MATSim where I had to do convert the OSM data that i created on JOSM to MATSim files for further processing. The problem is that i have no Idea about MATSim, I downloaded MATSim then followed all the procedures on TU Berlin website for beginning MATSim but it didn't work. I am confused that how i have to write the java codes for config file network file plan file etc. I am using MAC and have eclipse installed where i have also tried the cloning of MATSim project from Github but it also didn't work so now i am not sure what to do. I would highly appreciate if you can kindly help me with this.

**Comment by kainagel** [comment]
Hello, could you please provide a bit more detail.  If one does not know maven, the starting point presumably is 
1. downloading the newest release zip ([matsim.org/downloads], 0.10.1?), 
1. unzip that, 
1. double-click on the jar, which should start the matsim gui.  
1. From there, it should be possible to run one of the example scenarios that were also in the zipfile.  
1. Then one has to figure out how to look at results; in general, we recommend the commercial software VIA which is free up to 500 agents and usually free for student projects (ask the maintainer).

Only after these steps have been successfully taken does it make sense to consider one's own scenario.  This is, however, not an easy exercise; it also depends on one's training.  Converting an osm network (using the matsim plugin in josm) should be relatively straightforward.  Generating a handful of vehicles that drive around on that network should also be relatively straighforward.  Beyond that, it is no longer straightforward.
So, please, provide more detail.

**Comment by nnuk** [comment]
Thankyou for your reply.
I have gone through all of these steps but whenever i run an example on gui it gives me different errors for different examples. one of the example showed following error.

10 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:73)
	at org.matsim.core.controler.Controler.run(Controler.java:189)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)

The simulation did not run properly. Error/Exit code: 1

but all of them are giving errors. I also added files to check on VIA but it does not run me a proper simulation like when time is running slowly it shows only the network but when i select the the time to +150 it just blips some lights on the network for one time in one clock cycle.

I converted my own OSM data that i built to matsim layer and then converted it to shape file because i wanted to use my own network in VIA but in VIA that shape file gave only dotted paths and not the proper street and road network. maybe i have done something wrong.

I also searched a lot about the files ( network, plans, config, events etc... ) , actually i do not know how to build these files for ones own scenario.

 I cloned a matsim project from jithub to eclipse and followed all the steps and it gave a huge number of files which was very confusing.

I wanted to know how to build all the required matsim files for my own scenario.
I hope i have provided all the detail.

**Comment by nnuk** [comment]
Can someone help me with above case. It will be highly appreciated.

**Comment by mrieser** [comment]
can you provide a full log file where the error is shown? the above error message is not enough to figure out what's going wrong.

**Comment by nnuk** [comment]
[Berlin.docx](https://github.com/matsim-org/matsim-code-examples/files/2557394/Berlin.docx)
i am attaching this file because when i click on the output it open a folder which has a log file but has not these errors. the errors which occured are in the berlin file.

**Comment by tduberne** [comment]
Here is the relevant part of the log:

> Error injecting constructor, java.lang.RuntimeException: The output directory ./output/berlin already exists and is not empty! Please either delete or empty the directory or configure the services via setOverwriteFileSetting() or the "overwriteFiles" parameter of the "services" config group.

This is also the reason why you could not find the error message in the log file: MATSim stoped before writing anything in the directory, because by default, it is configured not to change anything in an existing directory.

When you get errors from `com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist`, it is usually necessary to scroll down to see what actually was the problem. This is actually the case for a lot of exceptions ("errors"): exceptions can be thrown when intercepting other exceptions, and then usually report their cause as well, lower in the log. For this reason:
- always try to look at all errors messages until the end of the log file, to see if you find one message that might put you on track for finding the problem
- if you need help understanding the messages, always join the full log file. The first line(s) of the error message are often no enough to pin down a problem.

**Comment by nnuk** [comment]
Thankyou very much for your reply. Can you kindly guide me step by step how can I correct this?

**Comment by nnuk** [comment]
Thanks @tduberne  now its working as i deleted the output directory and started MATSim so it created a new output file which was working fine in the visualizer (VIA).

Now i wanted to know that i am working on a very small area (OSM) in which i have done editions like made nodes as bus stops and streets but it is a small area. I imported that area in JOSM and wanted to convert that into a MATSim network. Actually can you kindly guide me step by step how can i create the necessary files (network file, Vehicles file, Events file, etc) for MATSim for my area. 

This is my first time on this type of project so my questions are at basic level.

Thanks.

**Comment by golanbendor** [comment]
You have three options to solve this issue:
1. In your scenario runner class (assuming you have an "Config" object) you can add one of these lines: 	
`config.controler().setOverwriteFileSetting(OverwriteFileSetting.deleteDirectoryIfExists);`
`config.controler().setOverwriteFileSetting(OverwriteFileSetting.overwriteExistingFiles);`

2. Manually delete the output directory.

3. Changing the parameter manually in your "config.xml" file under:
* `      <module name="controler" >`
  * `<!-- Possible values: failIfDirectoryExists, overwriteExistingFiles, deleteDirectoryIfExists -->`
  * `<param name="overwriteFiles" value="failIfDirectoryExists" />`
* `</module>`

**Comment by nnuk** [comment]
Thanks @golanbendor i just deleted the output directory and then everything was smooth.
Can you kindly guide me step by step how can i create the necessary files (network file, Vehicles file, Events file, etc) for MATSim for my area which is a small OSM area which i have edited in JOSM for routing.

**Comment by golanbendor** [comment]
Hi @nnuk . 

- Regarding the network, there is a chapter in the MATSim book about JOSM (here is the [link ](https://www.ubiquitypress.com/site/chapters/10.5334/baw.8/download/1476/)) you can use it as a starting point for converting your network to MATSim's specifications. 

- Creating a real population/vehicles is a more cumbersome process. You can use the following [RunPOnePersonPopulationGenerator](https://github.com/matsim-org/matsim-code-examples/blob/0.10.x/src/main/java/tutorial/population/example08DemandGeneration/RunPOnePersonPopulationGenerator.java) class as a starting point for creating a pseudo-demand and the [RunMobsimWithMultipleModeVehiclesExample](https://github.com/matsim-org/matsim-code-examples/blob/0.10.x/src/main/java/tutorial/mobsim/mobsimPassingVehicleQ/RunMobsimWithMultipleModeVehiclesExample.java) class for creating different vehicle types.

-  Events are created during the simulation processes. Thus there is no need to create them (unless you want to add your own custom events).

**Comment by nnuk** [comment]
Thankyou very much @golanbendor. I will follow all these steps and if there is any problem i will ask later.

**Comment by nnuk** [comment]
Hi,
I had a query that as I am working on a small map and I want that the cars should run on the paths with defined speed and should return their GPS coordinates after every 30 seconds so that if i wanted to change the path of the car midway. Is it possible with MATSim or is there other software for it?
Thanks.

**Comment by nnuk** [comment]
Hi,
Can anyone help me with above query it will be highly appreciated.
Thanks.

**Comment by jfbischoff** [comment]
MATsim is able to route agents _within-day_ . This allows you to change the agents' behavior while en-route.
As a starting point, see the relevant book chapters about the topic. There are also some code examples in this repository to start with.

**Comment by jalel-omri** [comment]
@nnuk @mrieser  I am facing the same problem with matsim , in fact I can't start the simulation from the existing example and it always outputs errors .
here is the log file when I run the berlin example 
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/5035985/logfileWarningsErrors.log)
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/5035986/logfile.log)

could help me to fix these errors and run correctly the simulation !
