### ISSUE TITLE
Allowed mode for drt vehicles

### ISSUE THREAD

**Issue by ChristophTraf** [matsim-org/matsim-code-examples#290]
Currently it seems to me that drt vehicles are just moving on links with the allowed mode “car”. Is there a config setting to define allowed modes for drt vehicle? We also would like to define “bus” as such mode.

**Comment by jfbischoff** [comment]
Yes, this can be set in the **DVRPConfigGroup** --> networkMode

**Comment by ChristophTraf** [comment]
Perfect, thnx
