### ISSUE TITLE
writing the location of users every specific time intervals 

### ISSUE THREAD

**Issue by zahraeftekhar** [matsim-org/matsim-code-examples#295]
Hello, 

I am working on data containing 140,000 users in Amsterdam. I need an additional output which I do not know if this is currently possible in MATSim. What I want is that, as output depending on the interval that I specify e.g., 5 minutes, MATSim gives me the location of the users every 5 minutes. Of course, in this case, the user may be on its way to the aimed activity and NOT on the activity, therefore, every 5 minutes I want the location of all the agents (even without any detail on their activity or anything else). Would you please help me?

**Comment by kainagel** [comment]
Try something like
```
	<module name="controler" >
		<param name="snapshotFormat" value="transims" />
                ...
```
in your config.  There is also `writeSnapshotsInterval`, which you should set to "300" (for 5min).  As usual, we strongly recommend to start with small examples (e.g. the `equil` scenario) until you have everything figured out.  The output file should contain csv, with columns "id" (agentId or vehicleId, I don't know), and "northing" and "easting" (the x/y coordinates).

Please let us know how it goes; this hasn't been used for a long time.

**Comment by zahraeftekhar** [comment]
Thank you for your response, Kai. 
As you suggested I tried with the "equil" examplesI tried your solution and it goes as follows:
In the "controler" module:  
`		<param name="snapshotFormat" value="transims" />
                <param name="writeSnapshotsInterval" value="10" /> 
	</module>`
It does not give me any snapshot output, but if I change `"snapshotFormat"` to `"googleearth"`, it gives me the output. Do you have any solution on how to get the output in the CSV format?

**Comment by kainagel** [comment]
It goes into the iterations directories, i.e. `ITERS/it.X`, under the name of `T.veh.gz`.  I just tried for myself, and it shows up.  Any luck there?

Sorry about the confusion between snapshot interval and snapshot period.

**Comment by zahraeftekhar** [comment]
Great. Thank you, Kai. You are right. I found the file and it seems to be what I was looking for :)
