### ISSUE TITLE
MATSIM for Commerical use

### ISSUE THREAD

**Issue by mrthalax** [matsim-org/matsim-code-examples#299]
Hello, I couldn't find anywhere else to post this. Is MATSim available for commercial use, or is it for education purposes only?

**Comment by mrieser** [comment]
Hi,
MATSim is currently licensed under the GNU General Public License (GPL) v2, see https://github.com/matsim-org/matsim-libs/blob/master/matsim/COPYING. As long as you follow all conditions in that license, you can use MATSim in a commercial context.

If you prefer a different license than the GPL, please let us know. We're currently investigating alternatives to the GPL, so additional feedback is welcome.
