### ISSUE TITLE
Using MATSim in Eclipse as a beginner

### ISSUE THREAD

**Issue by YannickMomoko** [matsim-org/matsim-code-examples#30]
I am working on a project related to MATSim. I chose a small network of a city to test. I created the basic input file: config, network, and population file.  I can run the simulation through the executable jar file (here it is matsim-0.10.1.jar). Right now, I want to run the simulation in Eclipse through Javascript. I have no coding background. 
Can anyone help me create my first MATSim java project?

**Comment by kainagel** [comment]
Something like this:
1. clone https://github.com/matsim-org/matsim-example-project into your IDE
1. make sure it is installed as a maven project
1. run "MATSimGUI" from inside the IDE.  It should look similar as what you had.
1. run "RunMATSim" from inside the IDE.  This will run matsim without the GUI.

I think that our TU Berlin matsim tutorial describes these steps including screen shots etc. https://matsim.org/docs/tutorials/general .

**Comment by YannickMomoko** [comment]
Hi kainagel, thanks for helping me. I did what you said and ran their examples. Right now, I am trying to find a way to write the code for my own project.

**Comment by YannickMomoko** [comment]
> Something like this:
> 
> 1. clone https://github.com/matsim-org/matsim-example-project into your IDE
> 2. make sure it is installed as a maven project
> 3. run "MATSimGUI" from inside the IDE.  It should look similar as what you had.
> 4. run "RunMATSim" from inside the IDE.  This will run matsim without the GUI.
> 
> I think that our TU Berlin matsim tutorial describes these steps including screen shots etc. https://matsim.org/docs/tutorials/general .

Hi kainagel, thanks for helping me. I did what you said and ran their examples and I'm doing well with this part. Right now, I am trying to find a way to write the code for my own project, not just run other people's project.

**Comment by nnuk** [comment]
Hi @YannickMomoko ,
Can you kindly guide me through which method you created Network and Population file ?
Thanks.

**Comment by YannickMomoko** [comment]
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/2617517/logfile.log)
I created a project in Eclipse and added the libraries to the Referenced Libraries, then I tried to run a class file. It turned out there were some errors (attached in the logfile). Then I put the same class file in a project I cloned from GitHub and ran it, there was no error. Can someone help me with this? Thanks.

**Comment by jfbischoff** [comment]
This looks like something in your setup went wrong (most likely, two different MATSim versions running at the same time). 
The github approach is the recommended and desired approach, anyway.

**Comment by YannickMomoko** [comment]
> This looks like something in your setup went wrong (most likely, two different MATSim versions running at the same time).
> The github approach is the recommended and desired approach, anyway.

Thank you very much for the help. I downgraded the MATSim library to 0.9.0 and it works well now.

**Comment by BarshaLamichhane** [comment]
Hi , @YannickMomoko How did you learn to create your project from scratch in MATSim?  I have downloaded the repositories and run the program but I am not getting any idea. Do you have any video links that you followed with?

**Comment by Janekdererste** [comment]
We use our university classes as tutorials, which you can find [here](https://matsim.org/content/2022-matsim-class-tu-berlin-matsim-version-14x). 

The course contains recorded videos of the seminar sessions. In the very first one we set up the required software together.

**Comment by BarshaLamichhane** [comment]
> We use our university classes as tutorials, which you can find [here](https://matsim.org/content/2022-matsim-class-tu-berlin-matsim-version-14x).
> 
> The course contains recorded videos of the seminar sessions. In the very first one, we set up the required software together.

Hi,

Thank you for your response but when I tried to access the link that you sent me it asked for login credentials. Do you have any idea about how could I get access for that?

**Comment by Janekdererste** [comment]
You have to log in as a guest. The page is in German, so the button says "Als Gast anmelden"
