### ISSUE TITLE
How to use SwissRailRaptor?

### ISSUE THREAD

**Issue by paud0** [matsim-org/matsim-code-examples#301]
Hi,

in another issue it got pointed out that nowadays most simulations use the SwissRailRaptor pt routing module.

So my questions are:
1. What are the differences to the standart pt router?
2. Is there a parameter description?

Thanks in advance
Paul

**Comment by vsp-gleich** [comment]
1. The main difference between the SwissRailRaptor and the default router is that the SwissRailRaptor is much faster and has more features.
2. There is a parameter description at the original repository of the SwissRailRaptor which has not been moved into the matsim-libs, yet: [https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions)

**Comment by paud0** [comment]
Thanks for the quick answer!
