### ISSUE TITLE
PT input files

### ISSUE THREAD

**Issue by jiao1997** [matsim-org/matsim-code-examples#302]
Dear all：
       I am doing a PT simulation. But I only have the shape file of the bus lines and bus stops. How can I convert them into transitvehicle.xml as the input file and match my road network. I am so confused, please help me.

**Comment by polettif** [comment]
Have a look at [pt2matsim](https://github.com/matsim-org/pt2matsim) which creates/converts public transit files for MATSim. However, creating a public transit schedule from shapes without acutal schedule data (provided by a pt agency) might be too difficult.

**Comment by jiao1997** [comment]
> Have a look at [pt2matsim](https://github.com/matsim-org/pt2matsim) which creates/converts public transit files for MATSim. However, creating a public transit schedule from shapes without acutal schedule data (provided by a pt agency) might be too difficult.

Thank you for your reply. I just want to match bus routes to specific links because the transit_scheduel file needs the specific links through which the bus route passes. Do you know how can do that.
Hope to get your early reply.

**Comment by polettif** [comment]
Matching bus routes of an "unmapped schedule" (as yours seems to be) to links is part of the [mapping step](https://github.com/matsim-org/pt2matsim/wiki/Mapping-a-MATSim-schedule-to-a-MATSim-network-(Public-Transit-Mapper)) in pt2matsim.

**Comment by jiao1997** [comment]
> Matching bus routes of an "unmapped schedule" (as yours seems to be) to links is part of the [mapping step](https://github.com/matsim-org/pt2matsim/wiki/Mapping-a-MATSim-schedule-to-a-MATSim-network-(Public-Transit-Mapper)) in pt2matsim.

   Thanks a lot. I have tried PublicTransitMapper in pt2matsim. But it seems that I didn't get the results I want. After mapping I got the transit_schduel, part of whom is shown as the following picture:
![image](https://user-images.githubusercontent.com/35290093/76061578-cca4d180-5fbe-11ea-9e35-725b480c5983.png)
    It directly created "artificial link" between two bus stops and didn't recognize the links between the two stops. I also has put the network into the VIA:
![image](https://user-images.githubusercontent.com/35290093/76061939-961b8680-5fbf-11ea-95aa-382568d8aae7.png)
    The yellow links are the origin refering links of the bus stations and the red ones are "artificial links". Could you please give me some advice.(Mt config file is attached with the message)
     Hope to get your early reply!

[config（1）.txt](https://github.com/matsim-org/matsim-code-examples/files/4297076/config.1.txt)
                                                                                                                            Yours sincerely,
                                                                                                                             Wang

**Comment by polettif** [comment]
It looks like you use transport mode "pt" in your schedule but your transportModeAssignment in your config doesn't use that:
```xml
<parameterset type="transportModeAssignment" >
	<param name="networkModes" value="car,bus" />
	<param name="scheduleMode" value="bus" />
</parameterset>`
```
I'd suggest changing the transport mode in your schedule to the actual mode used (i.e. "bus"). Another approach is changing transportModeAssignment in your config to include the scheduleMode pt.

Please use [pt2matsim's issue page](https://github.com/matsim-org/pt2matsim/issues) if you have further questions.
