### ISSUE TITLE
How to change config parameters by code?

### ISSUE THREAD

**Issue by applibres** [matsim-org/matsim-code-examples#304]
Dear MATSim friends:

I need to change some config file parameters from some modules. In previous versions, the way to change any parameter was using the function "config.setParam(moduleName, paramName, value);" but it is deprecated and it do not work in current matsim versions (>0.10.0). 
Specifically, I would like to change by code the "chargersFile" parameter located into ev module.
Which is the way to modify any parameter from config file?

**Comment by kainagel** [comment]
Normally something like
```
XyzConfigGroup xyzConfig = ConfigUtils.addOrGetModule( config, XyzConfigGroup.class );
xyzConfig.setAbc(...);
```
As a bonus you get type safety and IDE support.

**Comment by applibres** [comment]
Dear @kainagel:
Thanks for your help.
