### ISSUE TITLE
Which java version and maven ?

### ISSUE THREAD

**Issue by fr75** [matsim-org/matsim-code-examples#31]
Dear all,

I have clone the project and then tried to build it in terminal : 
mvn verify

But I have errors : java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

I have also tried this tutorial : https://www.matsim.org/docs/devguide/eclipse/
Many error building on Eclipse or directrly Maven (For example :  src/main/java/org/matsim/jaxb/lanedefinitions20/XMLCoordinateType.java:[13,32] error: package javax.xml.bind.annotation does not exist)

I am using 
- Java SE 11 (LTS) (jdk-11_linux-x64_bin.tar.gz)
- Maven :  apache-maven-3.3.9

Which versions are known to work ?

Thank you

**Comment by kainagel** [comment]
jaxb is no longer part of the java distribution.  I think it was removed between 8 and 9.  So compiling with java8 should work.  I would recommend trying this first to check if you have no additional errors.  Once that is verified, and you insist on a java larger than 8: The commands to load the missing packages should already be in pom.xml, but commented out.  Pls let us know how it goes.

**Comment by fr75** [comment]
Thank you,

My problem was the java version

I have installed Java 8 (jdk-8u191-linux-x64.tar.gz)
- Build of Matsim-example-project : 
  git clone https://github.com/matsim-org/matsim-example-project
  mvn verify
  build succes in 23 s. (Final Memory: 22M/990M)

- Build of full project :
  git clone https://github.com/matsim-org/matsim.git
  git status (to verify  the branch origin/master)
  mvn package -DskipTests
  BUILD SUCCESS in 14 minutes
  Final Memory: 486M/3215M
  I have not modified pom.xml and  so dependencies to jaxb are let commented in it. If we uncomment them, it does not compile. But I understand reading the comments in the file that we should do it.
