### ISSUE TITLE
Simulation stuck with adding vehicles

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/matsim-code-examples#312]
Hi everyone, 

I was running a simulation today that got stuck in the first iteration:

> 
> 2020-03-16 16:07:20,338  INFO QSimProvider:102 Added MobsimEngine class org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl
> 2020-03-16 16:07:20,339  INFO QSimProvider:108 Added Activityhandler class org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl
> 2020-03-16 16:07:20,339  INFO QSimProvider:114 Added DepartureHandler class org.matsim.core.mobsim.qsim.qnetsimengine.VehicularDepartureHandler
> 2020-03-16 16:07:20,339  INFO QSimProvider:102 Added MobsimEngine class org.matsim.core.mobsim.qsim.qnetsimengine.QNetsimEngine
> 2020-03-16 16:07:20,339  INFO QSimProvider:102 Added MobsimEngine class org.matsim.core.mobsim.qsim.DefaultTeleportationEngine
> 2020-03-16 16:07:20,339  INFO QSimProvider:114 Added DepartureHandler class org.matsim.core.mobsim.qsim.DefaultTeleportationEngine
> 2020-03-16 16:07:20,339  INFO QSimProvider:120 Added AgentSource class org.matsim.core.mobsim.qsim.agents.PopulationAgentSource
> 2020-03-16 16:07:20,339  INFO MobsimListenerManager:49 calling addQueueSimulationListener
> 2020-03-16 16:07:20,339  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimBeforeSimStepListener
> 2020-03-16 16:07:20,339  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimListener
> 2020-03-16 16:07:20,339  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.qsim.messagequeueengine.MessageQueueEngine
> 2020-03-16 16:07:20,340  INFO QSimProvider:126 Added MobsimListener class org.matsim.core.mobsim.qsim.messagequeueengine.MessageQueueEngine
> 2020-03-16 16:07:26,091  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,095  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,098  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,101  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,104  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,107  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,110  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,113  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,116  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,119  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,122  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,125  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,128  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,131  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,134  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,137  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,140  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,143  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,146  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,149  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,152  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,155  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,158  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,161  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,164  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,167  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,170  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,174  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,177  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,180  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,183  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,186  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,189  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,192  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,195  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,198  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,201  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 2020-03-16 16:07:26,204  INFO Counter:69 [VehiclesImpl] added vehicle # 1
> 
> 

this keeps going on infinitely.

Any clue why that could be?
Log file is attached
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/4339621/logfile.log)

I'm usng MATSim 12-SNAPSHOT from the 23 Jan (I believe):
r7a5299c88ccd63660b9b3181c120a2e7dbd7629f
2020-01-23 07:38:08

thanks
Nico

**Comment by kt86** [comment]
Hi Nico,

i think this came in with https://github.com/matsim-org/matsim-libs/pull/794/ . 
We are adding a new vehicle into the new introduced `allVehicles` container, every time `addParkedVehicle(...(` in the QSim is called.

From there it goes via `VehiclesImpl` to the `Counter`.

Since this is called one time for each vehicle added, it generates this endless looking logfile. :(

Maybe there is a good way to reduce this.
@kainagel : Maybe introducing a new "allVehicles" field in QSim.java, collecting the data there and deliverer it at the and (or from time to time)?

Best,
Kai

**Comment by kainagel** [comment]
Aber warum behauptet der Container, dass immer nur genau ein FZ drin ist?

**Comment by kt86** [comment]
Er behauptet meines Verständnisses nach, dass er immer nur eins **rein tut** und nicht, dass dort nur eins drin ist.

Er packt immer genau das eine rein, welches er gerade hinzufügt und deswegen kummuliert es leider nicht. 

So _vermute_ ich das jedenfalls. Weil eigentlich sollte er ja standardmäßig beim Counter wie wir in aufrufen mit dem Multiplier "2" ran gehen. Muss ich mir aber im Detail nochmal ansehen.

**Comment by kainagel** [comment]
Kann schon etwas mit `allVehicles` zu tun haben.  Aber irgendwie muss es dann so sein, dass der container immer wieder neu erzeugt wird, und dann wird ein Auto hineingetan.  

@nkuehnel , könntest Du das vielleicht mal in den debugger nehmen, und schauen, von wo aus das aufgerufen wird?  In intellij könnte man den debugger auf Zeile 69 von `Counter` setzen, und dann eine Bedingung formulieren, wann der dort anhalten soll.  Dann mal versuchen, den stacktrace zu verstehen, oder ihn hierhin kopieren, und hoffen, dass jemand reinschaut.

**Comment by nkuehnel** [comment]
Vielen Dank für die Kommentare, habe die Antworten leider erst spät gesehen. Das Problem taucht mittlerweile nicht mehr auf, ich glaube hatte eine neue MATSim core Version mit einer älteren DRT Version benutzt. Nachdem beides konsistent ist funktioniert es. Falles es nochmal auftreten sollte probiere ich nochmal den Debugger aus!
