### ISSUE TITLE
Incorporating distance based fare for multiple drt operators

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#321]
Hello,
(Hope this mail finds everyone in good health)
  I am working on a scenario with 2 drt operators (one private and one shared). I want to incoprporate distance based fares for both the operators. I tried to implement this in the 
<parameterset type="modeParams" > with <param name="monetaryDistanceRate". However this does not seem to work. 
Is there another way I could implement the fares in the config file
[config.txt](https://github.com/matsim-org/matsim-code-examples/files/4476509/config.txt)
? 
I am using the drt module and have attached my config file.

**Comment by g-bd** [comment]
Hi,

Just add the DrtFareConfigGroup and use setDistanceFare_m()

Also, see the "drtfares" module [**_here_**](https://github.com/matsim-org/matsim-maas/blob/199e11d31567093a433f69ef07ca446e64aef97e/scenarios/cottbus/drtconfig_door2door.xml#L43) and don't forget to set the fare for your two drt modes.

**Comment by golanbendor** [comment]
Hi,

Add 	the DrtFareModule::
		`controler.addOverridingModule(new DrtFareModule());`

You can also add the DrtFareConfigGroup and use setDistanceFare_m()

Also, see the "drtfares" module [**_here_**](https://github.com/matsim-org/matsim-maas/blob/199e11d31567093a433f69ef07ca446e64aef97e/scenarios/cottbus/drtconfig_door2door.xml#L43) for other parameters and don't forget to set the fares for your two drt modes.

I Hope this helps.

**Comment by jfbischoff** [comment]
I would also recommend using the fare groups.
That said, in theory monetaryDistanceRate should also work, if you are using a recent version of MATSim (i.e., the 12.0.-SNAPSHOT).

**Comment by ghost** [comment]
Thank you!
