### ISSUE TITLE
ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.1 died with exception while handling events

### ISSUE THREAD

**Issue by J15t98J** [matsim-org/matsim-code-examples#323]
Struggling to get my pt simulation running - it creates the network and then dies right after requesting the network routing module.

[config.txt](https://github.com/matsim-org/matsim-code-examples/files/4495716/config.txt)
[network files](https://github.com/matsim-org/matsim-code-examples/files/4495717/network.zip)
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/4495718/logfile.log)

Whilst tinkering with various settings in the config file I've seen different errors at the same stage e.g. NPE when requesting car nodes (?!?) near the agent. I've followed [the guides on Atlassian](https://matsim.atlassian.net/wiki/spaces/MATPUB/pages/83099693/Transit+Tutorial) and also copied bits from the examples that come with MATsim - no joy.

**Comment by mrieser** [comment]
The first error message states:
```
2020-04-17 01:34:30,893 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.2 died with exception while handling events.
java.lang.RuntimeException: fromLink missing.
```

In your population file, the first agent has the following plan:
```
    <person id="26.9.12">
        <plan>
            <activity type="pre" link="ACT_LOBBY" end_time="07:48:00"></activity>
            <leg mode="pt"></leg>
            <activity type="post" link="BOS_LOBBY"></activity>
        </plan>
    </person>
```

But your network file does not have a link with id `ACT_LOBBY` nor a link with id `BOS_LOBBY`.
So the link you specified simply cannot be found in the network, and thus it is missing.

Either adapt the population file to use only links you have in the network, or adapt the network to include all links you need.

**Comment by J15t98J** [comment]
Ah, I missed a line in my config generator. Thanks for your help!
