### ISSUE TITLE
problem with Ev charging logic

### ISSUE THREAD

**Issue by prvnpandey** [matsim-org/matsim-code-examples#324]
I am simulating the scenario using the ev module and its working fine until I am providing battery capacity and initial soc same. as soon as initial soc is different from battery capacity respecting the configuration logic ( initial soc is not greater than battery size). No vehicle is going to perform charging activity.  I have gone through the library but I did not find any evidence why it happening so, can you tell me specifically is there something I am doing wrong because in the first case its working fine and in second its not. Is code is written and programmed like this?.

@michalmac @jfbischoff

**Comment by michalmac** [comment]
As already answered here: https://github.com/matsim-org/matsim-code-examples/issues/293, this is not possible yet. We have recharging implemented for simulation of taxis (incl. shared taxis).

**Comment by jfbischoff** [comment]
see also #328

**Comment by Arsham77** [comment]
Hello @michalmac, @prvnpandey, @tschlenther 

Has any development been made on EVs charging behavior logic for urban scenarios since last year?
