### ISSUE TITLE
Learning MATSim

### ISSUE THREAD

**Issue by TaniyaSultana** [matsim-org/matsim-code-examples#326]
I would highly appreciate if anyone could tell me how to learn MATSim?
Do I need to learn any programming language beforehand?

**Comment by Janekdererste** [comment]
https://matsim.org/docs/ is a good starting point. This page also links our userguide which is a good resource for getting started.

You don't need to learn a programming language though it is necessary to write code fragments in Java if you have advanced use-cases.

**Comment by TaniyaSultana** [comment]
I went through the user guide, but I could not figure out how to use it. I have to model and simulate plans of almost 500 people for my thesis. I do not understand how can I modify/incorporate the excel files into MATSim Plan.

**Comment by Janekdererste** [comment]
The format of all input files is xml. Therefore you need to generate xml-files. The most flexible way is to use a programming language for this. Python for example is very well suited for parsing CSV-files. (You can export your excel data into csv from excel) But any other way is also fine, as long as your output matches the file format, e.g. the population file format.

If you would like to rely on existing infrastructure you would have to write your code in Java. An example can be found here:

https://github.com/matsim-org/matsim-code-examples/blob/11.x/src/main/java/org/matsim/codeexamples/population/demandGeneration/RunPPopulationGenerator.java
