### ISSUE TITLE
Small mistake in MATSim Book, Chapter 50

### ISSUE THREAD

**Issue by vasilis-mourtakos** [matsim-org/matsim-code-examples#329]
Hoping I'm not myself mistaken, in 50.1 in the MATSim Book, I believe there is a mistake:
>The maximum density equals one over the length of a vehicle ( effectivecellsize attribute of the links element) for a single-lane link and needs to be multiplied with the number of lanes ( permlanes attribute of the link element), otherwise.

It should probably say that the maximum density equals **the link's length over the length of a vehicle**...

**Comment by madspDTU** [comment]
Hi Vasileois,

The text in the book is correct. What your formula would calculate is the maximum number of vehicles on the link, but this is a different number than the maximum density. If you divide your formula by the link length, the maximum density is achieved. If doing so the link lengths cancel out, resulting in the formula stated in the book:

[maximum density] = [maximum number of vehicles on link] / [link length]
[maximum density] = ( [number of lanes of link] * [length of link]  / [length of a vehicle]  ) / [link length]
[maximum density] =  [number of lanes of link] / [length of a vehicle]


Sincerely
Mads Paulsen
Technical University of Denmark

**Comment by vasilis-mourtakos** [comment]
Dear Mr. Paulsen, 
Yes, I got confused with the calculation of the road capacity. Also I'm used to the expression of density being vehicles/km so that's why 1/vehicles length seemed weird to me. So 1000m of road length/7.5m of vehicle length gives about 134 max vehicles per km. 
Thank you for your time.

With respect, 
Vasileios Mourtakos
