### ISSUE TITLE
Issues with calibration.

### ISSUE THREAD

**Issue by LorenaBR** [matsim-org/matsim-code-examples#33]
Dear all,

When i runned my first scenário (Without calibrate with Cadyts),I was getting results as if there were  almost no one cars passing by (Atached my countscompare). I was using a population of 5%, storagecapacityfactor of 0.2%, flowcapaityfactor of 0.3% and CountScaleFactor of 20.  (I visualized the simulation with OTFVIS and there was vehicles passing, including some traffic jams)
After I runned with cadyts extension, my countscompare still the same, and the others outputs doesn't seems to change much (Or maybe i was not able to interpret the results very wel, if you have some userguide to help-me it would be usefull). 

Follow attached my countscompares ,  my calibration stats and my config, maybe someine could give-me some help.

Thanks
[calibration-stats.txt](https://github.com/matsim-org/matsim-code-examples/files/2573230/calibration-stats.txt)
[config_defaultDFv2.txt](https://github.com/matsim-org/matsim-code-examples/files/2573238/config_defaultDFv2.txt)

[15.countscompare.txt](https://github.com/matsim-org/matsim-code-examples/files/2573229/15.countscompare.txt)

**Comment by kainagel** [comment]
Dear Lorena, 

I can't see an _obvious_ problem with your setup (maybe someone else can). 

What is fairly obvious is that you have indeed by far not enough traffic.  On the links where you have counts they are around 3600 veh/hr; at 5% you should have around 180/hr, and not the 0 to 6 you are getting (before multiplying with 20).

I would for the time being forget about counts (and even iterations; set lastIteration=0) and try to find out where that missing traffic got lost.  Things to check:
* How many persons do you have in your input plans?  Look at your logfile towards the beginning; it will give you the number of persons that were read.
* How many persons have car plans etc.?  Assuming that you are programming Java, something like
https://github.com/matsim-org/matsim-code-examples/blob/ddfdd9fa9d9a1980d84394a102a5fa3495f40738/src/main/java/org/matsim/codeexamples/population/analyzePlans/AnalyzePlans.java#L29-L46
You should be able to verify approximate numbers; for example, if you have a city of 1 mio inhabitants and a car mode share of approx. 50%, then at your 5% you should have approx 25'000 car users.  Or if you are modelling commuter traffic only, then maybe you have 500k employees and maybe a car mode share of approx. 60% between those, resulting in 500k * 60% * 5% = 15k car users (and 30k car trips).  
* Etc.  

If you cannot get it plausible at this level, then the simulation will also not be plausible further downstream.

It is also our experience that most of such problems _are_ at this level.

Please keep us posted ...

PS: Note that the flow/storage factors (in your config file) are 0.2 und 0.3, without the "%".  Corresponding to 5% they should rather be 0.05, but that should (at this point) not be the problem you are having.

**Comment by LorenaBR** [comment]
Dear,
Thank you so much for your reply.
For your information,  I have around 120.000 agents in my simulation (5%), all the agents are being simulated and I have no inconsistency in my network.
As you recommended, I did only 1 iteration, and  with simple plans (origin - destination) only to test, and the result continued the same in the countscompare file.

I visualized in the OTFVIS and VIA and what happens is that, at a given moment (peak hours like 06am), all the agents are stopped and remain this way suntil the end of the day.  The network is very loaded and the agents stop to transit, I believe that this is why the count is so low.
I 
So I’m saharing with you (and with anyone who feel confortable to help-me), a folder with the following files:
1- Config
2- Network
3-Plans
4- Events (after 20 iterations);
5 .MVI for visualization in the OFTVIS

PS: I did what you’ve recomended about the flow/storage factors, thanks!

Ps2: In the scenário base, i’m only simulating bus and car as main mode... so Walk needs to be teleported?
Do i need to change my network for suporting car and buses? Or transit vehicles use the same network as car? 

Thanks in advance


https://drive.google.com/drive/folders/1qUVTypRheWwolwyBwEZeXrkR2LxnkkH6

**Comment by jiao1997** [comment]
Dear Lorena,
                Have you ever solved your problem. I got a similar question with you. Could you tell me are you using the RunCadyts4CarExample.java to run your own scenario?

**Comment by whizkid-25** [comment]
Dear @LorenaBR ,

I am facing the same problem. Did you solve the problem?

**Comment by LorenaBR** [comment]
Sorry for the delay, but the main problem was the geolocalization of my network and of my agent's plans, they weren't in the same coordenate. Once I fixed this, the calibration was possible.

**Comment by LorenaBR** [comment]
> solved your problem. I got a similar question with you. Could you tell me are you using the RunCadyts4CarExample.java to run your own scenario

No, i didn't use the RunCadyts4CarExample.jav to run my scenario, because after i fixed my coordinates, it was possible to calibrate "manually" my simulation.
