### ISSUE TITLE
matsim

### ISSUE THREAD

**Issue by Ranah2020** [matsim-org/matsim-code-examples#334]
i face this error when i try to make network file and plan file and config file to run it on matsim for my new project on matsim. any help here, please!
error 1:
Existing node: [id=1][coord=[x=0.0][y=0.0]] [type=null][nof_inlinks=2][nof_outlinks=2]
Node to be added: [id=1][coord=[x=0.0][y=0.0]] [type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.

error 2:
Error in custom provider, java.lang.NullPointerException
  while locating org.matsim.core.trafficmonitoring.ObservedLinkTravelTimes
  while locating org.matsim.core.router.util.TravelTime annotated with @com.google.inject.name.Named(value=car)
  while locating org.matsim.core.router.util.TravelTime annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=70, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.controler.Injector$3.configure(Injector.java:123) (via modules: com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.Injector$3 -> com.google.inject.multibindings.MapBinder$RealMapBinder)
  while locating java.util.Map<java.lang.String, org.matsim.core.router.util.TravelTime>
    for field at org.matsim.core.router.NetworkRoutingProvider.travelTimes(NetworkRoutingProvider.java:21)
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$Comb

**Comment by yomna20** [comment]
> i face this error when i try to make network file and plan file and config file to run it on matsim for my new project on matsim. any help here, please!
> error 1:
> Existing node: [id=1][coord=[x=0.0][y=0.0]] [type=null][nof_inlinks=2][nof_outlinks=2]
> Node to be added: [id=1][coord=[x=0.0][y=0.0]] [type=null][nof_inlinks=0][nof_outlinks=0].
> Node is not added to the network.
> 
> error 2:
> Error in custom provider, java.lang.NullPointerException
> while locating org.matsim.core.trafficmonitoring.ObservedLinkTravelTimes
> while locating org.matsim.core.router.util.TravelTime annotated with @com.google.inject.name.Named(value=car)
> while locating org.matsim.core.router.util.TravelTime annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=70, type=MAPBINDER, keyType=java.lang.String)
> at org.matsim.core.controler.Injector$3.configure(Injector.java:123) (via modules: com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.Injector$3 -> com.google.inject.multibindings.MapBinder$RealMapBinder)
> while locating java.util.Map<java.lang.String, org.matsim.core.router.util.TravelTime>
> for field at org.matsim.core.router.NetworkRoutingProvider.travelTimes(NetworkRoutingProvider.java:21)
> at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$Comb

I've the same issue raneen

**Comment by Ranah2020** [comment]
i know, it is a big a problem. thank you for you interest.yarab 7d yrod 3alena

**Comment by jalal1** [comment]
Please attach the config.xml, network.xml, and the logfile.log. I think that something wrong with the network.xml

**Comment by Ranah2020** [comment]
thanks,here are the config file,network file, plans file.
also i donot know how to choose the appropriate coordinate system 
[routing_matsim.zip](https://github.com/matsim-org/matsim-code-examples/files/4631538/routing_matsim.zip)

**Comment by jalal1** [comment]
You have some problems in the XML files. I would suggest looking to a simple example from MATSim GitHub repo, then change it. 

Network.xml 
line 20 : > is missing

plans11.xml
line 2: missing this line: `<!DOCTYPE plans SYSTEM "http://www.matsim.org/files/dtd/plans_v4.dtd">`


config.xml:
line 14: module facilities were added, but there is no file "facilities.xml"

Please compare these inputs with a working example, before you try, or nothing will work.

**Comment by Ranah2020** [comment]
Thanks so much,I tried them actually it worked.
