### ISSUE TITLE
MATSIM ERROR

### ISSUE THREAD

**Issue by yomna20** [matsim-org/matsim-code-examples#335]
I am trying to build a toy network. With a config, a population, and a network file.

When I run the config file I get this error. Obviously the node id has already been assigned.

I was wondering if there was a way of solving this issue without having to change my node id's to assigned numbers? 

Error in custom provider, java.lang.IllegalArgumentException: There exists already a node with id = 1.
Existing node: [id=1][coord=[x=0.0][y=0.0]][type=null][nof_inlinks=1][nof_outlinks=2]
Node to be added: [id=1][coord=[x=0.0][y=0.0]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.

**Comment by Ranah2020** [comment]
hello yomna, how are you?
i have the same problem, and i can not solve it yet!<3

**Comment by yomna20** [comment]
> hello yomna, how are you?
> i have the same problem, and i can not solve it yet!<3

you are so lovely and funny

**Comment by Ranah2020** [comment]
thanks, that is so kind!

**Comment by whizkid-25** [comment]
Hi, I faced the same error yesterday and I solved it. However, I don't know if this is going to help. For my case I was using A TransitSchedule.xml and transitVehicles.xml file. One of my PT was not scheduled properly in it's route profile. That's why this error was showing. Please, check the network file especially the link and node assignment.

**Comment by Ranah2020** [comment]
Hi,
Thanks, i will share my network file with you.
[network2.zip](https://github.com/matsim-org/matsim-code-examples/files/4626448/network2.zip)

**Comment by whizkid-25** [comment]
Apparently, you have used spaces inside you quotation commas. It shouldn't be like that. Also, make sure you are using the right coordinate systems for your network.

**Comment by yomna20** [comment]
hi, thank you so much.
here's the whole files can you please help me?
[routing_matsim.zip](https://github.com/matsim-org/matsim-code-examples/files/4626582/routing_matsim.zip)

also, I don't know how to choose the appropriate coordinate system 
WGS84/EPSG/ESRI 
those are 3 coordinate systems that i've tried to use them.

**Comment by yomna20** [comment]
[routing_example.zip](https://github.com/matsim-org/matsim-code-examples/files/4637806/routing_example.zip)
here's the file that worked properly after solving the errors for whom who is interested.
