### ISSUE TITLE
Parallel MATSim

### ISSUE THREAD

**Issue by jiao1997** [matsim-org/matsim-code-examples#338]
Dear all:
        I am using parallel MATSim to run my scenario. But the simulation stopped and some error occurred which shown below:
![image](https://user-images.githubusercontent.com/35290093/82136779-a5cb0d00-9843-11ea-8a36-ff7299f1ccdd.png)
        I have increased the JAVA heap memory, but it didn't help. Anyone familiar with parallel MATSim could please help me. I will appreciate it.

**Comment by jiao1997** [comment]
Besides，the log file is attached
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/4639819/logfileWarningsErrors.log)

**Comment by jalal1** [comment]
What was the amount of memory you specified when running MATSim, and what is your computer's memory size?

**Comment by jiao1997** [comment]
> What was the amount of memory you specified when running MATSim, and what is your computer's memory size?

Hi I set it to 10g and my computer's memory is totally 16g

**Comment by jalal1** [comment]
I still can't tell from the details you provided. If you add the config.xml, it could help.

**Comment by jiao1997** [comment]
> I still can't tell from the details you provided. If you add the config.xml, it could help.

Here is my config file.
[config.txt](https://github.com/matsim-org/matsim-code-examples/files/4641942/config.txt)
