### ISSUE TITLE
Will you provide Python APIs in the future?

### ISSUE THREAD

**Issue by GoingMyWay** [matsim-org/matsim-code-examples#34]
Hi, the library is awesome, will you provide Python APIs so that it can be used with some popular machine learning libraries, for example, TensorFlow and Pytorch?

**Comment by kainagel** [comment]
Thanks for the accolades.  Re python API: We have discussed this multiple times, but someone would need to write it.  Please let us know if you want to undertake that; we would happily give you a corresponding project within matsim-org and help if you get stuck somewhere.  All the best ...

**Comment by GoingMyWay** [comment]
@kainagel  Wow, I wrote Python extension for C++ with [Boost.Python](https://www.boost.org/doc/libs/1_68_0/libs/python/doc/html/index.html) before and it indeed gained more than 10 times speedup for Python codes. I don't know what skills your teams need to write Python APIs for Java codes.

**Comment by tduberne** [comment]
I think what Kai mentioned was not a lack of skills, but rather interest/capacity: we ourselves do not need the feature, and do not have capacity to develop it for others, but would be very happy to provide feedback if someone did start this independently.

That being said, I did consider using [JPype](https://jpype.readthedocs.io/en/latest/) myself in teaching, to avoid overwhelming students with yet another language (we use Python for data preparation and analysis). I did not have the time to experiment with it for this term, but as far as I understand, it should allow you to use any class from your Java classpath from Python (almost) as if they were Python classes, allowing you to prepare data, start a simulation, and analyze the results with one single Python script, with all MATSim data structures at your disposal. Maybe that is enough for your usecase?

In any case, if you experiment with anything, I would be very happy to hear back from you!

**Comment by GoingMyWay** [comment]
@tduberne  That's good, thank you for your suggestion. MATSim is a good simulator for traffic flow. And I am considering using it in my research. I  will use Python to write my algorithm models. And I will do some research on libraries(including JPype) that can successfully and easily connect Python and Java. Thank you.

**Comment by tduberne** [comment]
Hi,

I just took the time to document a bit my minimal experimentation (create a simple scenario with 10 empty plans and run it) and put it on GitHub: https://github.com/tduberne/matsim-python-experiments/blob/master/simple-run.ipynb

I am pretty sure there will be corner cases where it fails, but it seems to work extremely well for what I envision as the main use of Python for MATSim (data preparation or analysis), with virtually no boilerplate.

Closing this issue, as
- the question in the title is clearly answered
- a viable alternative seems to exist

**Comment by GoingMyWay** [comment]
@tduberne  thank you for your example code.
