### ISSUE TITLE
linkstats average travel time

### ISSUE THREAD

**Issue by kaidiwang** [matsim-org/matsim-code-examples#344]
Hi, I hope to use the average travel time on each link but notice that the API said the output is the average travel time of any iterations. Does this mean it is calculated based on randomly selected iterations or it is calculated based on all previous iterations? I would like to use the average travel time of the last iteration. Thank you in advance!

**Comment by Janekdererste** [comment]
Usually, all standard outputs refer to the last iteration.

Which API are you using in particular?
