### ISSUE TITLE
Learning how to use MATSim with Eclipse

### ISSUE THREAD

**Issue by ajha37** [matsim-org/matsim-code-examples#346]
Hello! 
I'm trying to learn how to use MATSim through eclipse by following the online tutorial but seem to be facing as issue. Each time I start a run, an OTFVis window opens that display the ongoing iteration. It seems like I need to manually start each iteration within OTFVis for the run to continue. This does not happen when I run the GUI directly. Could you help me better understand what is happening here and how I can run larger simulations without needing OTFVis. 

Thank You!

**Comment by kainagel** [comment]
Do you have the following line in your code:
```
		controler.addOverridingModule( new OTFVisLiveModule() ) ;
```
?  If so, comment it out and try again.

**Comment by ajha37** [comment]
Thank you for your quick response. This solved the issue!

**Comment by Bentdner11** [comment]
please can you provide what was the online tutorial you were following ?
