### ISSUE TITLE
PT simulation config

### ISSUE THREAD

**Issue by alexanderbachev** [matsim-org/matsim-code-examples#350]
Dear guys,

I am building a model for Sofia, Bulgaria and am trying to add public transit to it. I am struggling at configuring the simulation. To give you some details, I am using:
- 1 percent sample (10000 agents) with randomly generated home and work locations (random nodes); all leg modes are _car_, which might change later during replanning. 
- multimodal network, generated with `pt2matsim`. It's desired modes are _car_, _bus_ and _tram_. Cars and busses are using roads, while trams are using railways. It includes some further modes which sometimes are present together with _bus_ and _tram_ (i.e. _pt_, _rail_, _subway_), however I am not using them.
[network_sof_mm_mapped.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/4723162/network_sof_mm_mapped.xml.zip)
- transitSchedule (mapped), generated with `pt2matsim`. It contains only _bus_ and _tram_ lines and has been converted from a self made GTFS feed. 
[transitSchedule_mapped.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/4723176/transitSchedule_mapped.xml.zip)

My idea is that the pt vehicles should be simulated along cars on the network, so that they'll take congestions into account. I am a bit confused about the config file, precisely when to use the general _pt_ mode and when to explicitly use _bus_ and _tram_. I have also found some conflicting advice about mainModes in the QSim section:
https://matsim.atlassian.net/wiki/spaces/MATPUB/pages/83099693/Transit+Tutorial
This tutorial recommends adding the separate pt modes as mainModes. Conversely, here is recommended not to list pt in qsim mainMode, may be as _ride_...
> The mainModes in the qsim config group need to be car,bike (or maybe car,bike,ride) but should not contain pt. mainMode is a bit of a misnomer; it should be networkMode as in plansCalcRoute. It refers to the modes that are executed directly on the network, as opposed to modes where something picks you up and drops you off. Note that the networkModes in plansCalcRoute can be a superset of the mainModes in qsim, but not the other way round.
https://github.com/matsim-org/matsim-code-examples/issues/224 

I have a few questions for my particular case:
1. Should the `mainMode`s in the qsim section be car and pt (or car, bus, tram)?
2. In the plancalcrute:
2.1. Should the networkModes be car, pt?
2.2. Should I have teleported modes for walk and ride only? 

3. After completing iteration 0 (legs are car only), during the replanning phase the simulation breaks down with:
```
2020-06-03 15:56:03,261  WARN Dijkstra:307 No route was found from node 1107057421 to node 1916926924. Some possible reasons:
2020-06-03 15:56:03,261  WARN Dijkstra:308   * Network is not connected.  Run NetworkCleaner().
2020-06-03 15:56:03,261  WARN Dijkstra:309   * Network for considered mode does not even exist.  Modes need to be entered for each link in network.xml.
2020-06-03 15:56:03,262  WARN Dijkstra:310   * Network for considered mode is not connected to starting or ending point of route.  Setting insertingAccessEgressWalk to true may help.
2020-06-03 15:56:03,262  WARN Dijkstra:311 This will now return null, but it may fail later with a null pointer exception.
2020-06-03 15:56:03,264  INFO Counter:70 [PlanRouter] handled plan # 8
2020-06-03 15:56:03,275  INFO Counter:70 [PlanRouter] handled plan # 16
2020-06-03 15:56:03,262 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.1 died with exception. Will stop after all threads finished.
java.lang.RuntimeException: No route found from node 1107057421 to node 1916926924 by mode pt.
```
I am aware there might not be a PT connection between all possible nodes, but I thought such cases will simply use car only. 

I am posting my current config file, which is probably not configured probably. I'll appreciate some help.

```
<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
	<module name="global" >
		<!-- "global" number of threads.  This number is used, e.g., for replanning, but NOT in the mobsim.  This can typically be set to as many cores as you have available, or possibly even slightly more. -->
		<param name="numberOfThreads" value="8" />
		<param name="coordinateSystem" value="EPSG:32634" />
	</module>
	<module name="parallelEventHandling" >
		<!-- Number of threads for parallel events handler. _null_ means the framework decides by itself. 0 is currently not possible. -->
		<param name="numberOfThreads" value="1" />
	</module>

	<module name="controler">
		<!-- the output path is relative to your execution path. If you start the simulation using eclipse, the output will be in your project folder. You may also specify an absolute path. -->
		<param name="outputDirectory" value="scenarios/sofia/output/population_10k_pt/run03" />
		<param name="firstIteration" value="0" />
		<param name="lastIteration" value="10" />
		<param name="eventsFileFormat" value="xml" />
		<param name="mobsim" value="qsim" />
	</module>

	<module name="plans" >
		<!-- All input paths are relative to your config file. -->
		<param name="inputPlansFile" value="population_rdm_10k.xml" />
		<param name="removingUnnecessaryPlanAttributes" value="true" />
	</module>

	<module name="network" >
		<param name="inputNetworkFile" value="pt2matsim/v5_par_tweaks/network_sof_mm_mapped.xml" />
	</module>

	<module name="transit">
		<param name="transitScheduleFile" value="pt2matsim/v5_par_tweaks/transitSchedule_mapped.xml" />
		<param name="vehiclesFile" value="pt2matsim/v5_par_tweaks/transitVehicles.xml" />
		<param name="useTransit" value="true" />
		<param name="transitModes" value="bus, tram" />
	</module>

	<module name="qsim">
		<param name="startTime" value="00:00:00"/>
		<param name="endTime" value="30:00:00"/>
		<param name="flowCapacityFactor" value="0.01"/>
		<param name="storageCapacityFactor" value="0.01"/>
		<param name="numberOfThreads" value="5" />
		<param name="mainMode" value="car, pt" />
	</module>

	<module name="transitRouter" >
		<param name="extensionRadius" value="500.0" />
	</module>

	<module name="planscalcroute" >
		<!-- All the modes for which the router is supposed to generate network routes (like car) -->
		<param name="networkModes" value="car, pt" />
<!--		<parameterset type="teleportedModeParameters" >-->
<!--			<param name="beelineDistanceFactor" value="1.3" />-->
<!--			<param name="mode" value="bike" />-->
<!--			&lt;!&ndash; Free-speed factor for a teleported mode. Travel time = teleportedModeFreespeedFactor * <freespeed car travel time>. Insert a line like this for every such mode. Please do not set teleportedModeFreespeedFactor as well as teleportedModeSpeed for the same mode, but if you do, +teleportedModeFreespeedFactor wins over teleportedModeSpeed. &ndash;&gt;-->
<!--			<param name="teleportedModeFreespeedFactor" value="null" />-->
<!--			&lt;!&ndash; Speed for a teleported mode. Travel time = (<beeline distance> * beelineDistanceFactor) / teleportedModeSpeed. Insert a line like this for every such mode. &ndash;&gt;-->
<!--			<param name="teleportedModeSpeed" value="4.166666666666667" />-->
<!--		</parameterset>-->
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="walk" />
			<param name="teleportedModeFreespeedFactor" value="null" />
			<param name="teleportedModeSpeed" value="0.8333333333333333" />
		</parameterset>
		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="ride" />
			<param name="teleportedModeFreespeedFactor" value="1.0" />
			<param name="teleportedModeSpeed" value="null" />
		</parameterset>
	</module>

	<module name="planCalcScore">

		<parameterset type="scoringParameters" >
			<param name="earlyDeparture" value="-12.0" />
			<param name="lateArrival" value="-24.0" />
			<param name="marginalUtilityOfMoney" value="1.0" />
			<param name="performing" value="6.0" />
			<param name="subpopulation" value="null" />
			<param name="utilityOfLineSwitch" value="-1.0" />
			<param name="waiting" value="-0.0" />
			<param name="waitingPt" value="-0.5" />

			<parameterset type="activityParams" >
				<param name="activityType" value="home" />
				<param name="typicalDuration" value="08:00:00" />
			</parameterset>

			<parameterset type="activityParams" >
				<param name="activityType" value="work" />
				<param name="typicalDuration" value="08:00:00" />
				<param name="openingTime" value="07:00:00" />
				<param name="latestStartTime" value="11:00:00" />
				<param name="closingTime" value="20:00:00" />
			</parameterset>

			<parameterset type="modeParams" >
				<param name="constant" value="-4.0" />
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<param name="marginalUtilityOfTraveling_util_hr" value="-10" />
				<param name="mode" value="car" />
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				<param name="constant" value="-0.5" />
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<param name="marginalUtilityOfTraveling_util_hr" value="-0.5" />
				<param name="mode" value="pt" />
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				<param name="constant" value="0.0" />
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="walk" />
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
<!--			<parameterset type="modeParams" >-->
<!--				<param name="constant" value="-5.0" />-->
<!--				<param name="marginalUtilityOfDistance_util_m" value="0.0" />-->
<!--				<param name="marginalUtilityOfTraveling_util_hr" value="-8.0" />-->
<!--				<param name="mode" value="bike" />-->
<!--				<param name="monetaryDistanceRate" value="0.0" />-->
<!--			</parameterset>-->
		</parameterset>

	</module>
	<module name="travelTimeCalculator" >
		<!-- (only for backwards compatibility; only used if separateModes==false && + filterModes==true)  Transport modes that will be respected by the travel time collector. 'car' is default which includes also buses from the pt simulation module. -->
		<!--param name="analyzedModes" value="car,pt" /-->
		<param name="analyzedModes" value="car,pt" />
		<param name="separateModes" value="true" />
	</module>

	<module name="strategy">
		<param name="fractionOfIterationsToDisableInnovation" value="0.8" />
		<param name="maxAgentPlanMemorySize" value="5" />
		<parameterset type="strategysettings" >
			<param name="strategyName" value="ChangeExpBeta" />
			<param name="weight" value="0.7" />
		</parameterset>
		<parameterset type="strategysettings" >
			<param name="strategyName" value="TimeAllocationMutator" />
			<param name="weight" value="0.1" />
		</parameterset>
		<parameterset type="strategysettings" >
			<param name="strategyName" value="ReRoute" />
			<param name="weight" value="0.1" />
		</parameterset>
		<parameterset type="strategysettings" >
			<param name="strategyName" value="SubtourModeChoice" />
			<param name="weight" value="0.1" />
		</parameterset>
	</module>

	<module name="TimeAllocationMutator" >
		<param name="mutationAffectsDuration" value="true" />
		<param name="mutationRange" value="1800.0" />
	</module>

	<module name="subtourModeChoice" >
		<param name="chainBasedModes" value="car" />
		<param name="modes" value="car,pt,walk" />
	</module>

</config>
```

PS: I am running the simulation on a macbook pro with a quad core cpu (8 threads) and 8 GB of ram.

**Comment by kainagel** [comment]
Dear Alexander,

have you checked https://matsim.org/docs/userguide/ , in particular Chapter 7?  That is, at least from my side, the most consistent description.  We are currently in the process of updating the document for matsim-12, but most of it should also work for matsim-11.

`networkModes` or `mainModes` refers to modes where the travellers themselves move on the network.  Sometimes called "individual" modes.  So it might be car, walk, bike, ..., but not pt or taxi, since in the latter modes someone else makes the decision about which link to take next.

In your case, I would start with networkModes = mainModes = 'car'.  You could then start with configuring all other modes as teleportation and see if you can make it work. You will have to define teleportation routers for all other modes (including pt) although some may be there by default.

Next, you could switch on transit and see if that works.  From the passenger side (i.e. in the plans file), this will always be `pt`, no matter what vehicle type is taken on the ground.  

What often helps is setting `insertingAccessEgressWalk` to true.  

I can't say anything useful about how the network needs to be labelled for those links that are used by pt (e.g. train) only; this is a bit messy and needs to be cleaned up.

If you can't get it off the ground, could you put everything into a git repo and make it available? That makes it easier to debug.  If you can't make your data public, it would be enough to put in there: network file, transit files, config file, a population file that contains the offending plan(s).

Best wishes

Kai

**Comment by alexanderbachev** [comment]
Dear Kai,

thank you for the extensive reply. I have read chapter 7 of the user guide as well as most chapters of the book. It seems I had gaps in my understanding of the bigger picture. My confusion came from the Transit Tutorial where the individual pt modes are defined in qsim.mainModes. Anyways I have already managed a simulation with transit enabled, although the pt vehicles apparently ignore the transportMode defined in the schedule file.

Best wishes
Alexander

**Comment by kainagel** [comment]
You are rightly confused since it is inconsistent.  The transit stuff pre-dates our sorting out of the multi-modal network, and (unfortunately) never got adapted.   I just re-added this as an open issue https://github.com/matsim-org/matsim-libs/issues/1023 , with pointers to older material related to the same.  Feel free to add your observations there, or upvote it.

**Comment by kainagel** [comment]
Closing the issue since this the remaining problem is not a Q&A problem but a software problem.
