### ISSUE TITLE
Multimodal calibration

### ISSUE THREAD

**Issue by ngagnediop** [matsim-org/matsim-code-examples#351]
Dear MATSim user,
As a beginner, I have already established a multimodal model for a scenario at the regional scale. For the network.xml and schedules I used PT2MATSim and population from household surveys. After a simulation with a successful standard config file, I have a few questions:
1 / What do you advise me to calibrate the model. May i calibrate the network and plans also ?
I see Cadyts but i am not sure if it is the recommanded way and if is it adapted to multimodal network. 
2 / In the manual, it is explained that for the calculation of the score, the last activity is merged with the first in a single activity. For example, if the first activity ends at 7 a.m. and the last activity begins at 11 p.m., it is assumed that it is the same activity, lasting eight hours. So, is it useful to set a start_time for the first activity (home) and a start_time for the last activity (home)? I plan to delete the start_time of the first activity and keep the start_time of the last activity since it comes from the survey.

Thank in advance, hope you can help.
Best Regards,

**Comment by Janekdererste** [comment]
1. Usually, there is no need for cadyts. If you already have complete plans from travel surveys you want to make sure that certain indicators, such as modal-split or distance-distribution of trips are met. If you observe a discrepancy between your simulated and measured indicators you can push agents onto different modes for example by altering the "constant" in "scoringParameters" set of the config. (See exapmple in userguide p.43 [http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf]) 

2. I think you would only provide an end time for your start Activity. Respectively you could provide a start time for the last activity but you may also ommit that.

**Comment by ngagnediop** [comment]
ok thanks for your usefull feedback. i will see it

**Comment by ngagnediop** [comment]
Hello,
Thank you for your comment, I wanted to add after reading work and papers on calibration with modal split. Some propose a logarithmic function which gives Cmode according to the variation of the modal share of a mode, so that Cmode varies with each iteration. What allows to push agents towards a mode. My question is to see if MATSim supports the implementation of this formula.

Reference :
[cmode.pdf](https://github.com/matsim-org/matsim-code-examples/files/4785725/cmode.pdf)
[KickhoeferEtAl2016MatsimSantiago.pdf](https://github.com/matsim-org/matsim-code-examples/files/4785736/KickhoeferEtAl2016MatsimSantiago.pdf)

Best regards.
