### ISSUE TITLE
coordinate transformation

### ISSUE THREAD

**Issue by Alnik89** [matsim-org/matsim-code-examples#359]
I am currently working on my own model region which I have created according to the textbook "https://isis.tu-berlin.de/mod/page/view.php?id=587296".
CoordinateTransformation ct =
TransformationFactory.getCoordinateTransformation(TransformationFactory.WGS84, "EPSG:32632")
Since I am not very well versed in java coding, I have scripted a population generator in matlab which creates a population xml-file according to the required formatting (person, plan, activity, leg, etc.) with individual coordinates and timing.
With overpass-turbo (http://overpass-turbo.eu/) i extracted the building polygon coordinates of the model region which i assign as home coordinates to the agents in my matlab script.
Cause of the coordinates im working with are WSG84 and they have to match with the network file, I now face a problem.
Is there any chance to find out (quick and dirty) about the mathematical method used in the coordinate transformation of my network?
So that i can implement this method in matlab and transfer it to all of my coordinates.
Many thanks for any contribution in advance.
Cheers alexander

**Comment by Janekdererste** [comment]
This would be the java snippet you'd have to program:

```
                var transformation = TransformationFactory.getCoordinateTransformation("EPSG:4326", "EPSG:32632");
		var population = PopulationUtils.readPopulation("population-file.xml.gz")

                population.getPersons().values().parallelStream()
				.flatMap(person -> person.getSelectedPlan().getPlanElements().stream())
				.filter(element -> element instanceof Activity)
				.map(element -> (Activity)element)
				.forEach(activity -> {
					var transformedCoord = transformation.transform(activity.getCoord());
					activity.setCoord(transformedCoord);
				});

                PopulationUtils.writePopulation(population, "output-file.xml.gz);
```

**Comment by Janekdererste** [comment]
Sorry, this was no answer for your question. But I guess, this could be an easy copy paste solution since calculating projections is not super trivial.

**Comment by kainagel** [comment]
It might actually work natively (meaning matsim might be able to read your WGS84 file as is), I never tried.  In principle, matsim has the capability to read input files in arbitrary coordinate systems; you can set this either in the file itself, or in the config file.  The coordinate system in which the simulation runs should also be given in the config, maybe in `global`?  So it should actually be possible to have the network in coordinate system A, the population in coordinate system B, and to run the simulation in coordinate system C.  You then have to figure out in which coordinate system the output files are; I think they are now in C (we switched defaults here some time ago).

There should be a description of this in the user guide.  If not, please let us know and I will try to add it.

_If_ this works, you should still check what this does with the "length" attribute in the network links; they may become scrambled when not coming from a metric coordinate system. (Maybe something we should make configurable.)

Please let us know how it goes.

**Comment by Alnik89** [comment]
Thanks for all the helpful replies.
In the end I went for the solution Janek suggested, with some slight adjustments.
Please find the code below.:

public class CoordinateTransformation {

    public static void main(String[] args) {

        var transformation = TransformationFactory.getCoordinateTransformation("EPSG:4326", "EPSG:32632");
        Config config = ConfigUtils.loadConfig( "scenarios/equil/config.xml" );
        Population pop = PopulationUtils.createPopulation(config);

        PopulationUtils.readPopulation(pop,"direction to population_matlab.xml");

        pop.getPersons().values().parallelStream()
                .flatMap(person -> person.getSelectedPlan().getPlanElements().stream())
                .filter(element -> element instanceof Activity)
                .map(element -> (Activity)element)
                .forEach(activity -> {
                    var transformedCoord = transformation.transform(activity.getCoord());
                    activity.setCoord(transformedCoord);
                });

        PopulationUtils.writePopulation(pop, "direction to population.xml");
    }
}
