### ISSUE TITLE
Linking households with facilities / coords

### ISSUE THREAD

**Issue by idshklein** [matsim-org/matsim-code-examples#364]
Hi all, 
In via, it is possible to load a household layer. I'm trying to add spatial reference to households, whether by specifying explicit coordinates or providing a refid to a facility. However, I can't find any matsim versions that support this functionality, thus I cannot view the household layer in via.
Is there a way of linking households with facilities?

**Comment by mrieser** [comment]
Households in MATSim have indeed no default location, i.e. reference to a coordinate, link or facility.

When adding a households.xml file to Via and creating a Households layer, the agents get access to the household they are assigned to. This is mostly useful if the household has additional attributes, in such a case the agents can access the household's attributes.

For visualising households, the missing coordinate is a problem. To work around this, Via allows to select two attributes of the household as the X and Y value of a coordinate. This implies that the household coordinate must somehow be stored as an attribute, for example like this:

```
<household id="1">
    <members>
        <personId refId="1" />
        <personId refId="2" />
        <personId refId="3" />
    </members>
    <attributes>
        <attribute name="loc" class="org.matsim.api.core.v01.Coord">(1.4142;2.141452)</attribute>
    </attributes>
</household>
```

In this case, an attribute with name "loc" is added to the household which contains a MATSim coordinate. Alternatively, two attributes, e.g. "homeX" and "homeY", could be used to store the corresponding values.
Then, these attributes can be selected in Via to display the household locations:

![Screenshot 2020-06-25 at 12 44 43](https://user-images.githubusercontent.com/1038453/86258853-93bae900-bbbb-11ea-8579-6a0a8fed1477.png)

(The MATSim Coordinate "loc" is automatically converted into single-value attributes "loc.x" and "loc.y").

**Comment by Areza622** [comment]
Dear Mr. @mrieser , may I ask about different use cases of households data in MATsim? (as far as I found out, it has been used for Joint decision implementation but I have found no more information about that!
