### ISSUE TITLE
Taken more than an hour running example scenario

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#367]
Hello, I just cloned MATSim 12.0 into my IDEA yesterday, and I am currently testing it out. However, as image below, it has nearly taken me an hour running the "example config" within the "scenario" folder. When I was using the older 11.0 version, I remembered it would take less than 20 minutes or less. Is there anything wrong I have with the setting? Or it's because I am using the wrong GUI/scenario?

![image](https://user-images.githubusercontent.com/63421908/86246722-bc3ae700-bbab-11ea-8bfa-b465da70c2f3.png)

Update: Hello, I get it worked now. I realised this may be a new feature of MATSim 12.0 that it will run MASim OTFVis for visualization. However, do I need to click the first triangle bottom every time during each iteration? Is there any way it can be done automatically? Thanks very much for your help!
![image](https://user-images.githubusercontent.com/63421908/86268407-704a6b00-bbc8-11ea-82f6-c45c7b7af617.png)

**Comment by jingjunL** [comment]
Hello, I get it worked now. I realised this may be a new feature of MATSim 12.0 that it will run MASim OTFVis for visualization. However, do I need to click the first triangle bottom every time during each iteration? Is there any way it can be done automatically? Thanks very much for your help!
![image](https://user-images.githubusercontent.com/63421908/86268276-38dbbe80-bbc8-11ea-951c-50cd07c51140.png)

**Comment by mrieser** [comment]
If OTFVis is started or not depends on the Class you use to run it.

It looks as if in the example project, OTFVis is now included as an example on how to modify the Controler. In the class `org.matsim.project.RunMatsim`, there are the following lines:

```
// possibly modify controler here

controler.addOverridingModule( new OTFVisLiveModule() ) ;
```

just add `// ` in front of `controller.addOverridingModule(...` to disable that line and run it again. Then it should run without OTFVis.

**Comment by jingjunL** [comment]
> If OTFVis is started or not depends on the Class you use to run it.
> 
> It looks as if in the example project, OTFVis is now included as an example on how to modify the Controler. In the class `org.matsim.project.RunMatsim`, there are the following lines:
> 
> ```
> // possibly modify controler here
> 
> controler.addOverridingModule( new OTFVisLiveModule() ) ;
> ```
> 
> just add `// ` in front of `controller.addOverridingModule(...` to disable that line and run it again. Then it should run without OTFVis.

Hello Marcel, it works magically! Many thanks for your kind reminder :) I will close this issue!
