### ISSUE TITLE
Can you implement road pricing in multimode (car + transit) configuration? 

### ISSUE THREAD

**Issue by whizkid-25** [matsim-org/matsim-code-examples#368]
I am running a transit scenario to analyze mode shift from car to transit. I am trying to implement road pricing in specific links so that I can observe if commuters prefer public transit over car due to high  tolls. I have added the roadpricing module and toll.xml. However, I am getting the following  error: 

java.lang.RuntimeException: Unmaterialized config group: roadpricing
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:11)
	at org.matsim.core.config.Config.checkConsistency(Config.java:227)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
How can I resolve this? 
[Toll.txt](https://github.com/matsim-org/matsim-code-examples/files/4859141/Toll.txt)
[Config.txt](https://github.com/matsim-org/matsim-code-examples/files/4859142/Config.txt)

**Comment by JWJoubert** [comment]
I recommend you look at the examples in the `org.matsim.contrib.roadpricing.run`. There is some basic coding required, if I remember correctly, to _materialize_ the config group. 

To answer your question in the issue title, yes, you can. One way might be to implement a `TollFactor` (which you need to code). The `TollFactor` can currently be sensitive to the specific person (if a person has an _eTag_ or not), the specific vehicle (which might be mode-dependent), the specific link, and the time of day. There you can have a look at the `RunRoadPricingUsingTollFactorExample` class as an example.

**Comment by whizkid-25** [comment]
@JWJoubert 
Thank you for your prompt response. I am fairly new at MATSim and have been using GUI to run it. Is there a road-pricing package (JAR file) and run command which will able me to run road-pricing contrib without coding? I only need to implement toll into a specific link.

**Comment by JWJoubert** [comment]
Nope, @whizkid-25, sorry. As the instructions say: "some assembly required". Road pricing by file _only_ might work, but I have to say I am not so sure.

**Comment by tschlenther** [comment]
Maybe have a look at https://github.com/matsim-vsp/teach-roadpricing-decongestion

You will find some examples in the scenarios folder - look at roadpricingConfig.xml. It points to a toll.xml in which you can specifiy a toll per link per time slot.

To run MATSim from GUI with roadpricing, build yourself a JAR based on that repository. See it's README.md for instructions. But before you run the mvnw command, make sure to change the main class in the pom.xml to SimpleRoadpricingGUI (there is a outcommented line right above the specification of the current default main class in pom.xml - just change the comment markers).

Then you basically have a GUI to run any simple roadpricing scenario :)

It does not really provide any functionality for using custom TollFactors though

**Comment by whizkid-25** [comment]
Hi @tschlenther , 
I have build a JAR based on the repository. However, my config which includes Car+ Public Transit vehicles (i.e it has transit schedule and transit vehicles files) doesn't run. It shows the following error: 
![image](https://user-images.githubusercontent.com/60205511/88021595-c5104000-cafb-11ea-96ac-d11b21ab1bc5.png)

I am finding it difficult at what went wrong the simulation run!

**Comment by tschlenther** [comment]
Hi,

have changed the entry for main class in the pom.xml to SimpleRoadpricingGUI prior to building the jar? (see my last comment)

The problem you're having is that some analysis code is failing, as it is only compatible with the example scenarios contained in the repository. But this piece of analysis code should not be loaded if you run SimpleRoadpricingGUI.

If you do not feel comfortable with building the jar and editing the pom.xml you might also run SimpleRoadpricingGUI or SimpleRoadpricingController directly from your IDE of choice..

Let me know if you still get stuck.

Best regards,

Tilmann

**Comment by whizkid-25** [comment]
Hi @tschlenther, 

Thank you for your guidance. The GUI is working now!
