### ISSUE TITLE
Calibrating MatSim based on counting points

### ISSUE THREAD

**Issue by ChristophTraf** [matsim-org/matsim-code-examples#37]
We would like to calibrate our MatSim simulation based on several counting points which are irregularly distributed in our study area. The counting points related files include the number of vehicles which are passing a corresponding link. The measurements have a temporal resolution of 1 hour.

What is the best way to calibrate the simulation in that way, that the simulated hourly link volumes correspond to the measurements? Should we use the network capacity and speed as calibration parameters? Is there any existing tool to perform such sensitivity tests?

Thank you very much!

**Comment by golanbendor** [comment]
Calibration of Dynamic Traffic Simulations (Cadyts) is the answer to your question (created by Gunnar Flötteröd). Inside the following [link ](https://people.kth.se/~gunnarfl/cadyts.html) you can find some more information/publications about Cadyts.

Here are some more publications related to Cadyts (which are not included in the above URL):

1. Ziemke, D., Nagel, K., & Bhat, C. (2015). Integrating CEMDAP and MATSim to increase the transferability of transport demand models. Transportation Research Record: Journal of the Transportation Research Board, (2493), 117-125.‏

2. Ziemke, D., & Nagel, K. (2017). Development of a fully synthetic and open scenario for agent-based transport simulations–The MATSim Open Berlin Scenario. VSP Working Paper 17-12, TU Berlin, Transport Systems Planning and Transport Telematics.

3. Oliveros, M. M., & Nagel, K. (2016). Automatic calibration of agent-based public transit assignment path choice to count data. Transportation Research Part C: Emerging Technologies, 64, 58-71.‏

**Comment by ChristophTraf** [comment]
Thank you very much!!!
