### ISSUE TITLE
Generating Network with the Osmosis (used code from guidebook but failed)

### ISSUE THREAD

**Issue by CianGraham** [matsim-org/matsim-code-examples#371]
Hello everyone, 

I am currently generating my network for MATSim model. I was referred to the latest 2020 user guide book and used the instruction code there.
![image](https://user-images.githubusercontent.com/67740217/86352370-fbc60980-bc65-11ea-94ce-3c93c727218b.png)

My Osmosis environment is fine because I have tried the sample project on their website and it works. However, when I changed to the command above, the error message like below just keep showing up.

![image](https://user-images.githubusercontent.com/67740217/86356343-5f533580-bc6c-11ea-9d61-5522f73e3f4c.png)

Does anyone know the potential reasons account for this? Many thanks for the help in advance!

**Comment by dhixsingh** [comment]
The command in the user guide is Unix-like so you  should modify it suitably for Windows. 

The main issue seems to be that your command should say `--bounding-box` and `--completeWays` but says something else. 

The `\` is unnecessary too everywhere for your case I think. 

Hope that helps.

**Comment by CianGraham** [comment]
> The command in the user guide is Unix-like so you should modify it suitably for Windows.
> 
> The main issue seems to be that your command should say `--bounding-box` and `--completeWays` but says something else.
> 
> The `\` is unnecessary too everywhere for your case I think.
> 
> Hope that helps.

Hello Dhirendra, Many thanks for your reply!

I tried your approach by adding "--" before "boundingbox" and "completeWays", and removed the `\.` It may solve some problem, now the exception is like below, saying task type completeWays=true doesn't exist. 
![image](https://user-images.githubusercontent.com/67740217/86355896-a55bc980-bc6b-11ea-8d4c-22a0caf45ad4.png)

Any more comments to this? Thanks again for your help!

**Comment by dhixsingh** [comment]
Yes that is just my bad, there is no `--` before `completeWays` In the original command.  

Typically you should pay heed to the error message and debug based on that. You may find the osmosis user manual useful here https://wiki.openstreetmap.org/wiki/Osmosis.

**Comment by CianGraham** [comment]
> Yes that is just my bad, there is no `--` before `completeWays` In the original command.
> 
> Typically you should pay heed to the error message and debug based on that. You may find the osmosis user manual useful here https://wiki.openstreetmap.org/wiki/Osmosis.

It works!!! Thanks very much, Dhirendra.
