### ISSUE TITLE
Setting of flowCapacityFactor & storageCapacityFactor

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#384]
Hello everyone, I came across one question when I was reading the latest MATSim handbook. 

In chapter 4.4.1 about the Qsim, it says the parameters "flow & storage capacity factor" needs to be set accordingly when running a sample scenario (e.g. for 10% sample they need to be 0.1).

I'm wondering when should I use this parameter? Currently, the "plan.xml" I generated has already been a 10% sample of my study area, and I didn't choose "create sample population" in the MATSim GUI. In other words, my "plan.xml" is based on a 10% population, whereas the network is a 100% flow network.

In this situation, do I need to set these flow and storage capacity factor to 0.1? 

Many thanks for your help in advance :)

**Comment by mrieser** [comment]
Yes, if your `plans.xml` depicts only 10% of the population, you should set the flowCapacityFactor to 0.1.

In our experience, it is often helpful to have the storage capacity slightly higher with small samples, e.g. set the storageCapacityFactory to 0.3 for a 10% sample, or to 0.4 or 0.5 with a 25% sample.

**Comment by jingjunL** [comment]
> Yes, if your `plans.xml` depicts only 10% of the population, you should set the flowCapacityFactor to 0.1.
> 
> In our experience, it is often helpful to have the storage capacity slightly higher with small samples, e.g. set the storageCapacityFactory to 0.3 for a 10% sample, or to 0.4 or 0.5 with a 25% sample.

Hi Marcel, thanks for your suggestions. I will take that into consideration :)
