### ISSUE TITLE
Coordinate Transfermation in MATSim

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#386]
Hello everyone,

I am currently on the stage of building my first MATSim model. I encountered a problem with my coordinate system.

Basically, I generated my network followed the guidance of MATSim user handbook. Since my study area is in Belgium, I used the WGS84_UTM31N coordinate system for the proposed network. 

However, I just noticed that the coordinate of my plan data is based on EPSG:3857. Therefore, I'm wondering if there exists any setting in MATSim which could potentially transfer the data into my network coordinates? If not, I'm wondering if anyone is aware of any transformation methods for converting my data? Otherwise, any suggestions related to this is also much appreciated!

Thanks for your reading and help in advance :)

**Comment by kainagel** [comment]
You can set a separate coordinate system for plans either in the plans file itself, or in the config.  Hopefully someone else can help with the syntax.  Or could you please check the user guide (NOT the book)?  If it is not there, it would be an incentive for me to add it.

**Comment by jingjunL** [comment]
> You can set a separate coordinate system for plans either in the plans file itself, or in the config. Hopefully someone else can help with the syntax. Or could you please check the user guide (NOT the book)? If it is not there, it would be an incentive for me to add it.

Hello Kai,

Many thanks for your reply :)

Yes, I am checking the latest 2020 user guide, the text that most relevant to your description should be the image below?
![image](https://user-images.githubusercontent.com/63421908/87028281-b1e9a000-c1de-11ea-90fe-d17cfd5c089f.png)

I initially thought this method was only applicable to the network, but now I know once you have determined a global network, MATSim will generate other coordinate systems into the global one automatically. Now my agents are running on the link on which they should do, many thanks for your help  :)
![image](https://user-images.githubusercontent.com/63421908/87040897-ace21c00-c1f1-11ea-9573-aa3271ca3f8e.png)

**Comment by kainagel** [comment]
Glad it worked.  There is now also a 2nd option, where you can declare the coordinate system directly in the corresponding input file (e.g. the plans file).  I have written it up in the user guide, https://matsim.org/docs/userguide , same section you looked at.  (Note that we can't change the book contents, so newer functionality is in the user guide.)

**Comment by jingjunL** [comment]
> newer functionality is in the user guide

Sure, thanks for your reminder Kai. I have tried declaring the coordinate directly in the input file and it works 

In this way, I found it's handier since there's no need for remembering all your coordinate systems by the time you are making the config file. I will use this one in the future.

Thanks again and have a nice day :)

-Jingjun

**Comment by venetsia** [comment]
Is the WGS84 coordinate system accepted by MATSIM?

**Comment by JWJoubert** [comment]
> Is the WGS84 coordinate system accepted by MATSIM?

Is it _accepted_? Yes, but you should rather use a (consistent) projected coordinate reference system because WGS84 works in decimal degrees and you want MATSim to use metres to calculate distance correctly. See the MATSim book, section 2.2.1

**Comment by kainagel** [comment]
It should be possible to use WGS84 for _input_, e.g. in the network and/or plans file.  The coordinate system in which matsim computes internally, which is set in the config file (I think in the "global" section) should be metric.
