### ISSUE TITLE
 Issues in running two extensions in the same time

### ISSUE THREAD

**Issue by rntlira** [matsim-org/matsim-code-examples#39]
Dear all,

I have no Java background, so I'm sorry for asking something null.
 
I am facing issues in running matsim and its extensions- Cadyts and DRT- at the same time.
First of all, I was using MATSim GUI, but the outputs seemed to be wrong, especially the counting comparison file, since they counted no vehicles. So I tried to use the  cadyts extensions to calibrate, however the counting file didn't t change much, but the scores changed, which was a not bad result.
The problem is that now I need to add another extension with my scenario calibrated by Cadyts, and I don't know how to do that.

Just to certify that I'm not making any mistakes to use the Cadyts Extension, I first added on it as a dependency in my pom.xml.  Subsequently I copied the "cadyscar4example.java" into my project, added on it the path to my config.xml file and runned as java application and I got different results and because of that I think I runned cadyts properly.

I know that to use the DRT I also need to add it as dependency in my Pom.xml, however I don't know how to run the DRT with my scenario already "calibrated" by cadyts in java.

Anyone can help me?

**Comment by michalmac** [comment]
Please have a look at this projects: https://github.com/matsim-org/matsim-maas. It contains examples on how to run DRT and similar (e.g. taxi).

In general, cadyts and drt are two independent extensions, so they should work fine together.

**Comment by LorenaBR** [comment]
Ii'm facing the same issue.. Need to run 2 extensions together, but don't know how. 
I'am using the RunXXXExample as main class, but now i have to use another RunXXXexample together with the first one. Do I need to integrate into my controller, if yes how?? Or, somehow, i can run two main different class at the same time? 
i've tryed to run all the project at once, just adding the dependencie in the POM.XML, and i got this error:  _RuntimeException: Unmaterialized config group: DRT_

Can anyone help-me, please? Thanks in advance!
