### ISSUE TITLE
Communication between facilities

### ISSUE THREAD

**Issue by OrranaLhaynher** [matsim-org/matsim-code-examples#391]
During my research on MATSim, I discovered that there is a module called DVRP and that it is capable of communicating between vehicles and agents (as I understand it), like calling a taxi during the simulation for example. With that, I have a question: is it possible to create a communication module between facilities or if there is already an existing one?

**Comment by michalmac** [comment]
Could you please give some more background information on this. What would be the purpose? How should such a communication work?

**Comment by OrranaLhaynher** [comment]
First, thank you for your answer! I am working on a project whose proposal is to distribute emergency materials between depots, supply depots and demand depots. Demand deposits "request" materials from supply depots and for that I need to create some kind of communication between them. After the materials order "arrives" at the supply depot, a fleet must be calculated to deliver these resources. This is my proposal, and so I have the question of whether it is possible to implement it in MATSim?

Thank you again!

**Comment by JWJoubert** [comment]
@OrranaLhaynher you may want to look into the `freight` contribution with `shipment`s and `service`s. It probably, in the end, depends on how frequently/dynamic the VRP needs solving.

**Comment by michalmac** [comment]
What is the dynamics of this system? Is it real-time, same-day or next-day delivery?

**Comment by OrranaLhaynher** [comment]
Real-time delivery

**Comment by michalmac** [comment]
Then probably you could use the DVRP module and customise it (e.g. implement your own dispatch algorithms...).

A very simple example: https://github.com/matsim-org/matsim-libs/tree/master/contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/examples/onetruck (just one truck)

**Comment by OrranaLhaynher** [comment]
But is it possible to develop communication between deposits at MATSIm, if it doesn't already exist? With information from one deposit arriving at another? And then this deposit communicating with vehicles to deliver?

**Comment by michalmac** [comment]
Such a communication could be implemented with the existing event (=message) passing infrastructure.

**Comment by OrranaLhaynher** [comment]
Thank you! 😊
