### ISSUE TITLE
Visualise Home/Workplaces/Facilities on Map

### ISSUE THREAD

**Issue by CianGraham** [matsim-org/matsim-code-examples#392]
Hi everyone, 

I'm wondering if there's any function in MATSim through which I can visualise the locations of my facilities on the map? My plan/facilities files are all randomly generated, so I cannot really know their specific locations by the time I obtained my plan.xml file. 

Thanks very much for your help in advance!

**Comment by Janekdererste** [comment]
You can use Via (https://www.simunto.com/via/download) which is a commercial software though. It supports this functionality out of the box. 

Appart from this option you have to do things yourself. You could write your facilities into a csv file in the format of e.g. x,y,id. Then you could visualize those data points with some GIS software like QGIS.

**Comment by CianGraham** [comment]
> You can use Via (https://www.simunto.com/via/download) which is a commercial software though. It supports this functionality out of the box.
> 
> Appart from this option you have to do things yourself. You could write your facilities into a csv file in the format of e.g. x,y,id. Then you could visualize those data points with some GIS software like QGIS.

Hi Janek, I downloaded the software with a free licence and it works. Thanks for your answer!
