### ISSUE TITLE
getting a list of car ids which pass a link

### ISSUE THREAD

**Issue by SarahSie** [matsim-org/matsim-code-examples#393]
I want to get a list of cars ids which pass special links.
it would be great if you can help to find the best place in the code that I can add my code and get the list of car ids.

**Comment by JWJoubert** [comment]
Hi @KateHarison, it would probably be easiest to just run your model and process the `events.xml.gz` file afterwards by writing/coding and `EventHandler`.

**Comment by SarahSie** [comment]
Hi @JWJoubert Thank you for your reply. I have checked my ouput_event. but I could not find any 
"link" ids that I am looking for them.
I saw with Via that some agents pass those specific links but in the ouput_event, there were no link ids of them.
How is it possible?

**Comment by mrieser** [comment]
> I saw with Via that some agents pass those specific links but in the ouput_event, there were no link ids of them.

Maybe there are two links on top of each other, and the agents are not really on the specific link, but on another? You could check that in Via by selecting the link and then choose "Link Volumes" for that link (right-click in visualisation area after selecting the link).

Anyway, if you think there are vehicles on that link in Via, you can do a Select Link Analysis in Via and then create an agent group from it to get the agents on that link. 

For the Select Link Analysis in Via, see [here](https://docs.simunto.com/via/analyses/network-queries.html#-select-link-analysis) and the button "Create Agent Group" as visible in the screenshot, then choose "Show Agent Groups" from the menu "Window" in Via, there you find the created list of agents with options to view and export the list.

**Comment by SarahSie** [comment]
@mrieser Thank you very much for the clear explanation.
I have the Link volumes now (please see the screenshot), then how I can identity maybe there are two links on top of each other?
I have done "Create Agent Group" and you can see then the screenshot that agents on the link are shown on the left side.
As can be seen, some agents are passing this specific link (is presented with an orange color and a vehicle with green color passing it) and the "link Volumes" indicated that vehicles pass it differently during the time.
However, the number of agents in Link Analysis is still zero.
![link analysis](https://user-images.githubusercontent.com/40635602/87441747-c28d8200-c5f3-11ea-82ee-5b5946e17cfe.jpg)

**Comment by mrieser** [comment]
before creating the Agent Group, you can select the time window (I think by default it is 30min) of the Select Link Analysis. This has an influence on the created Agent Group. To test, probably choose "all" to get all agents of the whole day, not only those of the current hour or half hour.

**Comment by SarahSie** [comment]
Thank you  @mrieser

**Comment by bianchn2** [comment]
Hi, I would like to script the "Select Link Analysis" and "Create Agent Group" tools for automatic creation, following a MATSim simulation, of agent groups that use a particular link .  Does anyone happen to know if such scripting is possible in the Via scripting window or in java?  Thanks so much. - Michael
