### ISSUE TITLE
Unreasonably congested network and failing arrivals

### ISSUE THREAD

**Issue by alexanderbachev** [matsim-org/matsim-code-examples#395]
Dear community,

I am experiencing issues with the traffic model of Sofia I am currently building. So far I have used the pt2matsim module to create a multimodal network and the required mapped transitSchedule file and default transit vehicles files. I created a 10k population (about 1% of the true population) with home and work activities only. Their locations are taken from OSM POIs and building data, assigned randomly in the case of home locations and with a custom probability distribution which disfavours work locations too far from a given home location in the latter case. My default values for the flow and storage capacity factors are 0.01. All travel legs in the plans file are in car mode and I have enabled subTourModeChoice with pt, car and walk.

I have experienced a few issues very likely caused by heavy congestion in the network. Firstly, while looking at the live OTFVis visualisation, I found that PT vehicles appear to form long stationary queues at the end location of transit routes or sometimes along the routes. Please, see the corresponding issue [here](https://github.com/matsim-org/pt2matsim/issues/113).

Secondly, looking at leg histograms of the latest iteration, I found out that most of the agents using pt mode never arrive at the desired destination, while the ones using a car take 6x longer to arrive than what is the true situation in the city, with small part of agents also never arriving.

It appears to me that the issues are related to the network. It might have internal bottleneck links or I might have configured the simulation wrongly. I have tried increasing the flow and storage factors 0.1, which mostly solves the issues, however the results of the simulated model are no longer valid.

I have read in the issues section that the storage capacity factor could be increased for small sample simulations, however I have not found precise numbers. Am I making a fundamental mistake in the modelling process? I will attach most of the files I am using. In case it is needed I can also create a repo of my whole project. 

PS: The transport modal split in Sofia should be around 30:40:30 car:pt:walk, according to a study. I have not taken that into account in the plans file, because I believe I am not at the model calibration step, still experiencing issues. 

[pt2matsim_config_files.zip](https://github.com/matsim-org/matsim-code-examples/files/4924269/pt2matsim_config_files.zip)
[network_sof_mm_mapped.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/4924213/network_sof_mm_mapped.xml.zip)
[transitSchedule_mapped.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/4924216/transitSchedule_mapped.xml.zip)
[transitVehicles.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/4924217/transitVehicles.xml.zip)
[population_OSM_HWPairs_10k.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/4924220/population_OSM_HWPairs_10k.xml.zip)
[config_pt_v3.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/4924227/config_pt_v3.xml.zip)
![20 legHistogram_car](https://user-images.githubusercontent.com/63676508/87529934-5ca70600-c698-11ea-8ea5-1d042c0ca957.png)
![20 legHistogram_pt](https://user-images.githubusercontent.com/63676508/87529943-603a8d00-c698-11ea-8fc4-0a7ac3832ff5.png)

**Comment by kainagel** [comment]
There is something in matsim that addresses the pt vehicles issue.  Anybody remembers that?

As for the factors, we used to recommend to use storageCapacityFactory 0.03 together with flowCapFact of 0.01.  I think that this is no longer necessary (reason is that the mobsim has become considerably less stochastic over the years).

If you don't want to worry about mode choice at your current stage, I would rather fix mode choice at 30:40:30 beforehand.  If your input plans do not have routes yet, you can just go through all plans and change leg modes randomly.  You can do this "per plan" or "per trip"; I would do the latter.

**Comment by mrieser** [comment]
Regarding pt: One problem is, that the link capacity is scaled down to 1%, but there are still 100% of the transit vehicles driving around, leading to the congestion.
One way to fix this is to specify a very low passenger car equivalent in `transitVehicles.xml`:

```xml
...
<vehicleType id="...">
  ....
  <passengerCarEquivalents pce="0.05" />
</vheicleType>
....
```

It depends on how the file `transitVehicles.xml` was created, but often transit vehicles have a pce of 5 or a similar value, meaning they occupy space and capacity of around 5 regular cars. In sample-scenarios, this value should be reduced accordingly, so for a 1% scenario I would set the pce to 0.03 or 0.05 for the transit vehicles.

**Comment by kainagel** [comment]
Here it is:
```

static final String PCU_THRESHOLD_FOR_FLOW_CAPACITY_EASING = //
              "Flow capacity easing is activated for vehicles of size equal or smaller than the specified threshold. "
              + "Introduced to minimise the chances of buses being severely delayed in downsampled scenarios";


public double getPcuThresholdForFlowCapacityEasing() {
       return pcuThresholdForFlowCapacityEasing;
}

/**
 * @param pcuThresholdForFlowCapacityEasing -- {@value #PCU_THRESHOLD_FOR_FLOW_CAPACITY_EASING}
 */
public void setPcuThresholdForFlowCapacityEasing(double pcuThresholdForFlowCapacityEasing) {
       this.pcuThresholdForFlowCapacityEasing = pcuThresholdForFlowCapacityEasing;
}

```
In `QSimConfigGroup`.

Some comments:

* not in xml; can only be activated in code.

* I am not totally sure but I think that it complements what Marcel said.  So first you make your buses smaller.  And _then_ you activate this switch.

I _think_ the way it works is as follows.  Assume you have a 1pct scenario and a road with capacity 900.  Normally this means one veh/4sec, but with flow capacity factor 0.01 is means one veh/400sec.

So assume a bus tries to leave a link just after a regular vehicle.  It has to wait for 400 sec despite the fact that the bus itself has been made quite small via PCE.

The above switch will set that waiting time to zero, i.e. small enough vehicles can leave the link without having to wait the 400sec.  Their flow capacity contribution is still counted, so if some vehicle larger than that threshold wants to leave, it now will have to wait ... and any bus behind that as well (I would assume).  There was some use case (in Tel Aviv?) where I recall that this worked quite well.

**Comment by michalmac** [comment]
Here is some more discussion of `PCU_THRESHOLD_FOR_FLOW_CAPACITY_EASING`: https://github.com/matsim-org/matsim-libs/pull/55

**Goal**: address the issue of busses being delayed in down-sampled scenarios. In the case of 1% sampling, one car represents 100 cars, so if a bus moves behind such a synthetic car, the bus will have to wait a long time at an intersection (flow capacity consumed by this enormous car will recover in 100x longer time compared to the standard 100% scenario).

**Solution**: let small vehicles (in this case buses, as they are equivalent to only ~3 real cars, in contrast to simulated cars equal to 100 real cars) do not wait at intersections (= link ends) when at the front of the queue. They will of course consume the flow capacity making the recovery proportionally longer (but this will impact directly only big vehicles).

BTW. As for the actual implementation in QSim, we are not making cars 100 times bigger, but instead making link flow capacities and bus sizes 100x smaller. But the reasoning remains the same...

**Comment by alexanderbachev** [comment]
Thank you for the detailed answers, guys! I have modified the pt vehicle sizes and that has already fixed the queues in the first hours of the simulation, before agents start leaving their homes. I am trying to change the value of the `pcuThresholdForFlowCapacityEasing` variable, but unfortunately I am still quite a novice in java and am a bit lost in the way of doing that. As far as I know, I am unable to make changes to source files, so I have to change the variable value in my run file, possibly under the config section. Could someone suggest the right way to do it? I found a somewhat related [example](https://github.com/matsim-org/matsim-code-examples/blob/11.x/src/main/java/org/matsim/codeexamples/mobsim/addRemoveReplaceQSimCompoments/RunQSimComponentRequestInConfigExample.java) in matsim-code-examples, however I am unable to modify it for my case.

**Comment by kainagel** [comment]
It is much simpler than that.  Something like
```
	public static void main ( String [] args ) {
		Config config = ConfigUtils.loadConfig( args );
		config.qsim().setPcuThresholdForFlowCapacityEasing( 0.1 );
		Scenario scenario = ScenarioUtils.loadScenario( config );
		Controler controler = new Controler( scenario );
		controler.run() ;
	}
```
Does that make sense?  Or have you been running from MATSimGUI so far?

**Comment by alexanderbachev** [comment]
Thank you! It does make sense. I have been using IDE to run simulations, but hadn't configured anything other than the live OTFVis in the run class.
