### ISSUE TITLE
Tram's role as A Public Transport in MATSim (or Transport Modelling)

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#397]
Hello everyone,

I am currently building a base model for the city of Brussels using MATSim, facing lots of previous problems, but they are all solved. Thanks again for everyone who had helped me previously :)

Recently, I tried to add means of public transports into my model, and now I need to decide the roles of tram within my network. 

I am using the pt2matsim pipeline. Therefore I need to set the transportModeAssignment in my config file. Basically, this function determines which kind of links that specific PT is driving on, and if no network modes are defined, it will create some artificial links. For instance, I decided that all the buses in my model are only operating on the "car" links; meanwhile, I didn't define network modes for the metro, so the pipeline will generate artificial links for it (which is somewhat close to the reality).

However, many European cities have the third mean of public transports, trams. The situation is even more cumbersome for Brussels. The trams can either share the same roads with the normal cars (as the first image below) at some sections, or driving on their dedicated lanes (both above ground and underground) at other locations.

![image](https://user-images.githubusercontent.com/63421908/87557295-03e76580-c6b8-11ea-9708-c24588ed80d8.png)
![image](https://user-images.githubusercontent.com/63421908/87560479-c4bb1380-c6bb-11ea-8f5d-f1324a6b0705.png)
![image](https://user-images.githubusercontent.com/63421908/87560155-70179880-c6bb-11ea-9020-7f78b3ea7a4c.png)

As a result, I don't know what I should do for those links. Either do or do not specify artificial links don't feel right. 

My personal viewpoint about this is "do not specify artificial links for the tram", in other words, all the tram in my model will share the same link with other vehicles. I think this is better, since the service quality of trams will be heavily influenced by the congestion level of sections where there are no dedicate lanes (trams cannot change their routes when operating obviously).

I'm wondering if any of you have encountered a similar problem when building your model? What do you think about my choice? Or, I'm wondering if there exists any function in MATSim (pt2matsim) that can specify those links that shared by trams and cars, and other purely designed for cars? Thanks very much for your reading and answer in advance! 😊

**Comment by kainagel** [comment]
In _principle_ :-|, it should be possible to decide on a link-per-link basis if they use the same link or not.

I.e. it should be possible to have one link with modes="car,tram" splitting up into two that are modes="car" and "modes="tram".

In practice, I have never tried it out.  And there is some longstanding bug somewhere that buses use the car network.  Not sure if that has been systematically fixed.

**Comment by jingjunL** [comment]
> In _principle_ :-|, it should be possible to decide on a link-per-link basis if they use the same link or not. I.e. it should be possible to have one link with modes="car,tram" splitting up into two that are modes="car" and "modes="tram". In practice, I have never tried it out. And there is some longstanding bug somewhere that buses use the car network. Not sure if that has been systematically fixed.

Thanks for your reply, Kai. 

To avoid this annoying bug, do you mean I should specify the "bus" mode on my network.xml? I obtained my current network through 2020 user guide (osm.pbf - OSMOSIS - RunPNetworkGenerator), and the modes of each link through this process are purely for "car" (as below).
![image](https://user-images.githubusercontent.com/63421908/87566123-d81dad00-c6c2-11ea-95f3-8299bc6c2b38.png)

Is there any way I can obtain links for "car, bus" and solely "car"? Or, I may need to change some original code, making all the link modes I generated as "bus, car"?

**Comment by sebhoerl** [comment]
If you use the OSM converter in pt2matsim you could do the following:

1) Define a `wayDefaultParams` section, which converts "railway=tram" OSM links to "tram" MATSim links. By default there is a block that converts them to MATSim "rail" links, so you can simply change this value.
2) pt2matsim then cleans the network and removes soruces, sinks, islands etc. There are `routableSubnetwork` parameter sets, which define for which modes full routable network without those issues are requested. By default, pt2matsim will make a consistent network of "car" links, taking into account all "car" links from step (1), and a consistent network of "bus" links, taking into account all "car" and "bus" links from step (1). You can add one `routableSubnetwork` section, which makes sure that either all your `tram` links compose a consistent network, or maybe all `tram` and `car` links together. Which option makes sense depends a bit on how those things are defined in OSM (not sure if a road with a tram line is tagged as "railway=tram", or if there is a separate edge in the OSM data set).
3) In the PT mapping part, you can request with the `transportModeAssignment` block, that all lines with the `tram` schedule mode, are routed on links with the allwedMode `tram` (which you have made sure is consistent in step (2)).

There are two issues that come to my mind: 1) The network cleaner may still delete all `tram` links if they are defined with sources and sinks in the OSM data. It may help to set `oneway` to `false` in the `wayDefaultParams` in the OSM conversion step. 2) The mapping would now take into account the whole tram+car network, so if the mapper thinks that a car route that goes parallel to a tram route is faster, it would choose this one. You may correct the mapping by making all `tram` links quite fast (but then again, you may have a problem with combined car/tram links that share both modes.

Just some thoughts, now really tested, maybe they help a bit :)

**Comment by sebhoerl** [comment]
To the latter question: The bus issue works analogously to the tram example. Pt2matsim can generate a network with a "routable sub-network" for `bus` which consists of a consistent network of `car and/or bus` links from the initial step of data conversion. This makes sure that whenever you route on a network filtered for the "bus" mode, the router will not fail. What Kai mentioned (I think) is that internally, MATSim does not really make a difference for busses whether links are "car" or "bus". However, the line mapping in pt2matsim *will* make a difference and consider bus lanes.

**Comment by jingjunL** [comment]
> If you use the OSM converter in pt2matsim you could do the following:
> 
> 1. Define a `wayDefaultParams` section, which converts "railway=tram" OSM links to "tram" MATSim links. By default there is a block that converts them to MATSim "rail" links, so you can simply change this value.
> 2. pt2matsim then cleans the network and removes soruces, sinks, islands etc. There are `routableSubnetwork` parameter sets, which define for which modes full routable network without those issues are requested. By default, pt2matsim will make a consistent network of "car" links, taking into account all "car" links from step (1), and a consistent network of "bus" links, taking into account all "car" and "bus" links from step (1). You can add one `routableSubnetwork` section, which makes sure that either all your `tram` links compose a consistent network, or maybe all `tram` and `car` links together. Which option makes sense depends a bit on how those things are defined in OSM (not sure if a road with a tram line is tagged as "railway=tram", or if there is a separate edge in the OSM data set).
> 3. In the PT mapping part, you can request with the `transportModeAssignment` block, that all lines with the `tram` schedule mode, are routed on links with the allwedMode `tram` (which you have made sure is consistent in step (2)).
> 
> There are two issues that come to my mind: 1) The network cleaner may still delete all `tram` links if they are defined with sources and sinks in the OSM data. It may help to set `oneway` to `false` in the `wayDefaultParams` in the OSM conversion step. 2) The mapping would now take into account the whole tram+car network, so if the mapper thinks that a car route that goes parallel to a tram route is faster, it would choose this one. You may correct the mapping by making all `tram` links quite fast (but then again, you may have a problem with combined car/tram links that share both modes.
> 
> Just some thoughts, now really tested, maybe they help a bit :)

Hi Sebastian: 

That's surely helped. I didn't use the OSM converter in pt2matsim initially, but your algorithm does sound more suitable for my current situation. I will re-generate my network.

One more (maybe very simple?) question before I start. My current osm file is obtained through the following image: which firstly exacted the road network from a Brussels bounding box, then adding the large roads of a larger region and finally merge them (that's the `merged-network.osm`). 

I'm wondering if I can feed this `merged-network.osm` directly into the pt2matsim OSM converter? I am concerning because according to the description, step 3 in the image is only extracting the "road network". Is that mean links such as "railway=tram" has been omitted since ever start? If so, I guess it will be unsuitable to use this osm file for the converter?

Finally, a great thank for your help 😊

![image](https://user-images.githubusercontent.com/63421908/87582263-72d5b600-c6da-11ea-85d5-0128901f65db.png)
