### ISSUE TITLE
Location of Extrensions

### ISSUE THREAD

**Issue by K4Werri** [matsim-org/matsim-code-examples#400]
Hi.

The MATSim book (Horni et al (2016)) refers to a number of extensions that I cannot find at https://github.com/matsim-org. Is there another place I should be looking?

Thanks.

Kevin.

**Comment by kainagel** [comment]
Please use https://matsim.org/extensions .  If that does not work for your case, please let us know; we are sometimes removing extensions that are not maintained, and sometimes we are late in updating the above webpage.

**Comment by K4Werri** [comment]
Hi.

I did look at https://matsim.org/extensions. That's where the MATSim book sends you but not all are there eg the wagonSim or Minibuses extension (among others) is not there. I did find some referred to in the book at https://github.com/matsim-org/matsim-libs/tree/master/contribs. It looks as though the extensions referred to in the book are spread across the two locations?

Thanks.

Kevin.

**Comment by mrieser** [comment]
I think wagonSim was not maintained for quite some time and got removed.
There is a link on https://matsim.org/extensions that leads you to https://matsim.org/javadoc. There, the contribs are still listed, although wagonSim only with the old version from when it was last around.

**Comment by K4Werri** [comment]
Hi,

Thanks. Found the javadoc entries.

Kevin.

**Comment by K4Werri** [comment]
Thanks for your help.

K.
