### ISSUE TITLE
changing the  "Number of Lanes" attribute for links

### ISSUE THREAD

**Issue by SarahSie** [matsim-org/matsim-code-examples#401]
Hello all,

I want to increase the "Number of Lanes" for some links for my simulation.
Could you please help to find the best place in the code that I can give a list of link Ids and set their lanes number to my desire number?

**Comment by SarahSie** [comment]
update:
By using the networkChangeEvents.xml, I have added:
```
<networkChangeEvent startTime="08:00:00">
	<link refId="426767"/>
        <link refId="829609"/>
        <link refId="531696"/>
        <link refId="490345"/>
	<lanes type="absolute" value="2.0"/>
</networkChangeEvent> 
```
Then I have run it through the equilibrium solution with 2oo iterations.
However, the outcome results (output_Event) is totally the same as before. Therefore, it means even that the number of lines did not increase. Because if the number of lines would have increased, then through the iteration, more agents supposed to use those increased lines roads. 
How can I solve the issue?

**Comment by SarahSie** [comment]
I am still looking forward to a suggestion. If anyone can help me to simulate a scenario, in which I can add to the line of the road, would be great

**Comment by mhsrhm** [comment]
I am still looking forward to a suggestion. If anyone can help me to simulate a scenario, in which I can add to the line of the road, would be great

**Comment by mhsrhm** [comment]
I am still looking forward to a suggestion. If anyone can help me to simulate a scenario, in which I can add to the line of the road, would be great

**Comment by tschlenther** [comment]
Hello,

using the network change events provides you the opportunity to have time-dependent attributes. However, if you want to set the attribute of a link to constant value over the entire simulation, you can do so by manipulating the network.xml or doing it in java code (see https://github.com/matsim-org/matsim-code-examples/blob/11.x/src/main/java/org/matsim/codeexamples/network/RunModifyNetworkExample.java for an example - in your case you would do `l.setNumberOfLanes(2);` ).

Moreover, you need to know that, when using standard matsim, the number of lanes is not directly relevant for the throughput of a link. The attribute you are looking for is the flow capacity. You can double it for example by `l.setCapacity(2 * l.getCapacity());` or again, by doing that manually in the network.xml. You might want to read about the capacities in matsim, in the matsim book for example :)
