### ISSUE TITLE
door2door drt access and egress walk

### ISSUE THREAD

**Issue by KamijoYo** [matsim-org/matsim-code-examples#402]
I think that the door2door drt up to 11.x did not have access and egress walking, but in 12.x access and egress walking from OD to the nearest link occurred.
Is there any way to prevent access and egress walking in 12.x?

**Comment by tschlenther** [comment]
Try the switch insertingAccessEgressWalk in PlansCalcRouteConfigGroup :)

**Comment by KamijoYo** [comment]
Thank you very much for your reply.

I tried it, and I confirmed that the insertingAccessEgressWalk functioned for the car, but in the case of drt, access and egress walking occurred with both true and false.

**Comment by michalmac** [comment]
This dates back to the PR https://github.com/matsim-org/matsim-libs/pull/727. You can only modify this behaviour programmatically (as shortly described in the second section of the PR description)
