### ISSUE TITLE
Why MATSim Recognise Public Transport as Person?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#406]
Hello everyone,

My research got stuck in a very weird issue. If anyone has encountered similar problems, hopefully, could you please share how you solved that?

My network and pt schedule are both generated from pt2matsim via OSM and local GTFS data. Currently, there's only one agent in my model since I want to test this scenario. The plan of my agent is as image below:
![image](https://user-images.githubusercontent.com/63421908/88681497-ed96cc00-d0f1-11ea-9ae0-7840b33893ee.png)

A very weird thing happen when I ran my scenario: with only one agent like above in my plan, MATSim still ran into a dead circle (which means the simulation for the first iteration ran until 200:00:00 and doesn't seem like it will stop).
![image](https://user-images.githubusercontent.com/63421908/88682305-d1dff580-d0f2-11ea-8b06-4880bc37126a.png)

I thought maybe it's the problem of my population file, therefore, I did a bit edition by changing above agent mode as "car". This time MATSim works the results out and iteration stops properly at 26:00:00. But an even weirder thing happened when I checked my output event file. 

In that file, I can see my public transport entering and leaving their links and platforms. I tried to search the term "arrival", making sure that the agent processed its activity smoothly. But I have seen many lines of text like below:
![image](https://user-images.githubusercontent.com/63421908/88683121-c3dea480-d0f3-11ea-99cf-12c5efc14225.png)

Probably MATSim treated my public transport vehicles as people. I'm wondering if that's how it worked?

Maybe another thing worth highlighting is before I added the public transport vehicle and schedule into my config, the scenario (with one agent mode as "car" and the same network) seems to work fine: no weird public transport "person", agent drives to his work and come back home at an appropriate time with 6 sub-tour plan generated.

Will be very appreciated for any comments and suggestions. Thanks very much for your help!

**Comment by langkoos** [comment]
Check if your agent doesn't arrive at their transit stop after the last bus has already passed. Then they will be stuck indefinitely, and you have to set an explicit end time to the simulation (qsim section in config) rather than letting it run until the last agent finishes its plan.

transit driver agents are standard for the transit implementation, which is why you see them entering and leaving the vehicles when they start and end a circuit run.

**Comment by jingjunL** [comment]
> Check if your agent doesn't arrive at their transit stop after the last bus has already passed. Then they will be stuck indefinitely, and you have to set an explicit end time to the simulation (qsim section in config) rather than letting it run until the last agent finishes its plan.
> 
> transit driver agents are standard for the transit implementation, which is why you see them entering and leaving the vehicles when they start and end a circuit run.

Hello Pieter,

Exactly! I found the coordinate of that agent is too far away from the nearest pt stop, and took him 400 minutes walking there, that's why he cannot catch up with the latest pt and stuck there indefinitely.

Many thanks for your help, and all my confusion has solved now.

Cheers,
Jingjun
