### ISSUE TITLE
Are the PT in MATSim is Actually Teleported?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#407]
Hello everyone, 

I think this is an issue concerning my understanding of the MATSim platform. Maybe it is a very naive one, hopefully, anyone can answer this.

I generated one default config file in order for a more comprehensive understanding today. In its module `planscalroute`, I see settings as below:

`		<parameterset type="teleportedModeParameters" >
			<param name="beelineDistanceFactor" value="1.3" />
			<param name="mode" value="pt" />
			<param name="teleportedModeFreespeedFactor" value="2.0" />
			<param name="teleportedModeSpeed" value="null" />
		</parameterset>
`

Therefore, if I understand correctly, pt in MATSim is treated as teleportation. Does that mean they will not be interacting with other main modes (such as cars)? 

Or, once if I opened the `transit` setting, and set `useTransit` as true (with my transitSchedule and PTVehicle file of course), it will be treated as some "special" kind of teleportations (like what is mentioned in the second step of MATSim pt development history in the user guide: support detailed simulation of public transport). Therefore, this default old setting will no longer work? If so, are these public transport vehicle actually interacting with the normal "car"?

Many thanks for your kind answer in advance :)

**Comment by mrieser** [comment]
If `useTransit = false`, then the transit passengers will be teleported according to the default settings. No transit vehicles will be simulated at all.

If `useTransit = true`, then the simulation assumes that a full transit schedule is available, and transit vehicles are simulated on the network. If transit vehicles interact with normal cars depends on the modelling: private cars will use the `car`-links in the network, whereas transit vehicles drive along the route specified in the `transitschedule.xml`-file. If those routes also use car-links, then the vehicles will interact with each other, and e.g. buses can get stuck in a traffic jam and get delayed. If the routes in the transit schedule uses separate links that are not available to regular cars, than they do not interact with each other. This is useful e.g. for trains.

So it depends on how you model your data and how you configure your simulation, whether transit vehicles interact with normal cars or not.

**Comment by jingjunL** [comment]
> If `useTransit = false`, then the transit passengers will be teleported according to the default settings. No transit vehicles will be simulated at all.
> 
> If `useTransit = true`, then the simulation assumes that a full transit schedule is available, and transit vehicles are simulated on the network. If transit vehicles interact with normal cars depends on the modelling: private cars will use the `car`-links in the network, whereas transit vehicles drive along the route specified in the `transitschedule.xml`-file. If those routes also use car-links, then the vehicles will interact with each other, and e.g. buses can get stuck in a traffic jam and get delayed. If the routes in the transit schedule uses separate links that are not available to regular cars, than they do not interact with each other. This is useful e.g. for trains.
> 
> So it depends on how you model your data and how you configure your simulation, whether transit vehicles interact with normal cars or not.

Hello Marcel,

That's very detailed! My confusions are perfectly solved now.

Many thanks for your detailed answer as always! Much appreciate it 😊

Have a nice evening,
Jingjun
