### ISSUE TITLE
Configuring bus lane into base condition

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-code-examples#413]
Hello community,
I am trying to understand the impact of introducing a bus lane in the city and hence like to modify road network. So, I would need to change the base condition in three files 

a) transitSchedule 
Here, I need to change the segment information @ <stop> and <link> tags. 

b) In the matsim_network file both at the link and nodes level. 

However, I unable to understand how <route> and refId in the <stop> element section are getting populated in transitSchedule.xml and how to update them as a result of bringing changes to the route network. 

Any help would be very much appreciated.

**Comment by vsgo222** [comment]
I am willing to share the files if that helps.

**Comment by vsgo222** [comment]
Closing the thread as I have resolved this issue.

**Comment by jiao1997** [comment]
> Hello community,
> I am trying to understand the impact of introducing a bus lane in the city and hence like to modify road network. So, I would need to change the base condition in three files
> 
> a) transitSchedule
> Here, I need to change the segment information @ and tags.
> 
> b) In the matsim_network file both at the link and nodes level.
> 
> However, I unable to understand how and refId in the element section are getting populated in transitSchedule.xml and how to update them as a result of bringing changes to the route network.
> 
> Any help would be very much appreciated.

Hello, 
       I am working for bus lane now. Could you please tell me how did you introduce the busline? Hope to get your early reply. Yours,
Jiahao Wang

**Comment by vsgo222** [comment]
> 
> 
> > Hello community,
> > I am trying to understand the impact of introducing a bus lane in the city and hence like to modify road network. So, I would need to change the base condition in three files
> > a) transitSchedule
> > Here, I need to change the segment information @ and tags.
> > b) In the matsim_network file both at the link and nodes level.
> > However, I unable to understand how and refId in the element section are getting populated in transitSchedule.xml and how to update them as a result of bringing changes to the route network.
> > Any help would be very much appreciated.
> 
> Hello,
> I am working for bus lane now. Could you please tell me how did you introduce the busline? Hope to get your early reply. Yours,
> Jiahao Wang

Jiahao,
I ended updating the transitSchedule and matsim_network files. 
matsim_network is nothing but a xml tree containing details about the links and nodes. transitSchedule file uses these details to prepare traversed route information and stopIDs information. So we have to modify both this files
Say, for each links the modes attrib contains the information related to mode which can ply on the link. We edit this attribute type 
for e.g. if the original link 
`<link id="12345" from = ""0001" to="0002" freespeed="XXX" lane ="1" length = "100" capacity = "2000" mode = "car,bus,walk" >`
we split the original link into two parts -
```
<link id="12345" from = ""0001" to="0002" freespeed="XXX" lane ="1" length = "100" capacity = "2000" mode = "car" >
<link id="12345_bus_only" from = ""0001" to="0002" freespeed="XXX" lane ="1" length = "100" capacity = "2000" mode = "bus,walk"  >
```
The newly duplicated link needs to be further referenced in transitSchedules - stopIDs, refIds, minimaltransfer and transitRoutes section of transitSchedule so that when MATSim runs, it finds proper reference to the newly created links and directs transits vehicles to ply on them.

**Comment by jiao1997** [comment]
> The newly duplicated link needs to be further referenced in transitSchedules - stopIDs, refIds, minimaltransfer and transitRoutes section of transitSchedule so that when MATSim runs, it finds proper reference to the newly created links and directs transits vehicles to ply on them.

Thanks a lot. I think I got how to do it !
