### ISSUE TITLE
Understanding delay attribute in the output_events file

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-code-examples#416]
Apologies for double posting, 
Can someone explain me what does the delay attribute indicates. I am trying to understand a) base scenario b) the impact of changing PT daily frequency c) if exclusive lanes are introduced in the high ridership routes. 
1. Is the delay related to delay in arrival and departure at a particular stopfacility and hence difference between them either comes to 20sec (equal to offsetDeparture buffer time) or equivalent to time taken by agents to board the bus? 
2. Can Vehicle Hours Travelled which is equivalent to sum of the time difference between [vehicle enters traffic/entered link] - [left link] could be far greater than (sum of ) total time taken by bus to traverse the route? I ask this because my calculated VHT is around 4 times or larger than the observed transit vehicle hours.

Vedant

**Comment by vsp-gleich** [comment]
>     1. Is the delay related to delay in arrival and departure at a particular stopfacility and hence difference between them either comes to 20sec (equal to offsetDeparture buffer time) or equivalent to time taken by agents to board the bus?
It should relate to the departure or the arrival referred to in the event (at the stop facility referred to in the event), thus different for arrival and departure. If you are thinking about delays, keep sure link travel times are not too fast in the base case, otherwise delays can be compensated for.

>     2. Can Vehicle Hours Travelled which is equivalent to sum of the time difference between [vehicle enters traffic/entered link] - [left link] could be far greater than (sum of ) total time taken by bus to traverse the route? I ask this because my calculated VHT is around 4 times or larger than the observed transit vehicle hours.

This sounds like you maybe did not set `setAwaitDepartureTime(true)` at TransitRouteStops, so buses depart before their planned departure time and over the line can save a lot of time, reducing the VHT.

**Comment by vsgo222** [comment]
Thanks for the reply vsp-gleich

> This sounds like you maybe did not set `setAwaitDepartureTime(true)` at TransitRouteStops, so buses depart before their planned departure time and over the line can save a lot of time, reducing the VHT.

actually, no. I have exactly the same configuration (config file) used. The only difference is that a) mixed traffic in a base case b) scenario 1 - increased daily PT frequency c) Scenario 2 - increased PT frequency + bus lane introduced, By the way, how to set setAwaitDepartureTime = True. I am not JAVA conversant. 

> It should relate to the departure or the arrival referred to in the event (at the stop facility referred to in the event), thus different for arrival and departure. If you are thinking about delays, keep sure link travel times are not too fast in the base case, otherwise delays can be compensated for.

So, would that mean I would double count the delays if I end up summing the delays (both at vehicleArrivesFacility and vehicleDepartFacility) across stop-facilities traversed in a given PT route?

**Comment by vsp-gleich** [comment]
> actually, no. I have exactly the same configuration (config file) used. The only difference is that a) mixed traffic in a base case b) scenario 1 - increased daily PT frequency c) Scenario 2 - increased PT frequency + bus lane introduced, By the way, how to set setAwaitDepartureTime = True. I am not JAVA conversant.

This is not a config setting. Instead you have to set that variable to true in your TransitSchedule for each TransitRouteStop. I strongly recommend to code this in Java (see e.g. [here](https://github.com/matsim-org/matsim-libs/blob/e39bb15292660d0932ac1cbccfc6f54a3b77259d/matsim/src/test/java/org/matsim/pt/router/Fixture.java#L301)), but in theory you can also add this manually in the TransitSchedule xml file (at a high risk of typos which will lead to Matsim crashes later).

> So, would that mean I would double count the delays if I end up summing the delays (both at vehicleArrivesFacility and vehicleDepartFacility) across stop-facilities traversed in a given PT route?

Yes, indeed. Still, there are lots of ways to aggregate delays (average only last stop of the line arrival, all arrivals, ...), you have to decide on your own what you prefer.
