### ISSUE TITLE
Matsim wiki gives a 403 error forbidden

### ISSUE THREAD

**Issue by alexdawn** [matsim-org/matsim-code-examples#42]
Trying to follow many links on the https://www.matsim.org page gives a 403 error

such as the link:

https://matsim.atlassian.net/wiki/spaces/MATPUB/blog/2018/12/05/351240193/AI+Driving+Olympics%3A+Managing+an+Automated+Taxi+Fleet

even the wiki home page is forbidden:

https://matsim.atlassian.net/wiki

**Comment by jfbischoff** [comment]
Very strange. It does work for me, even if not logged into Atlassaian.
Perhaps some time/location-specific problem with confluence?

**Comment by alexdawn** [comment]
turns out it was an issue with chrome and some cookies it had been storing for the site, clearing the cookies and the site now works.
