### ISSUE TITLE
Mixed Traffic Population - Cars and Taxis 

### ISSUE THREAD

**Issue by NikolaAndro** [matsim-org/matsim-code-examples#420]
My goal is to design a multi-modal Pigou network where taxis or ridesharing vehicles (implemented using DynAgent package) interact with other non-dynamic traffic modalities (e.g. regular cars).

Due to the nature of different dtd files (e.g. plans_v4.dtd for cars and population_v5.dtd for taxis), I am unable to merge taxis with regular vehicles in one simulation environment. However, I am able to create separate Pigou networks with cars only and with taxis only successfully. I have even tried using population_v6.dtd, but still could not make it work. So, can anyone please help me in solving this issue?

My Failure Trace directs me to the calcDistanceExcludingStartEndLink function. I do not see why that would be a problem since the same network worked for the separate examples.

Please find my GitHub link where you can see my code and my error information inside the output/pigou_mixed_traffic.

https://github.com/NikolaAndro/Pigou-s-Example

Thank you!

Nikola Andric

**Comment by mrieser** [comment]
> Due to the nature of different dtd files (e.g. plans_v4.dtd for cars and population_v5.dtd for taxis), I am unable to merge taxis with regular vehicles in one simulation environment.

MATSim should be able to load both formats. Why are you unable to merge them? How did you try this? Do you get an error message? What does it state?

> you can see my code and my error information inside the output/pigou_mixed_traffic.

I could not see any error message or stack trace in this directory. Could you provide a full log file that contains the exception or error?

**Comment by NikolaAndro** [comment]
Mr. Rieser, 

Thank you for your response!

> Do you get an error message? What does it state?
> Could you provide a full log file that contains the exception or error?

When I try to run the simulation, my last message is that it is trying to load population_v5. There is no error message. It just stops there. I do not know what is the reason for that. 

The failure trace leads me to calcDistanceExcludingStartEndLink(final NetworkRoute route, final Network network).

If you enter the following repository https://github.com/NikolaAndro/MATSim/tree/master/Pigou's%20Example/output/pigou_mixed_traffic  , you will find ERROR_doc.txt and Error_population.PNG image that shows my screen.

> Why are you unable to merge them? 

I do not know what is the reason for not being able to merge them. I wish I knew that.   

> How did you try this? 

In my population file "plans_mixed_traffic.xml" at the top I labeled what type of the population file I would use. Then, under that I entered 10 regular cars and 10 taxis. 

Please let me know if you have any ideas how to resolve this!

Thank you!

**Comment by NikolaAndro** [comment]
The issue is solved. I was referring to nodes in the network instead of links...
