### ISSUE TITLE
Disable walking, bimodal routing & install() call

### ISSUE THREAD

**Issue by helgehr** [matsim-org/matsim-code-examples#427]
Hello everyone,

I have two basic questions regarding the configuration of a simulation and one regarding setting up my own module.

1. Is it possible to disable walking in the config? So far I changed the `beelineDistanceFactor` in the `planscalcroute` group in the config file to a high value (9999999) but I was wondering whether there is a more elegant way of doing that.
2. I am simulating a bimodal scenario with pt and drt and in the `population.xml` file I have added `pt` for all the leg modes (from origin to destination) and then created an extension which looks for the closest train stations (to origin and destination of each trip) and adds a leg + a dummy activity at the stations to have the bimodal transport. Is it possible that matsim automatically searches for such transfers without the random evolution over several days?
3. When I add my extension with `controler.addOverridingModule(new MyModule());` The module gets installed four times (see the short code example of my module below and the resulting log messages further)

 ```
   @Override
   public void install() {
        LOG.info("Initiating");
        this.addControlerListenerBinding().to(MyListener.class);
    }
```

Log messages:
```
2020-09-10T22:55:50,904  INFO MyModule:16 Initiating
2020-09-10T22:55:50,965  INFO MyModule:16 Initiating
2020-09-10T22:55:51,020  INFO MyModule:16 Initiating
2020-09-10T22:55:51,065  INFO MyModule:16 Initiating
```
I noticed that this also happens for the `ExampleIndividualizedScoringFunctionModule` in this repository, so I think it is a more general problem.
It becomes problematic if I want to pass an own config group to the MyModule as well. How can one avoid this multiple call of the install function?

Best regards and thanks you in advance!

**Comment by jfbischoff** [comment]
1. Disabling walking is not possible, mostly because walks is some kind of last fallback solution for several modes.
2. The [SwissRailRaptor](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/#swissRailRaptor) (part of the matsim core, though not yet the Standard PT Router), allows routing intermodal trips and thus combining DRT and PT trips (without any dummy activity in between). You can indeed disable walking as an access mode, though I'm not sure what the result will look like.

**Comment by helgehr** [comment]
Thanks for the answer, I am already using the swissrailwayraptor module but it does not search for intermodal trips automatically I noticed. For example when there is a pt leg and there is no pt available at the origin the person is stuck at its origin at least for the first iteration.
