### ISSUE TITLE
How to set activity as primary or secondary in config?

### ISSUE THREAD

**Issue by alexdawn** [matsim-org/matsim-code-examples#43]
From reading the matsim book it mentions primary and secondary activities, primary activities are fixed while secondaries can get dropped from the plan, and with another module can have a choice between facilities.

What is not clear is how in the config do you set an named activity to be primary or secondary:

Sioux Falls has an example of a secondary activity:
```
		<param name="activityType_2"            value="secondary" /> 
		<param name="activityPriority_2"        value="1" />
		<param name="activityTypicalDuration_2" value="01:00:00" />
		<param name="activityMinimalDuration_2" value="00:30:00" />
		<param name="activityOpeningTime_2"     value="08:00:00" />
		<param name="activityClosingTime_2" value="20:00:00" />
```
however with the exception of the activity name, doesn't have any difference from a primary activity, unless `activityType` takes a set of predefined defaults so that h, home w, work e, edu, education are automatically made primary?

**Comment by kainagel** [comment]
I think that this is meant as a conceptual help, not as something that is currently implemented.  In particular, we also point out that the scoring function will not work with activity insertion/dropping.  (There is an improved version of the utility function in newer code, marked by `typicalScoreComputation=relative`, described in newer versions of https://matsim.org/docs/userguide/ .).

The `locationchoice` contrib has, I think, a configurable list of activities that can be relocated.  Those would then be "secondary" activites, as opposed to "primary" activities for which the locations cannot be changed.  Note, however, that at least we here in Berlin to NOT have much experience with that contrib.

**Comment by alexdawn** [comment]
Thank you for your answer, it makes things much clearer!
