### ISSUE TITLE
OutOfMemryError

### ISSUE THREAD

**Issue by hyen0929** [matsim-org/matsim-code-examples#430]
Hello!
I'm using MATSim GUI, and I've got the OutOfMemoryError while simulating my own example file.
I used about 300,000 links.
How can I get rid of this error?
(I'm using ver.12.0)
Thank you!!

**Comment by mrieser** [comment]
The MATSim GUI has an option to specify how much memory your simulation runs with. Just increase this number and start again.

**Comment by hyen0929** [comment]
I didn't recognize that.. thank you!!
