### ISSUE TITLE
Public transit network

### ISSUE THREAD

**Issue by jalal1** [matsim-org/matsim-code-examples#431]
Dears, 

I am working on a model with both cars and public transit. I used GTFS2MATSim to create the needed input files, and also I used the car's network as input to combine it with the public transit network. So now I have a network file with both cars and public transit links. 

I noticed that both networks are separated, each with different nodes and links. Does this mean that cars will not be able to use public transit links, the same for busses? If that correct, and if I run an experiment with only busses in the network, how I can measure the congestion, counts, ...? Also, if I run an experiment with both modes, does it mean that busses will not be counted, because they are using different links? 

In Via I noticed that the public transit network doesn't use the car's network, instead, it connects stations together, is that how it works, or maybe I miss something. I attached an image, how a public transit route looks like.

Notice that when I did the conversion using GTFS2MATSim, I used:
'CoordinateTransformation ct = new WGS84toMercator();'
instead of
'CoordinateTransformation ct = TransformationFactory.getCoordinateTransformation(TransformationFactory.WGS84,"EPSG:26930");'
Because the second line cause an error. Could it be related ? 

![image](https://user-images.githubusercontent.com/1554493/93693337-1f118f80-fac4-11ea-8dd4-c8f4665e7312.png)

Thank you, 
Jalal

**Comment by Janekdererste** [comment]
Your observation is correct. The GTFS2Matsim facility creates a separate pt-network which means busses do not share the road with regular vehicles. This works well for studies where the interaction of busses and private cars is not important. If you're interested in such questions you have to implement your pt differently.

Also, GTFS2Matsim only generates a 'default' pt vehicle which is used for trains as well as busses. You'd have to tweak this parameter as if you're intersted in congestion effects of busses.

**Comment by polettif** [comment]
> This works well for studies where the interaction of busses and private cars is not important. If you're interested in such questions you have to implement your pt differently.

@jalal1 [pt2matsim](https://github.com/matsim-org/pt2matsim) provides GTFS converters and functions that produce a schedule/network where busses and cars use the same network.

**Comment by Janekdererste** [comment]
@polettif good to know. I'll try it sometime.

**Comment by jalal1** [comment]
Thank you @Janekdererste 

@polettif, I will try it. Thank you
