### ISSUE TITLE
Drt Extension

### ISSUE THREAD

**Issue by SapanTiwari** [matsim-org/matsim-code-examples#438]
I am trying to add DRT extension in the Melbourne model. I have created new taxies and wrote a new RunMelbourne_drt class to run the extended model. While running the class, It manages to run for iteration 0 and right after that results in errors. For iteration 0, I am not getting any stats or output for DRTs, I am just getting stats of the base model. I am using RunDoor2DoorExample. I am attaching the error file, RunMelbourne_drt class.

[RunMelbourne_drt.txt](https://github.com/matsim-org/matsim-code-examples/files/5303777/RunMelbourne_drt.txt)
[Eroor.txt](https://github.com/matsim-org/matsim-code-examples/files/5303776/Eroor.txt)

**Comment by michalmac** [comment]
Looks like there may be something wrong with the config file or maybe it does not match the matsim version you are using.

**Comment by SapanTiwari** [comment]
Thank You For your response. Yes, the error was with mats version.
