### ISSUE TITLE
Public Transport On Demand

### ISSUE THREAD

**Issue by ciolo** [matsim-org/matsim-code-examples#440]
Hello everybody,
I ran a successful pt simulation based on my data such as GTFS, population and network of my area of interest. The simulation correctly returns, as MatSim was designed, the rescheduling of the agents' plans (to summarize briefly). My goal, however, is the opposite: that is, based on the variation in the demand of agents, to return a rescheduling of public transport, such as rescheduling the frequency of some buses on certain routes based on demand, to use a bus with lower capacity for certain stops and so on. Basically I would like to "generate" a more efficient public transport supply (GTFS) based on demand. Is it possible through MatSim to reach such a result?

**Comment by vsp-gleich** [comment]
You can have a look into the minibus contrib and [https://doi.org/10.14279/depositonce-4096](https://doi.org/10.14279/depositonce-4096). It uses matsim transit schedules instead of GTFS.

**Comment by ciolo** [comment]
Oh, thank u very much!
