### ISSUE TITLE
PT capacity under 10% scenario

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#441]
Hello everyone,

My model currently has transit routes. However, I'm wondering what vehicle capacity number should I fill in if I am modelling a 10% scenario? For instance, currently, my bus can carry 50 people at the same time. However, since I am modelling a 10% scenario, do I need to change this capacity to 10% (5 passengers) as well? If so, what about the vehicle length? Or, MATSim will automatically do it for me if I have set my flow and storage capacity factor to a specific value? Any previous suggestions are very appreciated! Thank you :)

**Comment by michalmac** [comment]
Please have a look at https://github.com/matsim-org/matsim-code-examples/issues/395 for some general rules about sizing vehicles and buses in downscaled scenarios.

**Comment by jingjunL** [comment]
> Please have a look at #395 for some general rules about sizing vehicles and buses in downscaled scenarios.

Hi Michal, thanks for the information. I'm wondering if I also need to decrease the storage capacity of public transport? E.g. Now one bus can contain 100 passengers, but in a 10% scenario, I need to decrease its seats and standing capacity to 10 people.

For the remaining PCU and pcuThresholdForFlowCapacityEasing parameters, I have set them based on the suggestions. Thanks again for your help :)

**Comment by michalmac** [comment]
> Hi Michal, thanks for the information. I'm wondering if I also need to decrease the storage capacity of public transport? E.g. Now one bus can contain 100 passengers, but in a 10% scenario, I need to decrease its seats and standing capacity to 10 people.

Yes. Since the frequency remains the same, the size needs to be reduced.

**Comment by jingjunL** [comment]
> > Hi Michal, thanks for the information. I'm wondering if I also need to decrease the storage capacity of public transport? E.g. Now one bus can contain 100 passengers, but in a 10% scenario, I need to decrease its seats and standing capacity to 10 people.
> 
> Yes. Since the frequency remains the same, the size needs to be reduced.

Thank you! Have a nice weekend :)
