### ISSUE TITLE
Public Transport weird behaviour

### ISSUE THREAD

**Issue by ciolo** [matsim-org/matsim-code-examples#442]
Hi,
I ran a pt simulation with **pt** mode for each person (below an example of a plan)
<img width="972" alt="Screenshot 2020-10-08 at 19 30 36" src="https://user-images.githubusercontent.com/21953595/95493676-131b3e00-099d-11eb-9543-e52ef9502d06.png">
Simulation ends successfully, but when I check **output_plans** I notice something strange; no person plan has **pt** as leg mode and moreover the link value is always the same (below an example of a selected plan)
<img width="1176" alt="Screenshot 2020-10-08 at 19 31 07" src="https://user-images.githubusercontent.com/21953595/95494020-8d4bc280-099d-11eb-926f-98563d87fd58.png">

Someone can help me?
Thank u.

**Comment by vsp-gleich** [comment]
Your input plan has mode "transit_walk". This indicates the usage of an outdated matsim version. However, that should not cause the mode shift seen below. To understand what is happening please provide at least config, run class and matsim version. Relevant input files (plans, network, schedule, transitVehicles) can be helpful.

**Comment by ciolo** [comment]
Hi,
thank u for your response. I'm using jar MatSim v12, with **Controler** as run class. 
In this gist there are all relevant files: https://gist.github.com/ciolo/d92b942eb02dd8d05aa2387559225948
Can you show me an example of current/modern plan please?

Thank u in advance.

**Comment by vsp-gleich** [comment]
There is an issue with your coordinate reference systems. Activities have very different coordinates in respect to network and transit schedule. Check which coordinate reference systems you are using. Still that does not explain the mode shift. 

A single pt trip in recent model output (return trip and 2nd home activity are missing):


                        <activity type="home_51600.0" link="21031" x="4627743.102733562" y="5829552.661343944" end_time="09:12:04" >
                                <attributes>
                                        <attribute name="zoneId" class="java.lang.String">12064472</attribute>
                                </attributes>
                        </activity>
                        <leg mode="walk" dep_time="09:12:04" trav_time="00:16:32">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                                <route type="generic" start_link="21031" end_link="pt_42825" trav_time="00:16:32" distance="1046.4043917940255"></route>
                        </leg>
                        <activity type="pt interaction" link="pt_42825" x="4628104.442420426" y="5828833.3976725275" max_dur="00:00:00" >
                        </activity>
                        <leg mode="pt" dep_time="09:28:36" trav_time="00:32:18">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                                <route type="default_pt" start_link="pt_42825" end_link="pt_42817" trav_time="00:32:18" distance="21682.70888996706">{"transitRouteId":"S5---10157_109_12","boardingTime":"09:32:06","transitLineId":"S5---10157_109","accessFacilityId":"060320002001.2","egressFacilityId":"060176001002"}</route>
                        </leg>
                        <activity type="pt interaction" link="pt_42817" x="4609489.370724906" y="5821108.353804325" max_dur="00:00:00" >
                        </activity>
                        <leg mode="walk" dep_time="10:00:54" trav_time="00:01:54">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                                <route type="generic" start_link="pt_42817" end_link="pt_4427" trav_time="00:01:54" distance="121.10430194956534"></route>
                        </leg>
                        <activity type="pt interaction" link="pt_4427" x="4609580.353640592" y="5821088.344690264" max_dur="00:00:00" >
                        </activity>
                        <leg mode="pt" dep_time="10:02:48" trav_time="00:14:11">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                                <route type="default_pt" start_link="pt_4427" end_link="pt_4435" trav_time="00:14:11" distance="3024.754717728437">{"transitRouteId":"195---17348_700_5","boardingTime":"10:08:00","transitLineId":"195---17348_700","accessFacilityId":"070101005329","egressFacilityId":"070101005326"}</route>
                        </leg>
                        <activity type="pt interaction" link="pt_4435" x="4610211.330635572" y="5823766.321856056" max_dur="00:00:00" >
                        </activity>
                        <leg mode="walk" dep_time="10:17:00" trav_time="00:02:00">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                                <route type="generic" start_link="pt_4435" end_link="2460" trav_time="00:02:00" distance="125.75755242031117"></route>
                        </leg>
                        <activity type="work_21000.0" link="2460" x="4610117.732527201" y="5823741.880911222" end_time="15:28:58" >
                                <attributes>
                                        <attribute name="cemdapStopDuration_s" class="java.lang.Integer">21000</attribute>
                                        <attribute name="zoneId" class="java.lang.String">910020517</attribute>
                                </attributes>
                        </activity>

**Comment by ciolo** [comment]
I generated population file with python script. My original coords were in WGS84 and I transformed it with following statement:

`transformer = Transformer.from_crs("epsg:4326", "epsg:3003")` 

where `Transformer` is a `pyproj` object, while I used **pt2matsim** to  generate transitSchedule and network files setting in place _epsg:3003_ as coordinate system. Maybe isn't working this transformation. Is it possibile to leave population coords in latitude and longitude and set coordinate system conversion in config file? 
Thank u for plan example.

**Comment by vsp-gleich** [comment]
As far as I know all coordinates have to be in a projected coordinate reference system. So no lat/long. I can't say much about population file generation and coordinate transformations in python, we mostly use Java because matsim is written in Java.

**Comment by vsp-gleich** [comment]
I just tried to run your config file like you did in Controler (we usually write custom run classes due to using custom contribs and other additions). It gave me lots of file not found exceptions, e.g. Error in custom provider, org.matsim.core.utils.io.UncheckedIOException: java.io.FileNotFoundException: d92b942eb02dd8d05aa2387559225948-eddab8f20709f6eb0933758129e4b5708bee5c96/mappedNetwork.xml
The TransitVehicles file is also missing.
By the way, how did you download matsim 12? Did you download the source code or release zip [here](https://github.com/matsim-org/matsim-libs/releases/tag/matsim-12.0) or do you use maven?

**Comment by vsp-gleich** [comment]
The input population file is also weird in that it has access and egress to pt legs with "transit_walk", but it lacks any route. Usually you would either have a single unrouted pt leg or a fully routed plan.

**Comment by ciolo** [comment]
Hello,
Thank you. I forgot to add the transitVehicle file. Yes, I downloaded the zip file for the first tests, while now I'm using it with maven. I found that transforming the coordinates while generating the population file was returning incorrect results. After correcting it and editing the plan file using a single unrouted pt leg it seems that the simulation result conforms to a correct output.
Thanks again

**Comment by vsp-gleich** [comment]
So is it working now, that means is the initial issue of pt users switching to car not occurring any longer?

**Comment by ciolo** [comment]
Yep, that is someone switch to car while other not (I think this is normal, right?). The simulation fill plan with **pt interaction** activities, **walk** leg mode, **routingMode** attributes and **route** in legs.

**Comment by vsp-gleich** [comment]
In your config you enabled ChangeTripMode with modes car and pt, so yes, it should (randomly) select some agents and move them to car starting in iteration 1.
Great to hear it's working and no bug around :-)
