### ISSUE TITLE
Inquires for the actual meanings of several fields in the "output" folder of the "equil" scenario

### ISSUE THREAD

**Issue by yangxiong11** [matsim-org/matsim-code-examples#445]
Hello,

When I review the output results of the "equil" scenario, I found multiple fields are hard to understand. 

Fields **"car_wait"**, **"stageActivity_travle"** and **"stageActivity_wait"** in the **"ph_modestats.txt"** file. The values of these fields are zero.

Field **"car_wait"** in the **"output_trips.csv.gz"** file. The values of this field are zero.

Would you please explain the actual meanings of these fields for me? Many Thanks.

**Comment by vsp-gleich** [comment]
All modes are handled the same way, so there is a _mode_ _wait field for each mode no matter whether that actually makes sense. That has the advantage that you as a user don't have to specify which modes can have a wait time and which not.
The same applies for stageActivities which for simplicity we handle like another mode in those statistics. Stage activities are the short, i.e. usually 0s or 1s duration, activities for changing modes to keep the leg-activity-leg-... structure. So stageActivity_travel can have a value different from zero and stageActivity_wait and car_wait shall always be zero.
