### ISSUE TITLE
Some questions about the parameters in link stats file 

### ISSUE THREAD

**Issue by hsyfyc** [matsim-org/matsim-code-examples#454]
Hi,
I'm new to use matsim. I wonder what is the HRS in Link Stats file short for? And why there are three similar parameters (HRS-min,HRS-ave,HRS-max) per hour?  What are their relationship and differences?
Thank you in advance.

**Comment by helgehr** [comment]
Hello, as written [here](https://sourceforge.net/p/matsim/mailman/matsim-users/thread/AC0DACB1-392F-4FA0-B231-DD926814ACF0@senozon.com/)

> [...] The information is accumulated over a number of iterations, which explains the minimum, average and maximum values. HRS is indeed a bad label for the columns, it is actually the hourly traffic volumes observed on each link, while the TRAVELTIMES are the observed travel times during the time windows.

the different HRS parameters correspond to the hourly traffic volumes per link averaged (or min/max taken respectively) over different iterations.

**Comment by hsyfyc** [comment]
thanks for your reply
