### ISSUE TITLE
using subpopulations

### ISSUE THREAD

**Issue by fredshone** [matsim-org/matsim-code-examples#47]
Hello, two related questions about using sub-populations:
1) Is it possible to reference multiple plans inputs at setup and declare sub-population in setup? I came across such an issue marked as resolved but can find no docs. Upon more careful reading this is effectively confirmed as not possible [here](https://matsim.atlassian.net/browse/MATSIM-151)
2) I see that the planning module can make use of sub-populations, can the scoring module do similarly?

Appologies if i am overlooking some obvious resource, I have read carefully around the subject but still wondering/hopeful. Happy to be pointed at some docs. Many thanks.

**Comment by mrieser** [comment]
Regarding 1: Sub-populations are possible, but they all have to be merged into one population/plans-file that is specified as input. It is not possible to specify multiple plans as input file, but all sub-populations must be merged into one file that is used as input.

Regarding 2: The scoring-configuration in module `planCalcScore` has support for multiple `scoringParameters`-parametersets, and each can refer to a specific sub-population. For an example, see https://github.com/matsim-org/matsim/blob/941b360d952a3d4671eb9d419a76f392ab60edd5/examples/scenarios/equil-extended/config-with-subpopulation.xml#L49.

**Comment by fredshone** [comment]
Many thanks
