### ISSUE TITLE
NetworkChangeEvents called in EventHandler?

### ISSUE THREAD

**Issue by CLIVTI** [matsim-org/matsim-code-examples#470]
Hi, we have a project that we need to simulate route choice of freight trains in railway network, that is to say, using QSIM for car to find an equilbrium where trains act like cars. There then comes to a question to simulate single track. So once there is a train entering a given link X from node A to node B, the link Y on the opposite direction (from node B to node A) is blocked, or in other words, during the time this train is on link X, link Y has 0 capacity and therefore all vehicles that are going to enter link Y need to wait on the uppstream links until the train leavs link X.

So far i have tried to use the following way to model this problem:

1. bind my own eventhandler SingleTrackLinkEventHandler, see below:

		controler.addOverridingModule(new AbstractModule(){
			@Override public void install() {
				this.addEventHandlerBinding().toInstance( new SingleTrackLinkEventHandler( scenario.getNetwork() )  );
			}
		});

2.  SingleTrackLinkEventHandler then implements LinkEnterEventHandler, LinkLeaveEventHandler, VehicleEntersTrafficEventHandler, VehicleLeavesTrafficEventHandler and in each of the handleEvent method the networkChangeEvent is called using the following code: NetworkUtils.addNetworkChangeEvent(network,networkChangeEvent);

However, this does not seem to work. I realized that the injected eventHandler.handleEvent method is not called each time when an event is created during an iteration but is called after all events are created after one iteration is done. therefore networkChangeEvents will not influence the simulation of this iteration.

I therefore wonder what is the best way to depent networkChangeEvent on the LinkEnterEvent/LinkLeaveEvent?

Thanks a lot for your help.

best
chengxi

**Comment by CLIVTI** [comment]
Hi, I have found a very relevant example SimpleAdaptiveSignal. I think the logic there can be used for my purpose there as well. Thanks.

**Comment by mrieser** [comment]
> However, this does not seem to work. I realized that the injected eventHandler.handleEvent method is not called each time when an event is created during an iteration but is called after all events are created after one iteration is done.

Events are processed in their own threads, apart from QSim, and thus may lag behind the QSim in time. In such cases where events should be processed in the same time step as the QSim, you could enable this in the config with:

```xml
<module name="parallelEventHandling">
  <param name="synchronizeOnSimSteps" value="true" />
</module>
```
