### ISSUE TITLE
Run MATSim on Remote Compute Engine With Pom Errors

### ISSUE THREAD

**Issue by CianGraham** [matsim-org/matsim-code-examples#475]
Hi Everyone,

I tried to run MATSimon on our supercomputer cluster. To do so I guess I need to build a jar file.

I am now trying to run the example project (equil folder) for a test. I firstly entered "mvn clean" in the terminal of Intellij, and I got errors below:
![image](https://user-images.githubusercontent.com/67740217/99248966-9f751800-2809-11eb-87fb-5b45706ccfe7.png)

Seems like there is something wrong with my pom file. I'm wondering if you know how to solve this issue? Thanks for your help!

**Comment by mrieser** [comment]
**please don't post images of error messages. They are hard to read, they are not searchable, and thus other people with a similar problem likely won't find it, so it's also a waste of time for many people. Just copy and paste the text.**

Yes, there seems to be something wrong with your pom.xml. The error message states: `'repositories.repository.id' must be unique: ojo-snapshots`. You seem to have two repositories defined in your pom.xml, both with the same name (and only differing with `http://` vs `https://`, as clearly visible from the message). Just delete one, I suggest the `http://` one.
