### ISSUE TITLE
Any Alternative to fixed number of interations?

### ISSUE THREAD

**Issue by alexdawn** [matsim-org/matsim-code-examples#48]
Thanks for all your quick answers on previous questions.

I've been running through all the documentation I can find trying to get an overview of what Matsim can do. Having run some example models, I've noticed these all these have a set number of iterations:

Is it possible to set alternative stopping criteria? Similar to the convergence criteria required by UK standards [WebTAG Table 4](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/427124/webtag-tag-unit-m3-1-highway-assignment-modelling.pdf)  

Looking at the API for the controller it suggests there is not. If there is a fixed number of iterations then what does the config option `firstIteration` do?

**Comment by mrieser** [comment]
Indeed, MATSim currently only supports a fixed number of iterations.
Alternative stopping criteria could be implemented in code, but are currently not available out of the box.

The `firstIteration` specifies with which iteration MATSim should start. It is mostly used to resume runs that were interrupted for some reasons. As the random number generator used by MATSim is initialized with the iteration number as part of the seed, this allows to exactly resume a run.

**Comment by kainagel** [comment]
If you want to code in Java, there is a `TerminationCriterion` interface, which can be set at `Controler`.  An example is in the `ControlerIT` class under method `testTerminationCriterion()`.

**Comment by alexdawn** [comment]
Thanks for the clarification, I don't think I will have the opportunity to look at coding up a custom controller in the near future, but glad to know if we get clients wanting a WebTAG model it should be possible to make something.
