### ISSUE TITLE
error in running DRT module

### ISSUE THREAD

**Issue by Sharmeela16** [matsim-org/matsim-code-examples#49]
i am trying to run DRT module as mentioned on site:

> package com.runcottbusdrt;
> 
> import org.matsim.contrib.av.robotaxi.fares.drt.DrtFareModule;
> import org.matsim.contrib.av.robotaxi.fares.drt.DrtFaresConfigGroup;
> import org.matsim.contrib.drt.run.DrtConfigGroup;
> import org.matsim.contrib.drt.run.DrtControlerCreator;
> import org.matsim.contrib.dvrp.run.DvrpConfigGroup;
> import org.matsim.core.config.Config;
> import org.matsim.core.config.ConfigUtils;
> import org.matsim.core.controler.Controler;
> import org.matsim.vis.otfvis.OTFVisConfigGroup;
> 
> public class rundoortodoordrt {
> 
>     private static final String COTTBUS_DOOR2DOOR_CONFIG = "H:\\matsim-0.10.1\\dvrp-0.10.1\\cottbus\\drtconfig_door2door.xml";
> 
> 	@SuppressWarnings("unused")
>     private static final String MIELEC_CONFIG = "H:\\matsim-0.10.1\\dvrp-0.10.1\\mielec_2014_02\\mielec_drt_config.xml";
> 
> 	public static void run(Config config, boolean otfvis) {
> 		//Creates a MATSim Controler and preloads all DRT related packages
> 		Controler controler = DrtControlerCreator.createControler(config, otfvis);
> 
> 		//this is optional, adds fares to DRT
> 		controler.addOverridingModule(new DrtFareModule());
> 
> 		//starts the simulation
> 		controler.run();
> 	}
> 
i am getting this error - 
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	Implicit super constructor ConfigGroup() is undefined for default constructor. Must define an explicit constructor
	at com.runcottbusdrt.DrtFaresConfigGroup.<init>(DrtFaresConfigGroup.java:5)
	at com.runcottbusdrt.rundoortodoordrt.main(rundoortodoordrt.java:41)

how do i solve this please help?

**Comment by jfbischoff** [comment]
Hi,
do you, by chance, mix two versions of MATSim (e.g., the 0.10.1 release and the 0.11.0-Snapshot)?
For a good starting point, I'd recommend to check out  the MATSIM-maas repository:
https://github.com/matsim-org/matsim-maas/
and add it as a maven project to the IDE of your choice.
This ensures you are using the right versions of everything.

**Comment by Sharmeela16** [comment]
I am using the same version and working with  examples from MATSIM-maas repository as suggested and I am getting error as
1. ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider apple.applescript.AppleScriptEngineFactory not found
2. Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	DrtFaresConfigGroup cannot be resolved to a type
	at org.matsim.maas.drt.RunDoorToDoorDrtExample.main(RunDoorToDoorDrtExample.java:35)
how can solve this?
![picture2](https://user-images.githubusercontent.com/43937551/49950397-b922cc00-ff1d-11e8-8a3e-6800937b8fd8.jpg)
![picture1](https://user-images.githubusercontent.com/43937551/49950398-b9bb6280-ff1d-11e8-9cd3-161c582d25f3.jpg)

**Comment by jfbischoff** [comment]
Please try to use Maven in your project, otherwise some dependencies will not resolve or you end up mixing different versions. 
http://www.vogella.com/tutorials/EclipseMaven/article.html

**Comment by Sharmeela16** [comment]
one more query I am working on DRT project which is located in India so I  have to add coordinate reference system of India which is WGS198 UTM 43N which is missing in existing file how can is  add that. I tried making changes to existing files in "\org\matsim\core\utils\geometry - MGC.java and TransformationFactory.java its not working. how do I do that?

**Comment by jfbischoff** [comment]
You can simply add it via the EPSG code as a String.
"EPSG:xxxxx"
