### ISSUE TITLE
Converting XLS to XML for MATSIM

### ISSUE THREAD

**Issue by zdarovakoresh** [matsim-org/matsim-code-examples#498]
Hello! I prefer using Excel for creating and modifying data, but MATSim input format is XML. Could you advice me a way of converting XLS table to XML file formatted in a way compatible with MATSim? As I do not have a programming experience any solutions that have online tutorials that I can follow are appreciated.

It seems for me that somebody has definitely done this previously, but I did not find any example.

To be more specific, my aim is to convert rows of `population` file to the following `xml` structure.

[population.xlsx](https://github.com/matsim-org/matsim-code-examples/files/5698904/population.xlsx)

```
	<person id="6510_1" employed="no">
		<plan selected="yes">
			<act type="home" x="686386.7981000002" y="4824847.9253" end_time="08:00:01" />
			<leg mode="car">
			</leg>
			<act type="work" x="684264.4409999996" y="4824161.496099999" end_time="16:00:01" />
			<leg mode="car">
			</leg>
			<act type="home" x="686386.7981000002" y="4824847.9253" />
		</plan>

	</person>
```

**Comment by mrieser** [comment]
you could try to write a formula that combines your data with the necessary XML-tags, and then just copy/paste that column into a text file and save it with a `.xml` ending.

The formula could start like this:

```
="<person id=""" & O2 & """ employed=""" & P2 & """>"
```
(`"..."` is used for text fragments, `""` inside a text fragment results in a `"` in the text, `&` concatenates multiple text fragments)

**Comment by zdarovakoresh** [comment]
Thank you for a suggestion.

I found a workaround. I created an easy xls to xml python converter that basically creates a template with tags, and then searches through these tags and assign them a value from xls file based on occurrence sequential number of a tag.

**Comment by aayushtewari01** [comment]
@zdarovakoresh can you please share the xls to xml code that you wrote on python. I too am working on converting OD trip data to MATSim compatibe using Python. But not that satisfied. My file looks like as below.
Thanks
[tripdata_200_df.csv](https://github.com/matsim-org/matsim-code-examples/files/7828076/tripdata_200_df.csv)
