### ISSUE TITLE
Parsing emissions events

### ISSUE THREAD

**Issue by JWJoubert** [matsim-org/matsim-code-examples#502]
This question may have an easy answer, but I cannot quite get a working (elegant) solution.

When running the `emissions` contrib, in my case the online mode (but I would argue offline will have the same result), there are two new events in the `output_events.xml.gz` file, namely `ColdEmissionEvents` and `WarmEmissionEvents`. This is as expected.

But when I now _parse_ the same events file with the `MatsimEventsReader`, these two emissions events are parsed as `GenericEvents` but since both `ColdEmissionEvent` and `GenericEvent` inherits directly from `Event`, it is not possible to simply cast the `Event` in the `processEvent(...)` method of the `EventManager` to the required cold/warm emission type.

The pollutants are read as attributes of the `GenericEvent` which mean there is no clean way to get (only) the pollutants in a nice `Map<Pollutant, Double>` using the event's `getColdEmissions()`.

Am I doing something wrong? Is there a different events reader that I should use? It seems the default uses `events_v1-reader`

**Comment by JWJoubert** [comment]
Hm, it seems one needs to implement a `CustomEventMapper` to convert the `GenericEvent`. I am looking through the code of the `emissions` contrib, thinking that there might already be one implemented, but that does not seem to be the case.

**Comment by amit2011** [comment]
If I remember correctly, there used to be an `EmissionEventsReader` in the `emission` contrib. This might still be there.

**Comment by JWJoubert** [comment]
Thanks, @amit2011, for some reason I missed it. But, for what it's worth, now I know that the `CustomEventMapper` works as well :D
