### ISSUE TITLE
DRT fare

### ISSUE THREAD

**Issue by elyh1992** [matsim-org/matsim-code-examples#503]
Hi,

From my understanding, if we want to have two different levels of fare for pooled and unpooled drt rides we need to introduce two different kinds of drt service which one allows for sharing and the other one does not allow for sharing and define different price for each of them in drt fare module. However, in this case, people that use the service that allows for sharing would pay less anyway even if there aren't any plausible match rides available for them and their rides end up being solo.
I was wondering if there is a way to define cost based on the number of riders in the service in a way that people pay less if they actually end up using pooled service. Like having only one drt service that considers all the requests for a possible match, then if the match is successful people pay less, and if not they pay the regular fare.
Thank you in advance for your help.

**Comment by michalmac** [comment]
The default `DrtFareHandler` is generic, but also limited. Since fares can be really complex and differ from case to case, we are not planning to cover each possible case. So you need to modify `DrtFareHandler` or (preferably) replace it with your own handler.
