### ISSUE TITLE
Displaying a job position (postdoc on matsim)

### ISSUE THREAD

**Issue by mkilani-dev** [matsim-org/matsim-code-examples#508]
I have submitted a call for a postdoc position (using github) but do not yet find it in the MATSIM page.
I am wondering whether it is waiting for approval or did I missed a step. Can you please check. Thanks.

**Comment by jfbischoff** [comment]
It seems no one has reacted on the pull-request. Sorry for that,  I just merged it :)

**Comment by billyc** [comment]
@jfbischoff  -- thank you Joschka! The text wasn't in the proper post format (was missing the required headers) but I've fixed it and published it. 

@mkilani-dev  -- also our automated website build process seems to be broken! We are on it and your post will show up as soon as we can fix that build.
