### ISSUE TITLE
How to generate large travel demand sample from small sample in Matsim?

### ISSUE THREAD

**Issue by Sharmeela16** [matsim-org/matsim-code-examples#51]

**Comment by kainagel** [comment]
There is no quick answer.  

What we have done in the past is to "clone" agents, i.e. to copy agents and randomly modify each activity's coordinate by something, and each activity's endtime/duration by something.  Blowing up a population in this way by a factor of 10 seems "ok" in our experience, although someone with a statistical training will surely disagree.  (You essentially get too many trips on those OD relations that you have in the original data, and not enough on all other OD relations.)

The "clean" way is much harder: Use the data you have to estimate a model against it.  For that, you have to go to the activity based modelling community.

A compromise is what we have done for our open Berlin model (https://github.com/matsim-vsp/matsim-berlin).  It is a multi-step procedure.  See https://svn.vsp.tu-berlin.de/repos/public-svn/publications/vspwp/2019/19-01/ for details.  It is also not yet packaged in a way that it is easy to use, albeit we are working in that direction.

In general, if the cloning is not good enough, at this point we recommend finding someone who has the necessary expertise.  Sorry .....
