### ISSUE TITLE
Error on running matsim-berlin example in linux server !

### ISSUE THREAD

**Issue by mankar97** [matsim-org/matsim-code-examples#514]
I'm trying to run the matsim-berlin-5.5.1.jar in a remote linux server 
with the basic berlin-v5.5-1pct.config.xml (config file) , as shown in 
https://svn.vsp.tu-berlin.de/repos/public-svn/publications/vspwp/2014/14-20/user-guide-0.6.0-2014-09-12.pdf 
with the command :
java -Xmx8192m -cp matsim-berlin-5.5.1.jar org.matsim.run.Controler berlin-v5.5-1pct.config.xml
The error I am getting is : 
...
INFO VspConfigConsistencyCheckerImpl:73 running checkConsistency ...
WARN VspConfigConsistencyCheckerImpl:100 you are not using FastAStarLandmarks as routing algorithm.  vsp default is to use FastAStarLandmarks.
WARN VspConfigConsistencyCheckerImpl:201 You are not setting fractionOfIterationsToStartScoreMSA; vsp default is to set this to something like 0.8.  This means you have to add the following lines to your config file:
VspConfigConsistencyCheckerImpl:203 <module name="planCalcScore">
VspConfigConsistencyCheckerImpl:204       <param name="fractionOfIterationsToStartScoreMSA" value="0.8" />
WARN VspConfigConsistencyCheckerImpl:205 </module>
 WARN VspConfigConsistencyCheckerImpl:247 found `PlansCalcRouteConfigGroup.AccessEgressType.none'; vsp should use `accessEgressModeToLink' or some other value or talk to Kai.
WARN VspConfigConsistencyCheckerImpl:254 found qsim.usePersonIdForMissingVehicleId==true; this is only for backwards compatibility and should rather be set to false
WARN VspConfigConsistencyCheckerImpl:259 found `qsim.usingTravelTimeCheckInTeleporation==false'; vsp should try out `true' and report.
FATAL VspConfigConsistencyCheckerImpl:371 found a situation that leads to vsp-abort.  aborting ...
Exception in thread "main" java.lang.RuntimeException: found a situation that leads to vsp-abort.  aborting ...
        at org.matsim.core.config.consistency.VspConfigConsistencyCheckerImpl.checkConsistency(VspConfigConsistencyCheckerImpl.java:372)
        at org.matsim.core.config.Config.checkConsistency(Config.java:211)
        at org.matsim.core.controler.Controler.run(Controler.java:230)
        at org.matsim.run.Controler.run(Controler.java:54)
        at org.matsim.run.Controler.main(Controler.java:58)

**Comment by mrieser** [comment]
I think the Berlin-scenario requires a different main-class to start: `org.matsim.run.RunBerlinScenario` instead of `org.matsim.run.Controler`. Try running:

```sh
java -Xmx8192m -cp matsim-berlin-5.5.1.jar org.matsim.run.RunBerlinScenario berlin-v5.5-1pct.config.xml
```

**Comment by mankar97** [comment]
@mrieser Thank you for your fast answer ! Yes that command worked for me !
