### ISSUE TITLE
tools to extract pt lines from osm?

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-code-examples#52]
Dear MATSim pt experts,

Could you please (1) point me to tools that extract pt lines from OpenStreetMap, and (2) report experiences with those (if available)?  

Thanks ...

**Comment by mrieser** [comment]
not sure what exactly you look for... But i had good experience with https://github.com/matsim-org/pt2matsim for automatically mapping pt lines (from GTFS or HAFAS) to an osm-derived network. It likely does not produce a perfect result, but one that, in visualizations, looks good enough -- at least much better and realistic than having the pt vehicles drive in straight lines across buildings and lakes.
As mentioned, pt2matsim also requires GTFS or HAFAS data. If you wan't to extract lines only based on OSM, without other data, it might be a good start to look at the data it extracts from OSM to do the later matching.

Does it have to be in a MATSim context, or are you interested in PT lines in general?
If in general, one might try to come up with a query for the overpass-api to extract pt lines as json.

**Comment by kainagel** [comment]
Thanks.  No, I am looking at a situation where we don't have GTFS or similar (Joinville in Brazil, to be precise).

On 17. Dec 2018, at 13:08, mrieser <notifications@github.com<mailto:notifications@github.com>> wrote:


not sure what exactly you look for... But i had good experience with https://github.com/matsim-org/pt2matsim for automatically mapping pt lines (from GTFS or HAFAS) to an osm-derived network. It likely does not produce a perfect result, but one that, in visualizations, looks good enough -- at least much better and realistic than having the pt vehicles drive in straight lines across buildings and lakes.
As mentioned, pt2matsim also requires GTFS or HAFAS data. If you wan't to extract lines only based on OSM, without other data, it might be a good start to look at the data it extracts from OSM to do the later matching.

Does it have to be in a MATSim context, or are you interested in PT lines in general?
If in general, one might try to come up with a query for the overpass-api to extract pt lines as json.

**Comment by jfbischoff** [comment]
>Thanks.  No, I am looking at a situation where we don't have GTFS or similar (Joinville in Brazil, to be precise).

The MATSim JOSM plugin can do that and it doesn't look too bad :) , maybe @nkuehnel and @michaz 

In most other cases, pt2matsim is indeed the way to go.

**Comment by mrieser** [comment]
Looks like Joinville has PT data: http://öpnvkarte.de/#-48.8522;-26.283;13
At least that's a first visual clue if it's worth trying to try to extract data from OSM.

**Comment by nkuehnel** [comment]
> > Thanks.  No, I am looking at a situation where we don't have GTFS or similar (Joinville in Brazil, to be precise).
> 
> The MATSim JOSM plugin can do that and it doesn't look too bad :) , maybe @nkuehnel and @michaz
> 
> In most other cases, pt2matsim is indeed the way to go.

Yes, lines can be converted to MATSim in the plugin if the public transport is tagged according to the recommended tagging scheme. It's possible to extract pseudo network (direct links between stops) or the full route. However, in my experience you will often have to correct some/many of the eixsting tags.

**Comment by kainagel** [comment]
Joschka tried with JOSM, returned a couple of stops and lines, but no route links in between.

I tried with `TransitNetworkSink`, by @michaz , which returns roughly the same stops, but actually some route links in between.  One has to add departures manually, but that is kind of obvious since OSM does not have that info.  Afterwards, I end up having a handful of lines.

For whatever reason, both of these approaches miss a large majority of bus stops.  Since the maps are able to render them, this feels like a fixable thing.  But I don't know enough about OSM parsing to make this happen.
