### ISSUE TITLE
Fallback Mode for DRT

### ISSUE THREAD

**Issue by helgehr** [matsim-org/matsim-code-examples#524]
Dear MATSim Community,

I am trying to implement a fallback mode for people using DRT so that as soon as they get rejected they will try to get to their destination with their own car. I did not find a simple a way to get this behaviour therefore I tried to implement a `PassengerRequestRejectedEventHandler` with the following structure (`agents` is a map from Person IDs to mobsim agents)
```java
@Override
    public void handleEvent(PassengerRequestRejectedEvent event) {
        Id<Person> personId = Id.createPersonId(event.getAttributes().get("person"));
        MobsimAgent mobsimAgent = agents.get(personId);
        Plan modifiablePlan = WithinDayAgentUtils.getModifiablePlan(mobsimAgent);

        //...mess with the plan (delete "future plan" from current drt leg to destination and
        //add walk/car leg to destination instead)

        mobsimAgent.endActivityAndComputeNextState(event.getTime());
        WithinDayAgentUtils.resetCaches(mobsimAgent);
    }
```
However, this does not really alter the agents plans somehow.
Could you tell me what is wrong with the approach above and whether there exist other solutions for my problem?

**Comment by michalmac** [comment]
I think there is no straightforward/out-of-box solution for that. We are aiming to provide some sort of prebooking functionality, where agent could adapt their plans based on the service availability etc. 

Not sure if that makes sense in your case, but maybe you could consider request retrying (e.g. unscheduled requests will be reattempted after a fixed time) or turning off rejections completely.

**Comment by helgehr** [comment]
Alright, thanks for the response. With prebooking functionality you mean that agents can order a drt vehicle for a specific time in the future instead of filing a request at the time when they actually want to be picked up and start to wait?

**Comment by michalmac** [comment]
Yes, but that is only one part of the whole idea. The other is that arranging things ahead of time gives you an option to make some choices (e.g. choosing between taking this DRT service or maybe another or taxi or...).

I think preplanning (as a name) is more accurate here than prebooking.

**Comment by helgehr** [comment]
That sounds like a interesting Idea, looking forward to that feature.
