### ISSUE TITLE
Reasons an agent would be logged with "stuckAndAbort"

### ISSUE THREAD

**Issue by josiekre** [matsim-org/matsim-code-examples#526]
I am having a hard time finding detailed documentation about `stuckAndAbort` events. If this documentation exists somewhere, please close this issue with a link to the details.

What are all the reasons an agent would be logged with `stuckAndAbort`?

I understand that persons who are en route at the stop time of the simulation are logged with a `stuckAndAbort`. However, today I ran into for the first time a person logged who was not en route but had arrived at an `Other` location about 100 minutes before the end of the simulation. The events file is written as line-delimited json instead of xml in my case, but otherwise the content is the same as one would find in the default MATSim events file. I used `zgrep` to grab all lines related to the one agent, and am showing the final handful. I did verify that this person ID is only in the population file once.

```
...
{"time":"94735.0","type":"entered link","vehicle":"39049001901_2017001328274_346483_2","link":"905759108_F"} 
{"time":"94738.0","type":"left link","vehicle":"39049001901_2017001328274_346483_2","link":"905759108_F"} 
{"time":"94738.0","type":"entered link","vehicle":"39049001901_2017001328274_346483_2","link":"877791831_R"} 
{"time":"94764.0","type":"left link","vehicle":"39049001901_2017001328274_346483_2","link":"877791831_R"}
{"time":"94764.0","type":"entered link","vehicle":"39049001901_2017001328274_346483_2","link":"877791831_F"} 
{"time":"94789.0","type":"vehicle leaves traffic","person":"39049001901_2017001328274_346483_2","link":"877791831_F","vehicle":"39049001901_2017001328274_346483_2","networkMode":"car","relativePosition":"1.0"}
{"time":"94789.0","type":"PersonLeavesVehicle","person":"39049001901_2017001328274_346483_2","vehicle":"39049001901_2017001328274_346483_2"}
{"time":"94789.0","type":"arrival","person":"39049001901_2017001328274_346483_2","link":"877791831_F","legMode":"car"} 
{"time":"94789.0","type":"actstart","person":"39049001901_2017001328274_346483_2","link":"877791831_F","facility":"F390490011221040","actType":"Other"}
{"time":"100800.0","type":"stuckAndAbort","person":"39049001901_2017001328274_346483_2"}
```

**Comment by mrieser** [comment]
Any agent not yet at their last activity according to their plan will be receive a `stuckAndAbort` event at the end of the simulation. So if the agent had planned to go somewhere else after that `Other` activity, she/he will also be marked as `stuck` as she/he was no able to finish they day plan. It could also happen when some agents wait at a bus stop, but no more suitable buses come to pick them up. Then these agents will just wait at the bus stop until the simulation ends and they will be marked as being stuck as well.

**Comment by josiekre** [comment]
Okay I see. I was thinking the person had to be en route between places (either via car or bus or whatever mode). Now I get that the measure is against their planned day instead. Thanks!
