### ISSUE TITLE
ev extension charging infrastructure generation

### ISSUE THREAD

**Issue by mattjweist** [matsim-org/matsim-code-examples#529]
Hello,

I am attempting to produce a chargers.xml file which contains all charging stations in Germany of a minimum charging power and specific plug type. 

Is there an ev extension file (like "RunPNetworkGenerator.java" from matsim-code-examples) that will produce a chargers.xml file given geographical bounds?

I also tried a workaround method using an API with map.openchargemap.io. I was able to create an xml file with x,y coordinates for each charging station, but chargers.xml requires **links**, not coordinates. Is there a matsim file that finds the nearest link for each x,y coordinate pair?

Many thanks,
Matt

**Comment by jfbischoff** [comment]
Hi,
if you have the xy-Coordinates, creating chargers is really easy:
https://github.com/matsim-vsp/ers/blob/master/src/main/java/org/matsim/vsp/ers/bev/testscenario/GenerateChargersFromGasStations.java

Here is an example.

To get the nearest link to coordinate, you can use

            Link l = NetworkUtils.getNearestLink(network, coordinate);

Keep in mind the network should only consist of car links (or filter it beforehand, as in the example above).
