### ISSUE TITLE
AV and parking 

### ISSUE THREAD

**Issue by Hamadneh** [matsim-org/matsim-code-examples#53]
Hi, I would like to include parking utility in my project (I wanna assume certain number of space in each link and let AV park for vacant space when it becomes idle)?

**Comment by jfbischoff** [comment]
As a starting point, you can have a look for a similar implementation here:
https://github.com/matsim-vsp/vsp-playgrounds/tree/master/jbischoff/src/main/java/playground/jbischoff/avparking

The outcomes are described in this paper:
https://ieeexplore.ieee.org/document/8510918

J. Bischoff, M. Maciejewski, T. Schlenther and K. Nagel, "Autonomous Vehicles and Their Impact on Parking Search," in IEEE Intelligent Transportation Systems Magazine.
doi: 10.1109/MITS.2018.2876566

**Comment by Hamadneh** [comment]
Another question is how can I say there are travelers who ordered a car before certain time more than acceptable waiting time (pre-planned trip maybe from one day ago)? AV will serve them first!? and where are the first location of AV? do I need to assign them to legs?

**Comment by jfbischoff** [comment]
I would suggest you start from the starting points mentioned above. 
Pre-Bookings are currently not supported by any of the algorithms and would require quite a bit of coding.
