### ISSUE TITLE
Simunto VIA XML Parsing Error

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-code-examples#533]
Hello all,
I am facing a strange error when visualizing MATSim results in VIA. 
When I try to load the files, it stops parsing after sometime (see attached). also, transit schedule --> Export Traveler Statistics or Export Transit Transfer is not exporting the required csv. Any guess what is happening? 
Thank you for all the help. 
![Via Parsing Error](https://user-images.githubusercontent.com/56562366/109429769-a811e880-79cb-11eb-836d-4f359823a072.jpg)

**Comment by vsgo222** [comment]
> 
> 
> Hello all,
> I am facing a strange error when visualizing MATSim results in VIA.
> When I try to load the files, it stops parsing after sometime (see attached). also, transit schedule --> Export Traveler Statistics or Export Transit Transfer is not exporting the required csv. Any guess what is happening?
> Thank you for all the help.
> ![Via Parsing Error](https://user-images.githubusercontent.com/56562366/109429769-a811e880-79cb-11eb-836d-4f359823a072.jpg)

@mrieser 
Dr.Rieser, I also changed the memory allotted to VIA using VIA.INI file. I set it to 60GB since the event file is around 15GBs. Still get the same error. 
I can use the Export to Shapefiles functionality but unable to dissect how to use these shape-files to generate stats related to boarding, alighting and agentIDs at the stop-levels.

**Comment by mrieser** [comment]
@vsgo222: Can you please send me Via's logfile by email? Just from the screenshot it's not clear what causes the error.

You find the location of the log file and the email address to send it to by selecting the menu `Help > Report Bug/Feedback` in Via.

**Comment by vsgo222** [comment]
> 
> 
> @vsgo222: Can you please send me Via's logfile by email? Just from the screenshot it's not clear what causes the error.
> 
> You find the location of the log file and the email address to send it to by selecting the menu `Help > Report Bug/Feedback` in Via.
@mrieser , attached the file. 
[logfile.zip](https://github.com/matsim-org/matsim-code-examples/files/6057808/logfile.zip)

**Comment by vsgo222** [comment]
[logfile.zip](https://github.com/matsim-org/matsim-code-examples/files/6057826/logfile.zip)
> 
> 
> > @vsgo222: Can you please send me Via's logfile by email? Just from the screenshot it's not clear what causes the error.
> > You find the location of the log file and the email address to send it to by selecting the menu `Help > Report Bug/Feedback` in Via.
> > @mrieser , attached the file.
> > [logfile.zip](https://github.com/matsim-org/matsim-code-examples/files/6057808/logfile.zip)

Just to add on. The error is shown in one case scenario. For other cases (see other log file attached), it simply wont export the csv's. If you could hint me on how DEP_XX, ENTER_XX and EXIT_XX and PAX_XX at StopFacilities and TransitRoutes are related. I might end up writing a python code to get what I want.
