### ISSUE TITLE
BrainExpBeta in planCalcScore

### ISSUE THREAD

**Issue by SarahSie** [matsim-org/matsim-code-examples#537]
Hello,

It would be great if someone can explain what the strategy `BrainExpBeta` in practice means?
I have read the MATSim book, `BestScore` is clear; it is when the plan with the highest score will be chosen.
However, what does it mean `BrainExpBeta`, which perform MNL selection?
Could you please provide me with one real example?
And which one I should choose when I want to work with public transport?

Thanks

**Comment by mrieser** [comment]
`BrainExpBeta` is not a strategy, but a parameter used in the `SelectExpBeta`strategy. It is suggested to keep it at `1.0`.

Example:
Having 3 plans, each plan having a score. For each plan, a probability of being chosen is calculated based on formula 49.2 from the MATSim book. Then, one of the plan is chosen based on their probabilities.

Example with numbers:
- Having 3 plans with scores s1 = 45, s2 = 47, s3 = 50.
- the calculated probabilities are then (assuming beta = 1.0):
  - p1 = e^(beta\*s1) / (e^(beta\*s1) + e^(beta\*s2) + e^(beta\*s3)) = 0.00638
  - p2 = e^(beta\*s2) / (e^(beta\*s1) + e^(beta\*s2) + e^(beta\*s3)) = 0.04712
  - p3 = e^(beta\*s3) / (e^(beta\*s1) + e^(beta\*s2) + e^(beta\*s3)) = 0.9465
- note that p1 + p2 + p3 = 1.0
- now we can choose a random number `r` between 0.0 and 1.0, and based on that number choose a plan (`r < p1 --> use plan 1, r < p1+p2 --> use plan 2, else use plan 3`)

It does not have a strong influence on public transport. Generally, `ChangeExpBeta` (and not `SelectExpBeta`) is a good default to use as replanning strategy.

**Comment by BarshaLamichhane** [comment]
Hello, 

I have cloned and run the matsim-example-project repository but when I run up to the 10th iteration, I can see trips.xml and plans.xml files in output iteration files in iteration 0. For iteration 1, I can see plans.xml not trips.xml file. From Iteration 2, I can't see both plans.xml.gz and trips.csv.gz. As per my understanding for every iteration, the score function is calculated and the plans are selected according to the score function. Is there something wrong or did I misunderstand the scoring technique of matsim in each iteration?

**Comment by mrieser** [comment]
MATSim does not write out the files in every iteration, as it is very time consuming. Internally, MATSim still calculates the scores and does the replanning, but we don't write it out.

**Comment by BarshaLamichhane** [comment]
> MATSim does not write out the files in every iteration, as it is very time consuming. Internally, MATSim still calculates the scores and does the replanning, but we don't write it out.

@mrieser Thank you :)
