### ISSUE TITLE
Performance for large amounts of data and distributed computations

### ISSUE THREAD

**Issue by leonefamily** [matsim-org/matsim-code-examples#538]
How much of computing performance one has to have in order to provide simulating of a big city (aprox. 400k agents) with 5 types of plans (home, work, leisure plus different combinations of them) and different travel modes (car, pt, walk, bike) in a reasonable time?
Is there a possibility to arrange distributed MATSim computation using several PCs, or is it necessary to have all the hardware at one place?
Currently, I succeeded to process only around 4k agents without getting an error about lack of RAM, the PC has only 16gb of it, and 15 were dedicated for the needs of simulation.
Thank you for cooperation.

**Comment by mrieser** [comment]
> Is there a possibility to arrange distributed MATSim computation using several PCs, or is it necessary to have all the hardware at one place?

Currently, it's necessary to have all in one machine, there is no working distributed version of MATSim.

> Currently, I succeeded to process only around 4k agents without getting an error about lack of RAM, the PC has only 16gb of it, and 15 were dedicated for the needs of simulation.

This is unexpected. It should be possible to easily run around 20k agents with car and public transport with 4 GB RAM at most.

- How many nodes and links does your network have? Large, city-wide networks often have between 100k and 1m links. The more detailed the network, the more memory will the routes use.
- Do you use public transport? If yes, how many Transit Stop Facilities do you have? Depending on the region, it should not be a problem to have up to a few thousand stops, e.g. around 5k.
- If you use public transport, make sure to use the SwissRailRaptor for transit routing. The default transit router uses very, very much memory for large transit schedules, so this might be the culprit in your case.
- What MATSim version are you using? In MATSim 12, SwissRailRaptor is included, but needs to be activated manually in code. If you use a new SNAPSHOT, it should be possible to enable SwissRailRaptor with a config flag.

**Comment by leonefamily** [comment]
> * The default transit router uses very, very much memory for large transit schedules

Thank you for the response. As you say, the main problem appears to be in the default transit router that I have specified in config. The network has 100k links, 50k nodes, and around 1k stop facilities. I will try to figure out how it behave with SwissRailRaptor since I use MATSim 12. I appreciate your valuable advise.

**Comment by leonefamily** [comment]
After setting SwissRailRaptor simulation consumes 2 GB of RAM at maximum when running sample of 35k agents, so it is meaningfully memorz saving and faster as well
