### ISSUE TITLE
Simulation 

### ISSUE THREAD

**Issue by Hamadneh** [matsim-org/matsim-code-examples#54]
If I need to simulate only two modes (car and pt); what should I do for plans that have other modes in xml file? I have facilities, plans, network, transit schedule and config files... What should I do? I need for travelers/agent to use one of the two  odes based on utility function?

**Comment by jfbischoff** [comment]
You could simply teleport these modes by setting speeds for them in the PlansCalcRoute  part of  the config.

**Comment by Hamadneh** [comment]
> You could simply teleport these modes by setting speeds for them in the PlansCalcRoute part of the config.

Could you please give me more details?

**Comment by jfbischoff** [comment]
Please see 
https://matsim.org/the-book
and look for "teleportation"
