### ISSUE TITLE
Exception when using SwissRailRaptor

### ISSUE THREAD

**Issue by leonefamily** [matsim-org/matsim-code-examples#542]
I am struggling to run SwissRailRaptor as the main transit router. I was following instructions from https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions#swissRailRaptor, and matsim-example-project template was used. Though it was not possible to load dependency of version 12.0-SNAPSHOT, it went well with 13.0-SNAPSHOT (but I am not sure if this is supported by MATSim 12.0). 
When trying to run simulation with config that has specified RailRaptor module, program shuts down with the following exception, as if that dependency did not exist:
```
2021-03-29 16:28:22,199 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: swissRailRaptor
```
I also wanted to force RailRaptor to be the one that conducts transit computing through changing code, but did not find place where to put rows to activate it, since I am new to Java and programming in general.

Where should I look for a mistake or what do I need to change to get the simulation working?

**Comment by mrieser** [comment]
SwissRailRaptor is included in MATSim 12, but not enabled by default. To enable it, one still needs to follow the instructions you linked to (i.e. `controler.addOverridingModule(new SwissRailRaptorModule());`).

As you wrote that you also use MATSim 13.0-SNAPSHOT, there is a chance that you can enable SwissRailRaptor with a simple config-flag, as this was added in the meantime.

In your `config.xml`, try to add the following parameter:

```xml
<module name="transit">
  <param name="routingAlgorithmType" value="SwissRailRaptor" />
</module>
```
In a recent MATSim 13.0-SNAPSHOT, this should automatically enable SwissRailRaptor, all without the need for an additional dependency.

**Comment by leonefamily** [comment]
That totally worked, apologies for keeping the issue for that long time
