### ISSUE TITLE
EV Extension Charging/Queuing Issue

### ISSUE THREAD

**Issue by mattjweist** [matsim-org/matsim-code-examples#551]
I am testing the EV example from matsim.contrib.ev.example.RunEvExample using the Brandenburg-motorways network. I have questions pertaining to SOC output results.

In the image below, the default scenario was ran. Most vehicles charge until full capacity and then remain at the charging station for a couple minutes, as shown by the flat edges at 60 kWh. Why don't they leave the charging station immediately? In addition, other vehicles (1, 3, 5) do not charge all the way to 60 kWh -- why? What is the default charging strategy?
![image](https://user-images.githubusercontent.com/55769511/114737810-aa47c080-9d47-11eb-8d07-e54dfdb392ba.png)

In the next image, the departure time for each agent was set to 8am as opposed to the staggered departure times found in the default population.xml file. Here, the first five vehicles to reach the charging station charge until they are full. The next five charge for about eight minutes and then continue driving. The last five charge for 12 seconds and then continue driving. It seems like the program thinks the vehicles are charging while they are actually just queuing; or the vehicles are more concerned with finishing the route in a timely manner than charging. What is the explanation for this behavior, and how can it be fixed? 
![image](https://user-images.githubusercontent.com/55769511/114740094-d06e6000-9d49-11eb-8984-dd51afab6464.png)

In other threads, I've seen a few Matsim employees refer to an "Urban" model in the works that would presumably solve these issues. Why would the Brandenburg case be considered urban if this is a long-haul trip?

**Comment by mattjweist** [comment]
I think the main issue is that the duration of the charging activity is set before the simulation starts in the file EvNetworkRoutingModule.java, and it doesn't take into account the queuing time experienced by vehicles that arrive later to the charging station. How can I leave the length of the charging activity open-ended such that its end time is only dictated by when the vehicle actually finishes charging?

**Comment by jfbischoff** [comment]
The current EvNetworkRoutingModule indeed assigns fixed duration breaks for charging (the module has only been used in a prototype for which that assumption was sufficient, but it obviously fails if chargers are overcroweded). 
Adding flexible breaks needs a bit of a change in the setup, as you will require the agents to re-plan within day, making several things somewhat more complicated. 
As a starting point, I would recommend the within-day replanning chapter in the MATSim book, and also to look at the examples provided here:
https://github.com/matsim-org/matsim-code-examples/tree/14.x/src/main/java/org/matsim/codeexamples/withinday/withinDayReplanningFromPlans

You would require a MobsimListener that checks every x seconds whether a vehicle is fully charged and then tells the driver to get moving again (or to continue the charging activity).

---
You could also look at eDVRP  / eDRT, where charging is happening dynamically. However, getting the quintessentials that you need for your application from there might be rather complicated.

**Comment by mattjweist** [comment]
Thanks for the answer, @jfbischoff . What function would you recommend for getting the agents in the listener? Using "vehicle.getDriver()" from the example listener returns null, because the agents are not in the vehicles while charging.

**Comment by mattjweist** [comment]
> Thanks for the answer, @jfbischoff . What function would you recommend for getting the agents in the listener? Using "vehicle.getDriver()" from the example listener returns null, because the agents are not in the vehicles while charging.

FYI: this seems to work
`	private List<MobsimAgent> getAgentsToReplan(Netsim mobsim ) {

		List<MobsimAgent> set = new ArrayList<MobsimAgent>();
		
		// check agents once per 60 seconds
		if (Math.floor(mobsim.getSimTimer().getTimeOfDay()) % 60  != 0) {
			return set;
		} else {
			System.out.println("current time: " + mobsim.getSimTimer().getTimeOfDay());
		}
		
		/* mattjweist */
		final QSim qsim = (QSim) mobsim;
		for (MobsimAgent agent : (qsim).getAgents().values()){
			if (ChargingWithQueueingLogic.vehicleChargeStatus.containsKey(agent.getId()) && ChargingWithQueueingLogic.vehicleChargeStatus.get(agent.getId()) == 1) { // if done charging
				System.out.println("found agent done with charging: " + agent.getId());
				set.add(agent);
				ChargingWithQueueingLogic.vehicleChargeStatus.put(agent.getId(),0); // reset to zero for next charge event
			}
		}
		return set;
	}


	private boolean doReplanning(MobsimAgent agent, Netsim mobsim ) {
		double now = mobsim.getSimTimer().getTimeOfDay() ;
		
		Plan plan = WithinDayAgentUtils.getModifiablePlan( agent ) ; 
		if (plan == null) {
			log.info( " we don't have a modifiable plan; returning ... ") ;
			return false;
		}	
		
		/* mattjweist */
		EditTrips editTrips = new EditTrips(tripRouter, scenario, internalInterface);
		EditPlans editPlans = new EditPlans( (QSim) mobsim, editTrips);
		editPlans.rescheduleCurrentActivityEndtime(agent, now);
		
		// finally reset the cached Values of the PersonAgent - they may have changed!
		WithinDayAgentUtils.resetCaches(agent);
		
		return true;
	}`

**Comment by mattjweist** [comment]
> Thanks for the answer, @jfbischoff . What function would you recommend for getting the agents in the listener? Using "vehicle.getDriver()" from the example listener returns null, because the agents are not in the vehicles while charging.

FYI, this seems to work:
`	private List<MobsimAgent> getAgentsToReplan(Netsim mobsim ) {

		List<MobsimAgent> set = new ArrayList<MobsimAgent>();
		
		// check agents once per 60 seconds
		if (Math.floor(mobsim.getSimTimer().getTimeOfDay()) % 60  != 0) {
			return set;
		} else {
			System.out.println("current time: " + mobsim.getSimTimer().getTimeOfDay());
		}
		
		/* mattjweist */
		final QSim qsim = (QSim) mobsim;
		for (MobsimAgent agent : (qsim).getAgents().values()){
			if (ChargingWithQueueingLogic.vehicleChargeStatus.containsKey(agent.getId()) && ChargingWithQueueingLogic.vehicleChargeStatus.get(agent.getId()) == 1) { // if done charging
				System.out.println("found agent done with charging: " + agent.getId());
				set.add(agent);
				ChargingWithQueueingLogic.vehicleChargeStatus.put(agent.getId(),0); // reset to zero for next charge event
			}
		}
		return set;
	}


	private boolean doReplanning(MobsimAgent agent, Netsim mobsim ) {
		double now = mobsim.getSimTimer().getTimeOfDay() ;
		
		Plan plan = WithinDayAgentUtils.getModifiablePlan( agent ) ; 
		if (plan == null) {
			log.info( " we don't have a modifiable plan; returning ... ") ;
			return false;
		}	
		
		/* mattjweist */
		EditTrips editTrips = new EditTrips(tripRouter, scenario, internalInterface);
		EditPlans editPlans = new EditPlans( (QSim) mobsim, editTrips);
		editPlans.rescheduleCurrentActivityEndtime(agent, now);
		
		// finally reset the cached Values of the PersonAgent - they may have changed!
		WithinDayAgentUtils.resetCaches(agent);
		
		return true;
	}`

**Comment by mattjweist** [comment]
FYI, this seems to work: 

`	
private static List<MobsimAgent> getAgentsToReplan(Netsim mobsim ) {

		List<MobsimAgent> set = new ArrayList<MobsimAgent>();
		
		// check agents once per 60 seconds
		if (Math.floor(mobsim.getSimTimer().getTimeOfDay()) % 60  != 0) {
			return set;
		} else {
			System.out.println("current time: " + mobsim.getSimTimer().getTimeOfDay());
		}
		
		/* mattjweist */
		final QSim qsim = (QSim) mobsim;
		for (MobsimAgent agent : (qsim).getAgents().values()){
			if (ChargingWithQueueingLogic.vehicleChargeStatus.containsKey(agent.getId()) && ChargingWithQueueingLogic.vehicleChargeStatus.get(agent.getId()) == 1) { // if done charging
				System.out.println("found agent done with charging: " + agent.getId());
				set.add(agent);
				ChargingWithQueueingLogic.vehicleChargeStatus.put(agent.getId(),0); // reset to zero for next charge event
			}
		}
		return set;
	}


	private boolean doReplanning(MobsimAgent agent, Netsim mobsim ) {
		double now = mobsim.getSimTimer().getTimeOfDay() ;
		
		Plan plan = WithinDayAgentUtils.getModifiablePlan( agent ) ; 
		if (plan == null) {
			log.info( " we don't have a modifiable plan; returning ... ") ;
			return false;
		}	
		
		/* mattjweist */
		EditTrips editTrips = new EditTrips(tripRouter, scenario, internalInterface);
		EditPlans editPlans = new EditPlans( (QSim) mobsim, editTrips);
		editPlans.rescheduleCurrentActivityEndtime(agent, now);
		
		// finally reset the cached Values of the PersonAgent - they may have changed!
		WithinDayAgentUtils.resetCaches(agent);
		
		return true;
	}`
