### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by Hamadneh** [matsim-org/matsim-code-examples#56]
(1-10) Errors in custom provider, java.lang.IllegalArgumentException: There exists already a node with id = 1000027817.
Existing node: [id=1000027817][coord=[x=2109724.9968952355][y=6018105.135086829]][type=null][nof_inlinks=2][nof_outlinks=2]
Node to be added: [id=1000027817][coord=[x=2109724.9968952355][y=6018105.135086829]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network. 
what should I add or modify to the network I did not understand what I have to add, please any help

**Comment by jfbischoff** [comment]
You should try to rename the nodes that you want to add.
