### ISSUE TITLE
Stuck agents at pt stops

### ISSUE THREAD

**Issue by leonefamily** [matsim-org/matsim-code-examples#561]
Hello,

I ran into the same problem as few people back in the day, with agents getting stuck at stops in a large-scale simulation with over 250k agents using public transit. It often happens, that agent does not enter certain vehicle, mostly because it's full, or agent is late. That vehicle runs on some line, that has only one or two rides a day, causing agent to wait forever, even if there are plenty of lines that connect both initial and final stops. Around 5 % of pt users end up stuck in such a situation even after some iterations.

![image](https://user-images.githubusercontent.com/77976599/117024595-6cacd680-acfa-11eb-9fe0-8c0921d8ba85.png)
![image](https://user-images.githubusercontent.com/77976599/117029232-bc8d9c80-acfe-11eb-9e05-a8f720c90bd6.png)

Pt network and schedules were converted from GTFS with pt2matsim (so they are fragmented), currently enabled router is SwissRailRaptor.  The problem was seemengly [solved before](https://github.com/matsim-org/matsim-code-examples/issues/119#issuecomment-493377129), but I cannot access TransitConfigGroup to make changes in the source code, because notes at ["downloads" page](https://www.matsim.org/downloads/) say, that it's unavailable. 

How do I do that? I use Eclipse IDE.

Thank you in advance,
Dmitrii Grishchuk.

**Comment by mrieser** [comment]
>  I use Eclipse IDE.

Do you use the matsim-example-project in Eclipse?

If you are using Eclipse (or another IDE), you probably have your own main-method that you execute. You could configure the TransitConfigGroup accordingly in that part of the code, no need to modify the sources of MATSim directly.

If you use a rather new version of MATSim (e.g. MATSim 13.0, or (I think) a weekly snapshot of MATSim 12.0-2020w24 or newer), there is also an option in SwissRailRaptor which tries to detect such issues and tries to find better routes. Add the following part to your `config.xml`:

```xml
<module name="swissRailRaptor">
  <param name="useCapacityConstraints" value="true" />
</module>
```

**Comment by leonefamily** [comment]
> Do you use the matsim-example-project in Eclipse?

Yes, but I only launch MATSim GUI with it after making necessary changes (i.e. enabling/disabling SBBPt or OTFVis). I never had expirience with Java before (or any language like it), so it'll take some time, before I learn how to use its potential. I'd be very grateful though, if you could provide some instructions on how to implement mentioned solving into matsim-example-project (with MATSim 12.0-2020w48). 

Anyways, the config trick might do the thing, but I suppose, judjing by the parameter name, it only helps, if vehicles are full, not if agent is late.

**Comment by mrieser** [comment]
> (i.e. enabling/disabling SBBPt or OTFVis)

If you look at the class `RunMatsim` from the example project, where you enable/disable OTFVis, you'll also see the config-object being modified [around line 50](https://github.com/matsim-org/matsim-example-project/blob/60b68fa1df1901d0b401d3ffc49b6847b9682d5d/src/main/java/org/matsim/project/RunMatsim.java#L48).

You could add an additional line to make the change suggested in #119:

```java
config.transit().setBoardingAcceptance(BoardingAcceptance.checkStopOnly);
```

don't forget to add the following import statement near the top of the file, where all the other imports are as well:
```java
import org.matsim.pt.config.TransitConfigGroup.BoardingAcceptance;
```

> Anyways, the config trick might do the thing, but I suppose, judjing by the parameter name, it only helps, if vehicles are full, not if agent is late.

Yes, although sometimes agents are late at a connecting service, because they couldn't board the first one on time as it was full. So it might also help reduce the number of agents being late at pt stops.

**Comment by leonefamily** [comment]
@mrieser Thank you, adding that line into RunMatsim helped a lot, now agents happen to stuck rather randomly, not systematically.

Concerning config changes, useCapacityConstraints parameter for SwissRailRaptor is not recognized as valid. Could that be because of MATSim version?
