### ISSUE TITLE
Error when trying to run example configs in MatSim GUI "java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrappe"

### ISSUE THREAD

**Issue by djdylex** [matsim-org/matsim-code-examples#565]
I downloaded matSim today, i updated java to its latest version and installed JDK. When i try to run an example such as equil by loading config.xml from matsim-13.0\examples\equil i get the following error (copied and pasted from output)

https://pastebin.com/Xw8aE1ms

I'm running on Windows 10, with java version 8 update 291 (build 1.8.0_291-b10), and JDK (javac) version 16.0.1

I've tried restarting my computer which made no difference.

**Comment by jfbischoff** [comment]
MATSim 13 requires JDK 11 or above.

**Comment by djdylex** [comment]
I uninstalled JDK 16.0.1 and installed JDK 110.11 and this seemed to work, thanks.
