### ISSUE TITLE
Convert Int to Id?

### ISSUE THREAD

**Issue by mattjweist** [matsim-org/matsim-code-examples#566]
Hi,

This seems like a simple problem, but I'm just looking to get the associated Id (such as chargerId or agentId) given the Id as an int. How would I do that?

For example: 
```
int agentIdInt = 0;
Id<Agent> agentId = agentIdInt; // error: cannot convert from int to Id<Agent>
```

Thanks,
Matt

**Comment by kainagel** [comment]
Without looking into the code, I think that it should be something like `Id<Agent> agentId = Id.createId( agentIdInt, Agent.class )`.

**Comment by mattjweist** [comment]
Thanks @kainagel this works. And for a charger, one can simply use `Id<Charger> chargerId = Id.create(chargerIdInt, Charger.class)`
