### ISSUE TITLE
Convert OSM network to matsim xml and keep coordinate system

### ISSUE THREAD

**Issue by djdylex** [matsim-org/matsim-code-examples#568]
I need to convert an area i exported from OSM into a format to work with matsim. 

I've been using SUMO's netconvert, which works well but all the coordinates start from the bottom left of the area and seem to be in an arbitrary unit (thought possibly meters). For example, the middle of the area has coordinates (4000, 3500), but the lat long is more like -57, 1.5.
This doesn't work well for me as I have data on where agents need to be thats in lattitude and longitude (EPSG:4326 / WSG84 if i understand correctly). 

I'm not super experienced with using the matsim libraries, so ideally want to avoid using Java as im planning to use python to generate the population xml doc. 

How can I correctly convert from the OSM into matsim xml while keeping the geodesic coordinate system (or atleast a non arbitrary one)?

**Comment by Janekdererste** [comment]
the standard way to convert osm to matsim network requires a little bit of java

https://github.com/matsim-org/matsim-code-examples/blob/13.x/src/main/java/org/matsim/codeexamples/network/RunCreateNetworkFromOSM.java

Or a simpler example

https://github.com/matsim-org/matsim-libs/blob/master/contribs/osm/src/main/java/org/matsim/contrib/osm/examples/RunSimpleNetworkReader.java
