### ISSUE TITLE
Question about the relation between activity location and link

### ISSUE THREAD

**Issue by rara1484** [matsim-org/matsim-code-examples#570]
Hello.
I will be running a simulation that incorporates public transportation.
To do the simulation, I read a guidebook about simulations and found that activity locations and stop facilities are assigned the closest link to the location.

So I had a question.
"When is the agent considered to have arrived at the destination(activity location or stop facility)?"　
Is it when they come to the center of the link?　
Or when it enters the link from a node?

I would appreciate it if you could tell me.

**Comment by mrieser** [comment]
It is when the agent arrives **at the end** of the link.

You can observe this by looking at the timestamps of events. When an agent starts a trip, the "vehicle enters traffic"-event is usually just a second before the "leave link"-event. When an agent arrives, there is first a "enter link"-event, and the "vehicle leaves traffic"-event comes after several seconds that correspond to the current travel time on that link at that time.

**Comment by rara1484** [comment]
Thank you so much for your reply.
