### ISSUE TITLE
Minibus Basic Operator configuration

### ISSUE THREAD

**Issue by gammapopolam** [matsim-org/matsim-code-examples#583]
Hi!

We want to run a scenario of paratransit system with BasicOperator parameter instead of CarefulMultiPlanOperator. 
useFranchise parameter set to False. 

When I am trying to run modified scenario, it show this error:
```
2021-06-18T04:15:52,507 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.IllegalArgumentException: There is already a transit route with id p_0_1-0_0 with line p_0_1
	at org.matsim.pt.transitSchedule.TransitLineImpl.addRoute(TransitLineImpl.java:68) ~[classes/:?]
```
	
Are we able to configure scenario with BasicOperator type without any errors? If we are able, what should we fix?

**Comment by vsp-gleich** [comment]
It seems BasicOperator is no longer used. The example uses CarefulMultiPlanOperator. Without a minimal working example it is hard to comment why that error occurred.

**Comment by gammapopolam** [comment]
Sorry for the long answer. Thank you.

So, if the BasicOperator is no longer used, then we are not able to use SimpleBackAndForthScheduleProvider parameter in routeProvider?
