### ISSUE TITLE
Use matsim-berlin as a maven dependency

### ISSUE THREAD

**Issue by lubaso** [matsim-org/matsim-code-examples#588]
I'm trying to clone the Berlin Scenario as following:

`... using an IDE, e.g. Eclipse, IntelliJ - Alternative 2: use matsim-berlin as a maven dependency
`
But I get this error:

`Could not find artifact ch.sbb:matsim-sbb-extensions:pom:12.13 in osgeo (https://repo.osgeo.org/repository/release/)
`
Any idea on how I can solve that?

Thanks in advance!

**Comment by Janekdererste** [comment]
Hi, 

I had the same issues during the past weeks. I updated dependencies on the 5.6.x Branch, which is the current development/master branch. You could switch to this branch and get a working dependency, although this is not a stable version of the berlin scenario. (I haven't validated whether everything works as expected but I'd assume it does)

To include this version as a dependency, you can add the following to the pom.xml of your project

```
<dependency>
        <groupId>com.github.matsim-scenarios</groupId>
        <artifactId>matsim-berlin</artifactId>
        <version>5.6.0</version>
</dependency>
```

**Comment by lubaso** [comment]
@Janekdererste, thank you for the advice.
Now it works!
