### ISSUE TITLE
Error cannot find "org.matsim.examples.ExamplesUtils"

### ISSUE THREAD

**Issue by PhuongDuy-PP** [matsim-org/matsim-code-examples#589]
After I clone the source and install the dependency, I get the "cannot find "org.matsim.examples.ExamplesUtils" error. Can you help me fix this? Thanks

**Comment by JWJoubert** [comment]
Hi @PhuongDuy-PP, I am not sure what you mean with 

> ... and install the dependency...

but what worked for me is to add the following dependency to the `pom.xml` file:

```
        <dependency>
            <groupId>org.matsim</groupId>
            <artifactId>matsim-examples</artifactId>
            <version>12.0</version>
        </dependency>
```

**Comment by PhuongDuy-PP** [comment]
Hi @JWJoubert , can you send me the pom.xml file? Thanks.
![image](https://user-images.githubusercontent.com/28092838/126145766-f78bfe63-143c-4392-bd54-7eecb801255a.png)

**Comment by JWJoubert** [comment]
No need to replace the `pom.xml` file. Mine are all adapted for my specific projects/repositories. Just add that to the current `pom` file. I see you use IntelliJ - then just also make sure you right-click on the project and select `Maven` -> `Reload project`.

**Comment by PhuongDuy-PP** [comment]
Thanks @JWJoubert , I fixed.

**Comment by NikolaAndro** [comment]
This solved it for me as well. Thank you!
