### ISSUE TITLE
How MATSim will handle the trips that have the same origin and destination location?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#609]
Dear MATSim community,

We are currently generating a MATSim plan file for the city of Brussels. Some respondents in our travel behaviour survey have reported the same origin and destination location for their trips (probably as they didn't report their daily travel as detailed as possible). 

For instance, one guy said he ends his last `work` activity from `location A` at 10:40 am and start his next trip by pt (probably going to lunch which we are not sure about), it took him two hours to finish this trip and he came back to this `location A` at 12:40 pm. As a result, if we describe this travel in the MATSim format, we will get something like this:

`<activity type="work" x="0" y="0" start_time="08:40:00" end_time="10:40:00" >`
			`</activity>`
			`<leg mode="pt" trav_time="02:00:00">`
			`</leg>`
`<activity type="work" x="0" y="0" start_time="12:40:00" end_time="17:55:00" >`

I am wondering if I will confuse MATSim with a plan like this? How MATSim will handle this trip during simulation? Will MATSim be intelligent enough to search for a "pt" option which takes 2 hours from location A to location A (probably very hard to find a pt trip that takes 2 hours without location changes)? Do you have any suggestions for me to process this kind of data?

I hope I have explained my question clear and well enough for your understanding :) Thanks very much for your help in advance!

**Comment by balacmi** [comment]
Hi @jingjunL ,

In this case MATSim will route a pt trip between locations with the same coordinates (0,0) and will return a walking trip with zero seconds travel time, as it is the most sensible thing to do. This is how the routing works.

Now, it depends how you want to handle this problem. In most of the cases one would merge two work activities into one and live with not-modelling the pt trips and possible lunch activity in between. However, if this happens often in your survey, you might consider devising an approach to add these missing activities.

I hope this helps.

**Comment by jingjunL** [comment]
> Hi @jingjunL ,
> 
> In this case MATSim will route a pt trip between locations with the same coordinates (0,0) and will return a walking trip with zero seconds travel time, as it is the most sensible thing to do. This is how the routing works.
> 
> Now, it depends how you want to handle this problem. In most of the cases one would merge two work activities into one and live with not-modelling the pt trips and possible lunch activity in between. However, if this happens often in your survey, you might consider devising an approach to add these missing activities.
> 
> I hope this helps.

Hi Milos, 

Many thanks for your reply, and it is very helpful! :D

I just did a quick check and find the percentage of "one primary activity - the same primary activity (basically, primary activity means work and school in my case)" trips within all primary trips is about 18% in my data. I guess the main reason for this is we assume a fixed (and only one) primary location of our agents, however, most of this 18% of trips are working at multiple locations within that surveyed day. 

So I assume I can only merge such kinds of activities as you suggested since I cannot think of a way to deal with the primary location matching for these "same primary activity" trips (we are trying to use the same algorithm as the Ile-de-France scenario). Maybe an example will make my clarification more clear: although in the survey we know respondent A who lives in area B ends his work at area C and heading to area D for another work activity, however, if we match the same activity chain of this respondent for a people living in area E the matching of work-work seems tricky (and we also need to consider the distance constraints as the Ile-de-France)... Unless you know any existing scenario that has some special algorithm? I will be very appreciated if you can share it with me :)

Thanks for your help again!

**Comment by balacmi** [comment]
Hi Jingjun,

OK, I understand the problem. What you could potentially do (since you have a lot of cases with this issue) is treat secondary work locations as secondary activities, and assign their locations using the secondary location assignment procedure used in the IDF pipeline. This could help solve your problem.

**Comment by jingjunL** [comment]
> Hi Jingjun,
> 
> OK, I understand the problem. What you could potentially do (since you have a lot of cases with this issue) is treat secondary work locations as secondary activities, and assign their locations using the secondary location assignment procedure used in the IDF pipeline. This could help solve your problem.

Hi Milos,

That sounds interesting and I never thought about it this way :) I will try it out and keep you posted!

Thanks again!
