### ISSUE TITLE
Run the scenarios of Singapore and Berlin

### ISSUE THREAD

**Issue by GoingMyWay** [matsim-org/matsim-code-examples#61]
The [scenarios](https://www.matsim.org/gallery/) are very good, how can I run these scenarios of Singapore and Berlin?

**Comment by jfbischoff** [comment]
You can find the most up-to-date version of the Berlin scenario here:
https://github.com/matsim-vsp/matsim-berlin/
I think the Singapore scenario may not be openly available.
