### ISSUE TITLE
Help with coordinate system for OSM file

### ISSUE THREAD

**Issue by erotnem** [matsim-org/matsim-code-examples#612]
Hi everyone,

I am a first time MATSim user, and trying to convert my merged .osm into a network.xml. I am trying to use MATSim for modeling the city of Aachen in Germany; according to online sources, this city is in UTM-32N. However, the [code example](https://github.com/matsim-org/matsim-code-examples/blob/0.9.x/src/main/java/tutorial/population/example08DemandGeneration/RunPNetworkGenerator.java) given to us in the book have the coordinates transformed to UTM-33N. 

I tried simply changing this parameter to 32N, but the string wasn't recognized by the 'TransformationFactory' (and according to this [page](https://www.matsim.org/apidocs/core/0.4.0/org/matsim/core/utils/geometry/transformations/TransformationFactory.html), it isn't a valid thing to pass in).

I'm looking for suggestions now. Is it ok to keep using 33N, despite the city actually being in 32N? Is there another way I can convert to 32N?

Thank you!

**Comment by mattjweist** [comment]
Try this line of code. You can find EPSG codes here: https://spatialreference.org/ref/epsg/

`CoordinateTransformation ct = TransformationFactory.getCoordinateTransformation("EPSG:4326", "EPSG:32632");`

**Comment by erotnem** [comment]
That seems to have worked! Thank you!
