### ISSUE TITLE
normalizing scores

### ISSUE THREAD

**Issue by MahsaSiegrist** [matsim-org/matsim-code-examples#615]
Hello,

Are the scores normalized for car or public transportation?
if not, how can I normalize scores?
Because we can have an agent with a long trip and we can have an agent with a short trip, then if their utilities are not normalized then, of course, one has a smaller utility than the other one. 
For part of my analysis, I need to sort agents and compare them based on their scores.

Looking forward to your help.

**Comment by balacmi** [comment]
MATSim scores are not normalized.

The scores are mainly used to compare plans within a single agent's memory. I am not sure that I understand what would be the purpose of normalization in comparing scores among the agents.

Could you elaborate a bit more on what you plan to achieve with this analysis?
