### ISSUE TITLE
Issues of using NetworkChangeEvents (capacity)

### ISSUE THREAD

**Issue by Ohay-Angah** [matsim-org/matsim-code-examples#616]
With the file input, the error `Expected number of change events (1) differs from the number of events found (0)!` popped up.

It seemed like inside the core codes, the `ChangeValueGetter` couldn't recognize the `flowCapacity` events while the `freespeed` events worked fine. I went through all the issues and followed every suggestion with no luck. So I attached the log file here to see if anyone could help

Details can be seen [here](https://github.com/matsim-org/matsim-libs/issues/1684#issue-1007705423)

**Comment by ikaddoura** [comment]
I think we can close this issue as it was solved here: https://github.com/matsim-org/matsim-libs/issues/1684#issuecomment-933921046.
