### ISSUE TITLE
Running Scenario in HPC

### ISSUE THREAD

**Issue by khzannat** [matsim-org/matsim-code-examples#628]
I am running a scenario for #Dhaka with 10 percent sample. To complete a single iteration in my local machine it took 24hours. Then I started to run the scenario in #HPC with 30 core 4.8GB RAM. However, after 48 hours it could complete 4-5 iteration. What would be the efficient way of running the scenario with 10percent sample?

**Comment by kainagel** [comment]
Could you please upload the logfile from the HPC machine?  And: How long did it take for a 1 pct sample (on your local machine)?

**Comment by khzannat** [comment]
[HPC-job-log.zip](https://github.com/matsim-org/matsim-code-examples/files/7369137/HPC-job-log.zip)
I have attached herewith the logfile from HPC. For the 1 percent sample, if I am not mistaken it took 2 hours in my local machine.

**Comment by rakow** [comment]
Your qsim is running very long, you did not set any limit:

```	
<module name="qsim" >
		<param name="endTime" value="00:00:00" />
```

At the end, you have simulated nearly 60 years in one iteration.
```
 SIMULATION (NEW QSim) AT 532546:00:00 : #Veh=1 lost=0 simT=1.9171638E9s realT=172698s; (s/r): 11101.250738283014
```

There is one vehicle keeping the qsim busy, but I can not tell you why that is the case.
The easy fix is to just restrict the qsim with the parameter above, e.g. to 36:00:00.

**Comment by khzannat** [comment]
Thank you very much for your suggestion. I have restricted the qsim "endTime" value="36:00:00", it has improved the performance. Within 48 hours, it could complete 27 iteration. But, still after 27 iteration it could not continue the iteration (logfile attached). Can I restrict the qsim "endTime" value below "36:00:00"? What would be the standard value?
[class-example.logfile.log.zip](https://github.com/matsim-org/matsim-code-examples/files/7393583/class-example.logfile.log.zip)

**Comment by rakow** [comment]
At iteration 28 your simulation somehow hangs up and is not making any more progress.  Simulating until iteration 28 took in fact only a few minutes.

From the log alone it is very hard to see the reason for this, but there may be a few things you can try:

The number of threads is set to 30 according to the number of CPUs. I think your scenario is not big enough to fully utilize this. I would suggest that you reduce the number of threads to something like 8 for now.

What MATSim version did you use ? Could you also try to run this with the latest MATSim 14.0-SNAPSHOT?

**Comment by khzannat** [comment]
If I am not mistaken, I am using version 13 (pom.xml is attached). How to change the snapshot? Do I have to do it from config?
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>org.matsim</groupId>
	<artifactId>matsim-example-project</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>MATSim example project</name>
	<description>MATSim example project</description>

	<properties>
		
		<matsim.version>13.0</matsim.version>

		
		

		
		

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>

	<repositories>
	  
		<repository>
			
			<id>osgeo</id>
			<name>Geotools repository</name>
			
			<url>https://repo.osgeo.org/repository/release/</url>
		</repository>
		<repository>
			
			<id>matsim</id>
			<url>https://repo.matsim.org/repository/matsim</url>
		</repository>
		
		<repository>
			<id>topobyte</id>
			<url>https://mvn.topobyte.de</url>
		</repository>
		
		<repository>
			<id>slimjars</id>
			<url>https://mvn.slimjars.com</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			
			<groupId>org.matsim</groupId>
			<artifactId>matsim</artifactId>
			<version>${matsim.version}</version>
		</dependency>

		<dependency>
			
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			
			<groupId>org.matsim</groupId>
			<artifactId>matsim</artifactId>
			<type>test-jar</type>
			<version>${matsim.version}</version>
			<scope>test</scope>
		</dependency>

		
		
		<dependency>
			<groupId>org.matsim</groupId>
			<artifactId>matsim-examples</artifactId>
			<version>${matsim.version}</version>




		</dependency>

		
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>minibus</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>otfvis</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>roadpricing</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>taxi</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>av</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>freight</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>bicycle</artifactId>
			<version>${matsim.version}</version>
		</dependency>
		

	</dependencies>

	<build>
		<plugins>
			<plugin>
				
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
				<version>2.10</version>
				<configuration>
					<downloadSources>true</downloadSources>
					<downloadJavadocs>true</downloadJavadocs>
				</configuration>
			</plugin>
			<plugin>



				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.2</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<outputFile>${project.basedir}/${project.build.finalName}.jar</outputFile>
							<transformers>
								
								<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<manifestEntries>
										<Main-Class>org.matsim.gui.MATSimGUI</Main-Class>
										<Specification-Vendor>org.matsim</Specification-Vendor>
										<Implementation-Vendor>org.matsim</Implementation-Vendor>
										<Implementation-Version>${project.version}</Implementation-Version>
									</manifestEntries>
								</transformer>
								
								<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
							</transformers>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>META-INF/*.RSA</exclude>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.RSA</exclude>
									</excludes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by rakow** [comment]
Yes, you need to modify the properties and comment in this line:

`<matsim.version>14.0-SNAPSHOT</matsim.version>` (remove `<!--` and `-->`)

**Comment by khzannat** [comment]
Thank you very much, I am doing this. Meanwhile, I restarted the model using the last plan file as starting value. And, it is running uninterruptedly in my local machine. Is it a right way to do this?

**Comment by khzannat** [comment]
Hi @rakow, I have tried with <matsim.version>14.0-SNAPSHOT</matsim.version> however, in the first iteration when it shows info about "INFO MemoryObserver:41 used RAM: 1440 MB  free: 779 MB  total: 2220 MB" then it continues the same message and no iteration completed. Same for HPC. Attached the log file from HPC.
[job-log.log](https://github.com/matsim-org/matsim-code-examples/files/7633152/job-log.log)

**Comment by rakow** [comment]
Hi @khzannat, the log does unfortunately not contain helpful information. I would have to run the scenario myself to see what's going on there. Is the code and data available somewhere? You can also send it to me privately.

**Comment by khzannat** [comment]
@rakow The plan file I need to send you privately. Can you give me your email address? Other file I can share with you my github link.

**Comment by rakow** [comment]
Please send it to rakow@vsp.tu-berlin.de

**Comment by khzannat** [comment]
@rakow  Thank you very much for your support. The issue is now resolved.

**Comment by rakow** [comment]
The problem was links of zero length in the network, causing shortest-path finding in replanning to take forever.
