### ISSUE TITLE
Coordinate system

### ISSUE THREAD

**Issue by Hamadneh** [matsim-org/matsim-code-examples#63]
Coordinates of facilitates are in latitude and longitude form, do I need to change them to x,y meter as in network file?

**Comment by tduberne** [comment]
The files can be expressed in any coordinate system, but internally, MATSim needs a metric projection, as it computes "crow-fly" distances by assuming the coordinates are on a plane.

The metric coordinate system for your area can be specified in the config file, in the "global" config group, parameter "coordinateSystem". The most reliable way to specify the CRS is using the EPSG code, in the form "epsg:****". Note the lower case "epsg": "EPSG" will not work.

There are then two ways to specify in which coordinate system a file is expressed:

- in the config file, in the config groups where input files are specified, there should always be a "inputCRS" parameter. The same format as for the global CRS apply.
- in the latest release, you can specify it directly in the file (and this is the recommended way), by attaching a parameter "coordinateReferenceSystem" to the container:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v6.dtd">

<population>
	<attributes>
		<attribute name="coordinateReferenceSystem" class="java.lang.String" >epsg:1234</attribute>
	</attributes>

	<!-- plans go here -->
</population>
```

If both ways are used, the projection defined in the input file itself takes precedence. If no input CRS is specified, the file is assumed to be in the desired metric system already.
