### ISSUE TITLE
Exporting MATSim Plan File from R

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#631]
Dear MATSim community,

We are currently building a new MATSim model for Brussels, Belgium following an adapted algorithm of `MATSim Ile De France Scenario`. An `R script` was written for processing data from various sources. Until now, we have had every information we need to build a `MATSim plan file`. However, all information is in two R `data frame` so we need to export it into MATSim format (the data frame contains his personal attributes, activity coordinates, departure hour, activity end hour etc, basically all information needed).

I am wondering if there is any existing code or package that can help me do this in a handier way? Otherwise, I may need to write my own R code to export those data into XML format, which is much more time-consuming.

Many thanks for any help in advance :)

**Comment by tschlenther** [comment]
Hi,

i am pretty certain that this kind of converter does not exist, yet. Sorry..

**Comment by jafshin** [comment]
Hi @jingjunL , here is an R script to write MATSim Plan XML, there are also other scripts in this repository for plan generation that you might find useful: https://github.com/matsim-melbourne/demand/blob/master/R/xml.R

**Comment by jingjunL** [comment]
> Hi @jingjunL , here is an R script to write MATSim Plan XML, there are also other scripts in this repository for plan generation that you might find useful: https://github.com/matsim-melbourne/demand/blob/master/R/xml.R

Hi @jafshin, yes, that's exactly what I was looking for :) However, I have used MATSim in-built `populationFactory` as an alternative for my problem as this issue was published 20 days ago. But good to know that, I will keep it in mind and use it when needed in the future! Thanks
