### ISSUE TITLE
What is the best extension to simulate Uber-like trips?

### ISSUE THREAD

**Issue by jalal1** [matsim-org/matsim-code-examples#635]
I was reading about the Mobility as a Service in MATSim https://github.com/matsim-org/matsim-maas, but I am still not sure what is the best starting point to simulate uber-like trips. 

Any suggestion is appreciated. 

Thank you, 
Jalal

**Comment by balacmi** [comment]
I would suggest you look into the drt contrib. There you can find several examples how to use taxi-like services.

**Comment by jalal1** [comment]
Thank you @balacmi, I will check it.
