### ISSUE TITLE
Error: MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main

### ISSUE THREAD

**Issue by khzannat** [matsim-org/matsim-code-examples#638]
Hello,
I am having an error, however, from the error I'm not really able to understand the cause. I have attached herewith the logfile
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/7464723/logfileWarningsErrors.log)

**Comment by balacmi** [comment]
Dear Khatun,

It seems that you want to use a routable mode in your simulation but your network does not contain this mode. In most cases you need to make sure that all modes defined in `planscalcroute` module in the `networkModes` parameter can also be found in the allowedModes parameter of your links.

**Comment by khzannat** [comment]
Thank you it helped. :)
