### ISSUE TITLE
Decongestion Approaches

### ISSUE THREAD

**Issue by LevashevIlia** [matsim-org/matsim-code-examples#64]
I want to use decongestion module in Braess paradox study. I don't clearly understand description of decongestion approaches, so, is there some articles or another description(besides one in the java package). And may be decongestion parameters description?

**Comment by ikaddoura** [comment]
There is a paper in which the basic methodology, the parameters and some applications (Vickrey's bottleneck scenario, Berlin case study) are described: https://svn.vsp.tu-berlin.de/repos/public-svn/publications/vspwp/2017/17-14/.
