### ISSUE TITLE
Converting .csv (well known Text)to xml for network file

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#640]
I have a .csv file that has Digital Road Model (DRM) data in WKT format. I want to convert it into xml format which is compatible to MATSim input network file. I want to use Python. Are there any library or some tutorial from MATSim which would help me learn it.
The sample of .csv file is 
![image](https://user-images.githubusercontent.com/81128541/140468506-08fde443-dc10-4f7d-b0f3-7dc3f3501b18.png)

 

The sample of network.xml format is as is of 'equil'example in MATSim.: as below
![image](https://user-images.githubusercontent.com/81128541/140468210-22f480ec-89ff-4e50-9429-90a6e382fcfb.png)

**Comment by jfbischoff** [comment]
From what I know, there is no python network writer for MATSim, but I could be wrong. Writing one should be easy though.
You could also read the csv in java. It depends a bit where your programming a better :-)


As long as you have a reasonable definitions of nodes (I assume your source and target values depict these and you have a coordinate for them somewhere), the conversion of the data should be doable. However, bear in mind you also need reasonable values for the road capacities and freespeed values, so you probably need to guess these based on lanes and road category.
The line strings are probably not really necessary to use, as long as the length values are correct.

**Comment by jafshin** [comment]
I don't know about a Python network writer either, but you might want to check our R script that creates MATSim network from OSM, it might give you some idea on how to write your Python code: https://github.com/matsim-melbourne/network, 

This function converts a structured data frame to MATSim readable XML: 
https://github.com/matsim-melbourne/network/blob/298dbb86244d344ca7da6990e9a9044a10eec32c/functions/writeOutputs.R#L73_#L210

**Comment by Janekdererste** [comment]
We only have tutorials in Java, but I guess you could read them and then write your own python code. However, if you use python, you have to write the correct xml yourself. If you are able to use Java, you can use the more highlevel facilities provided by the matsim library. Examples on how to deal with networks can be found [here](https://github.com/matsim-org/matsim-code-examples/tree/13.x/src/main/java/org/matsim/codeexamples/network)
