### ISSUE TITLE
DRM to XML input

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#643]
I have Digital Road Map data of one particular location. I want to convert it into .xml input format of matsim. The input format needs to have nodes and links as defined in matsim input file. 
I am a complete beginner in matsim and coding. SO from where should I start. Is there any relevant tutorial for this . 
Matsim book has one example in chapter 92 , where DRM data of Tokyo, Japan is converted to xml using Matsim API.
Considering that I am a beginner in programming , where can I learn  Matsim API .
Thankyou

**Comment by Janekdererste** [comment]
This project provides code examples on several topics related to creating a MATSim scenario. Our examples regarding networks are [here](https://github.com/matsim-org/matsim-code-examples/tree/13.x/src/main/java/org/matsim/codeexamples/network)
