### ISSUE TITLE
Interpretation of output

### ISSUE THREAD

**Issue by khzannat** [matsim-org/matsim-code-examples#657]
Hi, 
While I am trying to extract the departure time of the agent using departure time event handler, the output shows something like this:
AgentDepartureEvent -- time: 7200.0 -- linkId: 5116738900008f -- personId: 17110141
AgentArrivalEvent -- time: 8351.0 -- linkId: 6436654590007f -- personId: 17110141
Person17110141started activitywork

I am a bit confused with the time. What does it mean by time: 7200.0?
TIA

**Comment by vsp-gleich** [comment]
Times in Matsim are given in seconds after midnight. So 7200.0 seconds = 7200/3600 = 02h:00m

**Comment by khzannat** [comment]
You mean 2AM in the morning?

**Comment by khzannat** [comment]
If It is 2am then it is exactly the time when that person in reality departs from home for work. Does the real departure time remain fixed throughout the simulation? Since, in my case I am doing mode choice model, the change should be only on modal share?

**Comment by balacmi** [comment]
It will remain fixed unless you use one of the innovation strategies that can change the departure time, i.e., TimeAllocationMutator.

**Comment by khzannat** [comment]
Thank you very much @balacmi  @vsp-gleich , one last query about the output, I estimated a link hourly volume:
The output looks like:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Zannat/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Zannat/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Hour;Value
--
33;3
 
11;2
 
12;1
 
13;2
 
16;4
 
17;3
 
18;3
 
19;4
 
5;1
 
6;6
 
7;4



</body>

</html>
Then, how the hour is 33? Is it because I fixed my qsim "endTime" value="36:00:00"? For this analysis I have used LinkLeaveEventHandler. 
Also, as I am using 1pc sample for this simulation, even with the 10 pc sample the link volume would not be close too reality. Then, in my article what would be the wise way to show the link volume? I have also used flow capacity factor and storage capacity factor 0.01 for 1 pc sample and flow capacity factor and storage capacity factor 0.1 for 10 pc sample.

**Comment by khzannat** [comment]
> It will remain fixed unless you use one of the innovation strategies that can change the departure time, i.e., TimeAllocationMutator.

I found this strategy settings in manual. 
![image](https://user-images.githubusercontent.com/34195237/143860589-fe33e3ea-0d11-4a7c-90f9-12761e77c182.png)
However, how these weights are defined? and What is the meaning? If I sum up then it is not equal to one. Are they still probability?

**Comment by balacmi** [comment]
To answer your first question:

- It is your choice how you will report the link volumes. Only make sure to report what is the sample size you used. The larger your sample the more accurate your results will be. The hour 33 is there because you let your simulation run for 36 hours, and then either in your population someone is departing around the hour 33 or the agents are in a heavy congestion and are severely delayed, meaning that your simulation is not in equilibrium yet.

Second question:

- those values are weights, they do not have to sum up to 1, if you sum them up and divide a single weight by the sum, you get a probability for each strategy.

**Comment by khzannat** [comment]
@balacmi Thank you very much, it clarifies my all confusion. :)
