### ISSUE TITLE
Understanding of the subtourModeChoice

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#664]
Hello everyone,

Assume that I have four modes in my MATSim model names A (network mode), B (network mode) and C (teleported mode) and D (teleported mode). At the very initial plan.xml, four modes all have their respective users. My question is if I do the below settings in my config:

`<module name="subtourModeChoice" >`
`        <param name="modes" value="A,B" />`
`    </module>`

How should I understand this `subtourModeChoice` setting? If in the initial plan, person 1 only has trips using mode C, what will happen after several iterations? Is it possible for some of his trips to shift to mode A/B, or MATSim see his initial plan is mode C, so this mode will not be shifted forever? In other words, does the "mode shift" only applies to the trips that initially use the modes A and B, or does it means all trips are possible to shift to mode A and B during the simulation?

I hope I have explained my confusion well, thanks in advance :)

**Comment by Janekdererste** [comment]
The module will only change tours which originally have one of the modes specified in ```<param name="modes" value="A,B" />```. Also, the modes to which a tour might be changed are the ones listed in that paremter.

This means tours with mode C or D won't be touched. Also, mode C and D will not be selected for tours which have mode A or B initially. 

This is the part of the code where this is handled: https://github.com/matsim-org/matsim-libs/blob/675d96bbd7333a50ebdde3af34bf53b5d6ed24d9/matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java#L177

And https://github.com/matsim-org/matsim-libs/blob/675d96bbd7333a50ebdde3af34bf53b5d6ed24d9/matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java#L331

**Comment by jingjunL** [comment]
> The module will only change tours which originally have one of the modes specified in `<param name="modes" value="A,B" />`. Also, the modes to which a tour might be changed are the ones listed in that paremter.
> 
> This means tours with mode C or D won't be touched. Also, mode C and D will not be selected for tours which have mode A or B initially.
> 
> This is the part of the code where this is handled: https://github.com/matsim-org/matsim-libs/blob/675d96bbd7333a50ebdde3af34bf53b5d6ed24d9/matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java#L177
> 
> And https://github.com/matsim-org/matsim-libs/blob/675d96bbd7333a50ebdde3af34bf53b5d6ed24d9/matsim/src/main/java/org/matsim/core/population/algorithms/ChooseRandomLegModeForSubtour.java#L331

That's very clear, thanks Janek :)
