### ISSUE TITLE
Understanding configuration file of MATSim

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#667]
I want to understand configuration file of MATSim. I read the 'equil' example config file and one config file of 'project of Santiago city', (available online). I want to understand what purpose different codes serves in config file. How can I alter them to desired output. Basically, I am looking for a video or text tutorial which teaches line by line  configuration file, so that I develop proper understanding and use it for my part of research. Please if any recommendation is available.
Thank you

**Comment by Janekdererste** [comment]
A good starting point is our [userguide](https://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf)
