### ISSUE TITLE
add a mode (in code)

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-code-examples#67]
I do (in code)
```
config.plansCalcRoute().setNetworkModes( Arrays.asList( TransportMode.car, TransportMode.bike ) );
```
and then get
```
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=bike) was already configured at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:58) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule).
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
```

Clearly, I can read the error message, and could go through the code.  But does someone maybe _know_ how this is meant to work?

If someone wants to try around, the code is here: https://github.com/matsim-org/matsim-code-examples/blob/0.11.x/src/main/java/org/matsim/codeexamples/integration/RunMultipleModesExample.java .

**Comment by amit2011** [comment]
As I had this before, this is happening because, bike, walk, ride etc. (modes other than car) are assumed as teleportation modes and their parameters are set by default in `PlansCalcRouteConfigGroup`. Thus, a teleportation router is assigned to such modes. One way to fix this is to remove the default parameters for such modes first, e.g. `config.plansCalcRoute().removeModeRoutingParams(  TransportMode.bike );`.  I guess these values were set before we had multiple network modes.

**Comment by gprichter** [comment]
hi @amit2011 

could the removal / setting of these default parameters also be done using the configuration file?
should the default values ONLY be filled in if corresponding information is missing in the config?

**Comment by kainagel** [comment]
Ah thanks, Amit.  Then one also needs to set up the travel time for bike.  The now working code is under the link given above.

@gprichter : Dear Gerald, could you please open a separate issue for your question?  I don't think it is possible, which is odd, because you could just bypass the default mode and define your own mode "bicycle" and then it would probably work, but you would end up with a (teleported) "bike" mode and a (network-routed) "bicycle mode" together, not good.  But maybe someone else knows, but they won't find the question in the issue here.  Thanks ...
