### ISSUE TITLE
How to use and visualise the count output in MATSim example project equil scenario?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#678]
Hi everyone,

From the MATSim user guide, I read that MATSim will plot link volume comparisons between hourly simulated and counted values for the specific link. This is very interesting for our Brussels model calibration. I tried to play with the `counts100.xml` provided by the MATSim example project. What I did was simply add the following config code in my runMATSim.class:

`config.counts().setInputFile("counts100.xml");`

By running the simulation, I saw from the `output_counts.xml` and `output_config.xml` that this input file has been successfully specified. I also checked the folder in iteration 10, there are indeed two `txt` files namely `countscompare.txt` and `countscompareAWTV.txt` (BTW, what is the meaning of this AWTV?). However, I cannot find either the image similar to Figure 6.1 as below nor a "google maps-based visualisation" (what should this google map thing look like?)

<img width="415" alt="1643907283(1)" src="https://user-images.githubusercontent.com/63421908/152389936-6d5c44cb-2628-47f6-bac4-00ca4ee1ca8e.png">

Also, I feel it is hard to understand this `countscompareAWTV.txt` file.  For instance, one line extracted as below:
`Link Id	Count Station Id	MATSIM volumes	Count volumes	Normalized Relative Error`
`14	handmade_01	9	11.1	0.189`

MATSim car volume in `link 14` is 9, and the counter station `handmade_01` says it is 11.1, this is perfectly understandable. However, what is the time of this comparison? During which time slot does this difference happen? I see from the output that there are 25 lines for the counter `handmade_01`, so I assume each line represents a one-hour time slot. Nevertheless, by referring back to the `counts100.xml`, I noticed that only during 7 am does the file specify a traffic volume 11.1 (the remaining times are all 0). However, why the `countscompareAWTV.txt` has all 25 lines count volumes as 11.1 (as image below)?
<img width="362" alt="1643908522(1)" src="https://user-images.githubusercontent.com/63421908/152393928-062a54be-2685-48e8-a1d6-975450f04ddc.png">

One last question, how should I generate a `count.xml` file via MATSim `writer` (similar to the populationWriter, networkWriter). I didn't find such an example in the matsim code example, maybe it is because I am using the wrong term? Do you have any examples for it?

Thanks very much for the help in advance!

**Comment by Janekdererste** [comment]
Sorry for the late response, I somehow oversaw your issue.
>  However, I cannot find either the image similar to Figure 6.1 

These can be generated with Via.

>  (BTW, what is the meaning of this AWTV?)

Unfortunately I don't know. I have never used this file. 

> how should I generate a count.xml file via MATSim writer 

You can peek [here](https://github.com/matsim-vsp/mosaik-2/blob/master/src/main/java/org/matsim/mosaik2/prepare/CreateCounts.java). The ```GetCount``` class is a custom class for the count data format we had received in that project. The transformation of that data structure into MATSim-Counts should work the same way for your data as well. The syntax to write the counts to a file is on [line 65](https://github.com/matsim-vsp/mosaik-2/blob/adfcbddba1b1fc75994a0e063b733dbcb8aa4c93/src/main/java/org/matsim/mosaik2/prepare/CreateCounts.java#L65)

**Comment by jingjunL** [comment]
> Sorry for the late response, I somehow oversaw your issue.
> 
> > However, I cannot find either the image similar to Figure 6.1
> 
> These can be generated with Via.
> 
> > (BTW, what is the meaning of this AWTV?)
> 
> Unfortunately I don't know. I have never used this file.
> 
> > how should I generate a count.xml file via MATSim writer
> 
> You can peek [here](https://github.com/matsim-vsp/mosaik-2/blob/master/src/main/java/org/matsim/mosaik2/prepare/CreateCounts.java). The `GetCount` class is a custom class for the count data format we had received in that project. The transformation of that data structure into MATSim-Counts should work the same way for your data as well. The syntax to write the counts to a file is on [line 65](https://github.com/matsim-vsp/mosaik-2/blob/adfcbddba1b1fc75994a0e063b733dbcb8aa4c93/src/main/java/org/matsim/mosaik2/prepare/CreateCounts.java#L65)

Thanks for the reply, Janek! 

So if I have understood everything correctly, when you are working with the count data, you just issue a count file and then insert it with the event file in Via? No need to do the additional configuration like me specifying `config.counts().setInputFile("counts100.xml");` in my `runMatsim.java`?

**Comment by Janekdererste** [comment]
I think if you add the counts file into your configuration, you get output counts with simulated and measured values already. On the other hand it should be possible to calculate the simulated counts lateron as well.
