### ISSUE TITLE
Understanding of ChangeMode Parameter (Got confused about the description in config)

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#682]
Hello everyone, 

I asked one similar question earlier in this post about the subtouModeChoice #664 

However, I found in my plan file the percentage of subtourMode is relatively small, so I need to adapt to `changeSingleTripMode `for mode innovation.

From the MATSim handbook, I see the setting I need to have is as below:

```
	<module name="changeMode" >
		<!-- Defines whether car availability is considered be considered or not. An agent has no car only if it has no license, or never access to a car. Default: true -->
		<param name="ignoreCarAvailability" value="true" />
		<!-- Defines the mode switch behavior. Possible values [fromAllModesToSpecifiedModes, fromSpecifiedModesToSpecifiedModes] Default: fromSpecifiedModesToSpecifiedModes. -->
		<param name="modeSwitchBehavior" value="fromSpecifiedModesToSpecifiedModes" />
		<!-- Defines all the modes available, including chain-based modes, seperated by commas -->
		<param name="modes" value="car,pt" />
	</module>
```

I got confused about terminology here, so for the para `modes`, it says I should define all the modes available. Does it mean I should define "all modes I would like to have for mode innovation", or I should define "all modes that are available in my simulation"? (i.e. I have `car, pt, bike` in my simulation, I only want my car and pt change mode whereas agents with an existing bike mode should keep this mode, what should I define in this parameter?)

Moreover, for the para `modeSwitchBehavior`, it has two possibilities: `from all to specified` and `from specified to specified`, I am wondering if the term "all" represents "all modes in my simulation" or "all modes available" in the description of parameter `modes`?

To make these questions easier, assume I have modes A, B, C and D in my simulation. I want to have Mode A, B and C switch between each other (A change to B, B change to C etc.), whereas I want the agent has mode D doesn't do the mode innovation (keep D forever during 500 iterations). Can I achieve this by setting the changeMode parameters? How should I do it?

**Comment by Janekdererste** [comment]
You can achieve what you want by using the ```from specified to specified``` and have ```<param name="modes" value="A,B,C" />```. 

I think having ```from all to specified``` considers all available modes (ABCD) in your simulation for a change to the specified modes (ABC).

**Comment by jingjunL** [comment]
> You can achieve what you want by using the `from specified to specified` and have `<param name="modes" value="A,B,C" />`.
> 
> I think having `from all to specified` considers all available modes (ABCD) in your simulation for a change to the specified modes (ABC).

Hi Janek, indeed, I have tried this setting out in my simulation and it works very well :)

Thanks for the help! I will close this issue
