### ISSUE TITLE
event.xml.gz file not generated after 10th iteration

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#684]
I ran MATSim simulation for 10 iterations but I can not locate the events.xml.gz file, which we can visualize in Simunto Via. I am using the basic the config file of equil example for my test run. Do we need to write any special module for it in config file?

**Comment by Janekdererste** [comment]
The events file should indeed be part of your output folder. Is there any output at all? If so, could you list what is present?

**Comment by aayushtewari01** [comment]
@Janekdererste , thankyou Sir. So I edited the config file to write event file after 1 iteration, and got the output in events.xml.gz and subsequently in 10.

**Comment by Janekdererste** [comment]
Ah very nice.
