### ISSUE TITLE
I am creating simple agents that are limited to trips between 7:00AM-9;00AM, but the events is between  7:00AM -2:00PM

### ISSUE THREAD

**Issue by Zenilos** [matsim-org/matsim-code-examples#687]
I am defining my agents, going `from A to B at time T` like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plans SYSTEM "http://www.matsim.org/files/dtd/plans_v4.dtd">
<plans xml:lang="de-CH">
   <person id="1">
      <plan>
         <act type="h" link="199174843_0" end_time="08:00" />
         <leg mode="car" />
         <act type="w" link="227401549_0" dur="00:10" />
      </plan>
   </person>
   <person id="2">
      <plan>
         <act type="h" link="28905146_0_r" end_time="08:00" />
         <leg mode="car" />
         <act type="w" link="147668197_0" dur="00:10" />
      </plan>
   </person>
  .
  .
  .
</plans>
```
After simulationn is done, when I parse the  events file after simulation, I have agents that are driving in the city even after 13.
Which part I am doing wrong?

**Comment by Janekdererste** [comment]
My first guess would be, that your agents are stuck in a traffic jam. You could have a look at the traffic pattern in Via or OTFVis and check whether it looks plausible what your agents do.

**Comment by Zenilos** [comment]
I reduced the number of agents and the output is in the same time range of input file.
Thanks.
