### ISSUE TITLE
The combination of two extensions

### ISSUE THREAD

**Issue by XanderPENG** [matsim-org/matsim-code-examples#690]
Is it possible to combine two extensions together? Now I'm trying to simulate the urban freight activities and some vehicles are EVs in the fleet.  So, is there a way to turn a carrier vehicle into an EV and simulate it?

**Comment by tschlenther** [comment]
This is generally possible. The question is where the planning of charging takes place. There are advancements in planning this in jsprit, from where it could be fed into the ev schedule. There are also experiments where EVs preplan their charging for a day within urban areas. But these parts do not communicate with each other (yet) and at least the second thing is only experimental so far.
If you want to track SoC in the first place and then do analysis, it should actually be possible to "combine" both extensions more or less easily:
[EV can be read from the matsim input vehicles file](https://github.com/matsim-org/matsim-libs/pull/1605), where they need to be attributed specifically
