### ISSUE TITLE
Error running MATSim on Eclipse

### ISSUE THREAD

**Issue by fbastarianto** [matsim-org/matsim-code-examples#691]
Hi everyone!

I have an issue related to Java when running MATSim on Eclipse while it works fine when running on matsim.jar.
The error message shown on Eclipse is as follows (starting from line 36).

```
Feb 28, 2022 3:06:43 PM com.google.inject.internal.MessageProcessor visit

INFO: An exception was caught and reported. Message: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper

java.lang.IllegalStateException: Unable to load cache item

at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)

.....

.....
```

I have cut the error message above as it's too long, however, the log outputted from my Eclipse Console is attached to this issue
[output_log.txt](https://github.com/matsim-org/matsim-code-examples/files/8154552/output_log.txt)

I have explored the solution to this matter but I have not found it yet. Would anyone have a solution regarding the error message above?

Thank you

**Comment by mrieser** [comment]
What version of MATSim and what Java version are you using? It looks like one of MATSim's dependency (juice) is not compatible with the Java version you are using. Try it with Java 11, that should work with the latest release, or try a snapshot-version of MATSim that includes an updated dependency that works with newer Java versions.

**Comment by fbastarianto** [comment]
Hi mrieser, thank you for responding to my query.

I am using the latest version of MATSim (Version 13.0 “Spring 2021”, released April 2021). For Java, I installed Java version 11.0.13. According to your reply above, it should be working. Or should I try your second alternative?

**Comment by mrieser** [comment]
MATSim 13 + Java 11 should work. If not, please report here, so we can fix it. But this should be a supported configuration.

**Comment by antboy** [comment]
Hi fazabastarianto,
I am using Eclipse v2021-12 with Java 11 and MATSim 13 and I can run the equil scenario ok in Eclipse.

You need to import, as "an existing Maven project", the 'matsim-code-examples' and then run it by selecting from the project explorer: RunMatsim.java which is under src/main/java org.matsim.codeexamples.run .  
You can change the scenario by changing the run configuration arguments.

**Comment by fbastarianto** [comment]
Hi @mrieser 
I have tried many times yet the same error still appeared.

---------------------------------------------------------

Hi @antboy 
We use the same Eclipse -mine v2021-12 (4.22.0)- with Java 11 and MATSim 13.

I followed the steps on how to import into Eclipse according to this https://github.com/matsim-org/matsim-example-project . However, step number 3 does not work, then I did the right-click to configure->convert to maven project. Still, it does not work when running RunMatsim.java as the same error still appeared.

**Comment by fbastarianto** [comment]
Hi @mrieser 

I am not sure whether this information is useful or not, but here I noticed there is a sign -with lamp and an exclamation mark- in the RunMatsim.java code after running. The code that has this sign are as follows:

```
import com.google.inject.internal.asm.$Type;
import org.matsim.api.core.v01.Id;
import org.matsim.api.core.v01.Scenario;
import org.matsim.api.core.v01.TransportMode;
import org.matsim.api.core.v01.network.Link;
import org.matsim.contrib.otfvis.OTFVisLiveModule;
import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.config.groups.PlanCalcScoreConfigGroup;
import org.matsim.core.config.groups.PlansCalcRouteConfigGroup;
import org.matsim.core.config.groups.QSimConfigGroup;
import org.matsim.core.config.groups.QSimConfigGroup.SnapshotStyle;
import org.matsim.core.config.groups.QSimConfigGroup.TrafficDynamics;
import org.matsim.core.config.groups.QSimConfigGroup.VehiclesSource;
import org.matsim.core.config.groups.StrategyConfigGroup;
import org.matsim.core.controler.Controler;
import org.matsim.core.controler.OutputDirectoryHierarchy;
import org.matsim.core.controler.OutputDirectoryHierarchy.OverwriteFileSetting;
import org.matsim.core.replanning.strategies.DefaultPlanStrategiesModule;
import org.matsim.core.scenario.ScenarioUtils;
import org.matsim.core.utils.collections.CollectionUtils;
import org.matsim.vehicles.VehicleType;
import org.matsim.vehicles.VehicleUtils;
import org.matsim.vis.otfvis.OTFVisConfigGroup;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Set;
```
I have also attached a screenshot showing this sign below. 
<img width="1186" alt="Screenshot 2022-03-02 at 14 44 14" src="https://user-images.githubusercontent.com/100368935/156384533-1f03e40b-d42a-4160-b49f-0b02f6c96431.png">

**Comment by antboy** [comment]
@fazabastarianto
In Eclipse menu, choose File->Import then Maven->Existing Maven Project then enter the directory path to your local copy of matsim-code-examples.

**Comment by fbastarianto** [comment]
Hi @antboy 

I have followed your steps, however, I could not go further as the "next" button is not available when importing Maven Projects and there is also a warning sign stated that "Project matsim-example-project is already imported into workspace" as follows.

<img width="663" alt="Screenshot 2022-03-02 at 15 19 46" src="https://user-images.githubusercontent.com/100368935/156393091-50e25b7b-c90b-4b74-aa9e-05559d7d6418.png">

**Comment by michalmac** [comment]
> We use the same Eclipse -mine v2021-12 (4.22.0)- with Java 11 and MATSim 13.

@fazabastarianto I do not use Eclipse, so I started to wonder what Java 11 means here. Is it language level (Java 11) or JDK version (JDK 11). I am asking, because the error you get is typical for JDK 16. Maybe you run Matsim 13 & Java 11 on JDK 16+?

**Comment by fbastarianto** [comment]
Hi @michalmac 

I have checked regarding to this matter. I run MATSim 13 & Java 11 on JDK 11 (as attached). So it should be working yet it's still showing the error.

<img width="565" alt="Screenshot 2022-03-07 at 14 39 01" src="https://user-images.githubusercontent.com/100368935/157055342-65da1e6f-696b-4795-b822-83f2e88da3de.png">

**Comment by michalmac** [comment]
Thanks for confirming. Maybe try to run `mvn clean package -DskipTests` in the matsim-lib directory. If that works fine then there must be something wrong with Eclipse.

**Comment by fbastarianto** [comment]
Hi @michalmac 

Would you mind helping guide me where I can find the "matsim-lib" directory on the matsim-example-project repository? As I have not found it yet using the search tool. Further, how do I run this code `mvn clean package -DskipTests` in the matsim-lib directory? I do apologise for asking this as I have no experience in Java language, eclipse, and MATSim prior to this, and I have also just been appointed to attend the MATSim lecture at TU Berlin this April 2022.

**Comment by kainagel** [comment]
(0) I am sorry that you are having problems.  It is amazing how many things can go wrong.

(1) If you are using the matsim-example-project setup (which is good), you would have to go to the root of that directory.  Probably `/Users/fazafawzan/git/matsim-example-project` (looking at one of your screenshots).  In any case, it has to be the directory where the File `pom.xml` is located.  Then try `mvn clean package -DskipTests` and report the output.

(2) The "lightbulbs" in your screenshot are not the cause, but a consequence of your problem.  The whole project is not "plugged together".

(3) If you google-search for |guice "java.lang.IllegalStateException: Unable to load cache item"|, then you get answers that seem to point into the right direction.  I.e. some versioning issue as others have already pointed out above.  Possibly your maven is too new for the version of java you have.

(4) What comes out if you type `mvn -v`?  For me, it is
```
[matsim-example-project]$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 14.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/14.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
[matsim-example-project]$ 
```
As you can see, I use java14.  I don't want to downgrade to java11 just to see if I can replicate your error.

**Comment by fbastarianto** [comment]
Hi @kainagel 

Thank you for responding to my query.

1) I have run the `mvn clean package -DskipTests` to send the report of the output

4) Here is what comes out when I try `mvn -v`
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/homebrew/Cellar/maven/3.8.4/libexec
Java version: 17.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "11.5.2", arch: "aarch64", family: "mac"
```

I come up confused when just noticed that the Java version above is Java17, where previously I have installed Java11 on JDK11 as shown in one of my screenshots.

**Comment by kainagel** [comment]
1. I did not receive or find the output from `mvn clean package -DskipTests`.
2. This means that at least on the command line it is picking up the wrong version of java.  I can't say how to fix this; there are several instructions on the web.  I also don't know how these things are plugged together in eclipse (I am using intellij).  Since this is homebrew, you might be able to just uninstall that java version.

**Comment by fbastarianto** [comment]
Hi @kainagel 

1. It seems that I have missed uploading the output from `mvn clean package -DskipTests`. I do apologise for this. Here I have attached the output 
[mvn clean package -DskipTests_Output.txt](https://github.com/matsim-org/matsim-code-examples/files/8216639/mvn.clean.package.-DskipTests_Output.txt)

2. I was trying to remove the Java17. However, I could not remove this as there is no Java17 detected when I tried to type `java -version`, `/usr/libexec/java_home -V` and `ls /Library/Java/JavaVirtualMachines`. So I am not sure whether there are multiple versions of Java installed on my Mac.

**Comment by kainagel** [comment]
Re 2: `brew list` shows all installed packages; one of them should be the java17 package; maybe `openjdk17`.  `brew uninstall openjdk17` should remove that.  (I am sure that there are other fixes to this problem, but some eclipse person needs to come to the rescue.)

Re 1: So it compiles on the command line.  To some extent that makes sense, since what you originally had was a runtime error.  But to some other extent that does not make sense, since what you had in eclipse was a compilation problem.  Hm.  

Can anybody else see the light?

**Comment by kt86** [comment]
Hello, if eclipse is picking up the wrong jdk (with java 17) please have a look at that entry [https://matsim.org/docs/devguide/eclipse/jdk](https://matsim.org/docs/devguide/eclipse/jdk). This was originally written some time ago for setting up eclipse for MATSim developer -> You need to adapt it to your jdk version you want to use and to the path on your computer. And I cannot say whether this way of checking and changing the configuration is still available in current eclipse versions...

Maybe that helps... good look!

**Comment by fbastarianto** [comment]
Hi @kainagel and @kt86 

Thank you for your help. I have solved the issue by changing the JRE version on my Eclipse. I changed the previous JRE (17.0.1) to JRE (11.0.13). Then I run `RunMatsim` and `MATSimGUI` and these two works well.

**Comment by kainagel** [comment]
Hooray! :-)
