### ISSUE TITLE
demandGenerationFromShapeFile .csv file structure

### ISSUE THREAD

**Issue by cedricvdbd** [matsim-org/matsim-code-examples#698]
Hi, 

when trying to use this class I run into multiple issues: 

1. As the links to the original data is not working anymore I can't figure out what the structure of the data should be. Especially for the commuter statistics this proves to be an issue. Currently I'm working with these headers, but this is not ideal as there is two times the header "Schlüssel". 
![Bildschirmfoto 2022-03-12 um 23 12 29](https://user-images.githubusercontent.com/75860447/158036827-1be4dd4e-7f70-4ad4-8a0d-7e535d99c5bf.png)

2. When I run RunCreateDemand I get this error: 
![Bildschirmfoto 2022-03-12 um 23 15 44](https://user-images.githubusercontent.com/75860447/158036926-9f36d783-ccc7-4e8b-8e54-f12a9db121d7.png)
So, I figure there must be some error with the handling of duplicates, so I tried this solution: https://stackoverflow.com/questions/68907511/duplicate-key-attempted-merging-values-x-and-x
However, this gives me an empty population file. 

I assume there is something wrong with the structure of my .csv files. Does someone have the answer I'm looking for? 

Thank you in advance for your kind reply. 

Cédric

**Comment by Janekdererste** [comment]
The error you have says, that there is a duplicate key when loading the shape file of the different regions on [linke 78](https://github.com/matsim-org/matsim-code-examples/blob/c67c1cdf670be7e1e3635375f1e8e72324bf805e/src/main/java/org/matsim/codeexamples/population/demandGenerationFromShapefile/CreateDemand.java#L77). This means your shape file has two features with the same value for the "RS"-Attribute. 

The code assumes that each feature only occurs once. So, you have to either make sure, that the shape file you are using has features with unique values in the "RS"-Attribute, or you can use another Attribute - which is unique - to distinguish your Shapefile Features
