### ISSUE TITLE
Average trip duration between "lastepoch.legduration.txt" and "output_trips.csv.gz" is inconsistency

### ISSUE THREAD

**Issue by 162-web** [matsim-org/matsim-code-examples#699]
Hello, everyone.

I found that the calculated average trip duration is not consistency between "lastepoch.legduration.txt" and "output_trips.csv.gz" .

- The average trip duration in the "50.legduration.txt" is about **37 min** at the last iteration (Fig.1).

![image](https://user-images.githubusercontent.com/58126178/158123304-4a03dd74-1e7b-4594-a402-164de457f435.png)
                                                                                         `Fig.1`

- The average trip duration calculated from "output_trip.csv.gz" is about **120 min** (Fig.2). I have converted the unit of travel time to minutes with Python, and also checked the codes.
![image](https://user-images.githubusercontent.com/58126178/158127220-fdb66f70-3df3-4e92-9a3c-3327d7959a0d.png)

`Fig.2`

I don't understand why the average trip duration is not consistency?

I’d appreciated if anyone could help with the problem.

**Comment by jfbischoff** [comment]
The issue is one with the wording. 
In the .legdurations.txt, it should be average leg duration, not trip duration. 
The values in the trips.csv are thus the correct ones.

**Comment by 162-web** [comment]
Thank you very much!
