### ISSUE TITLE
Specifications for running in a cluster

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#7]
Hello all,
  I am working with a scenario for the city of Amsterdam with about 140000 agents. The modes available are pt, car, taxis/avs, walk, and bike. Due to the size of the scenario, I am running it in a HPCC in Netherlands. I have exhausted my allocated budget (core-hours) and I am applying for more. I have to fill in an application form for this which describes the project and my simulation specifications. I would appreciate some help with some of the questions in the application form(mentioned below) from people who have already used such a facility.
  
Describe the implementation details of your numerical approach for the preferred system (MPI, OpenMP, hybrid, CUDA, OpenCL, OpenACC, ….);
Which standard package(s) (application software, if any) and which libraries will be used ?
Indicate the parallel performance of the code(s) you plan to use;
Indicate how much memory and how much I/O (volume and bandwidth) will be needed.

Regards,
Jishnu

**Comment by mrieser** [comment]
Hi Jishnu,
It's hard to answer all these questions without knowing more details about your scenario, but in general:
- MATSim does currently not use any of the technologies (MPI, OpenMP, CUDA, ...). It's just one Java process that uses multithreading
- Java 8 will be required
about the parallel performance and memory, this depends on your scenario and your configuration and scenario.

**Comment by ghost** [comment]
Hello Marcel,
  Thank you for the reply. My simulations take around an hour for an iteration with 140000 agents and 2000 avs. The config file is given below: 

<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
	<!-- Fare start -->
	<module name="taxifare">

		<!-- Basefare per Trip (fare = positive value) -->
		<param name="basefare" value="0.5" />

		<!-- Daily subscription fee (fee = positive value) -->
		<param name="dailySubscriptionFee" value="0.0" />

		<!-- taxi fare per meter (fee = positive value) -->
		<param name="distanceFare_m" value="0.0002" />

		<!-- taxi fare per hour (fee = positive value) -->
		<param name="timeFare_h" value="3.6" />
	</module>
	
	<!-- Fare end -->
	<module name="dvrp">
		<param name="mode" value="taxi" />
	</module>

	<module name="taxi">
		<param name="destinationKnown" value="false" />
		<param name="vehicleDiversion" value="false" />
		<param name="pickupDuration" value="120" />
		<param name="dropoffDuration" value="60" />
		<param name="onlineVehicleTracker" value="false" />
        
        <param name="breakIfNotAllRequestsServed" value="false" />
		<param name="changeStartLinkToLastLinkInSchedule" value="true" />
		
		<param name="taxisFile" value="taxi_vehicles(7085).xml" />

		<!--<param name="timeProfiles" value="true" />
		<param name="detailedStats" value="true" /> -->

		<parameterset type="optimizer">
			<param name="type" value="RULE_BASED" />
			<param name="id" value="example" />
			<param name="goal" value="DEMAND_SUPPLY_EQUIL" />
			<param name="nearestRequestsLimit" value="40" /> <!--99999 -->
			<param name="nearestVehiclesLimit" value="40" /> <!--99999 -->
			<param name="cellSize" value="1000" />
		</parameterset>
	</module>

	<module name="global">
		<param name="randomSeed" value="8000" />
		<param name="coordinateSystem" value="Atlantis" />
		<param name="numberOfThreads" value="5" />
	</module>
	
	<module name="parallelEventHandling" >

		<!-- Estimated number of events during mobsim run. An optional optimization hint for the framework. -->
		<param name="estimatedNumberOfEvents" value="null" />

		<!-- Number of threads for parallel events handler. 0 or null means the framework decides by itself. -->
		<param name="numberOfThreads" value="5" />

		<!-- If enabled, each event handler is assigned to its own thread. Note that enabling this feature disabled the numberOfThreads option! This feature is still experimental! -->
		<param name="oneThreadPerHandler" value="false" />

		<!-- If enabled, it is ensured that all events that are created during a time step of the mobility simulation are processed before the next time step is simulated. E.g. neccessary when within-day replanning is used. -->
		<param name="synchronizeOnSimSteps" value="true" />
	</module>
	
	<module name="network">
		<param name="inputNetworkFile" value="new.xml" />
	</module>

	<module name="plans">
		<param name="inputPlansFile" value="AlbatrossAgentsCleaned_Sample_Stable.xml" />
	</module>

	<module name="controler">
		<param name="outputDirectory" value="./Results for Amsterdam Sample(3-1-1)/output/intermodalExample" />
		<param name="firstIteration" value="0" />
		<param name="lastIteration" value="100" />
		<param name="eventsFileFormat" value="xml" />
		<param name="writeEventsInterval" value="100" />
		<!-- iterationNumber % writePlansInterval == 0 defines (hopefully) in which iterations plans are written to a file. `0' disables plans writing completely.  Some plans in early iterations are always written -->
		<param name="writePlansInterval" value="5" />
		<!-- iterationNumber % writeSnapshotsInterval == 0 defines in which iterations snapshots are written to a file. `0' disables snapshots writing completely -->
		<param name="writeSnapshotsInterval" value="0" />
		<param name="mobsim" value="qsim" />
	</module>

	<module name="qsim">
		<!-- "start/endTime" of MobSim (00:00:00 == take earliest activity time/ run as long as active vehicles exist) -->
		<param name="startTime" value="00:00:00" />
		<param name="endTime" value="30:00:00" />
		<param name="simStarttimeInterpretation" value="onlyUseStarttime"/>
		<param name="flowCapacityFactor" value="0.01" />
		<param name="storageCapacityFactor" value="0.01" />
	
		<param name = "snapshotperiod"	value = "00:00:00"/> <!-- 00:00:00 means NO snapshot writing -->
	</module>

	<module name="planCalcScore">
		<param name="learningRate" value="1.0" />
		<param name="BrainExpBeta" value="2.0" />
        <!-- fraction of iterations at which MSA score averaging is started. The matsim theory department suggests to use this together with switching off choice set innovation (where a similar switch exists), but it has not been tested yet. -->
		<param name="fractionOfIterationsToStartScoreMSA" value="0.8" /> 
		 <param name="marginalUtilityOfMoney" value="-0.685" />
		 
		<param name="lateArrival" value="-18" />
		<param name="earlyDeparture" value="-0" />
		<param name="performing" value="+6" />
		<param name="traveling" value="-6" />
		<param name="waitingPt" value="-12.0" />
		<param name="utilityOfLineSwitch" value="-0.5" />
		<!--
		<param name="traveling_taxi" value="0" />
		<param name="traveling_car" value="0" />
		<param name="traveling_transit_walk" value="0" />
		<param name="traveling_pt" value="10" />
		<param name="waiting" value="-0" />
		
		-->
		
		<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="-12" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6" />
				<param name="mode" value="car" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="40" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6" />
				<param name="mode" value="pt" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.000154" />
			</parameterset>
			<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="9" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6" />
				<param name="mode" value="walk" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="-6" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="bike" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="0.0" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="ride" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="0.0" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="other" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="40" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="taxi" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.00154" />
			</parameterset>
			<parameterset type="modeParams" >
				<!-- [utils] alternative-specific constant.  no guarantee that this is used anywhere. default=0 to be backwards compatible for the time being -->
				<param name="constant" value="0.0" />
				<!-- [utils/m] utility of walking per m, normally negative.  this is on top of the time (dis)utility. -->
				<param name="marginalUtilityOfDistance_util_m" value="0.0" />
				<!-- [utils/hr] additional marginal utility of traveling.  normally negative.  this comes on top of the opportunity cost of time -->
				<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
				<param name="mode" value="transit_walk" />
				<!-- [unit_of_money/m] conversion of distance into money. Normally negative. -->
				<param name="monetaryDistanceRate" value="0.0" />
			</parameterset>
			
			<parameterset type="activityParams">
			<param name="activityType" value="work" />
			<param name="typicalDuration" value="08:00:00" />
			<param name="openingTime" value="04:00:00" />
			<param name="latestStartTime" value="18:00:00" />
			<param name="closingTime" value="23:00:00" />
			<param name="priority" value="1.0" />
		</parameterset>

		<parameterset type="activityParams">
			<param name="activityType" value="home" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="12:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="bringget" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="01:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="business" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="08:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="shoppingD" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="04:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="shoppingND" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="04:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="service" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="04:00:00" />
			
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="sozializing" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="08:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="leisure" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="08:00:00" />
		</parameterset>
		
		<parameterset type="activityParams">
			<param name="activityType" value="touring" />
			<param name="priority" value="1.0" />
			<param name="typicalDuration" value="12:00:00" />
		</parameterset>
	  	
	</module>

	<module name="strategy">
	    <param name="fractionOfIterationsToDisableInnovation" value="0.8" />
		<param name="maxAgentPlanMemorySize" value="3" /> <!-- 0 means unlimited -->

		<param name="ModuleProbability_1" value="0.7" /> <!--0.7 -->
		<param name="Module_1" value="BestScore" />

		<param name="ModuleProbability_2" value="0.1" />   <!--0.1 -->
		<param name="Module_2" value="ReRoute" />

		<param name="ModuleProbability_3" value="0.1" />  <!--0.1 -->
		<param name="Module_3" value="TimeAllocationMutator" />

		<param name="ModuleProbability_4" value="0.1" />  <!--0.1 -->
		<param name="Module_4" value="ChangeTripMode" />
	</module>

	<module name="transit">
		<param name="useTransit" value="true" />
		<param name="transitScheduleFile" value="transitSchedule.xml" />
		<param name="vehiclesFile" value="transitVehicle.xml" />
		<param name="transitModes" value="pt" />
	</module>
	
	<module name="changeMode">
		<param name="modes" value="pt,car, taxi,walk,bike" />
	</module>

</config>

**Comment by JWJoubert** [comment]
I would recommend noting Maven too, if you plan to do a Maven build on the server . At least that's what we're doing, and we had to explicitly have a Maven module installed on the cluster.
