### ISSUE TITLE
VolumesAnalyzer aggregating all pt volumes into "car" mode

### ISSUE THREAD

**Issue by LockeBirdsey** [matsim-org/matsim-code-examples#70]
Need to get link volumes out for buses, cars and trams. However the VolumesAnalyzer returned by controler.getVolumes() only has the "car" mode registered, but each of the volumes returned is an aggregate of the valid pt sub-modes (in my case: bus, train, tram, subway) for each link.

**Comment by golanbendor** [comment]
Inside the [VolumesAnalyzer ](https://github.com/matsim-org/matsim/blob/5b77bd781d18a2c11d44b31ef8180cfa4e2a9af8/matsim/src/main/java/org/matsim/analysis/VolumesAnalyzer.java#L46)class you have some overloading methods for multi-modal support

**Comment by LockeBirdsey** [comment]
I am aware of this and have already set `observeModes` to true. 
After some digging, it appears that every event triggered generates a vehicleId of "car", even on links that do not specify "car" as a valid mode.
