### ISSUE TITLE
Is it possible to assign priorities to vehicles ?

### ISSUE THREAD

**Issue by abouuuu** [matsim-org/matsim-code-examples#702]
I was wondering if it's possible to assign different priorities to vehicles..

**Comment by Janekdererste** [comment]
Could you be more specific please?

**Comment by abouuuu** [comment]
Sure thing.. My bachelor's thesis project is about priority-based constrained routing for road vehicle, so in a certain network i will be having priorities set for each vehicle.. for instance, if a pedestrian car and an ambulance are both willing to go from point A to point B and their trips are starting at the same exact time, of course the ambulance has the higher priority so the ambulance will take the shortest path and the pedestrian car will have to be re-routed to another route (which night be longer).. Long story short, i hope you understood what i meant by assigning priorities to vehicles (which will be decided based on lot's of different factors, i just took the example of an ambulance and a pedestrian car so you get the idea) and i wanted to know if it's possible to add that "priority" attribute to vehicles so i can simulate my algorithm once I'm done with it

**Comment by abouuuu** [comment]
> Could you be more specific please?

Sure thing.. My bachelor's thesis project is about priority-based constrained routing for road vehicle, so in a certain network i will be having priorities set for each vehicle.. for instance, if a pedestrian car and an ambulance are both willing to go from point A to point B and their trips are starting at the same exact time, of course the ambulance has the higher priority so the ambulance will take the shortest path and the pedestrian car will have to be re-routed to another route (which night be longer).. Long story short, i hope you understood what i meant by assigning priorities to vehicles (which will be decided based on lot's of different factors, i just took the example of an ambulance and a pedestrian car so you get the idea) and i wanted to know if it's possible to add that "priority" attribute to vehicles so i can simulate my algorithm once I'm done with it

**Comment by Janekdererste** [comment]
Each agent in MATSim performs its routing individually. If an agent does a re-routing of some trip, it will select the path the the least cost (usually the one with the shortest Travel Time). Whether this was a good choice is then determined during the mobsim, where the different agents compete about the limited capacity of the road network. 

I haven't understood yet, why the car can't take the same route as the ambulance?

**Comment by abouuuu** [comment]
I understand that perfectly, the thing is my project is about constrained routing, for instance, road x is constrained to a certain threshold (determined by multiple factors), if a car gets routed to pass by that road x, we need to check if the threshold will be passed or not, if yes, the car needs to be re-routed, if no, the car gets to go in, so at the time of the routing, cars with higher oriority get to get routed first. 
Let's make it more clear, so road x has a threshold of 10, we have car Y that affects by 5 and car Z that affects by 6. Cary Y gets routed to road X first as it has the highest priority and now we have 5, car Z wants to go by road X but it affects by 6 and (6+5=11 > 10) then car Z needs to be re-routed and can't pass by road x. 
It's a little confusing but i hope i could make it a little bit more clear ..

**Comment by Janekdererste** [comment]
This is not supported out of the box. The MATSim loop has three steps:
1. Generation of plans - For example by re-routing
2. Excecution of plan - This is the part where constraints are enforced and where it is figured out whether the planned behaviour works with applied constrains
3. Evaluation of the executed plan. Each plan receives a fitnes score. Plans with low scores will be discarded. 

This leads to an equlibrium where each agent can't improve its score unilateraly anymore. See also http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf Chapter 1. 

The routing, as said, is done individually and independent of other vehicles. The part to figure out constraints is the mobsim. 

I guess what you propose could be implemented. It sounds like a certain Link has a certain capacity (in your example 10) and certain types of vehicles consume different ammount of capacity.

In MATSim each link has a ```capacity``` value. This indicates how many Passenger Car Equivalent Units (PCE) can travel this link per hour. This constraint is enforced when vehicles leave a link. Now, you could define different vehicle types which have different PCE. We have this for cars and bikes usually. Cars have a PCU of 1, bikes have a PCU of 0.25. If a link has a capacity of 1000, 1000 cars or 4000 bicycles can pass this link within one our (Or any combination). 

Now, the constraint of who can go first is not implemented by default. However, you could sort the buffer of the previous link by priority. This would have to be programmed though. If you want to spend your Bachelor Thesis programming something in MATSim and if you have somebody at hand who can help you, I'd say it is achievable. If you just want to use some tool to do the kind of routing you"ve described, I'm afraid this functionality is not available

**Comment by kainagel** [comment]
Maybe have a look at the Ph.D. dissertation of Laura Bieker.  But that would be SUMO, not MATSim ...

**Comment by tthunig** [comment]
If you want to implement vehicle priorities into MATSim, I think, you should not change the routing but the queue implementation of the links. In the default implementation (see QueueWithBuffer), each link works as a FIFO (first in first out) queue. If you change this and order vehicles in the link queues according to their priorities, vehicles with higher priorities will automatically be allowed to leave the links with restricted capacity earlier than vehicles with lower priorities. This influences the scores and with that indirectly influences the routing in the next iterations.
But as Janek already mentioned, this will require some programming effort.
