### ISSUE TITLE
Event networkMode is always "car" preventing VolumesAnalyzer return correct pt volumes

### ISSUE THREAD

**Issue by LockeBirdsey** [matsim-org/matsim-code-examples#71]
(Extension of #70 as this is technically a different issue)
In the execution events, every networkMode is set to "car" even when the event is for a non-car e.g. bus, train, etc. This directly affects how volumes in VolumeAnalyzer are calculated. This seems like correct behaviour as how networkModes are defined (in the planCalcRoute module?), but how can you then get volumes of pt modes?

Just in case I'm missing something, my qSim.mainMode is set to are "car,train,tram,bus,subway,bicycle" and transit.transitModes is set to "bus,tram,subway,rail", each vehicle is defined in a vehicles.xml (for qsim) and a transitVehicles.xml (for the transit module)

**Comment by mrieser** [comment]
I think this is a know issue with public transport, that all pt vehicles use "car" during the simulation: https://matsim.atlassian.net/browse/MATSIM-533

**Comment by LockeBirdsey** [comment]
Forgot to close this issue, was resolved shortly after. Just created a lookup table and extended the VolumesAnalyzer.
