### ISSUE TITLE
zero vehicles on links

### ISSUE THREAD

**Issue by fernandabmallon** [matsim-org/matsim-code-examples#711]
Hello! I have been experimenting with MATSim for a few weeks, and recently encountered a problem that doesn't present any errors. The simulation runs just fine, but the results demonstrate that there are no vehicles in any of the links. I have concluded the problem is with the network because that's the only change I made, but I have no idea what the problem is. 
Basically I ran the scenario (in GUI) with a network from OpenStreetMap, but obtained poor results comparing with counts. Then I tried converting a network available from the city's mobility plan, which showed no errors, but also showed no vehicles in any of the links. Can anybody spot what the error is or what can I do to find it?

PS: all the files used in the simulation are uploaded on [https://github.com/fernandabmallon/fernandabmallon](url), where the network from OSM is named "network_MATSim", and the network from the city's mobility plan is "network_MATSim_PLAMUS"

**Comment by Janekdererste** [comment]
did you solve your issue, or should I still look into your problem?

**Comment by fernandabmallon** [comment]
couldn't solve it yet, still trying to calibrate the results obtained with the OSM network, since it's the only one working. But I would appreciate some help with the network from the city's mobility plan.

**Comment by Janekdererste** [comment]
I have tried to run your set up. One thing I have noticed is that you had set the following parameters to zero.
```
<!-- iterationNumber % writeEventsInterval == 0 defines in which iterations events are written to a file. `0' disables events writing completely. -->
<param name="writeEventsInterval" value="0" />
<!-- iterationNumber % writePlansInterval == 0 defines (hopefully) in which iterations plans are written to a file. `0' disables plans writing completely.  Some plans in early iterations are always written -->
<param name="writePlansInterval" value="0" />
```
This disables the writing of output plans and events. If you want to visualize what your agents did during the last iteration's mobsim, those files are essentially what you need. A good default value for both files is 50, which means that those files are written every 50th iteration, as well as in the last iteration. 

With the events file being written out I can see a lot of traffic with both networks. 

Does this answer your question, or did I miss something?

**Comment by fernandabmallon** [comment]
Yes! It is working now, thanks!
