### ISSUE TITLE
DRT : OutOfMemoryError

### ISSUE THREAD

**Issue by sinkan851014** [matsim-org/matsim-code-examples#716]
Hi MATSim Community, I was trying to use drt contribute by RunMultiModeDrtExampleIT  to run my scenario.
However, it got error when only replaced plan and network.

I think the problem may cause by network(also crash when there is only one agent in network), but it worked well when I simulate the same scenario by "matsim-example-project".

Besides, I has adjusted the memory setting to 8GB in intellij.

Running enviroment:
mac air M1(2020), 8gb ram.
Java version 11.

The log files and config, network is:

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/8562222/logfile.log)
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/8562522/logfileWarningsErrors.log)

[plan, config, vehicle.zip](https://github.com/matsim-org/matsim-code-examples/files/8562503/plan.config.vehicle.zip)

[TaoyuanCity_boundary_3826_fixed.xml.zip](https://github.com/matsim-org/matsim-code-examples/files/8562338/TaoyuanCity_boundary_3826_fixed.xml.zip)

Thanks!

**Comment by jfbischoff** [comment]
Hi,
at least according to the logfile only 2GB of RAM have been allocated.
2022-04-26T18:19:09,072  INFO Gbl:71 max. Memory: 2048.0MB (2147483648B)

Maybe you have mixed up Program and VM options in intelliJ?
The VM option should be -Xmx8g

Bests

**Comment by sinkan851014** [comment]
Dear @jfbischoff ,

I had set VM option to

-Xms4096m
-Xmx8000m
-XX:ReservedCodeCacheSize=512m
-XX:+IgnoreUnrecognizedVMOptions
-XX:+UseG1GC
-XX:SoftRefLRUPolicyMSPerMB=50
-XX:CICompilerCount=2
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-ea
-Dsun.io.useCanonCaches=false
-Djdk.http.auth.tunneling.disabledSchemes=""
-Djdk.attach.allowAttachSelf=true
-Djdk.module.illegalAccess.silent=true
-Dkotlinx.coroutines.debug=off
-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof

but log still show 
2022-04-26T21:34:57,529  INFO Gbl:71 max. Memory: 2048.0MB (2147483648B)

The problem may be from otherwhere.
Could you run this scenario by my data successfully?

Thanks!

Cooper

*Update: Try another desktop computer with 16gb ram, crash again.

**Comment by sinkan851014** [comment]
Problem solved!

setting vm option in here with  -Xmxs 16g would be run!

Closed this issue.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/80673880/165367154-38ae74d0-0c88-4b5d-a4a2-99e3f636b925.png">
