### ISSUE TITLE
Comparing Calibrated MATSim Scenario's Network Travel Time with the Reality Data

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#720]
Hi everyone,

I have a calibrated MATSim scenario and I would like to validate its performance. Suppose I have some OD pairs `point a & b`, I can put point a and b into Google Map to calculate the estimated travel time between these two points. However, I am wondering how can I get the simulated car network travel time on MATSim for the same OD pair? Which tools/outputs can I use?

Thanks very much for your help in advance :)

---------------------------------------------------------------
A quick update: 

Indeed, I know, from the matsim trip file, I can see the actual travel time of this agent travelling between these two points. However, suppose this agent is travelling between 1pm to 2pm, the travel time from the trip output is only for this period. Let's say I would like to know the travel time between this OD during the morning peak, it is very unlikely that I can find another agent travelling between two points during the morning peak. How should I get the travel time for this situation?

Hope I have explained my questions well. Thanks!

**Comment by fredshone** [comment]
Hi @jingjunL,

we use a variety of approaches for validating performance, the most common:

1. compare aggregated flows of vehicles (eg count/hour) against observed data
2. compare average speed across a link (also per hour typically) to observed data
3. compare individual agent trip durations to google API duration queries

We do the former two so often that they are built into a post processing tool called [elara](https://github.com/arup-group/elara).

Our experience is that no one asks for validation of link flows or speeds where no vehicles might be simulated for an hour.

Your specific request sounds like extracting "skims" to me. These would normally aggregate origins and destinations spatially, ie from zone to zone (or region). Such that you would be able to witness some trips for (most of) your zones. Such skims are pretty popular with transport folks, especially economists, but I'm not sure if/how observed data would be available. Therefore I'm not sure how useful as validation.

You can post process this yourself or use SBBs "skimmer" described [here](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions#skim-matrices).

**Comment by jingjunL** [comment]
> Hi @jingjunL,
> 
> we use a variety of approaches for validating performance, the most common:
> 
> 1. compare aggregated flows of vehicles (eg count/hour) against observed data
> 2. compare average speed across a link (also per hour typically) to observed data
> 3. compare individual agent trip durations to google API duration queries
> 
> We do the former two so often that they are built into a post processing tool called [elara](https://github.com/arup-group/elara).
> 
> Our experience is that no one asks for validation of link flows or speeds where no vehicles might be simulated for an hour.
> 
> Your specific request sounds like extracting "skims" to me. These would normally aggregate origins and destinations spatially, ie from zone to zone (or region). Such that you would be able to witness some trips for (most of) your zones. Such skims are pretty popular with transport folks, especially economists, but I'm not sure if/how observed data would be available. Therefore I'm not sure how useful as validation.
> 
> You can post process this yourself or use SBBs "skimmer" described [here](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions#skim-matrices).

That's very interesting @fredshone. It's my first time hearing about this tool, I will check it out! Thanks
