### ISSUE TITLE
OSM to XML

### ISSUE THREAD

**Issue by 123-Njayou** [matsim-org/matsim-code-examples#721]
Hello I have difficulty converting an osm file into an xml file. I open the file with a text editor and I rename it but the file is not acceptable in VIA. I would like to have the possible solutions of conversion.
I would also like to know how the conversion is done with eclipse. I would also like to know how the conversion is done with eclipse. Thank.

**Comment by Janekdererste** [comment]
The osm file format is not the same as the matsim network file. As you have already guessed, the osm data must be converted. Here https://github.com/matsim-org/matsim-code-examples/blob/14.x/src/main/java/org/matsim/codeexamples/network/RunCreateNetworkFromOSM.java is an example script which you can use.

**Comment by 123-Njayou** [comment]
Thank you for the intervention I will use your script I return to you in difficulty thank you.
