### ISSUE TITLE
Road Pricing Issue 

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-code-examples#73]
Following the tutorial on roadpricing and I am unable to reproduce - https://www.matsim.org/apidocs/core/0.4.0/org/matsim/roadpricing/package-summary.html

Matsim Version - `0.10.1`

config:

```
      <module name="scenario">
		<param name="useRoadpricing" value="true" />
	</module> 

	<module name="roadpricing">
		<param name="tollLinksFile" value="./road_pricing.xml.gz" />
	</module>
```
Error:
`java.lang.RuntimeException: Unmaterialized config group: roadpricing`

**Comment by golanbendor** [comment]
It looks like your missing the ConfigGroup of the RoadPricing contrib.
Look into this class [RunRoadPricingUsingTollFactorExample.java](https://github.com/matsim-org/matsim/blob/master/contribs/roadpricing/src/main/java/org/matsim/roadpricing/run/RunRoadPricingUsingTollFactorExample.java) or try using the following:
                

		//load config 
		Config config = ConfigUtils.loadConfig("yourconfigfile.xml");

		//add RoadPricing ConfigGroup
		RoadPricingConfigGroup rpConfig = ConfigUtils.addOrGetModule(config, RoadPricingConfigGroup.class);
		rpConfig.setTollLinksFile("yourtollfile.xml");

		//load config into scenario
		final Scenario scenario = ScenarioUtils.loadScenario(config);

		//create Controler and run
		Controler controler = new Controler(config);
		controler.setModules(new ControlerDefaultsWithRoadPricingModule());
		controler.run();

**Comment by gac55** [comment]
Thanks @golanbendor! 

I'm unfamiliar with initiating matsim in this way.

I generally execute `java -cp matsim-0.10.1.jar org.matsim.run.Controler config.xml`

How would I go about executing the code snippet above? Apologies for a relatively simple question (new to both matsim and java)

**Comment by golanbendor** [comment]
It is better to start with a clone of the [matsim-example-project](https://github.com/matsim-org/matsim-example-project) and then check out the class [RunMatsim](https://github.com/matsim-org/matsim-example-project/blob/master/src/main/java/org/matsim/run/RunMatsim.java) as starting point. @gac55  I hope this helps.

**Comment by jinkai89** [comment]
@golanbendor How to change the RunRoadPricingUsingTollFactorExample.java so that public transit won't be charged?
