### ISSUE TITLE
Research on plate-number restriction

### ISSUE THREAD

**Issue by hsyfyc** [matsim-org/matsim-code-examples#730]
Hello,
I want to do some research on plate-number based car driving restriction in MATSim, but I don't know how to do it.  The result I want to achieve is that person whose plate-number is odd can not use the specific link. Is there any way to solve this problem?
Can anyone help me, please? Thanks.

**Comment by Janekdererste** [comment]
In general this should be possible. However, this would require some Java programming skills. I would think you could get away with the following steps:

- Generate Vehicles with license plates. This could be done by assigning the plate number as id, or by adding a license plate attribute
- Assign vehicles to persons. The vehicles must be assigned to the persons. By default Matsim does that automatically but then the vehicles are also automatically generated
- Replace the `TravelTime` like [here](https://github.com/matsim-org/matsim-code-examples/blob/15.x/src/main/java/org/matsim/codeexamples/router/example20customTravelTime/RunCustomTravelTimeExample.java) For license plates with odd numbers you could return a very high travel time which should be comparable to restricting the entirely

A second approach could be to have two vehicle types. One of type odd and one of type even. Then you could implement the restrictions via the `allowedMode` parameter on the network. Something along the lines of [this example](https://github.com/matsim-org/matsim-code-examples/blob/fb11acabc18792aa25cfb1e9c001d0ef2e85a8f9/src/main/java/org/matsim/codeexamples/network/RunCreateNetworkFromOSM.java#L66) In this case you would also have to get the distribution of odd and even license plates right.

**Comment by hsyfyc** [comment]
Thanks for your reply.
