### ISSUE TITLE
Bus routes

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#732]
Hello,
In the transit schedule, if we have a bus going from node 1 to node 9 and returning from node 9 to node 1, these 2 routes have to be created as 2 routes under the same transit line or as 2 different transit lines?

Thank you.

**Comment by Janekdererste** [comment]
Both would work. The hierarchy in the schedule is as follows:

TransitLine -> TransitRoute -> Departure

Each line can have multiple routes which contain stop references. Depending on what you want to model you could have two separate routes serving those directions, or two routes of the same line serving those directions.

**Comment by ghost** [comment]
Ok thank you.
