### ISSUE TITLE
Running specific vehicle 

### ISSUE THREAD

**Issue by sarah-heejeong** [matsim-org/matsim-code-examples#737]
Hello,

I am designing a simulation that shows the behaviors of particular agents and vehicles
I have a network.xml file, but have been struggling to create other files that need to run the simulation (such as population.xml file).

A simple scenario would be that 30% of agents drive trucks, rest of the agents drive cars. 
All truck drivers travel long distances (around 10 hours a day), and they have different designated destinations and return points. 
For those agents I would like them to drive on the assigned highways - can this be also set up in the plan file?
I don't have access to the details of the population, so I am currently setting the arbitrary population, assuming that the population consists of only the drivers. -- no other types of agents (if possible).
Even if I would like to focus on the truck drivers' plans and activities, do I need to set up the plans for non-truck drivers? 
Or can I set up the plan for the different number of agents that I would like to simulate (for example, 4 different plans) and multiply by 250, if I want to see the result of the simulation with 1000 agents?

Thank you all for your help, in advance.

**Comment by Janekdererste** [comment]
There are some exmpamples of how to create a population [here](https://github.com/matsim-org/matsim-code-examples/tree/15.x/src/main/java/org/matsim/codeexamples/population/demandGeneration) and [here](https://github.com/matsim-org/matsim-code-examples/tree/15.x/src/main/java/org/matsim/codeexamples/population/demandGenerationFromShapefile) and [here](https://github.com/matsim-org/matsim-code-examples/tree/15.x/src/main/java/org/matsim/codeexamples/population/demandGenerationWithFacilities)

Everything you plan is possible. In general a plan consists of a list of alternating `Activity`, `Leg` elements. It is sufficient to only specify activity locations and end-times/durations. The legs need to have a mode with which the agent is supposed to do the leg. Everything else will be handled by Matsim. This includes: Finding the nearest link for activity locations, finding routes for each leg, assigning vehicles based on your `vehicles.xml` file to the agents. 

If you want to have more control, you can also specify all the information beforehand and store them in the plans file. 

Also refer to the [user guide](http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf) chapter 2. Your particular questions are handled in chapter 2.3.1.2.

**Comment by sarah-heejeong** [comment]
Hello Janek,

Thank you for providing the resources!
I was looking for a method to plan one-way long distance travel with only one agent, and I was wondering if I can manually plan this with the population of 1 person. Do I still need to generate a decent number of agents even though I want to simulate the scenario with one person (truck driver)?

Thank you.

**Comment by sarah-heejeong** [comment]
Hello Janek,

Thank you for providing the resources.
I am designing the scenario that a one-way long distanced travel in a day.
As of now, I just like to see the behavior of one agent in our scenario. Should I still need to create a decent population (ex. 100 agents in the population.xml file) by using the generator in the link, or would it be fine to manually write the code for one agent and assign him the plan (which will be the path the driver drives)?

+
I see there are also some files that include a tiny population and one-way travel plan in the example project.
Would modifying those files be a good start, as a small population with one-way travel data are what I need to run the scenario.

**Comment by Janekdererste** [comment]
> would it be fine to manually write the code for one agent and assign him the plan

Yes, that would  be fine. 

> Would modifying those files be a good start

That sounds like a good idea :-)

**Comment by sarah-heejeong** [comment]
@Janekdererste 

Hello Janek, 

Thank you for your reply!
