### ISSUE TITLE
Insert congestion on a specified link at a certain time

### ISSUE THREAD

**Issue by EMES92** [matsim-org/matsim-code-examples#74]
Hi, i would like to know if there is a way to create congestion on a certain link in a specific moment, for example saturating the link-capacity. I would do this to test the re-planning strategy. I don't know if there is a simple way just adding some cars stopped on a certain link in the "population.XML" (in this case how to do it? )or there is a way to add in the Java code...could anyone post a code example?

**Comment by kainagel** [comment]
Maybe time-dependent network?  See RunTimeDependentNetworkExample in matsim-code-examples, or the time-dependent network in the user guide.  If this is not enough info to get started, please ask back.

On 18. Jan 2019, at 18:07, EMES92 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, i would like to know if there is a way to create congestion on a certain link in a specific moment, for example saturating the link-capacity. I would do this to test the re-planning strategy. I don't know if there is a simple way just adding some cars stopped on a certain link in the "population.XML" (in this case how to do it? )or there is a way to add in the Java code...could anyone post a code example?

**Comment by EMES92** [comment]
Thank you very much and thank you for the speed, it was just what I was looking for.

**Comment by miilljana** [comment]
Hi

I would like to implement closure of a street for cars in particular time of the day. I tried using the time dependent network where I set the link capacity = 0 or number of lanes =0, but there are vehicles (cars + busses) still on the network.


Any suggestions are welcomed.
