### ISSUE TITLE
Pt transfer

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#744]
Hello,
When a passenger have to transfer from a bus to another at the same station (in my network nodes are bus stations), for example my passenger should leave the bus at node 4 and take another line from the same node 4 to reach node 9. What matsim is doing is starting from the end of link so it seems that the passenger is taking the bus at the next station!
Is there a solution to this problem?

Thank you.

**Comment by Janekdererste** [comment]
I haven't fully understood your problem yet. Is your problem, that the link is travelled twice, or is it the opposite, that it seems like the link is not travelled at all?

**Comment by ghost** [comment]
In fact it seems like the link is not travelled at all.
In the picture below I circled this link in yellow, it's the agent's plan in via.

![Screenshot 2022-06-14 081853](https://user-images.githubusercontent.com/101840494/173507204-b5429e4f-76b1-47f8-974b-7a951448694a.png)
