### ISSUE TITLE
change passenger mode

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#745]
Hello,
On my network I have runned 3 bus lines using different links, I have a passenger that is supposed to take bus, the plan is:

```
<person id="1">
	    <plan>
		    <activity type="" x="2300.00" y="0.00" end_time="06:20:00" /> 
		    <leg mode="pt"/>
		    <activity type="" x="-300.0" y="0.0" />
	    </plan>
    </person>
```
I blocked a link used by this line, so this passenger is stucked, the plan is not realized. How can I let this passenger walk into another bus stop and use another bus line or even use a car to accomplish his plan?

Thank you

**Comment by Janekdererste** [comment]
If you have mode choice enabled, the agent will try other options automatically as part of the replanning inbetween iterations. If you run a sufficient number of iterations, the agent should at some point switch to another mode, if this woks better for it. 

For the bus stop, I think the pt routing always tries to find the best route based on the pt schedule. This means the agent would not use another pt stop as long as the bus is scheduled to run. The agent will get a bad scoring for getting stuck though and will therefore find other alternatives wich yield better scoring results.
