### ISSUE TITLE
1.Extract person wise trajectory from output_plan.xml file 

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#749]
I want to read only list of trajectory ( i.e list of links traversed ) of each person from the output_plan.xml file in output to compare with existing trajectory data of each person. Can somebody explain an easy way to read it directly in .csv file without using any java based code. 

Like is there any way to export the ouput_plans.xml file to excel?
Any guidance would be appreciated

**Comment by Janekdererste** [comment]
You can't really export the plans file into excel. The schema in which the data is layed out is not a tabular, but a hierachical one. There are several csv-based output files though. "persons.csv.gz", "trips.csv.gz" and "legs.csv.gz" as part of the standard output. You can read those in with excel or R and then conduct your analysis.

If you want to do it with output_plans.xml, using Java is probably the easiest way. You could do something along the lines of:
```
var popoulation = PopulationUtils.readPopulation("filename.xml.gz");
Map<Id<Person>, Collection<Collection<Id<Link>>>> result = new HashMap<>();
		
		
for (var person : popoulation.getPersons().values()) {
	var plan = person.getSelectedPlan();
	var legs = TripStructureUtils.getLegs(plan);
			
	for (var leg : legs) {
		if (leg.getRoute().getRouteType().equals("links")) {
			var networkRoute = (NetworkRoute) leg.getRoute();
			var linkIds = networkRoute.getLinkIds();
					
			var trajectoryList = result.computeIfAbsent(person.getId(), key -> new ArrayList<>());
			trajectoryList.add(linkIds);
		}
	}
}

// write result to csv
```

**Comment by aayushtewari01** [comment]
@Janekdererste Thanks sir. I will work on it
