### ISSUE TITLE
cadytsCar module 

### ISSUE THREAD

**Issue by SahaBijoy** [matsim-org/matsim-code-examples#754]
Hello.
I have been trying to use cadytsCar module for model validation based on car counts. The config file runs if there is no specification for cadytsCar module. Before using cadytsCar module, it was added to the library by modifying the pom.xml file, however, the config file with the cadytsCar module is not running. I have been trying to figure out why it's not working. According to the log file, cadytsCar module is unmaterialized config group. I would really appreciate if anyone can give me some directions to solve this issue. The config file is attached for your convenience. Thanks in advance.
[config.zip](https://github.com/matsim-org/matsim-code-examples/files/8985713/config.zip)

**Comment by mrieser** [comment]
> cadytsCar module is unmaterialized config group

This means that Cadyts is not enabled in your code.

Adding it as a dependency in the `pom.xml` is the first, correct step. But then, one also needs to add the `CadytsCarModule`.

See [RunCadyts4CarExample.java](https://github.com/matsim-org/matsim-libs/blob/master/contribs/cadytsIntegration/src/main/java/org/matsim/contrib/cadyts/run/RunCadyts4CarExample.java) for more details and an example.

**Comment by nickolanack** [comment]
This issue can be closed

using maxsim 11.0 and this repo https://github.com/ChristophTraf/CadytsTests , the CadytsCarModule needed to be added in code, as mrieser mentioned

https://github.com/ChristophTraf/CadytsTests/blob/8e755fa413fcac2a84ddcbc18e3ccfa4b72296cf/src/main/java/run/RailRaptor.java#L25-L30

```java
...
controller.addOverridingModule(new AbstractModule() {
            public void install() {
                ...
                ...
                this.install(new CadytsCarModule());
            }
        });
...
```

I believe this way also worked 
```java
...
controller.addOverridingModule(new CadytsCarModule());
...
```
