### ISSUE TITLE
Network Congestion Analysis

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#756]
I am willing to analyze difference in network congestion using MATSim output after 10 iterations and after 50 iterations. 
One way is to use linkstats from output and compare the avg link volume for same duration during the day e.g 8-9 am and 5-7 PM.
Second way is to compare the travel time  from linkstats for same duration as above. If travel time increases then it might represent more vehicle on that link.
These are my understandings and I consider these as basic way of analyzing network congestion and am not sure whether it is the standard way.
I request someone to lead me to some other methods or research papers through which I can represent congestion over a large network.
Thank you

**Comment by Janekdererste** [comment]
I think travel times are more important thatn volumes when you want to investigate congestion. As long as there is no congestion, the travel time for a certain link shoud be constant. Once you reach the maximum flow capacity, the link volumes will not increase anymore, but the travel times will.
