### ISSUE TITLE
Coordinate use

### ISSUE THREAD

**Issue by dfuribe** [matsim-org/matsim-code-examples#758]
I have information in latitude, longitude coordinates and I need it to be readable by MATSIM, my network was generated from OSM and I do not know how to either transform the coordinate system of the facilities or let MATSIM do the transformation.
I have tried

	<attributes>
		<attribute name="coordinateReferenceSystem" class="java.lang.String" >epsg:3857</attribute>
	</attributes>

In the plans file, but I get an error telling me that "Element type "attributes" must be declared."

PS:  What's the difference between the population and the plans files?

**Comment by JWJoubert** [comment]
> PS: What's the difference between the population and the plans files?

They are the same, @dfuribe. Using the word _plans_ is, I guess, just historical. But you can create a population without travel demand (not that that would do much in MATSim).

Simply giving the `coordinateReferenceSystem` as an attribute is not enough. MATSim will not (and should not) auto-magically know what you want to do with it. Best is to convert the coordinates yourself. One way to do that is to use the `MatsimNetworkReader`'s functionality. I see there are two specific methods that might be helpful. I am not sure if the first assumes an network as being in the WGS84 (`epsg:4326`) coordinate reference system (CRS). 

```
Scenario scenario = ScenarioUtils.createScenario(ConfigUtils.createConfig());
new MatsimNetworkReader("epsg:3857", scenario.getNetwork()).readFile("yourNetworkInWgs84.xml");
new NetworkWriter(scenario.getNetwork()).write("yourNetworkInEpsg3857.xml");
```

where the first argument is the target CRS. Alternatively, there is another method where the source _and_ target CRS is specified.

```
Scenario scenario = ScenarioUtils.createScenario(ConfigUtils.createConfig());
new MatsimNetworkReader("epsg:4326", "epsg:3857", scenario.getNetwork()).readFile("yourNetworkInWgs84.xml");
new NetworkWriter(scenario.getNetwork()).write("yourNetworkInEpsg3857.xml");
```

Maybe these two give the same result. There are alternative ways too, but I think they will require a tad bit more scripting/coding.

**Comment by dfuribe** [comment]
Thank you, I realized that my coordinate system is slightly synthetic as I created the network from a SUMO network.  I was able to use the SUMO transformation coordinates to transform my set of coordinates from lon/lat to the same coordinate system.
