### ISSUE TITLE
Disable mode change innovation for a subset of agents

### ISSUE THREAD

**Issue by alexdawn** [matsim-org/matsim-code-examples#76]
I have a config file with 3 vehicles modes plus pt
```
<module name="planscalcroute" >
		<param name="networkModes" value="car,lgv,hgv" />
</module>
```

The mode change module is set for these modes, so that car and pt can change between one another
```
<module name="changeMode">
		<param name="modes" value="car,pt" />
</module>
```

looking in the mode share log file, the lgv and hgv proportions are constantly dropping as agents can switch away but not into these modes. How can I disable agents whose mode is lgv or hgv from innovating mode?

EDIT: https://github.com/matsim-org/matsim-code-examples/blob/0.10.x/examples/tutorial/programming/multipleSubpopulations/config.xml looks like it has the answer but has an empty strategy section

**Comment by kainagel** [comment]
Hm.  There is, in "changeMode", something like

<param name="behavior" value="fromSpecifiedModesToSpecifiedModes"/>

Looks like that is only in the development version, not in the last release (0.10.x).

Not sure what to recommend.  If you are using matsim via maven, could try to find a weekly release that works for you.

https://github.com/matsim-org/matsim-example-project/blob/master/pom.xml shows (commented out) how that can be achieved.

Hope that helps.  Next release sometimes this spring, but we ain't there yet.

**Comment by tduberne** [comment]
> EDIT: /examples/tutorial/programming/multipleSubpopulations/config.xml@0.10.x looks like it has the answer but has an empty strategy section

Indeed, that is the solution I would propose, as I understand agents either choose from car and pt or follow hgv/lgv. Looking at your output config should help you to write your config file. The basic idea is the following:

- put those agents with modes "lgv" and "hgv" in a special subpopulation, by adding a "subpopulation" attribute. It used to be in the person_attributes.xml file, but should now also be possible directly in the population file. If this is unclear, I could try to search for or design an example
- each strategy has a "subpopulation" parameter. This allows to specify different strategies for different subpopulation: simply do not specify a mode choice strategy for your lgv/hgv population.

It is recommended to give a named subpopulation to other agents as well. It used to be that all agents without a subpopulation attribute would be considered the "default" subpopulation, but it appeared not to be a very good practice. I do not remember if this is strongly enforced, though.

The solution Kai proposes solved a slightly different problem, I would say: it allows to have agents with some trips that do not change modes and some that do. Subpopulation force to separate agents into groups, but then different groups can have very different replanning strategies/scoring function. In Switzerland, we had scenarios where trucks only reroute, whereas other agents might change modes, departure times or even activity locations.

**Comment by alexdawn** [comment]
Thanks for your quick answers,

@tduberne your solution sounds exactly what I am looking for, would be very grateful for any snippets you could share as I've not yet made use of sub-populations. Unrelated to the posted question but would sub-populations also allow me to set different scoring parameters for each sub-population?

**Comment by alexdawn** [comment]
Is it possible to add an agent to more than one sub-population?

for example could you have a sub-population called `has_bicycle` and another called `has_motorbike` with some agents in both groups. No matter if it doesn't just means the groups will combinatorally grow with more attributes.

**Comment by tduberne** [comment]
No, subpopulations are a partition of the "global" population: each agent pertains to one and exactly one subpopulation. Things like "has_bicycle" or "has_motorbike" need to be included programmatically (I do think there is the infrastructure for this, but probably not exposed in the config).

**Comment by alexdawn** [comment]
I used the equilibrium extended example to generate the person attribute file however it was complaining of not all sub-population having a re-planning option:

## first approach
Error message:
```
2019-02-06 09:55:05,146 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: No strategy found! Have you defined at least one replanning strategy per subpopulation?
```
I have written a little script to check and every agent id, has an object id with either one of the two subpopulation names

config file:
```
<module name="plans">
                <param name="inputPersonAttributesFile" value="personAttributes.xml" />
		<param name="inputPlansFile" value="jtw_with_nts_agents.xml" />
        <param name="subpopulationAttributeName" value="subpopulation" />
	</module>
<module name="strategy">
		<param name="maxAgentPlanMemorySize" value="5" /> <!-- 0 would mean unlimited, bad idea for your RAM! -->
        <!--gradually phase out options, last 10 iterations are just selecting from existing plans -->
        <parameterset type="strategysettings" >
			<param name="strategyName" value="BestScore" /> <!-- changes plan weighted towards the best option  (ChangeExpBeta) -->
			<param name="subpopulation" value="agent,freightdriver,default" /> <!-- doesn't work with or without default-->
			<param name="weight" value="0.6" />
		</parameterset>
        <parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="45" />
			<param name="strategyName" value="ReRoute" />
			<param name="subpopulation" value="agent,freightdriver,default" />
			<param name="weight" value="0.2" />
		</parameterset>
        <parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="40" />
			<param name="strategyName" value="TimeAllocationMutator_ReRoute" />
			<param name="subpopulation" value="agent" />
			<param name="weight" value="0.1" />
		</parameterset>
        <parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="25" />
			<param name="strategyName" value="SubtourModeChoice" />
			<param name="subpopulation" value="agent" />
			<param name="weight" value="0.1" />
		</parameterset>
	</module>
```



## second approach:

I then tried to add the attributes directly to the plan/population file but started getting this error:

```XML-ERROR: file:/home/vagrant/matsim-0.10.1/model_input/jtw_with_nts_agents.xml,                                                     line 1, column 147:  
org.xml.sax.SAXParseException; systemId: file:/home/vagrant/matsim-0.10.1/model_                                                    input/jtw_with_nts_agents.xml; lineNumber: 1; columnNumber: 147; Document root e                                                    lement "population", must match DOCTYPE root "plans".
```


I'm failing to appropriate the difference between the plans and the population files, one section of the manual seemed to use the two interchangeably, is there a config to say it is a population_v6 file instead of a plans_v4 file?

**Comment by JWJoubert** [comment]
On your first approach, I was not aware that the `subpopulation` parameter can take multiple values. I know it worked for me if I duplicated the `strategysettings` for each subpopulation (where necessary).

In the second approach, you will have to go and check in the `PopulationWriter.write(...)` what the version of the plans/population file was. I recall we simply move from `plans` to a more generic `population` file as the latter can have more than just plans, like person attributes too. The interchangeable use is just a legacy issue: much of the documentation is written by volunteers who has developed through the different seasons of MATSim ;-) we get confused.

**Comment by alexdawn** [comment]
Looking at the example config it is unclear as it seems to use both multiple and single values:

```
<module name="strategy" >
		<param name="fractionOfIterationsToDisableInnovation" value="Infinity" />
		<param name="maxAgentPlanMemorySize" value="5" />
		<param name="planSelectorForRemoval" value="WorstPlanSelector" />

		<parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="-1" />
			<param name="executionPath" value="null" />
			<param name="strategyName" value="ChangeExpBeta" />
			<param name="subpopulation" value="time,reroute" />
			<param name="weight" value="1.0" />
		</parameterset>

		<parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="-1" />
			<param name="executionPath" value="null" />
			<param name="strategyName" value="TimeAllocationMutator" />
			<param name="subpopulation" value="time" />
			<param name="weight" value="0.2" />
		</parameterset>

		<parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="-1" />
			<param name="executionPath" value="null" />
			<param name="strategyName" value="ChangeExpBeta" />
			<param name="subpopulation" value="time" />
			<param name="weight" value="0.8" />
		</parameterset>

		<parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="-1" />
			<param name="executionPath" value="null" />
			<param name="strategyName" value="ReRoute" />
			<param name="subpopulation" value="reroute" />
			<param name="weight" value="0.2" />
		</parameterset>

		<parameterset type="strategysettings" >
			<param name="disableAfterIteration" value="-1" />
			<param name="executionPath" value="null" />
			<param name="strategyName" value="ChangeExpBeta" />
			<param name="subpopulation" value="reroute" />
			<param name="weight" value="0.8" />
		</parameterset>
	</module>
```

Trying either single values or both the single and multiple values is yielding the same error

**Comment by alexdawn** [comment]
Ah solved it added a replan strategy with `<param name="subpopulation" value="null" />` fixes the error, I'm not sure how but some of the agents must have somehow been generated without attributes?? I don't know how because I tested the model with only two agents

**Comment by tduberne** [comment]
It seems the subpopulations are not recognized. This is odd, because in 0.10.x they should come from the ObjectAttributes, as you did. Could you provide an example file, so that I can test?
