### ISSUE TITLE
Cannot MATSiming my customerized example

### ISSUE THREAD

**Issue by zhuyiNBU** [matsim-org/matsim-code-examples#761]
Hello, everyone.
I am A total beginner of MATSim and Java.
I try to modify some provided examples to realize my own network and example but here are the troubles at the beginning.
Here are the 7 errors I encountered:
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: node id given by link cannot be dereferenced; node label=1000

2) Error in custom provider, java.lang.IllegalArgumentException: There exists already a node with id = 2000.
Existing node: [id=2000][coord=[x=800.0 | y=400.0]][type=null][nof_inlinks=0][nof_outlinks=0]
Node to be added: [id=2000][coord=[x=800.0 | y=400.0]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.

7 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:178)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:242)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:74)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.run.Controler.run(Controler.java:54)
	at org.matsim.run.Controler.main(Controler.java:58)

The simulation did not run properly. Error/Exit code: 1

Error 3 to 7 is just the same as Error 2.

I modified the resources in ParkingSearch Contribs.
The modified files are down below.
[ZhuYiNBU.zip](https://github.com/matsim-org/matsim-code-examples/files/9075795/ZhuYiNBU.zip)

Can anyone help me with this?
I am depressed to be helped!

**Comment by JWJoubert** [comment]
> I am depressed to be helped!

Depressed or desperate, @zhuyiNBU ? 😉

The error message is quite clear: you are trying to add a node to the network that already exists: node with `id=2000`. You have to be careful when manually changing the network XML file, because you have to do it consistently. From I infer from the message, you changed some node from `id=1000` (which is referenced by a link) to `id=2000`, but the latter node already exists. The code will crash because you have an inconsistent network.

> I am A total beginner of MATSim and Java.

I suggest you at least work through the first few chapters of the [MATSim book](https://www.matsim.org/the-book) otherwise you might not get much feedback/help on this forum.

**Comment by zhuyiNBU** [comment]
> > I am depressed to be helped!
> 
> Depressed or desperate, @zhuyiNBU ? 😉
> 
> The error message is quite clear: you are trying to add a node to the network that already exists: node with `id=2000`. You have to be careful when manually changing the network XML file, because you have to do it consistently. From I infer from the message, you changed some node from `id=1000` (which is referenced by a link) to `id=2000`, but the latter node already exists. The code will crash because you have an inconsistent network.
> 
> > I am A total beginner of MATSim and Java.
> 
> I suggest you at least work through the first few chapters of the [MATSim book](https://www.matsim.org/the-book) otherwise you might not get much feedback/help on this

**Comment by zhuyiNBU** [comment]
> > I am depressed to be helped!
> 
> Depressed or desperate, @zhuyiNBU ? 😉
> 
> The error message is quite clear: you are trying to add a node to the network that already exists: node with `id=2000`. You have to be careful when manually changing the network XML file, because you have to do it consistently. From I infer from the message, you changed some node from `id=1000` (which is referenced by a link) to `id=2000`, but the latter node already exists. The code will crash because you have an inconsistent network.
> 
> > I am A total beginner of MATSim and Java.
> 
> I suggest you at least work through the first few chapters of the [MATSim book](https://www.matsim.org/the-book) otherwise you might not get much feedback/help on this forum.

**Comment by zhuyiNBU** [comment]
> > I am depressed to be helped!
> 
> Depressed or desperate, @zhuyiNBU ? 😉
> 
> The error message is quite clear: you are trying to add a node to the network that already exists: node with `id=2000`. You have to be careful when manually changing the network XML file, because you have to do it consistently. From I infer from the message, you changed some node from `id=1000` (which is referenced by a link) to `id=2000`, but the latter node already exists. The code will crash because you have an inconsistent network.
> 
> > I am A total beginner of MATSim and Java.
> 
> I suggest you at least work through the first few chapters of the [MATSim book](https://www.matsim.org/the-book) otherwise you might not get much feedback/help on this forum.

Thanks for your kindly reply! I will learn from that for my future work and I am working on the MATSim book, also. It's a little bit hard for me but I believe I am making progress. And I will improve my English as well. 😉

**Comment by Janekdererste** [comment]
The [user guide](https://matsim.org/docs/userguide/) could also be a helpfull resource for you

**Comment by zhuyiNBU** [comment]
> The [user guide](https://matsim.org/docs/userguide/) could also be a helpfull resource for you

Thanks for your kind reply. I am working on the MATSim book😉.
