### ISSUE TITLE
Error while simulating Multi modes on a network using teleportation

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#765]
I created a plan for 1 agent ,as a trial, consisting of car, bike and walk modes. My objective is to simulate only car over the network and teleport bike and walk mode. I read few related issues here and it was helpful for setting up config file. 
The error that I get is
ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.NullPointerException: null

I have attached the config , plan and logfilewarningerror in repository
https://github.com/aayushtewari01/MATSim-and-People-Flow-Analysis.git
(I hope it works)
The network file is large, have attached as dropbox link

https://www.dropbox.com/scl/fo/s9qencan15lz1cbq7a9dl/h?dl=0&rlkey=azdnpywqniyxjxcycia12iuxq

I request someone to please look into my settings and kindly guide what could be possible error.

Thank you

**Comment by aayushtewari01** [comment]
Waiting for guidance from respected members.
I went through similar issues on #66 and #621 . Read recommendations from those issues and tried simulating but the error remains same as "Getting uncaught Exception in Thread main
java.lang.NullPointerException: null"
Thank you

**Comment by aayushtewari01** [comment]
@Janekdererste Sir, sorry for bothering. But if you can kindly throw some light on the error. I am totally stuck about how to progress now. Regards

**Comment by Janekdererste** [comment]
This is indeed weird. You can fix this by adding 
```
<parameterset type="modeParams">
	<param name="mode" value="pt"/>
	<param name="constant" value="0.0" />
	<param name="marginalUtilityOfTraveling_util_hr" value="0.0"/>
	<param name="marginalUtilityOfDistance_util_m" value="0.0" />
</parameterset>
```
To the `plansCalcScore` section of your config.

**Comment by aayushtewari01** [comment]
Great help, thankyou @Janekdererste sir, the simulation works now.
