### ISSUE TITLE
PassingQ for some vehicle types

### ISSUE THREAD

**Issue by alexdawn** [matsim-org/matsim-code-examples#77]
Very grateful for all of your answers so far, hopefully the model I am building will get matsim more widely used in the UK

Is it possible to set a PassingQ link dynamic for some vehicle types and not others? e.g. I would like to be able to have motorbikes and bicycles to have passing queue behaviour, yet have cars get stuck behind slower HGVs.

**Comment by jfbischoff** [comment]
In my opinion, this is not currently supported. 
If, one should probably make this a function of a link, as one would expect that a car can overtake an HGV on a motorway but not on a one-lane backcountry road. 

Implementing this should, in theory, be possible, but I can imagine that quite a bit of hacking is required.

**Comment by alexdawn** [comment]
Reading more of the manual I think I can get all the behaviour I want for motorbikes and bicycles with SeepageQ. HGVs will need code changes

**Comment by JWJoubert** [comment]
It is actually doable. There were two papers, actually a single two-part paper presented at ABMTrans last year: http://dx.doi.org/10.1016/j.procs.2018.04.133 and http://dx.doi.org/10.1016/j.procs.2018.04.134 . Not sure if there were serious changes in the core itself required. But if there was, I'm sure we can review it and merge it into the core.
