### ISSUE TITLE
ERROR writing output events did not work

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#771]
ERROR DumpDataAtEndImpl:170 writing output events did not work; probably parameters were such that no events were generated in the final iteration

While running a simulation for 1 iteration of 5.69 million agents , total trips 13.6 million over a network of 6 million links I received above error in logfilewarning. The simulation was complete but the linkcounts in linkstats.txt  is significantly less than expected.

I used same config file first for simulation of agents with modes 'car,bike,walk'. Bike and walk were teleported and the results were justifiable. Also there was no such error.

But when I included additional agents with mode 'car,bike,walk and pt' , pt also teleported , then my results were 1/10th of previous simulation. 
I want to ask whether the above error has something to do with the less count in linkstats.
Please go through my config file and error and kindly suggest what could be possible mistake I might have done
Thankyou 
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/9386520/logfileWarningsErrors.log)
[config.txt](https://github.com/matsim-org/matsim-code-examples/files/9386524/config.txt)

**Comment by Janekdererste** [comment]
The relevant part of your config for writing events looks fine:
```
	<module name="controler">
                ...
		<param name="writeEventsInterval" value="1" />
		<param name="writePlansInterval" value="1" />
		<param name="writeSnapshotsInterval" value="1" />   
	</module>
```
This should write events for iteration 0 and 1. Do you have files in the iteration folder?

**Comment by aayushtewari01** [comment]
@Janekdererste yes sir, I have it including the linkstats and events file. The iteration was complete and so did the simulation. 

But I had this error at last. The linkstats was  around 1/10th of previous simulation in which the number of trips was around 6 million , when it should have increased.

**Comment by Janekdererste** [comment]
Hm, I don't have an emmediate idea. Can you share the entire log file please?

**Comment by aayushtewari01** [comment]
> 

Thanks, please find the file
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/9402120/logfile.log)

**Comment by Janekdererste** [comment]
I can't find anything special in you logfile. I am very sorry, but I don't really see, what's going wrong.

**Comment by aayushtewari01** [comment]
I understand sir. I have moved ahead. I changed strategy settings to Changeexpbeta and re-rran the simulation. It ran. Although I am sure this is not the issue. Still to move on with some trial simulations I did so. In few days I will rerun the simulation with this config. and will update. As of now I am closing this issue. Thank you
