### ISSUE TITLE
VKT/VMT 

### ISSUE THREAD

**Issue by FURSAL** [matsim-org/matsim-code-examples#772]
Hello,

I have a question related to Vehicles Kilometer Traveled/Vehicle Miles Traveled, I have read many research papers utilizing MATSim software and they analyze the VKT. Is it something we can get from MATSim directly? Or, it has to be calculated?

Thank you,

**Comment by Janekdererste** [comment]
Matsim will not give you this number as direct output. You can compute this number from its output though.

**Comment by gac55** [comment]
You can get VKT as output from Elara, see [here](https://github.com/arup-group/elara#post-processing-handlersworkstation-tools)

More info on [Elara](https://medium.com/arupcitymodelling/def-elara-e09fc23dfda3)

**Comment by FURSAL** [comment]
> You can get VKT as output from Elara, see [here](https://github.com/arup-group/elara#post-processing-handlersworkstation-tools)
> 
> More info on [Elara](https://medium.com/arupcitymodelling/def-elara-e09fc23dfda3)

I'll try Elara out. Thank you so much

**Comment by FURSAL** [comment]
> You can get VKT as output from Elara, see [here](https://github.com/arup-group/elara#post-processing-handlersworkstation-tools)
> 
> More info on [Elara](https://medium.com/arupcitymodelling/def-elara-e09fc23dfda3)

I tried elara. But, didn't get results for DRT. Can you please help?
I got results for car and bus. I have DRT in my work as well.

![image](https://user-images.githubusercontent.com/45188976/191820266-75e48ffb-4774-48a9-9aa0-4337cc1e088c.png)

**Comment by FURSAL** [comment]
> 

How can I compute them? Any coding to do that? 
I am working on a big network, so I don't think manually will work.

**Comment by FURSAL** [comment]
> Matsim will not give you this number as direct output. You can compute this number from its output though.

How can I compute them? Any coding to do that?
I am working on a big network, so I don't think manually will work.

**Comment by vsp-gleich** [comment]
Hi, in a typical matsim run you will find pkm_modestats.txt in the output directory, which gives person-kilometers travelled. Since car has exactly one passenger per vehicle and never moves without the passenger(=driver), car-pkm equals car-vkm. If you use drt you will find a drt_vehicle_stats_drt.csv which among others gives the total km travelled. Both outputs should come out automatically at the end of the run unless they were deliberately switched off.

**Comment by FURSAL** [comment]
> 

Great. Thank you so much
