### ISSUE TITLE
Full iteration information

### ISSUE THREAD

**Issue by dfuribe** [matsim-org/matsim-code-examples#774]
As iterations advance, the process seems to demand more and more resources, which in some cases make me leave my computer running overnight to finish a single iteration.
I have seen that if I use the plans files from the last finished iteration as a starting point, MATSIM has to do the whole analysis for that iteration before starting the second iteration with new information, basically repeating the whole process for the first iteration that was done before in order to obtain a "new" plans file.
What information is necessary from the iteration files to be in the config file so that after finishing one iteration I can run the simulation  immediately in the next iteration, without losing all the previous computing effort?

**Comment by Janekdererste** [comment]
Such a slow down can have many reasons. Can you give more information about your set up? Your input, a link to your project repository, as well as a log file would be helpful.

Regarding the restart: If you supply a plans file from the previous iteration, MATSim will start with that plans file and emmediately execute the next iteration. There are no extra calculations involved. However, there is quite some overhead for internal bookkeeping before the first iteration of a run is started. These computations will be performed regardless of your plans file. In general it is faster to not interrupt the execution of the simulation. You should only do this if you have limited computing time on your cluster for example.
