### ISSUE TITLE
How to get the occupancy of drt-maas for whole population?

### ISSUE THREAD

**Issue by vishalmhjn** [matsim-org/matsim-code-examples#78]
I am running the matsim-maas using 10% of the population. The simulation is running fine and I get the values of different indicators such as occupancy in DRT vehicles. However, I face one issue regarding scaling up of occupancy for the population. Since the trips/ rides in sample (10%) will be less dense, so it is natural that probability of ride share or occupancy will also drop down and will not reflect the actual scenario of ride share with full population. How can I arrive at approximate occupancy using the sample population?

**Comment by jfbischoff** [comment]
An interesting question. If the demand is high enough, our studies show that 10 and 100% scenarios are pretty comparable (such as "all car traffic in Berlin uses DRT"). 
For low demand scenarios, this will not necessarily be true, but in the end you will need to find it out for yourself depending on your scenario.
