### ISSUE TITLE
I need help to build a DRT scenario for a specific city

### ISSUE THREAD

**Issue by Areza622** [matsim-org/matsim-code-examples#788]
17.09.2022
Hello. I am a beginner in MATsim, although I have read the tutorial book but I still don't exactly know which are the steps to build a scenario/project to chech the effects of implementing autonomous ride-pooling system in a specific area. I would be thankful if you can give me hints or tell me the basic steps to build this scenario and import my own network and also agents.
Thank you in advance.

19.09.2022
Now after some search I have found the MATsim MaaS, but the thing is now as I don't know Java programming, I don't know how should I implement my desired map network, Karlsruhe, and also implement some agents, 50 people, can you please help me on this issue?
Also another thing is that I don't know exactly what different parameters are used in MaaS project!
Thank you in advance.

**Comment by Areza622** [comment]
Now after some search I have found the MATsim MaaS, but the thing is now as I don't know Java programming, I don't know how should I implement my desired map network, Karlsruhe, and also implement some agents, 50 people, can you please help me on this issue?
Also another thing is that I don't know exactly what different parameters are used in MaaS project!
Thank you in advance.

**Comment by ywf** [comment]
you can download the soure code and there is a drt scenario and many examples.

**Comment by Areza622** [comment]
> you can download the soure code and there is a drt scenario and many examples.

ok, thank you
