### ISSUE TITLE
Getting network from OSM and some issues with JOSM

### ISSUE THREAD

**Issue by Areza622** [matsim-org/matsim-code-examples#791]
Hello, I have four issues and I would appreciate it if someone can help me:

First, when I convert OSM to MATsim layer using JOSM, the public transport is removed! even when I try to keep it from preferences it shows 2 errors

Second how can I remove areas out of a boundary in JOSM, in fact I know how to select the objects inside a boundary but I don't know how to delete objects out of a boundary

Third, how can I select only roads, streets and highways in JOSM and remove other objects?

Fourth, after converting OSM to MATsim layer, should I change map projection code or I can directly use it?

Thanks in advance

**Comment by JWJoubert** [comment]
Hi @Areza622 for public transport, you may want to look at [pt2matsim](https://github.com/matsim-org/pt2matsim) - I have had mixed success, but it may be a good start for you.

For the rest of your questions, you may find solutions in using the command line tool [osmosis](https://wiki.openstreetmap.org/wiki/Osmosis): filter the _OpenStreetMap_ data first, and then convert it in/with JOSM (or MATSim code, or `pt2matsim` directly).

Regarding projection, I am not sure if it is done right from within the JOSM plugin, but you _should_ work with a projected coordinate system (one that is suitable to your area).

**Comment by Areza622** [comment]
> Hi @Areza622 for public transport, you may want to look at [pt2matsim](https://github.com/matsim-org/pt2matsim) - I have had mixed success, but it may be a good start for you.
> 
> For the rest of your questions, you may find solutions in using the command line tool [osmosis](https://wiki.openstreetmap.org/wiki/Osmosis): filter the _OpenStreetMap_ data first, and then convert it in/with JOSM (or MATSim code, or `pt2matsim` directly).
> 
> Regarding projection, I am not sure if it is done right from within the JOSM plugin, but you _should_ work with a projected coordinate system (one that is suitable to your area).

Dear Dr. W. Joubert, thank you so much for your response.
I tried JOSM and MATsim plugin but the MATsim layer extracted does not include public transport!(I tried even from preferences to activate Transit support alpha but I got error!)
About the pt2matsim I have my network file in .osm format and also found GTFS zip from the link below which consists of several text files:
https://transitfeeds.com/p/karlsruher-verkehrsverbundes/896
Would you please tell me how should I activate/install pt2matsim and import my files and retrieve the network file including public transport?
Thank you in advance.
