### ISSUE TITLE
Build agents plan from raw data

### ISSUE THREAD

**Issue by Areza622** [matsim-org/matsim-code-examples#796]
Hello. In fact I have the raw data of the agents that tells their origin and destination address, and I want to build a plan file for MTSim scenario, would you please guide me how should I do that?

**Comment by Janekdererste** [comment]
There are a few examples [here](https://github.com/matsim-org/matsim-code-examples/tree/15.x/src/main/java/org/matsim/codeexamples/population) on how to generate population data from different input sources.

**Comment by Areza622** [comment]
@Janekdererste Thank you for your response. In case that I want to use my MATsim network in xml format (EPSG:31468 projection) and create random demand which of them is more suitable?
I think RunPPopulationGenerator is ok but my problem is that I don't exactly know how should I input my network and coordinate system

**Comment by Janekdererste** [comment]
The scripts in these folders are more of an example on how to write your own script to generate a popoulation. You can use the most suitable one as a starting point and then adjust it to your needs. The idea to have these examples here is to provide an overview of which APIs to use. 

You don't necessarily need a network for creating your population. You can simply assign geocoordinates to your activities. MATSim will then assign an activity to the closest link once you start the simulation. 

If you want to have control over which activity is assigned to which link you indeed need a network. You can read a network into memory like the folling
```
var network = NetworkUtils.readNetwork("path/to/your/network.xml.gz");
```

**Comment by Areza622** [comment]
@Janekdererste Thank you for your explanation. One more question, for example in one of the examples in DRT there is this plan sample :

	<person id="12052000_12052000_100">
		<plan score="112.83915061460992" selected="yes">
			<activity type="home" link="1655" x="457685.4705887371" y="5740004.041388335" end_time="07:48:38" >
			</activity>
			<leg mode="drt">
			</leg>
			<activity type="work" link="9690" x="456223.8089950741" y="5732282.2554312255" end_time="15:31:17" >
			</activity>
			<leg mode="drt">
			</leg>
			<activity type="home" link="1655" x="457685.4705887371" y="5740004.041388335" >
			</activity>
		</plan>

	</person>

If I want to build my plans in this format, I don't understand what is "Score" and how is it calculate and import it? also is it necessary to write the link id closest to the (X,Y) coordinate of the home or work? or I leave it blank and as you told after simulation MATsim will assign the link itself?

Also in Taxi's plan, there is not any Score, what is logic behind this parameter?

**Comment by Janekdererste** [comment]
> or I leave it blank and as you told after simulation MATsim will assign the link itself?

You can leave it blank

>  I don't understand what is "Score"

Please see [user guide](http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf) chapter 1 and 5. You don't have to supply a score in your input plans. Once you have read the recommended chapters this should make sense

**Comment by Areza622** [comment]
@Janekdererste Thank you for your help.
I know what is score, but giving score before simulation was strange for me, but now after your answer it is clear.
