### ISSUE TITLE
Size of the Plan file and MATSim convergence

### ISSUE THREAD

**Issue by alainT2** [matsim-org/matsim-code-examples#80]
Dear MATSim community,

CASE1: I have been running MATSim in a network of  77080 links and  463 938 agents. 
In the config file the "lastIteration" was set to "30" and the learning parameters were set to: 
    `<param name="learningRate" value="1.0" />` and `<param name="BrainExpBeta" value="2.0" />`
  The output files (event and experienced Plan file were significant)

CASE2: same network of  77080 links and  2 319 690 agents. 

Problem: I have increased the population file  by generating new copies of agent (5 times). This for calibration purpose.  Running MATSim do not produce satisfactory output files (especially when looking at the Experienced Plan files: many plans are not executed)  even after "lastIteration" was set to "160"

Question: is there anyway to guarantee the convergence in MATSim?
I have increased the number of iterations until the maximum capacity  of 1TB (with 20GB of RAM) of my desktop. How can solve this problem?

Thank you in advance for your time and consideration.

**Comment by mrieser** [comment]
> many plans are not executed

Why do you think so?

If the (experienced) plans seem incomplete, then the agent might be stuck in the simulation (just a guess). In that case, one would have to figure out why they got stuck, or in general: why they were not fully simulated.

> I have increased the number of iterations until the maximum capacity of 1TB

I'm not sure I understand: what does the number of iteration has to do with the (hard drive?) capacity? Except that more iterations produce more data, but when plans are only written every 10th iteration or so, this should not be a problem I think.

**Comment by alainT2** [comment]
Dear Prof. Marcel,

Thank you for your reply. You are right my question was not very clear. 


Part 1: I have been running a MATSim scenario (San Francisco Bay Area) with a network of 77080 links and a population file of 463 938 agents.
     At the configuration level, 
    -    The “lastIteration” was set to “30” (controller level)
    -    The   “learning rate” was set to “1.0” (planCalcscore) 
    -    The   “BrainExpBeta” was set to “2.0” (planCalcscore) 

     The output of the simulation corresponded to the last  iteration 30. 

     Result 1:  Using your terminology:  when analysing the “Experienced_plans file” most of the plans were fully simulated. 
 

Part 2: (objective) increase the number of agents in order to study certain geographical areas in our network.

I made a scenario with the same network of 77080 links and a population file of 2 319 690
Agents (I generated 5 copies of each agent in the previous plan file, and assigned a new ID to each of them).

I run again  the simulation with the same configuration:

At the configuration level, 
-	The “lastIteration” was set to “30” (controller level)
-	The   “learning rate” was set to “1.0” (planCalcscore) 
-	The   “BrainExpBeta” was set to “2.0” (planCalcscore) 

The output of the simulation corresponded to the iteration 30. 

Result 2:  Using your terminology:  when analysing the “Experienced_plans file” many plans were not fully simulate. Many agents did not complete they plan, hence get stuck some where( as Prof. Marcel is suggesting).


Part 3: (objective)  run part 2 with The “lastIteration” set to “160” (controller level). With the hope to increase the convergence in MATSim.

The output of the simulation corresponded to the iteration 160.
 
Result 3: when analysing the “Experienced_plans file”,  many plans were not fully simulate even with an increased number of iterations (namely result2  was similar to result 3).


Question: is it due to the fact that many agent get stuck  in the traffic and their overall plan is not performed or MATSim need also more iterations to reach the convergence?

In you previous answer you suggest to check the reason why many agents get stuck in the traffic.

Thank you for your time and consideration.






I

**Comment by aayushtewari01** [comment]
@alainT2 were you able to resolve this issue that 'many agents were stuck and plans were not fully simulated' with further increased number of iterations. Or if you can please cite what were your observations as I am experiencing similar issue that even after increasing iteration there remain some agents who are not able to simulate their plan. The numbers are few in comparison to to total agents like out of 45115 agents only 700 agents were not simulated. 
Thank you

**Comment by alainT2** [comment]
Try to increase the link capacity factor parameters ..!!
And the number of commuters staying idle will decreases as long as they can
perform their trip.


That parameter can be seen as the sampling rate of the real population you
are considering.


Hope this help
Alain

**Comment by aayushtewari01** [comment]
@alainT2 Thanks for your reply, may I seek a clarification. By link capacity you mean the storagecapcityfactor or the flow capacity  that we define in the network.
Thanks

**Comment by alainT2** [comment]
Yes …!!!!
