### ISSUE TITLE
av

### ISSUE THREAD

**Issue by Hamadneh** [matsim-org/matsim-code-examples#81]
**Hello,
I would like to ask you about an error that I faced when I run my example. I used the RunRobotaxiExample, unfortunately, I got the attached log file:**
https://www.dropbox.com/s/zutwhbe96uag1q8/Budapest.rar?dl=0
**Could you please tell me how can I solve this kind of problem**
FYI, the input files (network, plans, etc) are working and no errors were found when I simulate them as an existing condition (regular modes). 
My laptop capability is I7-7500U CPU-2.7-2.9GHZ  8GB RAM AND SSD drive

Many thanks

**Comment by michalmac** [comment]
You've got `java.lang.OutOfMemoryError: Java heap space`. Looks like you need to allocate more memory:

```
2019-02-03 22:49:28,041  INFO QSim:505 SIMULATION (NEW QSim) AT 05:00:00 : #Veh=1701 lost=0 simT=18000.0s realT=8s; (s/r): 2250.0
2019-02-03 22:49:28,041  INFO Gbl:58 used RAM: 1259121544B = 1229610kB = 1200MB  free: 267080824B = 254MB  total: 1526202368B = 1455MB
```
The total of 1.5 GB is not enough.

Here are some hints on how to set it: https://stackoverflow.com/questions/1493913/how-to-set-the-maximum-memory-usage-for-jvm
