### ISSUE TITLE
Combine several Matsim contributions

### ISSUE THREAD

**Issue by nirmeenLu** [matsim-org/matsim-code-examples#82]
I would appreciate your advice on how can roadpricing and parking contributions be combined or parking and carsharing contributions. In order to be able to run studies with combinations of existing contributions.

**Comment by jfbischoff** [comment]
The general advice would be to first try and understand how each of the extensions is working on their own by looking at the RunXXExamples.
Then, start combining two of them by creating your own Run class. Depending on the setup of the contributions, this may _or_ may not work in a simple way.

**Comment by JWJoubert** [comment]
I fully agree with Joschka. Also, from a simulation methodology point of view it is not advisable to throw everything into the same pot. You will, in the end, not have any idea of what component caused you to have the required signal for the experiment... or NOT get the signal you expected.
