### ISSUE TITLE
ERROR MatsimRuntimeModifications:76 Getting uncaught Exception in Thread main

### ISSUE THREAD

**Issue by GA18gua** [matsim-org/matsim-code-examples#829]
Hi,everyone
An error occurred when I tried to run parkingsearchexmple.
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/10150857/logfileWarningsErrors.log)

**Comment by tschlenther** [comment]
Hi,
i just ran `org.matsim.contrib.parking.parkingsearch.RunParkingSearchExample` on the most recent MATSim version und could not reproduce your problem. Which version do you use?

Normally, this class is covered by an integration test...

**Comment by GA18gua** [comment]
Thank you for your reply. I have solved the problem. It's a problem with my computer。
