### ISSUE TITLE
Public Transit

### ISSUE THREAD

**Issue by puneetssharma** [matsim-org/matsim-code-examples#841]
I am trying to implement periodic public transit lines on a chessboard. I am trying to implement a multi modal scenario with public transit and DRT. I keep on getting the following error message:

ERROR AbstractTransitDriverAgent:280 java.lang.RuntimeException: Transit vehicle is not yet at last stop! vehicle-id = tr_4_0; next-stop = pt_8_8-8_9_trStop

Does it mean that transit vehicles is not at the last stop of the stop list or it is not at the stop it was scheduled to be at this time.

What could be the source of error? Any insights would be of great help.

**Comment by Janekdererste** [comment]
This error happens if a TransitDriverAgent doesn't have any links in its route list anymore, though it still has stops it has to go to. 

You probably have a misalignment in your transit schedule, where the network route doesn't cover all your stops.

**Comment by puneetssharma** [comment]
Yes, thanks. Figured it out, looking into transitSchedule.xml was helpful
