### ISSUE TITLE
Question regarding dynamic traffic lights control

### ISSUE THREAD

**Issue by dittohed** [matsim-org/matsim-code-examples#842]
Hi!

We're currently running a student project focused on optimizing city traffic by controlling traffic lights dynamically (based on current, real-time demand) and would like to utilize MATSim as a simulator to evaluate our algorithm. Hence we would like to kindly ask a few questions. In order to meet our assumptions about the controlling algorithm, we would need to be able to:

* control traffic lights for each intersection individually at runtime (i.e. for each simulation step, pick the phase / lanes for which a score is maximized, where e.g. score is a weighted sum of mean speed of incoming vehicles, mean waiting time etc.);
* gather statistics about the current traffic for each lane / phase (as above, e.g. number of incoming vehicles etc.).

As far as we've checked it should be feasible although it seems that it would require implementing some custom code. Is it actually feasible to do in MATSim? If so, could you please provide us with any resources or tips where to look further?

Thank you a lot!

**Comment by tthunig** [comment]
Hi! 

Yes, that is possible in MATSim. Have you already checked the signals contrib? There is an implementation for an adaptive traffic signal control named [LaemmerSignalController](https://github.com/matsim-org/matsim-libs/blob/master/contribs/signals/src/main/java/org/matsim/contrib/signals/controller/laemmerFix/LaemmerSignalController.java), which you might use as a basis for your implementation. You can find an example how to start a MATSim Simulation with these signals under the [code examples](https://github.com/matsim-org/matsim-libs/blob/master/contribs/signals/src/main/java/org/matsim/codeexamples/adaptiveSignals/RunAdaptiveSignalsExample.java). There is also a [paper](https://www.sciencedirect.com/science/article/pii/S2352146518306343) describing and testing this approach.

Another adaptive traffic signal control approach within MATSim, based on reinforcement learning is described [here](https://ieeexplore.ieee.org/document/9468362).

Hope that helps!
Theresa

**Comment by dittohed** [comment]
Perfect! Thanks for your reply! We're now looking into it.
