### ISSUE TITLE
conversion into xml

### ISSUE THREAD

**Issue by Sharmeela16** [matsim-org/matsim-code-examples#86]
how can I convert excel data into xml file for network and population input in Matsim? Can someone help?

**Comment by fredshone** [comment]
One way (not the best way I'm sure), using the Python language, is to injest with the [pandas library](https://pandas.pydata.org/index.html) and then write to xml with [lxml library](https://lxml.de/tutorial.html). This makes sense if you are happy writing code and or need to manipulate the data significantly. However, if you are not coding then it will be a severe learning curve.

More broadly, it will be hard for people to assist you with your query becasue it is not clear how your data is formatted and therefore what exactly would be required. I imagine that there are a lot of little tools and tricks in the community, made to work with specific input formats. You might try including a little more detail with your issue, perhaps a *small* sample of your input data.

If you want to run some small tests, consider writing some of your own xml docs with a text editor, perhaps by opening and editing some example inputs from [here](https://github.com/matsim-org/matsim-code-examples/tree/0.10.x/scenarios)?

**Comment by kainagel** [comment]
Somewhat similar answer from our side.  We in Berlin prefer java over python for the above purpose, not because it is the better language for the task (it is not), but because matsim is in java and thus we are much more fluent in java than in python.  also, there are java bindings for network and plans output in the correct format, which do not exist in python (although someone should write them).

The above link to the matsim code examples is essentially correct, except that the material will be in the [network](https://github.com/matsim-org/matsim-code-examples/tree/0.10.x/src/main/java/tutorial/network) and [population](https://github.com/matsim-org/matsim-code-examples/tree/0.10.x/src/main/java/tutorial/population) packages.

**Comment by tduberne** [comment]
Note that, as I mentioned in other answers already (see #34 and #84), it is relatively straightforward to mix the two approaches above using [JPype](https://jpype.readthedocs.io/en/latest/). Some of my experiments with it are available [here](https://github.com/tduberne/matsim-python-experiments). Note that this repository is what the title claims: experiments, mostly related to my own pain points.

I do not have experience with reading Excel data using pandas, but pandas is indeed generally much nicer to manipulate data tables than self-backed Java approaches. JPype allows you to use the MATSim writers to write the data to files, removing the pain from writing the xml "by hand".

If I had to do it, I would probably do it this way. The downside is that it requires both knowledge of Python with pandas and MATSim.

**Comment by kainagel** [comment]
Thomas Nicolai and I looked at JPype in the context of matsim4urbansim.  It seemed like a logical choice, but at that point in time most of the python libraries, importantly including numpy and scipy, did not work for that java implementation of python.  Has that changed?  You (@tduberne) imply panda can be used from jpype, or am I misreading that sentence?  Thanks ...

Edit: Note that I confused JPype and Jython in this post; see next comment.

**Comment by tduberne** [comment]
JPype does work with pandas and numpy, and even takes charge of the automatic conversion between numpy and Java arrays. It is a standard (C)Python library, and as such, does not restrict any other library you might want to use. It works for Python >2.6 and 3.x.

From your description, I think you might be speaking of Jython. Jython is an implementation of Python 2.x for the JVM. This means that the only python libraries it can use are the ones written in pure Python 2.x. As you mention, this makes it rather limited, as most interesting libraries rely on C or Fortran bits and pieces, and as such only work with CPython (the "official" python implementation). On the other side, it means it should be fast for those libraries that work with it, as everything gets converted to Java Bytecode.

JPype works by having both the CPython VM and JVM running in parallel, and make them communicate through the JNI (the Java Native Interface, the thing your profiler uses to talk to the JVM).
This comes with some overhead with each communication between the VMs. For applications such as building a Scenario and writing is to files, as was the question here, this is totally acceptable. But when I played with implementing an EventHandler in Python, the impact was very noticeable, even for a relatively small scenario.

So for the moment, my intuition about it is that it is mostly useful for things like transforming tabular data to MATSim formats, and/or starting runs and processing the output.

**Comment by kainagel** [comment]
Ah, difference between jpype and jpython.  Thanks for the clarification.  This is indeed good to know, and good news.
