### ISSUE TITLE
Mode Split Change Using MATSim Version 13 and 14

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#864]
As mentioned in #856 , I eventually found the problem lies in the version that I am using. I did another test using exactly the same config and input for our MATSim Brussels scenario (so the only difference is the MATSim version) and I found the final mode split has shifted a lot. Is anyone has the same issue? Thanks!

**Comment by Janekdererste** [comment]
Yes, we had the same issues. Between version 13 and 14 some bugs in the Qsim were fixed which leads to different results.

**Comment by jingjunL** [comment]
> Yes, we had the same issues. Between version 13 and 14 some bugs in the Qsim were fixed which leads to different results.

Thanks for confirming Janek ;)
