### ISSUE TITLE
Post processing event file - best practice

### ISSUE THREAD

**Issue by mattiasingelstrom** [matsim-org/matsim-code-examples#866]
Hi,

I have created a new PersonScoreEvent that I would like to show in Via as an aggregated zonal plot. To do this I want to post process the events file and gather the XY location from the link. My question is how to best read the events file in a post processing step? I've tried to find an example of this in the MATSim code examples but not found anything that does what I intend. 

My idea is to go through each event in the events file, check its type. If it's the correct type, write type and location into a csv or similar.  One way forward is to read the events file line-by-line but that seems unnecessary. I hope that someone can point me in the direction of where to find an example of this type of post-processing? 

All the best,
Mattias Ingelström

**Comment by Janekdererste** [comment]
`matsim-libs` provides some infrastructure to parse events files. If you are comfortable to use Java for the task you can utilize this. The basic structure is the same as in [this example](https://github.com/matsim-org/matsim-code-examples/blob/15.x/src/main/java/org/matsim/codeexamples/events/eventsHandling/RunEventsHandlingExample.java). You have to initialize an `EventsManager`, then add `EventsHandler`s to it, then initialize an `EventsReader` which parses the events file. The Reader will pass all events to the Manager. The Manager will then pass events to all the handlers, already figuring out which handler has subscribed to which type of event. 

Your event handler could look somethin like the following. For how to keep track of vehicles in your network you can peek [here](https://github.com/Janekdererste/matsim-example-project/blob/seminar_4/src/main/java/org/matsim/analysis/TravelledDistanceHandler.java). This was part of the [fourth seminar](https://isis.tu-berlin.de/mod/videoservice/view.php/cm/1419386/video/133198/view) of the current MATSim Tutorial. 

```
public class SomeMeaningFullNameHanlder implements PersonScoreEventsHandler, PersonEntersVehicleEventsHandler, PersonLeavesVehicleEventsHandler, LinkEnterEventHandler, LinkLeaveEventHandler {

    private final Network network;
    private final HashMap<Id<Person>, Id<Vehicle> person2vehicle = new HashMap<>>();
    private final HashMap<Id<Vehicle>, Id<Link> vehicle2link = new HashMap<>();

    public SomeMeaningFullNameHanlder(Network network) {
        this.network = network;
    }

    void handleEvent (PersonScoreEvent event) {
        var personId = event.getPersonId();
        var vehId = person2vehicle.get(personId);
        var linkId = vehicle2link.get(vehId);
        var link = network.getLinks().get(linkId);
        var coord = link.getToNode().getCoord();
        var scoreAmount = event.getAmount(); 

        // collect your score and your coordinate somehow
    }

    // This needs to implement all the other event handling methods to keep track of which person is in which vehicle on
    // which link
}
````

**Comment by mattiasingelstrom** [comment]
Hi and thank you Janek!

I have watched the seminar from the course now and I feel that I have a much better understanding of how to proceed. Just to make sure that I understand it correctly I want to check my reasoning.

The EventHandler implemented to throw this PersonScoreEvent is bound to the controler. This EventHandler keeps track of person2vehicle and the linkID is also obtainable within the event. 

Would it make sense to create a copy of this EventHandler which keeps a Map of the variables I want to look at in the post processing? And then after I have processed the events-file, write that Map to a csv or some other useful file. I'm thinking that the other option would be to directly implement this into the EventHandler throwing the PersonScoreEvent, but then the CSV writing would happen at the end of each iteration which it doesn't have to. I hope you understand what I mean and that I have understood what I can do. 

Is it normal to process the events-file and write to CSV or do you normally do it another way, e.g. with R-programming? 

Thank you once again!

All the best,
Mattias

**Comment by mattiasingelstrom** [comment]
I have created an EventHandler that connects vehicles to persons, and events to coordinates in the network. The EventReader is placed after controler.run() and I can follow the PersonEnter/LeavesVehicleEvents. However, the two other events I want to add handlers to are EV specific (ChargingEndEvent and MissingEnergyEvent). These seem to not be handled by the EventReader, do you have any idea of why that is? Do they need to be bound somehow?

My other way forward, as I see it, would be to implement the storage of the information I'm interested in the EventHandler within mobsim and output a csv or txt-file after each iteration.

**Comment by Janekdererste** [comment]
The way I usually do it is to collect information in a handler and then write it out separately. The [example](https://github.com/Janekdererste/matsim-example-project/blob/seminar_4/src/main/java/org/matsim/analysis/RunAnalysis.java) from the fourth seminar also does this. It collects trips by person and then the main script handles printing information to the console. Instead of printing to the console you can also write data to some file. This way you can also attach the handler to your simulation as in the snippet below. This handler will collect information and then after the controller has run the simulation you can do whatever you like with that information. You can handle things differently though. 

```
    var handler = new Handler();
    controler.addOverridingModule(new AbstractModule() {
	 @Override
         public void install() {
		this.addEventHandlerBinding().toInstance(handler);
         }		
    });
    controler.run();
    
    // retreive and print data here. 
    var data = handler.getData();
    System.out.println("Your data is: " + data);
```

The ev specific events are not bound in our events manager by default. The easiest way of doing this is to implement a `BasicEventHandler` like so. `handleEvent` will be called for each event. Your handler must ensure itself to only handle the events your are interested in. 
```
class Handler implements BasicEventHandler {
		@Override
		public void handleEvent(Event event) {
			
			if (event.getEventType().equals("your event type")) {
				// do something
			}
		}
	}
```

**Comment by mattiasingelstrom** [comment]
Thank you, I tried the first way and it worked!
