### ISSUE TITLE
Converting LinkID to lat-long

### ISSUE THREAD

**Issue by khzannat** [matsim-org/matsim-code-examples#867]
Hello, 
I am working with eventfile, where for each person ID I can get link id for each event (act_end, left link, entered link). However, I would link to know the latitude and longitude of every linkid traversed by the agent throughout the simulation. From the output file I can only know the lat-long of activity start and end location. However, how can I get the lat-long for the trajectory? 
TIA

**Comment by mrieser** [comment]
As the MATSim events files may get very large, we try not to include redundant data. Thus, the longitude/latitude (which would be the same every time for a link) is not included in the events.

You need to load the network, and then do a lookup in the network, e.g. `network.getLinks().get(link_id_from_events).getToNode().getCoord()`. The link itself gets its location from the `fromNode` and `toNode`, which contain the coordinates.

**Comment by khzannat** [comment]
Thank you very much for your suggestion. Following your suggestion I tried to get lat-long from a csv file where I have linkId at 4th column (https://github.com/khzannat/dhaka-matsim-example-project/blob/master/src/main/java/org/matsim/project/LinkIDtoLatLong.java). However, in the given code, at line 37, link1 seems empty while I am debugging. Could you please let me know, whether my code is correct?
