### ISSUE TITLE
Cannot Run Urban EV Example in vsp contrib

### ISSUE THREAD

**Issue by DiegoFad** [matsim-org/matsim-code-examples#871]
Hi, 
I forked and cloned the matsim-example-project repo: [(https://github.com/DiegoFad/matsim-example-project)]
I want to modify and run the RunUrbanEvExample. In order to do so I have to copy and paste the class from the external library to my project to be able to modify input file pathes etc.. The problem is that the classes ElectricFleetUpdater and UrbanVehicleChargingHandler are not accessible anymore. For now, I will just copy the classes to my project but maybe there is a better solution.

**Comment by kainagel** [comment]
I reworked both your example and the upstream code a little bit, and it is running now.  However, I cannot push.  Could you please invite me?  Thanks

**Comment by DiegoFad** [comment]
I invited you. Thanks!

**Comment by kainagel** [comment]
Thanks.  I pushed it.  Should work now.  Note that this changes pom.xml, so you need to reload the maven project, and wait until all the new dependencies were pulled.



On 9. Feb 2023, at 10:27, DiegoFad ***@***.***> wrote:



I invited you. Thanks!
