### ISSUE TITLE
How to handle "travelled" Event

### ISSUE THREAD

**Issue by DiegoFad** [matsim-org/matsim-code-examples#872]
Hi,
I want access to the distance attribute inside the travelled event by using an event handler. In my case the event is written to the event file using the UrbanEvExample when the Plugin and Plugout Trips of agents are teleported (mode: Walk, Routing Mode: car). I cannot find an event handler interface or even the class of the travelled event.

**Comment by Janekdererste** [comment]
This one is not obvious. It't the `TeleportationArrivalEventHandler`.

**Comment by DiegoFad** [comment]
Thanks!
