### ISSUE TITLE
Simunto VIA Link Doesn't Load

### ISSUE THREAD

**Issue by laevorin** [matsim-org/matsim-code-examples#877]
The link doesn't load properly when I load the MATSim output data in Simunto VIA. Attached below are some missing links even though the nodes exist as the UTM coordinate. Can anyone help me with this issue? Thanks.

![via](https://user-images.githubusercontent.com/125447361/218985428-a7e4885c-2f42-4903-994c-cc75bb88f0a5.jpg)
![via2](https://user-images.githubusercontent.com/125447361/218985436-7fc1fed2-b7b9-44d7-af85-17afce0d0639.jpg)

**Comment by Janekdererste** [comment]
Have you checked whether the links are present in your network file?
