### ISSUE TITLE
I cannot Import the folder as a new Maven project to Eclipse

### ISSUE THREAD

**Issue by 14841484** [matsim-org/matsim-code-examples#878]
Hello.

I am planning to do a study using matsim-maas, but maven is not working properly.
I have downloaded the zip folder and imported it from an existing maven file as described in the ReadMe for matsim-maas.

When I import it, it describes an error in the pom.xml.
The details are as follows:

Description	Resource	Path	Location	Type Project build error: Non-resolvable parent POM for org.matsim:matsim-maas:master-SNAPSHOT: org.matsim:matsim-all:pom:15.0-2023w07 failed to transfer from https://repo.matsim.org/repository/ma tsim during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of matsim has elapsed or updates are forced. Original error: Could not transfer artifact org.matsim:matsim-all:pom:15.0-2023w07 from/to matsim (https://repo.matsim.org/repository/matsim): repo.matsim.org and 'parent.relativePath' points at no local POM	pom.xml	/matsim-maas-master	line 9	Maven pom Loading Problem

And the pom file is as follows
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<artifactId>matsim-maas</artifactId>
	<packaging>jar</packaging>
	<version>master-SNAPSHOT</version>

	<parent>
		<groupId>org.matsim</groupId>
		<artifactId>matsim-all</artifactId>
		<version>15.0-2023w07</version>
		<relativePath/>
	</parent>

	<name>MATSim MaaS simulation</name
	<description>A toolkit for using MATSim to simulate Mobility as a Service (MaaS)</description>

	<repositories>
		<repository>
			<id>matsim</id>
			<url>https://repo.matsim.org/repository/matsim</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.matsim</groupId>
			<artifactId>matsim</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>otfvis</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>taxi</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>av</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>drt</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>org.matsim.contrib</groupId>
			<artifactId>dvrp</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.matsim</groupId>
			<artifactId>matsim</artifactId>
			<version>${project.parent.version}</version>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.4.1</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<shadedArtifactAttached>true</shadedArtifactAttached>
							<shadedClassifierName>shaded</shadedClassifierName>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<outputFile>${project.basedir}/${project.build.finalName}.jar</outputFile>
							<transformers>
								<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<manifestEntries>
										<Main-Class>org.matsim.maas.RunMaasGui</Main-Class>
										<Specification-Vendor>org.matsim</Specification-Vendor>
										<Implementation-Vendor>org.matsim</Implementation-Vendor>
										<Implementation-Version>${project.version}</Implementation-Version>
										<Multi-Release>true</Multi-Release>
									</manifestEntries>
								</transformer>
								<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
							</transformers>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.DSA</exclude>
										<exclude>META-INF/*.RSA</exclude>
									</excludes>
								</filter>
							</filters>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by Janekdererste** [comment]
So, the pom file you posted is [this one](https://github.com/matsim-org/matsim-maas/blob/master/pom.xml)?

I just cloned the repository using git and executed `mvn clean install`. That builds the project without errors.

Could you try whether the following steps work:

- Unpack your zip file
- Open a command prompt and navigate to the folder where the pom.xml is
- execute `mvn clean install -DksipTests`

That's basically what I did.
