### ISSUE TITLE
Route element in the input plans doesn't work

### ISSUE THREAD

**Issue by andboc88** [matsim-org/matsim-code-examples#880]
Hello, I'm using MATSim and I generated the population.xml to run the simulation with only one iteration. I want to specify in the plan the route that the agent does to travel from an activity location to the next. I'm using the population_v6 and I defined the element "route" with the set of links that I want the agent to go through:

![immagine](https://user-images.githubusercontent.com/91594883/219704247-e67e8cfb-51d2-4832-bbfe-893a63d2877a.png)

This doesn't work. MATSim reads the route but recalculates and overwrites it. I tried to switch off the strategy module "reroute" and to set the plan as "selected" but nothing changed. How can I fix this problem?

**Comment by Janekdererste** [comment]
I just had a look at one of my plans files and my leg element looks differently from yours. It has attributes like travel time and vehicle id. 

Can you provide the log file of your simulation please? 
```
<leg mode="car" dep_time="09:20:02">
    <attributes>
        <attribute name="routingMode" class="java.lang.String">car</attribute>
    </attributes>
    <route type="links" start_link="144395" end_link="134075" trav_time="00:08:54" distance="7483.395897460802" vehicleRefId="10000001">144395 13185 110920 110771 110773 13324 110367 110369 143404 98098 143528 111248 111278 111280 143420 143410 131204 133161 13679 93161 26733 26730 46537 41913 134075</route>
</leg>
```
Also, a general remark for filing issues, please don't provide text as image. Rather put them here as markdown.

**Comment by mrieser** [comment]
There are other legs which do not have a route. I think MATSim will reroute the whole plan when at least one of the routes is missing, as is the case with the walk-legs and the second car-leg in your image.

**Comment by andboc88** [comment]
Hi, thanks to both of you for responding to my issue. 
@Janekdererste I had tried entering the remaining attributes as well but it still didn't work so i think the cause is what @mrieser suggested. In my case the goal was to define a specific route for some agents during the day and I solved it in an alternative way, adding the route as a public transportation, defining what was needed in the two files transitVehicles and transitSchedule.

Next time I will put the text as markdown, thanks for the advice.

**Comment by Janekdererste** [comment]
Glad, that you found a solution. Depending on what you want to achieve it might be sufficient to follow the advice of @mrieser and simply provide routes to the remaining legs of your plans.

I don't know what you are working on, but it sounds  a little odd to use public transit if initially you were to simulate car and walk trips.
