### ISSUE TITLE
Why the max duration in the output plan change so much compared to the original input? And why some agents' activities disappeared in the output event?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#881]
From what I read in the issue #428 , I understand that the attribute `max_dur` define the duration that must follow by agents when conducting plans. I used this attribute to define some car interaction activities in my plans. Let's say I define the max_dur of one activity `A` is 5 minutes (and a typical duration of 5 minutes, same as the Berlin scenario). but from the output_plans, for the same agents and same activity `A`, MATSim just changed the `max_dur` to another random larger value (20 minutes or more).

Is there any reason for the change? 

I also find another weird thing, suppose the activity of one agent is `B-C-D-E-F`. However, in the `output_trip`, I can only see activity `B-C`. The remaining are missing. Why this can happen?

Thanks!

-------------------------------------------------------------------(update)

I re-review my output files, the maximum duration of some agents' plans is still keep as the original 5 minutes, but there are also cases that the maximum duration has changed to more than 1 hour. I checked the output_trip, and indeed that agent stayed in that activity for more than 1 hour instead of 5 minutes. I am wondering if anyone know the reason? Thanks!

**Comment by kainagel** [comment]
(a) There is a setting in the "TimeAllocationMutator" config group called "mutationAffectsDuration".  Set this to "false".   Also make sure that that plan does not have an end time.
(b) Did the agent get stuck?  Find out from the events file.

**Comment by jingjunL** [comment]
> (a) There is a setting in the "TimeAllocationMutator" config group called "mutationAffectsDuration". Set this to "false". Also make sure that that plan does not have an end time. (b) Did the agent get stuck? Find out from the events file.

Thanks very much Kai. Agents indeed got stuck and I am fixing that :)
