### ISSUE TITLE
关于wgs84坐标系转换成matsim中模拟路线

### ISSUE THREAD

**Issue by maple-hzy** [matsim-org/matsim-code-examples#89]
当获取到一条完整车辆行驶路径轨迹时（wgs84坐标），如何转换成一条与路网上节点，线路对应的路径xml数据

**Comment by jfbischoff** [comment]
Not sure if I understand your question correctly, however, we do recommend to use a Cartesian coordinate system in MATSim, such as UTM. 
https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system

You can easily convert coordinates in MATSim, or use any other tool for that purpose.

**Comment by maple-hzy** [comment]
非常感谢您的回复，我已经实现了在MATSim中转换坐标，使用的UTM坐标系，现在的问题是无法将车辆轨迹信息转换成一条完整且正确的xml数据。

**Comment by ikaddoura** [comment]
您需要提供一个输入计划，其中每个活动都有正确的坐标。然后运行模拟至少一次迭代并编写计划。现在应该将网络路由写入输出计划文件。

**Comment by maple-hzy** [comment]
@jfbischoff @ikaddoura 
非常感谢您的帮助。
我已经提供了输入计划，每一个活动都有正确的坐标，以下图片是一条完整的输入计划：
输入计划：
![image](https://user-images.githubusercontent.com/47765263/53063073-e089ac80-34fd-11e9-9ff1-90f28ea9ec54.png)

生成的执行计划：
![image](https://user-images.githubusercontent.com/47765263/53063092-eb444180-34fd-11e9-8b5d-ae0033d8e158.png)

在这您可以发现，坐标已经对应上，但是没有和路网中的line对应上，导致在模拟的时候，车辆行驶轨迹不准确，明显有问题。

在MATSim的例子中，我看到另外一个执行计划的范例，里面包括了之前的经纬度以及两点之间的行驶线路route：
![image](https://user-images.githubusercontent.com/47765263/53063107-f4cda980-34fd-11e9-846e-7d26d6234ea0.png)

这个执行计划的行驶轨迹以及和路网中的line对应上了，确定走那条线路，所以模拟出来的轨迹是没问题的。

我的疑问就是如何和路网中的line给对应起来，让车辆模拟轨迹完全正确，而不是自己随机行驶。
再次感谢您的帮助，非常感谢。
