### ISSUE TITLE
Problems with running the UrbanEvExample with different example scenario

### ISSUE THREAD

**Issue by DiegoFad** [matsim-org/matsim-code-examples#890]
Hello,
I am trying to test the UrbanEvModel with a small example scenario. Therefore, I chose the chessboard scenario from matsim-libs. The urban ev example works when using the default example with just one agent but when using the bigger chessboard scenario an error occurs during the run. (not directly in the beginning) Now, I am not sure if this has something to do with my scenario set up or with the upstream code. Do you have an idea where this error comes from?

Repository:
https://github.com/DiegoFad/matsim-example-project

Logfile:
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/10911552/logfile.log)

**Comment by michalmac** [comment]
Thanks for reporting. It's fixed via matsim-org/matsim-libs#2442.

Here an explanation what has happend: https://github.com/matsim-org/matsim-libs/pull/2442#issuecomment-1461487424

**Comment by michalmac** [comment]
Please merge in the latest changes from https://github.com/matsim-org/matsim-example-project and then set `matsim.version` in `pom.xml` to `<matsim.version>15.0-PR2442</matsim.version>`.

**Comment by DiegoFad** [comment]
Thanks!
