### ISSUE TITLE
After DRT Simulation, Lots of Agents are Left with Walk, Potential Reason for that?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#898]
Hi everyone,

I tried to run a DRT simulation without mode innovation. What I found is the overall score has decreased a lot compared to the original scenario without DRT. Using the original flow and storage capacity (0.1), there were many agents have the `stuckAndAbort` event in the event file, and also, there are lots of agents left walking after the simulation (see below):
<img width="506" alt="1679390332409" src="https://user-images.githubusercontent.com/63421908/226563287-a2257a4b-7f0c-4c26-b97b-1025b8bfe907.png">

Because of the stuck issue, I tried to do a test that uses the full flow and storage capacity (which is 1). However, the score does not change very much :( And still, there are lots of agents left walking, similar to the image. 

Any potential reasons for that? Thanks!

**Comment by tschlenther** [comment]
Hi,
did you just replace (all?) car trips by drt? Might be that your fleet is too small.. What are waiting time percentiles? Did you set up a stop-based or door2door service? In case of too few stop locations, the drt vehicles might be in heavy congestion around the stops. Also, in case you have too few stops, agents might be mapped to the exact same drt stop for both pickup and dropoff and thus walk instead...
So, it's a little hard to diagnose what's going wrong with the given information. But you certainly want to find out `why` the agents stuck. Try doing so with some visualizations or by looking into the events file...
