### ISSUE TITLE
Provide Coordinate for Activity that Next Activity is Car, but MATSim Assigned the Activity on pt_link so the event get stuckAndAbort. How to fix this?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#899]
I found many agents got `stuckAndAbort` during a MATSim simulation. And I went into my plan file. We have a `parking` activity for which we only provide a coordinate for such activity in the plan (see below for an example). The travel mode next to this activity is `car`. What is happening in the event is that: MATSim first find a link for this `parking` activity, and he finds one which `allowedMode` does not contain `car`, so the next car trip gets `"stuckAndAbort" `...

How should I fix this? So basically, what I have is a link for all activity except `parking`

<img width="528" alt="1679419040585" src="https://user-images.githubusercontent.com/63421908/226689892-f44a6d41-c15b-4223-8073-f1d446cc5887.png">

**Comment by tschlenther** [comment]
which MATSim version do you use. We had a version, where such activities were not necessarily assigned to the car network but to the general network instead but then faced the issue that the car mode is hardcoded in several other places and also observed similar issues like yours. This is to say that updating MATSim might help. Alternatively, you could assign the nearest _car_ link to the activity, yourself.

**Comment by jingjunL** [comment]
> which MATSim version do you use. We had a version, where such activities were not necessarily assigned to the car network but to the general network instead but then faced the issue that the car mode is hardcoded in several other places and also observed similar issues like yours. This is to say that updating MATSim might help. Alternatively, you could assign the nearest _car_ link to the activity, yourself.

Hi Tilmann, I am using version 14. So I will probably update to 15 for a try :) 

I don't really want to assign them to a fixed car network as I still want to have some try with pt in the future
