### ISSUE TITLE
DRT+PT - output files

### ISSUE THREAD

**Issue by LorenaBR** [matsim-org/matsim-code-examples#90]
Dear  MATSim comunity,

I am writing because I am having some isues  about the output files of my simulation.
In summary, I've simulated 149,992 agents, corresponding to 7% of my population. Of these, one part (38%) uses car, another part uses PT and DRT. The percentages of the PT and DRT vary according to the scenario I am simulating, for each different percentage I modify the "leg mode" of the file plans.xml,

I've used Maven and "contrib" DRT to run my simulation using the Rundoortodoor.java script.
The first question is:
**1)  If using this script (rundoortodoor.java) am I also simulating conventional public transport? I ask this because in my Config.xml the <transit> module is inserted, as well as all the files needed to simulate Conventional Public Transport. In my plans.xml file are also inserted the three legs modes (Car, Pt DRT)
That being said, I do not know if using the RunDoor2Door.java script I'm simulating (TP + CAR + DRT) at the same time.**

From this first doubt comes my second question.
2) When I use only the MATSim interface (GUI), without using any contributions, the global outputs are usually (scoretast.txt, traveldistance.txt, modestats.txt ... etc) and the outputs of each iterations are usually: leghistogram, tripduration , events..etc.
When I use Maven and contrib drt, in addition to the conventional files generated (the same files generated as if you were using only the GUI)  a number of other drt files are also generated (DRt_Customer_Stas.csv, ..etc)
**Should I consider the DRT output files as only drt results and the other output files as a result of the PT + CAR simulation? For example, if i want to know what mileage was produced by the DRT, I should look at drivenDistance? And if I want to know the mileage produced by PT + CAR should I look at the file traveldistancestats.txt?**

My final question is in relation to the units of the results.
**3) Whenever it is unit relative to time the default unit is in seconds and whenever it is relative the distance will be in minutes?**

Thanks a lot for all your support!

**Comment by michalmac** [comment]
re 1: `RunDoorToDoorDrtExample` runs standard matsim+DRT (both car and PT are in the standard matsim)

re 2: the additional files are related only to the DRT mode, while the standard files should include all modes (also DRT)

re 3: (According to my knowledge) Yes, in general, we use seconds and meters. If different units are used, they are usually explicitly declared in files.

**Comment by LorenaBR** [comment]
Thanks for your answer.

2 more questions:

The wait time is the time since the user "call" the DRT until the same arrive?

Analyzing the file "Drt_trips_dtr.CSV" some agents do not have destination coordinate, (only the origin coordinate) instead, some symbols are written e.g:  ï¿½
Does that mean that the agent got stuck in traffic and "never" arrived? What should I do to prevent this from happening?

Thanks one more time.
You've been very kindly and helpfully
