### ISSUE TITLE
Is stop-based DRT always a better solution compared to door2door service?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#900]
I read from some papers that the stop-based DRT service will produce less noise, less fleet size and less emission, and meanwhile, the service level can also be ensured. However, I am unsure whether I am catching up with the latest articles. So, is the stop-based simulation always better than door-based in all perspectives? Any papers for recommendations are welcomed! :)

Also, is there any other algorithm for designing the stops for stop-based DRT service besides just use the existing pt stops?

**Comment by michalmac** [comment]
Let's take two extreme cases:
- a stop-based DRT service with only two stops: it's very efficient for the fleet operations (high fill rates), no detours for customers (while on the bus), but they are forced to walk long distances
- a door-to-door DRT service - less efficient to operate (lower fill rates), possible detours but no need to walk
As you see, it all depends on the actual scenario considered and the decision criteria.

**Comment by jingjunL** [comment]
> * (lower fill rates), possible detours but no need to walk
>   As you see, it all depends on the actual scenario considered and the decision criteria.

That's very clear, thanks so much Michal :)
