### ISSUE TITLE
Multiple Mode Replanning Modules

### ISSUE THREAD

**Issue by fredshone** [matsim-org/matsim-code-examples#92]
Another question rather than an issue...

I am using 'mode innovation', but hoping to implement different mode choices per subpopulation (for example subpopulations without cars/liscenses not replanning to car).

It seems like it is not feasible to have multiople mode innovation modules? Or configuring the ModeChange module to allow different mode choices per subpopulation? Hope someone can point me at docs/example to the contrary.

Searching has suggested that i might be able to set a: carAvail = “never” or hasLicense = “no” parametre 'externally' (page 237 of https://www.simunto.com/matsim/tutorials/mpg2018/course_slides_day2.pdf), but I've not seen this in the docs - perhaps this means adding an additional input rather than using population attributes?

Many thanks!

**Comment by fredshone** [comment]
The option (suggested above) to set carAvail = “never” or hasLicense = “no” is described on page 237 of the following: https://www.simunto.com/matsim/tutorials/mpg2018/course_slides_day2.pdf

**Comment by kainagel** [comment]
Just by config no.  Reason is that there is only one configuration for the strategy, so if you have configured your mode choice for some set of modes, than that is it.

In code, I think you could do something like
```
StrategySettings sMC2Settings = new StrategySettings(  ) ;
sMC2Settings.setStrategyName("subtourModeChoice2");
sMC2Settings.setSubpopulation( "subpop2" );
sMC2Settings.setWeight( 0.2 );
config.strategy().addStrategySettings( sMC2Settings );

...

controler.addOverridingModule( new AbstractModule(){
	@Override
	public void install(){
		this.addPlanStrategyBinding( "subtourModeChoice2" ).toProvider( new Provider<PlanStrategy>(){
			@Inject private Provider<TripRouter> tripRouterProvider;
			@Inject private GlobalConfigGroup globalConfigGroup;
			@Inject private ActivityFacilities facilities;
			@Override public PlanStrategy get() {
				PlanStrategyImpl.Builder builder = new PlanStrategyImpl.Builder( new RandomPlanSelector<>() ) ;
				SubtourModeChoiceConfigGroup subtourModeChoiceConfigGroup = new SubtourModeChoiceConfigGroup(...);
				subtourModeChoiceConfigGroup.set... ;
				builder.addStrategyModule(new SubtourModeChoice(tripRouterProvider, globalConfigGroup, subtourModeChoiceConfigGroup));
				builder.addStrategyModule(new ReRoute(facilities, tripRouterProvider, globalConfigGroup));
				return builder.build() ;
			}
		} ) ;
	}
} ) ;
```
The config part could as well be in xml, but adding the strategy not.

The idea is that you can configure as many strategies as you like, with as many different names as you like, and configure these different strategy names with different subpopulations.

**Comment by fredshone** [comment]
understood, thank you for the explanation and code.

**Comment by kainagel** [comment]
Also tried to code an [example](
        matsim-code-examples/src/main/java/org/matsim/codeexamples/programming/multipleSubpopulations/RunDifferentStrategiesWithDifferentSubpopsExample.java
      ).
