### ISSUE TITLE
Run Technology Average Emission Example Error. RuntimeException: emissions factor for key=PASSENGER_CAR; CO; RUR/Semi-MW/90; FREEFLOW; average; average; petrol (2S) is missing.  There used to be some fallback, but it was inconsistent and confusing, so we are now just aborting.

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#930]
I am playing with the emission example so that we can use it for our simulation. Currently, the example vehicle file has two vehicle categories, but the `HbefaTechnology` are both `average`. What I would like to do is set one to electricity and another to average (so that in our simulation, we can set DRT as electricity and the remaining vehicles as average). Specifically, what I have now in the vehicle file is the following:

```
	<vehicleType id="car_average">
		<length meter="7.5"/>
		<width meter="1.0"/>
		<engineInformation>
			<attributes>
				<attribute name="HbefaVehicleCategory" class="java.lang.String">PASSENGER_CAR</attribute>
				<attribute name="HbefaTechnology" class="java.lang.String">electricity</attribute>
				<attribute name="HbefaSizeClass" class="java.lang.String">average</attribute>
				<attribute name="HbefaEmissionsConcept" class="java.lang.String">average</attribute>
			</attributes>
		</engineInformation>
	</vehicleType>

	<vehicleType id="carTeleport">
		<length meter="7.5"/>
		<width meter="1.0"/>
		<engineInformation>
			<attributes>
				<attribute name="HbefaVehicleCategory" class="java.lang.String">NON_HBEFA_VEHICLE</attribute>
				<attribute name="HbefaTechnology" class="java.lang.String">average</attribute>
				<attribute name="HbefaSizeClass" class="java.lang.String">average</attribute>
				<attribute name="HbefaEmissionsConcept" class="java.lang.String">average</attribute>
			</attributes>
		</engineInformation>
	</vehicleType>
```

I adapted a bit the averageEmissionExample as below:

```
          emissionsConfig.setDetailedVsAverageLookupBehavior( DetailedVsAverageLookupBehavior.tryDetailedThenTechnologyAverageElseAbort );
          emissionsConfig.setDetailedColdEmissionFactorsFile("../coldEmission_average.csv");
          emissionsConfig.setDetailedWarmEmissionFactorsFile("../hotEmission_average.csv");
```

The cold and hot emission file I use has the below format (sorry, for confidential reasons, I cannot show the number). This one is for `cold`:
<img width="431" alt="1682506178749" src="https://user-images.githubusercontent.com/63421908/234553215-87def8d7-cba8-4e61-a713-4b6d17a101fd.png">

This one for `hot`:
<img width="498" alt="1682506212196" src="https://user-images.githubusercontent.com/63421908/234553317-81178c93-3fa3-498e-b854-057750e2dd99.png">

I haven't changed other codes as illustrated in `RunAverageEmissionToolOfflineExample.java`. But I keep getting the following exception:
```
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: RuntimeException: emissions factor for key=PASSENGER_CAR; CO; RUR/Semi-MW/90; FREEFLOW; average; average; petrol (2S) is missing.  There used to be some fallback, but it was inconsistent and confusing, so we are now just aborting.
  at EmissionModule.<init>(EmissionModule.java:64)
  while locating EmissionModule

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
EmissionModule:   "org.matsim.contrib.emissions.EmissionModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1104)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1139)
	at org.matsim.emission.runEmissionExample.main(runEmissionExample.java:103)
Caused by: java.lang.RuntimeException: emissions factor for key=PASSENGER_CAR; CO; RUR/Semi-MW/90; FREEFLOW; average; average; petrol (2S) is missing.  There used to be some fallback, but it was inconsistent and confusing, so we are now just aborting.
	at org.matsim.contrib.emissions.WarmEmissionAnalysisModule.<init>(WarmEmissionAnalysisModule.java:134)
	at org.matsim.contrib.emissions.WarmEmissionHandler.<init>(WarmEmissionHandler.java:82)
	at org.matsim.contrib.emissions.EmissionModule.createEmissionHandlers(EmissionModule.java:230)
	at org.matsim.contrib.emissions.EmissionModule.<init>(EmissionModule.java:74)
	at org.matsim.contrib.emissions.EmissionModule$$FastClassByGuice$$489552.GUICE$TRAMPOLINE(<generated>)
	at org.matsim.contrib.emissions.EmissionModule$$FastClassByGuice$$489552.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1101)
	... 2 more

Process finished with exit code 1

```

Where I made the mistakes? Thanks!

**Comment by kt86** [comment]
Hi jingjunL,

I do not know if the following is everything, and have not the time to look in into detail right now, but some quick first ideas:

1. You are setting values the _detailed_ tables in the config. But putting in there the _average_ table files -> This will not work. Please set the detailed tables and average tables with the corresponding config-setter(s).
2. DetailedVsAverageLookupBehavior.tryDetailedThenTechnologyAverageElseAbort --> This will ignore the average table and thus abort instead, please use another setting, which uses both: TechnologyAverage (from the detailled table) and Average (from the average table)
3. When working with (subsets) of emissions tables OR tables that include different vehicleCategories (like car, HGV, etc) there are issues in the consistency check, because it is sometimes too restrictive for it. Please try another setting for it. HbefaTableConsistencyCheckingLevel.NONE will do no checks. This is not preferred, but maybe a good starting point.

Maybe that helps a bit.

**Comment by tschlenther** [comment]
In my understanding, the the emission module checks whether all possible combinations of road type, emission concept etc. are provided in the input tables. In most cases, the input tables do not provide that. Can you try one consistency checking level lower, i.e. try
`eConfig.setHbefaTableConsistencyCheckingLevel(EmissionsConfigGroup.HbefaTableConsistencyCheckingLevel.consistent);`

**Comment by jingjunL** [comment]
Thanks very much for your answers guys! I have two additional questions:

1) What are the biggest differences between `average` and `detailed` tables? In the HBEFA files I get, there are `Vehcat_2020_average`, `detailed_perTechAverage` and `detailed_perTechAverage_Bln_carOnly`. In my case, I think I am using the data for `detailed_perTechAverage` as you can see in the image that it distinguishes between `diesel`, `CNG `and `electricity`. Is this still not the detailed table referred to in the config?

2) I get it that there will be a consistent check at the beginning, and the default is `allCombinations`. But what are the differences between the `consistent` and `none`? I'm asking because @kt86 suggests `none` and @tschlenther suggests `consistent`...

Thanks again in advance! :D

**Comment by kt86** [comment]
Re 1: perTechAverage is a detailed table, and indeed, as long as you have vehicles, where you distinguishes between diesel, CNG and electricity this is correct. But in your first screenshot you have also defined a vehicle (car) with only average values -> average table is needed for it.

Re2: `none` is easiest to debug and ensure, that everything else is set up correctly. -> It just disables that check. If everything is good, please follow the advise of @tschlenther .

**Comment by kt86** [comment]
And as long as you are using the sample data, most probably the consistency checks will fail, because this is not a full data set and not meant for productive use!

**Comment by jingjunL** [comment]
Thanks, guys. This perfectly solved my questions 😄=====👍
