### ISSUE TITLE
Minibus implementation stops not created or randomly selected

### ISSUE THREAD

**Issue by Owen295** [matsim-org/matsim-code-examples#938]
I am trying to run the minibus model with paratransit data. I am struggling with this error: 

ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.NullPointerException: Cannot invoke "org.matsim.pt.transitSchedule.api.TransitStopFacility.getCoord()" because "stop1" is null

My Paratransit stops are read into the simulation but when the RouteProvider does not seem to get the randomly created stops. I have checked all the inputs and the routing strategies I have failed to understand the issue. 

I have tries this with different inputs files for another city I still get the same error. @neuma  Is the problem in the way the stops are initialized as I see there is no weights on them as I debug.

@vsp-gleich  I have put in a minimum reproducible example of inputs:

https://www.dropbox.com/scl/fo/t50jmezgkl6ra361vcf3i/h?dl=0&rlkey=rt0ap7fp9ohbagsftimzuywxo

Does anyone know where can start looking to solve this?

Thank you

**Comment by mrieser** [comment]
Duplicate #952
