### ISSUE TITLE
Estimated time for building a scenario

### ISSUE THREAD

**Issue by lindman** [matsim-org/matsim-code-examples#94]
Hi, 

I am a fairly new to MATSim and traffic simulation in general and have spent a limited amount of time using the software.
My intention in the long run is to create a scenario of a real (fairly large) city but before I set out to do this it would be great to know roughly how much time that is required to do this, i.e., converting and modifying traffic networks from OSM, validating traffic demands, and so on.
As listed at https://www.matsim.org/gallery/ there are many (large) scenarios considered within the MATSim community and it would be really helpful if anyone taking part in developing these could share how much time and effort you spent on building and maintaining a scenario, which parts of the implementation requires most time, if there were any unforeseen problems along the way, etc. 

Regards, 
Anders

**Comment by JWJoubert** [comment]
The answer to your question probably depends on whether you want to use the scenario for research purposes, i.e. it must reflect reality _sufficiently_, or whether you want to use it for real decision-support. For the latter, I recall Prof Axhausen once giving a rule-of-thumb of 10,000 man-hours. That was a while ago, and I think the core team has made MATSim much simpler to work with over the last few years.
