### ISSUE TITLE
[Beginner] How to see traffic volume on specific links

### ISSUE THREAD

**Issue by Armanapattt** [matsim-org/matsim-code-examples#943]
Hi everyone! I'm a beginner user of MATSim and I'm trying to get the traffic counts of specific links from my model. I added the counts module to my config file and it ran successfully. However, I could not find the corresponding output that shows the volume count. Also, I found an example of the input counts file but I don't understand what `loc_id` and `cs_id` mean. Can you kindly tell me? Thank you in advance and my config.xml is as follows:

`<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>

	<module name="global">
		<param name="coordinateSystem" value="EPSG:32647" />
	</module>

	<module name="network">
		<param name="inputNetworkFile" value="network.xml" />
	</module>

	<module name="plans">
		<param name="inputPlansFile" value="population.xml" />
	</module>

	<module name="controler">
		<param name="outputDirectory" value="./kmutt/output" />
		<param name="firstIteration" value="0" />
		<param name="lastIteration" value="10" />
	</module>

	<module name="qsim">
		
		<param name="startTime" value="00:00:00" />
		<param name="endTime" value="24:00:00" />
		<param name = "snapshotperiod"	value = "00:00:00"/> 
	</module>
  <module name="counts" >
		<param name="analyzedModes" value="walk" />
		<param name="averageCountsOverIterations" value="5" />
		<param name="countsScaleFactor" value="20.0" />
		<param name="distanceFilter" value="null" />
		<param name="distanceFilterCenterNode" value="null" />
		<param name="filterModes" value="false" />
		<param name="inputCRS" value="null" />
		<param name="outputformat" value="txt" />
		<param name="writeCountsInterval" value="5" />
	</module>

	<module name="planCalcScore">
		<param name="learningRate" value="1.0" />
		<param name="BrainExpBeta" value="2.0" />

		<param name="lateArrival" value="-18" />
		<param name="earlyDeparture" value="-0" />
		<param name="performing" value="+6" />
		<param name="waiting" value="-0" />

		<parameterset type="activityParams" >
			<param name="activityType"    value="h" /> 
			<param name="priority"        value="1" />
			<param name="typicalDuration" value="10:00:00" />
		</parameterset>
		<parameterset type="activityParams" >
			<param name="activityType"    value="edu" /> 
			<param name="priority"        value="1" />
			<param name="typicalDuration" value="01:00:00" />
			<param name="openingTime"     value="07:00:00" />
			<param name="closingTime"     value="18:00:00" />
		</parameterset>
		<parameterset type="activityParams" >
			<param name="activityType"    value="eat" /> 
			<param name="priority"        value="2" />
			<param name="typicalDuration" value="00:30:00" />
			<param name="openingTime"     value="06:30:00" />
			<param name="closingTime"     value="20:00:00" />
		</parameterset>
		<parameterset type="activityParams" >
			<param name="activityType"    value="play" /> 
			<param name="priority"        value="2" />
			<param name="typicalDuration" value="00:30:00" />
			<param name="closingTime"     value="20:00:00" />
		</parameterset>
		<parameterset type="modeParams" >
			<param name="constant" value="0.0" />
			<param name="marginalUtilityOfDistance_util_m" value="0.0" />
			<param name="marginalUtilityOfTraveling_util_hr" value="-6.0" />
			<param name="mode" value="walk" />
			<param name="monetaryDistanceRate" value="0.0" />
		</parameterset>
	</module>
	<module name="vehicles" >
		<param name="vehiclesFile" value="modes.xml" /> 
	</module>
	<module name="strategy">
		<param name="maxAgentPlanMemorySize" value="5" /> 

		<param name="ModuleProbability_1" value="0.9" />
		<param name="Module_1" value="BestScore" />

		<param name="ModuleProbability_2" value="0.1" />
		<param name="Module_2" value="ReRoute" />
	</module>

</config>
`

**Comment by jingjunL** [comment]
The easiest way of comparing traffic counts would be through the Via visualisation tool (https://simunto.com/via/). I am also not sure how to use the count module via MATSim's in-built function :)

**Comment by kainagel** [comment]
Even if you use VIA, you need a way to input the data from reality.  

(1) In your config file, you need to specify your counts file.  Something like
```
<module name="counts">
   <param name="inputCountsFile" value="counts.xml"/>
</module>
```

(2) I am relatively optimistic that `cs_id` means "counting station ID", i.e. some "name" that the counting station has in reality.  Presumably, all of these need to be different, but apart from that do not matter. And `loc_id` means the link ID (I think; you need to try out).

**Comment by mrieser** [comment]
The counts module in MATSim is to compare against real-world data.

If you're only interested in link counts from the MATSim simulation, look at the file `linkstats.txt.gz` which is written by default every 10th iteration (it is thus located e.g. in `output/ITERS/it.10/10.linkstats.txt.gz`).

This file lists for every link the average link-volume (averaged over the last 5 iterations) for every hour in the simulation (e.g. the column `HRS6-7avg` contains the average link volumes for the hour from 06:00 to 07:00).

As Via was mentioned: if you load the network and events file into Via, you could query the volumes of specific links by clicking on them: https://docs.simunto.com/via/analyses/network-queries.html#link-volumes

**Comment by Armanapattt** [comment]
Thank you for every help, it works for me now by providing the input counts file and the output file is in the ITERS folder every 5 iteration named countscompare.txt
