### ISSUE TITLE
Simunto Via does not display the walk mode for vehicles layer

### ISSUE THREAD

**Issue by Armanapattt** [matsim-org/matsim-code-examples#944]
I completed my matsim model and I tried to visualize my result. 

However, I use only one mode choice for my model which is "walk". I tried to add the vehicles layer and nothing showed up. Then I tried changing the plan of every agent to "car" by keeping the rest of the setting to be the same, and the vehicles showed up in the Via.

I tried to find the setting in Via but found nothing related. Could anybody help me to fix?
Thank you in advance.

**Comment by Armanapattt** [comment]
By recognized that "walk" is not considered to be a vehicle by default

**Comment by mrieser** [comment]
Did you follow the steps in https://docs.simunto.com/via/getting-started/first-visualization.html ?

Does the network show in Via?

Are all your agents using "walk" as mode? By MATSim's default, "walk" is teleported, and thus no vehicle will be visible in Via.

You could use the "show agent plan" query in Via: https://docs.simunto.com/via/analyses/agent-queries.html#-show-agent-plan  to search for agents by id and see their teleported legs.

**Comment by Armanapattt** [comment]
I fixed this by providing the vehicle input file and adding these lines into the config.xml

`	<module name="vehicles" >
		<param name="vehiclesFile" value="modes.xml" /> 
	</module>`

<module name="qsim">
		<param name="vehiclesSource" value= "modeVehicleTypesFromVehiclesData" />
		...
</module>

Which I defined "walk" as a vehicle in modes.xml which an example can be found here: [https://github.com/matsim-org/matsim-code-examples/blob/15.x/scenarios/equil-mixedTraffic/mode-vehicles.xml](url) 

It also needs to clear the default teleporting mode and define a new teleporting mode by inserting these lines in the config section in RunMatsim.java

`		config.plansCalcRoute().clearTeleportedModeParams();
		{
			PlansCalcRouteConfigGroup.TeleportedModeParams params = new PlansCalcRouteConfigGroup.TeleportedModeParams("teleport");
			params.setTeleportedModeSpeed(0.5);
			params.setBeelineDistanceFactor(1.0);
			config.plansCalcRoute().addTeleportedModeParams( params );
		}`

Thank you for every help
