### ISSUE TITLE
Code Problem

### ISSUE THREAD

**Issue by TaniyaSultana** [matsim-org/matsim-code-examples#95]
could you please help me to sort out the problem with the following code? it says in the error that "last activity of person driver agent id 44 has end time < infty; setting it to infty"

<person id="44" employed="yes" >
		<plan selected="yes">
			<act type="h" facility="1" x="520533.5097" y="3693324.411" start_time="00:06:21" max_dur="08:00:00" end_time="08:06:21" />
			<leg mode="car">
			</leg>
			<act type="w" facility="4" x="518242.8125" y="3708640.878" start_time="08:06:21" max_dur="08:00:00" />
            <leg mode="car">
			</leg>
            <act type="h" facility="1" x="520533.5097" y="3693324.411" start_time="08:06:21" max_dur="08:00:00" end_time="16:06:21" />
		</plan>

	</person>

**Comment by mrieser** [comment]
If an activity has an end time, it usually means the agent will end the activity and go somewhere else afterwards. But the last activity in a plan should never end, thus it either should not have an end time, or the end time should be set to infinity.
The message tells you that some agents have an end time set on their last activity, and that the simulation will overwrite this end time with infinity.

**Comment by TaniyaSultana** [comment]
Thank you for the explanation.
