### ISSUE TITLE
Issue in Creating VrpPaths (DRT)

### ISSUE THREAD

**Issue by SapanTiwari** [matsim-org/matsim-code-examples#956]
Hi. 
I am working on relocating a vehicle from a link to another by creating a VrpPaths between two different links. I manage to do so but get a constant precondition error stating that FromLink and path are not connected, although the values indicate that they are connected. I have tried to run it in multiple scenarios with different MATSim versions as well, but I face the same issue. The error can be seen in the following paragraph. As you can see that **toLink.fromNode() == path.ToNode()**. (i.e. ID 130). What is the reason, and how can we resolve this? Any help would be appreciated.

java.lang.IllegalArgumentException: path and toLink are not connected. To link: org.matsim.core.network.LinkImpl@2a631049[id=345]**[from_id=130]**[to_id=148][length=317.0][freespeed=9.72222222222222][capacity=300.0][permlanes=1.0][modes=[car]. Last link in path: org.matsim.core.network.LinkImpl@425b5fe2[id=346][from_id=148]**[to_id=130]**[length=317.0][freespeed=9.72222222222222][capacity=300.0][permlanes=1.0][modes=[car]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.1-jre.jar:?]
	at org.matsim.contrib.dvrp.path.VrpPaths.createPath(VrpPaths.java:101) ~[dvrp-15.0-PR2223.jar:?]
	at org.matsim.contrib.dvrp.path.VrpPaths.createPath(VrpPaths.java:82) ~[dvrp-15.0-PR2223.jar:?]
	at org.matsim.contrib.dvrp.path.VrpPaths.calcAndCreatePath(VrpPaths.java:46) ~[dvrp-15.0-PR2223.jar:?]
	at org.matsim.contrib.drt.scheduler.EmptyVehicleRelocator.relocateVehicle(EmptyVehicleRelocator.java:63) ~[drt-15.0-PR2223.jar:?]

**Comment by michalmac** [comment]
This is the line where the check is run:
https://github.com/matsim-org/matsim-libs/blob/776e121aa4421f9b2dcb5d4de57aff66ca051750/contribs/dvrp/src/main/java/org/matsim/contrib/dvrp/path/VrpPaths.java#L101

As you can see, we check if the nodes are exactly the same objects (so they come from the same network). It looks that in your case they are not the same objects. This means that the link passed to `EmptyVehicleRelocator.relocateVehicle(DvrpVehicle vehicle, Link link)` is from a different network to the one used by the router (`LeastCostPathCalculator`) passed to `VrpPaths.calcAndCreatePath(Link fromLink, Link toLink, double departureTime,
LeastCostPathCalculator router, TravelTime travelTime)`.

**Comment by SapanTiwari** [comment]
Hi,
Thank you for clearing the doubt, there was an issue with the binding.
