### ISSUE TITLE
Visualising Traffic Volumes Comparasion on Links Between Two Scenarios on VIA

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#967]
I came across a paper that can show the change in daily traffic volume between 2 scenarios on each road segment in Figure 5 of the paper "Towards welfare optimal operation of innovative mobility concepts: External cost pricing in a world of shared autonomous vehicles". I really like the idea of this image, and I want to make one for our research as well. I think probably this figure is produced by VIA? How should I make the settings?

Attached is the detailed screenshot of the figure that I want to reproduce.

Thanks!

<img width="502" alt="1687445797323" src="https://github.com/matsim-org/matsim-code-examples/assets/63421908/aec78251-f7ff-4da7-9483-bc36c2c405c4">

**Comment by tschlenther** [comment]
Hi,
you need to load your network as well as the two events files from your simulation cases into VIA. Then add the network layer, go to it's corresponding settings, then

1. Link Attributes -> Add... -> Avg. Speeds and Volumes -> choose one of your events files and a clear identifier -> Create Attributes
2. repeat 1. with choosing the other events file
3. then Link Attributes -> Add... -> Attribute Difference -> choose your two newly created volume attributes (normally you should do (policy minus base) -> Create Attribute
4. then change your display settings

By the way, you can also dig into [SimWrapper](https://vsp.berlin/simwrapper/), an interactive viz platform developed @VSP which, among many other things, can produce the same plot for you.
See the [docs](https://simwrapper.github.io/docs/), especially for [link plots](https://simwrapper.github.io/docs/link-vols). You'd need to have the volumes prepared in a csv file, you can do that for example by running `org.matsim.application.analysis.traffic.LinkStats` in matsim-libs, but you'd probably want to reduce the csv file size for faster loading in SimWrapper.

**Comment by jingjunL** [comment]
Thanks for the answers @tschlenther :)

I add a comment for the first VIA method for future people: the attributes created by VIA are time-dependent. So if you would like to know the overall traffic volume (like me and that paper I showed), after you generated the volume, you should go to link Attributes - manage - select your attribute and change the time Resolution to "all".
