### ISSUE TITLE
why some output document cant be recognized and be added 

### ISSUE THREAD

**Issue by lucici1999** [matsim-org/matsim-code-examples#977]
hello everyone, I am a beginner, after I downloaded the pt-tutorial file and ran it through the GUI that comes with matsim, when I put the output file into via to run it, it says One or more files were not recognised and could not be added，I'd be grateful if someone could help me. (my English is not very good please forgive me)
![微信图片_20230711174750](https://github.com/matsim-org/matsim-code-examples/assets/68318084/aee9593f-c5f0-4136-b6af-c38f664fd054)

**Comment by jingjunL** [comment]
If you would only like to visualise the outcomes of your simulation, you don't need to drag all outputs to Via. The primary file needed (only for visualization purposes) is the output_network and output_event (or output_trip). And then you can select what you would like to visualise based on the features of Via

**Comment by lucici1999** [comment]
> 
I see, thanks for the answer, have a nice life!

**Comment by lucici1999** [comment]
> 如果您只想可视化模拟结果，则无需将所有输出拖到 Via。所需的主文件（仅用于可视化目的）是output_network和output_event（或output_trip）。然后，您可以根据 Via 的功能选择要可视化的内容

**Comment by lucici1999** [comment]
> If you would only like to visualise the outcomes of your simulation, you don't need to drag all outputs to Via. The primary file needed (only for visualization purposes) is the output_network and output_event (or output_trip). And then you can select what you would like to visualise based on the features of Via
我明白了， thanks for the answer, have a nice life!
