### ISSUE TITLE
What version of the dependency should be changed to？

### ISSUE THREAD

**Issue by lucici1999** [matsim-org/matsim-code-examples#979]
hello everyone，I keep getting this error when I run the example, so I found out it's because the class uses Java 17 and my jdk is 11, and I found out that the dependency in the pom is 15.0, which could be the reason for the error, and what version should I change it to?
![微信图片_20230712193327](https://github.com/matsim-org/matsim-code-examples/assets/68318084/fca04935-a407-4bef-bc33-17d394747103)
![微信图片_20230712193311](https://github.com/matsim-org/matsim-code-examples/assets/68318084/82aa8b1c-bffd-4db4-9442-6e4b805a946b)
![微信图片_20230712193234](https://github.com/matsim-org/matsim-code-examples/assets/68318084/3c15a5b8-96e9-4f96-8d1a-9b95e74cfe44)

**Comment by lucici1999** [comment]
I tried modifying a lower version but got a new error，“Inspection 'Maven Model Inspection' has no
quick-fixes for this problem. Click to editinspection options, suppress the warning, ordisable the inspection completely.”
![微信图片_20230712194255](https://github.com/matsim-org/matsim-code-examples/assets/68318084/13a65ce1-5f85-4170-9bad-2494b1db4f3b)

**Comment by kainagel** [comment]
I assume that you have cloned matsim-code-examples.  And from there are using matsim-libs as a dependency.  I seem to remember that we switched to jdk17 just before 15.0 was released.  Could you please try "15.0" together with "jdk17"?

(Note that "15.0" is _newer_ than something like "15.0-2023w07".)

And you may have to force a full rebuild.

**Comment by kainagel** [comment]
(Note that the relevant variable is in the `<parent>` section.  There may have been (depending on your version) an entry in the `<properties>` section which, however, was not used anywhere.)

**Comment by lucici1999** [comment]
> 我假设你已经克隆了 matsim 代码示例。并从那里使用 matsim-libs 作为依赖项。我似乎记得我们在 17.15 发布之前切换到 jdk0。你能把“15.0”和“jdk17”一起试试吗？
> 
> （请注意，“15.0_”比“_15.0-2023w07”更新。
> 
> 而且您可能必须强制完全重建。

good morning, thanks for your answer! I downloaded this project to convert osm to matsim network. But the matsim-release I'm using is still 13.0.  I‘m using the jdk11 in my computer, that's mean I should unload 11 and download jdk17?  In addition，if I use jdk17 ， the version of matsim-release should be 15.0?(sorry my English is poor)

**Comment by paulheinr** [comment]
Yes, this is correct. We use the following versions: 
* MATSim 13.x -> Java 11
* MATSim 15.x -> Java 17
