### ISSUE TITLE
stuck during PersonPrepareForSim

### ISSUE THREAD

**Issue by hsyfyc** [matsim-org/matsim-code-examples#982]
Hi all!
I had some problems with a new scenario. During the running process, it stucked at PersonPrepareForSim just like the photo shows below.
![6225c4efa153b7d960297b1224c49ab](https://github.com/matsim-org/matsim-code-examples/assets/73547130/6582a6ab-86da-409e-923a-3e5b76c59a7d)
![07fcddf6a2b0346c1ab257a86fb95a4](https://github.com/matsim-org/matsim-code-examples/assets/73547130/b66acd25-2b6d-4e5a-8181-d841cea67acb)
Before this time, I have tried to find which person had problem by reduce the scale of population from 16 to 8, but when the population scale is 16, the program stucked at person#8, when the population scale is 8, the program stuck at person #4.

network file and population file are attached below.
[input.zip](https://github.com/matsim-org/matsim-code-examples/files/12036993/input.zip)

Hope for your answers.

**Comment by kainagel** [comment]
This is not enough information.  Could you please provide the full logfile.  Thanks .

**Comment by hsyfyc** [comment]
The logfile and logfileWarningsErrors are attached below.
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/12037561/logfileWarningsErrors.log)
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/12037562/logfile.log)

**Comment by kainagel** [comment]
Oh, I see, this is something worse.  :-(.  You probably saw that before me.  @mrieser or @michalmac or anybody else, do you maybe have an idea?  From my side:
* I can't say from what you show if this is a multi-threading issue.  Does the problem go away if you set the number of threads in the `global` config group to `1`?
* Can you do this agent by agent, i.e. run plans files with single agents and see what happens?  I can see that you say it just jumps to "earlier", but that may (or may not) have to do how agents are distributed onto threads.
??

**Comment by hsyfyc** [comment]
Thanks for your reply.
For the first way, after setting number of threads to 1, the program still stucked at the same place.
For the second way, I tried to run with one agent a time, when it comes to the fifth agent, the program stucked. Then I checked the plan in Via, found that in Via route can be found between two node close to the coordinate of agent's activity.

Plan 
![0b674f164b54d2eba334fc7a04b1f16](https://github.com/matsim-org/matsim-code-examples/assets/73547130/d3bb2539-0e63-4266-8450-552cb7ab656a)
Home
![ad2f75eb12b808ea5933bb1528096ae](https://github.com/matsim-org/matsim-code-examples/assets/73547130/16448425-9f5a-4a69-b66b-1dab4928d29c)
Work
![6146cc5c3e1e0a44af44c053c508352](https://github.com/matsim-org/matsim-code-examples/assets/73547130/2ccb45d2-8c8b-462c-8fc2-5ba8ef9aefa3)
Route
![6bd765f8f23909e45c95a6b9345da61](https://github.com/matsim-org/matsim-code-examples/assets/73547130/012dead7-cf6b-46c6-8dd6-b63f01312a11)

For the problem, I think it may be wrong with the network?

**Comment by mrieser** [comment]
There seem to be some issues with the network.

When searching for the exact from-node/to-node in Via as the MATSim router does, I get the following result:
![Screenshot 2023-07-18 at 11 30 38](https://github.com/matsim-org/matsim-code-examples/assets/1038453/82fc6313-3c34-4074-8e0b-0d8783ac63dd)

That's not what one would expect and points in the direction, that the network is not connected in a way as one would expect.

Also, what looks like direction-separated highways are actually bi-directional links:
![Screenshot 2023-07-18 at 11 31 44](https://github.com/matsim-org/matsim-code-examples/assets/1038453/f8d05229-1b2d-4c85-9d47-3fc397e006e3)

So, they agents can actually "drive backwards" on these highway-like structures. In the screenshot, there are like 4 roads, and on each road agents can travel from left to right AND from right to left, while it probably should be only 2 roads from left to right and 2 other roads from right to left.

How did you create/convert the network? (And what city is it?)

Digging further, the algorithm seems to hang in a place where two nodes are basically on top of each other:

```xml
<node id="sz17121" x="1.3425928733942334E7" y="3686702.4930818207" ></node>
<node id="sz17122" x="1.3425928730825387E7" y="3686702.493668799" ></node>
```

There are links connecting these two nodes:
```
<link id="-26423" from="sz17121" to="sz17122" length="0.003256847106865249" freespeed="19.444444444444443" capacity="4800.0" permlanes="3.0" oneway="1" modes="pt,car" ></link>
<link id="26423" from="sz17122" to="sz17121" length="0.003256847106865249" freespeed="19.444444444444443" capacity="4800.0" permlanes="3.0" oneway="1" modes="pt,car" ></link>
```

But these links are very short (0.003m = 0.3mm), so my current guess is that the travel-time and travel-disutility essentially becomes 0.0 on those short links, which then results in an endless loop in the routing process.

Try to fix the network, make sure you don't have such short links, make sure you properly convert unidirectional links like freeways, and make sure intersections are properly connected (which the current detour to get from A to B suggests they are not).

**Comment by mrieser** [comment]
Maybe we should include an additional warning in the code if links are very short? Currently there is only a warning I think if a link has length 0.0, but probably everything < 1.0 is worth to know about and might pose some problems.

**Comment by hsyfyc** [comment]
Thanks for your reply. I hadn't converted the network correctly. I will fix it later.
