### ISSUE TITLE
Choosing the order of activities of a agent in MATSIM

### ISSUE THREAD

**Issue by utkaez** [matsim-org/matsim-code-examples#984]
We have the following scenario: We have a glass collection vehicle and coordinates of the locations of the glass containers that need to be visited for a day. Now, we want the vehicle to approach the containers using the shortest route. Where can we define that activities should be selected according to Dijkstra's algorithm? The simulation already works when we specify the order in which the containers should be visited. Attached is our plans.xml file

![Снимок](https://github.com/matsim-org/matsim-code-examples/assets/131811139/1fcd2e6e-6e91-4b15-b3fb-9f05cfdbbad2)

**Comment by paulheinr** [comment]
If I understand you correctly, you want to solve the Vehicle Routing Problem, don't you? Either you do it yourself before or you use the MATSim freight contrib. The `RunFreightExample` is a good starting point for that.
