### ISSUE TITLE
EPSG Referencing Error when running a simulation on HPC Cluster 

### ISSUE THREAD

**Issue by lorenznitsch** [matsim-org/matsim-code-examples#989]
When running a MATSim run on the HPC Cluster (at TU Berlin), an error occurs concerning the EPSG Database. This doesn´t happen if the run happens locally without building a .jar-file. The problem seems to be connected either to the building of the jar-file or to the HPC Cluster.

This is the logfile: [log-drtStopBased-true-extraPtPlan-true.log](https://github.com/matsim-org/matsim-code-examples/files/12136248/log-drtStopBased-true-extraPtPlan-true.log)

It seems that there might be a connection to [this ](https://stackoverflow.com/questions/27429097/geotools-cannot-find-hsql-epsg-db-throws-error-nosuchauthoritycodeexception)issue.
I tried it with different configurations in the pom.xml, using plugins either from the Open MATSim Berlin Scenario, from the matsim-example-project or from matsim-code-examples (from [here](https://github.com/matsim-org/matsim-code-examples/blob/15.x/pom.xml)). The error still occurs when trying to run the simulation on the cluster.

There were a few occasions where this error did not occur when running the simulation on the cluster. It seems to be a new issue though, since this problem did not occur using the same .jar-file just a couple of weeks ago.

Also for further info, [here](https://github.com/matsim-vsp/playground-schlenther/tree/lorenz)´s the link to the used repository for building the run.

Thank you in advance!

**Comment by mrieser** [comment]
Digging through the exceptions, I end up here:

```
Caused by: java.io.FileNotFoundException: /tmp/GeoTools/Databases/HSQL/v9.6.0/EPSG_creation_lock.txt (No such file or directory)
```

GeoTools must extract the included zip-file with the database to a location on the filesystem to access it. Probably this location is not available on your HPC cluster, or it is, but another process might already access and block it.

You might try to run MATSim with the following system property pointing to a different directory you control where the database will be extracted to:

```
java -Xmx24g -DEPSG-HSQL.directory=/path/to/some-directory -jar my-matsim.jar config.xml
```

This system property is mentioned [here in the GeoTools sources](https://docs.geotools.org/stable/javadocs/org/geotools/referencing/factory/epsg/hsql/HsqlEpsgDatabase.html#createDataSource()).

**Comment by lorenznitsch** [comment]
Thank you very much, this solved the issue!
