### ISSUE TITLE
How to add / remove agents at full speed

### ISSUE THREAD

**Issue by markusstraub** [matsim-org/matsim-code-examples#990]
What I want to achieve: simulate through-traffic by adding and removing agents on motorways at the edge of my simulation area.

Simply adding agents with a start  and end location on the motorway (insertion links) to the population works in theory, but I noticed that the rate at which agents can start from an insertion link is quite limited. I figure the queuing is modeled so that an agent stepping in the car and starting to drive blocks agents behind him until he is on his way.

Can I somehow get the agents to immediately start at full speed so that the capacity of my insertion links can be increased?

Or is there another method I could use to insert more agents at the same place without them blocking each other?

**Comment by mrieser** [comment]
Agents should be able to start more or less immediately. But they get inserted at the end of the link where they first have to leave the link and then continue to their next one. On that first link, the (flow) capacity constraints take over the control.

Example: You have 1000 agents all starting at the same time on the same link. The agents will still only be able to leave that link with the given flow capacity on that link.

So if you want to have more agents leave in a shorter amount of time, you need to increase the (flow) capacity of that "insertion" link. Depending on the network design, a traffic jam could then occur further down the road at the next intersection/node, as then the flow capacity constraints of the "normal" road is taken into account.

> Or is there another method I could use to insert more agents at the same place without them blocking each other?

Not really, MATSim always tries to ensure specified flow capacities are not exceeded.

Does that help you?

**Comment by markusstraub** [comment]
Perfect, thank you for these insights!

(When I believed to encounter a very low agent generation rate on a high-capacity motorway link i overlooked that Simunto Via displays the vehicles (red triangles) only on the **second** link of a route.. and the first link of the route was a low-capacity link, which explained the low generation rate)
